### ISSUE TITLE
World loading crash upon pressing a ModHotKey during loading

### ISSUE THREAD

**Issue by gorateron** [bluemagic123/tModLoader#101]
Title. You crash (somewhere after/during something liquid related) if you press a bound ModHotKey during this stage. (when loading a world)

**Comment by gorateron** [comment]
Here I've provided error logs when this bug happens, simply press (spam it) a bound ModHotKey while loading a world:
```
The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Terraria.GameInput.KeyConfiguration.CopyKeyState(TriggersSet oldSet, TriggersSet newSet, String newKey)
   at Terraria.GameInput.PlayerInput.KeyboardInput()
   at Terraria.GameInput.PlayerInput.UpdateInput()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
```
