### ISSUE TITLE
tmodloader crashes in chest rename UI

### ISSUE THREAD

**Issue by LyraelRayne** [bluemagic123/tModLoader#138]
tmodloader 0.9.1
Terraria 1.3.4.4

I think this is something to do with hotkeys which have been saved to input profiles.json but no longer exist in any mod (for example if the mod is disabled).

Steps to reproduce:

1. Install a mod with hotkeys
2. Go into key bindings menu and bind Home to a key.
3. Disable all mods.
4. Close the game (not sure if necessary)
5. Open the game again.
6. Open a world with some chests and open the rename ui.
7. Hold the Home key
8. Eventually the game will crash with the exception below.

```
The "Open Logs" shows me 
`The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Terraria.GameInput.KeyConfiguration.CopyKeyState(TriggersSet oldSet, TriggersSet newSet, String newKey)
   at Terraria.GameInput.PlayerInput.KeyboardInput()
   at Terraria.GameInput.PlayerInput.UpdateInput()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
```

**Comment by JavidPack** [comment]
This is something already fixed in next release. Thanks though.
