### ISSUE TITLE
InvalidOperationException when loading world sometimes

### ISSUE THREAD

**Issue by LyraelRayne** [bluemagic123/tModLoader#144]
Since 0.9.2.1 I've been intermittently received the below error in Windows 10 Steam version of Terraria.

I've included a screenshot of my spawn area in case knowing what items are nearby helps (looks like some kind of lighting problem).

The lunar monolith was also active in the area, although I think I've had it crash without as well.

I haven't determined whether it happens without mods on, but the mods i have installed don't have any items in them (Hero's mod and the keybinding mod I'm working on).
---------------------------
Terraria: Error
---------------------------
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Terraria.Lighting.PreRenderPhase()
   at Terraria.Lighting.LightTiles(Int32 firstX, Int32 lastX, Int32 firstY, Int32 lastY)
   at Terraria.Main.do_Draw(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args)

![crashyspawn](https://cloud.githubusercontent.com/assets/11632412/24068354/a666f2ee-0be0-11e7-993a-93995dcd61d1.JPG)

**Comment by Jofairden** [comment]
We need more testcases. You _have_ to test this without any mods on, also test with/without mods on on a _fresh_ character _**separately**_. Also if the monolith is on, try disabling it. If you can't get in the game, I advise you make a backup of your world and use a worldeditor to remove the tile and/or disable the effect.

**Comment by LyraelRayne** [comment]
Yeah I'm going to do so, just haven't had a chance yet.

It's very hard to determine whether it doesn't happen in any given scenarion because it only happens once every N times I log on, where N is a number larger than 3. Thus it's going to take time to actually rule anything out.

**Comment by LyraelRayne** [comment]
I had a go at reproducing this. I managed to reproduce it once, on the same world, without the monolith activate, with only hero's mod installed. I've restarted the game about 100 times both with and without hero's since and it was unable to reproduce it.

The one time I reproduced it I had just set the time to night and turned rain on, saved the game then reloaded.

Sorry I can't provide more conclusive results. Testing intermittent faults is the worst.

**Comment by Jofairden** [comment]
@LyraelRayne it sounds like this is either a very minor bug in vanilla or something in Heros Mod that causes this issue. Since @JavidPack maintains Heros Mod, I will tag him, maybe he knows whats up.

**Comment by LyraelRayne** [comment]
Thanks. And yeah I agree. This has not happened on any other worlds and happens extremely rarely on the world that I discovered it on (as opposed to just before I reported it when it happened 6 times out for 20 or something like that).
