### ISSUE TITLE
0.9.2.1 Mod Browser NRE

### ISSUE THREAD

**Issue by Jofairden** [bluemagic123/tModLoader#145]
Issue thread for reference.
```
Object reference not set to an instance of an object.
   at Terraria.ModLoader.UI.UIModDownloadItem..ctor(String displayname, String name, String version, String author, String modreferences, ModSide modside, String download, Int32 downloads, Int32 hot, String timeStamp, Boolean update, Boolean updateIsDowngrade, Boolean exists)
   at Terraria.ModLoader.UI.UIModBrowser.PopulateFromJSON(List`1 modBuildProperties, String json)
```

**Comment by Jofairden** [comment]
Fixed (hopefully) 6f9a525b2d2ce42ed8ec07128ac6c91e6ff969b9
