### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by Apples1** [bluemagic123/tModLoader#165]
24/04/2017 19:37:11
System.DllNotFoundException: Unable to load DLL 'CSteamworks': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame(String[] args)

24/04/2017 19:37:17
System.DllNotFoundException: Unable to load DLL 'CSteamworks': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode)
   at Terraria.Program.LaunchGame(String[] args)
WHAT?

**Comment by bluemagic123** [comment]
Duplicate issue: #61
