### ISSUE TITLE
unable to load CSteamworks.dll

### ISSUE THREAD

**Issue by FierceDragon680** [bluemagic123/tModLoader#170]
idk how or why i just need help. also its in terraria 1.3.5 this is what it says:
System.EntryPointNotFoundException: Unable to find an entry point named 'Init' in DLL 'CSteamworks'.
   at Steamworks.NativeMethods.SteamAPI_Init()
   at Terraria.Social.Steam.CoreSocialModule.Initialize()
   at Terraria.Social.SocialAPI.Initializalize(Nullable'1 mode)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)

**Comment by JavidPack** [comment]
This is caused by 1.3.5 being installed. Please install the 1.3.5 compatible version of 0.9.2.3. For mac/linux instructions: https://forums.terraria.org/index.php?threads/1-3-tmodloader-a-modding-api.23726/page-842#post-1341266
