### ISSUE TITLE
cs0012: Missing reference to mscorlib 

### ISSUE THREAD

**Issue by Juptian** [bluemagic123/tModLoader#1964]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

When using the create mod option, attempting to build (or build & reload) I get an error saying that I am missing a reference to the ` mscorlib `, which is strange as I have had no problems with it working on other projects.

### Log File

```
[23:12:36] [1/INFO] [tML]: Starting tModLoader v0.11.8.5 Windows client (2021-11-13)
[23:12:36] [1/INFO] [tML]: Running on NetFramework 4.8
[23:12:36] [1/INFO] [tML]: Executable: O:\SteamLibrary\steamapps\common\tModLoader\tModLoader.exe
[23:12:36] [1/INFO] [tML]: Working Directory: O:\SteamLibrary\steamapps\common\tModLoader
[23:12:36] [1/INFO] [tML]: Launch Parameters: 
[23:12:36] [1/INFO] [tML]: Developer mode enabled
[23:12:36] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[23:12:36] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[23:12:36] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[23:12:36] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[23:12:36] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[23:12:37] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[23:12:37] [1/INFO] [tML]: Checking Steam installation...
[23:12:37] [1/INFO] [tML]: Steam installation OK.
[23:12:37] [1/INFO] [Terraria]: Found Terraria steamapp install at: O:\SteamLibrary\steamapps\common\Terraria
[23:12:37] [1/INFO] [Terraria]: Steam Cloud Quota: 105.8 MB available
[23:12:38] [1/DEBUG] [Terraria]: Graphics Device: NVIDIA GeForce RTX 2060 {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
[23:12:38] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach -> HiDef, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[23:12:39] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[23:12:39] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[23:12:39] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[23:12:39] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[23:12:40] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[23:12:41] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 1920, Height: 480 -> 1057, Fullscreen: False, Display: \\.\DISPLAY1
[23:12:41] [10/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[23:12:41] [10/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[23:12:41] [10/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[23:12:41] [8/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[23:12:41] [10/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[23:12:42] [7/INFO] [Terraria]: JIT loading finished
[23:12:42] [8/INFO] [tML]: Unloading mods
[23:12:43] [8/INFO] [tML]: Finding Mods...
[23:12:43] [8/INFO] [tML]: Instantiating Mods...
[23:12:43] [8/INFO] [tML]: Initializing: ModLoader v0.11.8.5
[23:12:43] [8/INFO] [tML]: Setting up...
[23:12:43] [8/INFO] [tML]: Loading: ModLoader v0.11.8.5
[23:12:43] [8/INFO] [tML]: RAM usage: 876.7 MB
[23:12:43] [8/INFO] [tML]: Adding Recipes...
[23:14:00] [15/INFO] [tML]: Reading properties: Insanity
[23:14:00] [15/INFO] [tML]: Building: Insanity
[23:14:00] [15/INFO] [tML]: Compiling Insanity.XNA.dll
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: RoslynWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: RoslynWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: RoslynWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[23:14:00] [15/DEBUG] [tML]: Assembly Resolve: System.Reflection.Metadata, Version=1.4.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a -> System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
[23:14:01] [15/DEBUG] [tML]: Assembly Resolve:  -> Microsoft.CodeAnalysis.CSharp.resources, Version=2.10.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
[23:14:01] [15/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> Microsoft.CodeAnalysis.CSharp.resources, Version=2.10.0.0, Culture=en-US, PublicKeyToken=31bf3856ad364e35
[23:14:01] [15/DEBUG] [tML]: Assembly Resolve:  -> Microsoft.CodeAnalysis.CSharp.resources, Version=2.10.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
[23:14:01] [15/DEBUG] [tML]: Assembly Resolve: Microsoft.CodeAnalysis.CSharp, Version=2.10.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 -> Microsoft.CodeAnalysis.CSharp.resources, Version=2.10.0.0, Culture=en, PublicKeyToken=31bf3856ad364e35
[23:14:01] [15/INFO] [tML]: Compilation finished with 2 errors and 1 warnings
[23:14:01] [15/WARN] [tML]: warning CS8021: No value for RuntimeMetadataVersion found. No assembly containing System.Object was found nor was a value for RuntimeMetadataVersion specified through options.
[23:14:01] [15/ERROR] [tML]: C:\Users\jupti\Documents\My Games\Terraria\ModLoader\Mod Sources\Insanity\Insanity.cs(5,25) : error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
[23:14:01] [15/ERROR] [tML]: C:\Users\jupti\Documents\My Games\Terraria\ModLoader\Mod Sources\Insanity\Insanity.cs(5,14) : error CS0518: Predefined type 'System.Void' is not defined or imported
[23:14:01] [15/ERROR] [tML]: Compiling Insanity.XNA.dll failed with 2 errors and 1 warnings
Error: C:\Users\jupti\Documents\My Games\Terraria\ModLoader\Mod Sources\Insanity\Insanity.cs(5,25) : error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Terraria.ModLoader.Exceptions.BuildException: Compiling Insanity.XNA.dll failed with 2 errors and 1 warnings
Error: C:\Users\jupti\Documents\My Games\Terraria\ModLoader\Mod Sources\Insanity\Insanity.cs(5,25) : error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
   at Terraria.ModLoader.Core.ModCompile.CompileMod(BuildingMod mod, String outputPath, IDictionary`2 refs, Boolean xna) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 680
   at Terraria.ModLoader.Core.ModCompile.BuildModForPlatform(BuildingMod mod, Boolean xna) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 554
   at Terraria.ModLoader.Core.ModCompile.Build(BuildingMod mod) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 412
   at Terraria.ModLoader.Core.ModCompile.Build(String modFolder) in tModLoader\Terraria.ModLoader.Core\ModCompile.cs:line 369
   at Terraria.ModLoader.UI.UIBuildMod.<>c__DisplayClass5_0.<Build>b__0(ModCompile mc) in tModLoader\Terraria.ModLoader.UI\UIBuildMod.cs:line 31
   at Terraria.ModLoader.UI.UIBuildMod.BuildMod(Action`1 buildAction, Boolean reload) in tModLoader\Terraria.ModLoader.UI\UIBuildMod.cs:line 67
[23:14:02] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:\Users\jupti\Documents\My Games\Terraria\ModLoader\Logs\client.log" 
```

### Steps to reproduce

1. Open up tmodloader (Terraria ver 1.3.5.3, TmodLoader ver 0.11.8.5)
2. Head over to the ` mod sources ` tab
3. Hit the ` Create mod ` button
4. Give it a name, an author, and optionally a basic weapon
5. Hit build & reload (or simply build)

### Expected Behavior

I do not believe I should be getting an error as all the videos I've seen on this has had no error.

### Actual Behavior

I am getting an error that states the following:
` Error: C:\Users\jupti\Documents\My Games\Terraria\ModLoader\Mod Sources\Insanity\Insanity.cs(5,25) : error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
Terraria.ModLoader.Exceptions.BuildException: Compiling Insanity.XNA.dll failed with 2 errors and 1 warnings `

### Reproduction frequency

I am able to reproduce this 100% of the time, and I cannot find a solution that works on google.

### Additional Information

* I have Visual Studio Community 2022 installed, I've uninstalled & reinstalled it. 
* I've tried editing ` tmodloader.targets ` to have it as a project reference. 
* I am able to locate the DLL, so it definitely exists, and this is the only time I've run into this issue without being able to fix it. 
* I've uninstalled & reinstalled, as well as verified the integrity of both Terraria's and TmodLoader's files, all to no avail.

The mods name is ` Insanity ` as I have no other way to describe it so far.

**Comment by Juptian** [comment]
I have fixed the solution by:
Reinstalling VS 2022 community once again, repairing it, creating a new solution from scratch, importing all of the dependencies, and building before opening tModLoader.

**Comment by Juptian** [comment]
The issue has not been solved, tModLoader still cannot build.

**Comment by Juptian** [comment]
Genuine solution found: Uninstall Visual Studio 2022, and install visual studio 2019.

Install link to VS2019: https://docs.microsoft.com/en-us/visualstudio/releases/2019/history#installing-an-earlier-release

**Comment by ultrawhal3** [comment]
Thanks for this. I've been very frustrated at this for a while.

**Comment by Hoopou** [comment]
Still not fixed (2022/01/29)
