### ISSUE TITLE
Bug in 1.4 branch: Method not found: 'Void Terraria.Player.QuickSpawnItem(Int32, Int32)'

### ISSUE THREAD

**Issue by NuarkNoir** [bluemagic123/tModLoader#1966]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

I decided to create a mod, which will open all the treasure bags, crates, and other same type things.
There is my code: [code sample on gist](https://gist.github.com/NuarkNoir/7c773fc1b3f3a8dca54b8ace7f3d67a1)
When I press key "H" (default keybind for my mod) this exception appears:
![image](https://user-images.githubusercontent.com/13624284/141689706-03fb78d6-312b-4e0d-95fa-63b19e1a146f.png)
And in `client.log`:
```
[23:35:29] [Main Thread/INFO] [Terraria]: Entering world with player: Пушка, IsCloud=False, Size=4200x1200
[23:35:33] [Main Thread/WARN] [tML]: Бесшумно пойманное исключение: 
System.MissingMethodException: Method not found: 'Void Terraria.Player.QuickSpawnItem(Int32, Int32)'.
   at MagicStorage.Items.RadiantJewelBag.OpenVanillaBag(String context, Player player, Int32 arg)
   at Terraria.ModLoader.ItemLoader.OpenVanillaBag(String context, Player player, Int32 arg) in tModLoader\Terraria\ModLoader\ItemLoader.cs:line 1139
   at Terraria.Player.OpenBossBag(Int32 type) in tModLoader\Terraria\Player.cs:line 4057
   at AutoOpener.AOModPlayer.DoOpening() in AutoOpener\AOModPlayer.cs:line 30
   at Terraria.ModLoader.PlayerLoader.ProcessTriggers(Player player, TriggersSet triggersSet) in tModLoader\Terraria\ModLoader\PlayerLoader.cs:line 515
   at Terraria.GameInput.TriggersSet.CopyInto(Player p) in tModLoader\Terraria\GameInput\TriggersSet.cs:line 603
   at Terraria.Player.Update(Int32 i) in tModLoader\Terraria\Player.cs:line 17528
   at Terraria.Main.DoUpdateInWorld(Stopwatch sw) in tModLoader\Terraria\Main.cs:line 13246
   at DMD<Terraria.Main::DoUpdate>(Main this, GameTime& gameTime)
   at Creativetools.src.Tools.TimeControl.TimeControl.Main_DoUpdate(orig_DoUpdate orig, Main self, GameTime& gameTime) in Creativetools\src\Tools\TimeControl\TimeControl.cs:line 89
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12457
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 543
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 880
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 207
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 173
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 52
```

### Log File

[23:34:19] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.2.3+0.12-1.4-Alpha-0dcd1a1312119ef3e94ab43ede116a950172a81c-5249410273373461866
[23:34:19] [Main Thread/INFO] [tML]: Log date: 14.11.2021
[23:34:19] [Main Thread/INFO] [tML]: Running on Windows X64 NetCore 6.0.0
[23:34:19] [Main Thread/INFO] [tML]: Executable: C:\SteamLibrary\steamapps\common\tModLoader\tModLoader.dll
[23:34:19] [Main Thread/INFO] [tML]: Working Directory: C:\SteamLibrary\steamapps\common\tModLoader
[23:34:19] [Main Thread/INFO] [tML]: Developer mode enabled
[23:34:20] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=21.10.0.0, Culture=neutral, PublicKeyToken=null -> FNA3D
[23:34:20] [Main Thread/DEBUG] [tML]: 	attempting load C:\SteamLibrary\steamapps\common\tModLoader\Libraries\Native\Windows\FNA3D.dll
[23:34:20] [Main Thread/DEBUG] [tML]: 	success
[23:34:21] [Main Thread/INFO] [tML]: Checking Steam installation...
[23:34:21] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=15.0.1.0, Culture=neutral, PublicKeyToken=null -> steam_api64
[23:34:21] [Main Thread/DEBUG] [tML]: 	attempting load C:\SteamLibrary\steamapps\common\tModLoader\Libraries\Native\Windows\steam_api64.dll
[23:34:21] [Main Thread/DEBUG] [tML]: 	success
[23:34:21] [Main Thread/INFO] [tML]: Steam installation OK.
[23:34:21] [Main Thread/INFO] [Terraria]: Found Terraria steamapp install at: C:\SteamLibrary\steamapps\common\Terraria
[23:34:21] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 152.6 MB available
[23:34:21] [Main Thread/INFO] [FNA]: FNA3D Driver: D3D11
[23:34:21] [Main Thread/INFO] [FNA]: D3D11 Adapter: NVIDIA GeForce GTX 1060
[23:34:22] [Main Thread/DEBUG] [Terraria]: Device Created, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: Reach, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[23:34:22] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: Reach, Width: 800 -> 1920, Height: 480 -> 1027, Fullscreen: False, Display: \\.\DISPLAY1
[23:34:22] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=21.10.0.0, Culture=neutral, PublicKeyToken=null -> FAudio
[23:34:22] [Main Thread/DEBUG] [tML]: 	attempting load C:\SteamLibrary\steamapps\common\tModLoader\Libraries\Native\Windows\FAudio.dll
[23:34:22] [Main Thread/DEBUG] [tML]: 	success
[23:34:35] [.NET ThreadPool Worker/INFO] [tML]: Unloading mods
[23:34:35] [.NET ThreadPool Worker/INFO] [tML]: Поиск модов...
[23:34:35] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: Autofish
[23:34:35] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: AutoOpener
[23:34:35] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: ChatSource
[23:34:35] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: CheatSheet
[23:34:35] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: CompareItemStats
[23:34:35] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: Creativetools
[23:34:36] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: imkreborn
[23:34:36] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: MagicStorage
[23:34:36] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: OreExcavator
[23:34:36] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: QuickResearch
[23:34:36] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: SimpleLevels
[23:34:36] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: WMITF
[23:34:36] [.NET ThreadPool Worker/INFO] [tML]: Инстанция модов...
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: ModLoader v0.12
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: Autofish v0.2.2
[23:34:37] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Projectile::FishingCheck() modified by Autofish
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: AutoOpener v0.1
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: ChatSource v1.0.4
[23:34:37] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.GameContent.UI.Chat.RemadeChatMonitor::AddNewMessage(string, Color, int) added by ChatSource
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: CheatSheet v0.7.0.5
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: CompareItemStats v0.1.0.4
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: Creativetools v4.4.6
[23:34:37] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Player::RecalculateLuck() added by Creativetools
[23:34:37] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Graphics.Renderers.LegacyPlayerRenderer::DrawPlayerInternal(Camera, Player, Vector2, float, Vector2, float, float, float, bool) added by Creativetools
[23:34:37] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Main::DoUpdate(ref GameTime) added by Creativetools
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: imkreborn v0.1
[23:34:37] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: MagicStorage v0.5.1.2
[23:34:37] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.NetMessage::SendData(int, int, int, NetworkText, int, float, float, float, int, int, int) added by MagicStorage
[23:34:37] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.MessageBuffer::GetData(int, int, out int) added by MagicStorage
[23:34:38] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Recipe::FindRecipes(bool) added by MagicStorage
[23:34:38] [.NET ThreadPool Worker/WARN] [tML]: Granted native detouring access to MagicStorage
[23:34:38] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck_ApplyHoldStyle_Inner(float, Item, Rectangle) modified by MagicStorage
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: OreExcavator v0.6.1
[23:34:38] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::KillTile_PlaySounds(int, int, bool, Tile) modified by OreExcavator
[23:34:38] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::KillWall_PlaySounds(int, int, Tile) modified by OreExcavator
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: QuickResearch v1.6.2
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: SimpleLevels v2.0.0
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: WMITF v2.6.3
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Настройка...
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: ModLoader v0.12
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: Autofish v0.2.2
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: AutoOpener v0.1
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: ChatSource v1.0.4
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: CheatSheet v0.7.0.5
[23:34:38] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: CompareItemStats v0.1.0.4
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: Creativetools v4.4.6
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: imkreborn v0.1
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: MagicStorage v0.5.1.2
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: OreExcavator v0.6.1
[23:34:39] [.NET ThreadPool Worker/DEBUG] [OreExcavator]: Looking for modded ores and gems to whitelist...
[23:34:39] [.NET ThreadPool Worker/DEBUG] [OreExcavator]: Saving config 'OreExcavatorConfig_Client' changes...
[23:34:39] [.NET ThreadPool Worker/DEBUG] [OreExcavator]: Config 'OreExcavatorConfig_Client' saved, and updated!
[23:34:39] [.NET ThreadPool Worker/DEBUG] [OreExcavator]: Done whitelisting modded content.
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: QuickResearch v1.6.2
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: SimpleLevels v2.0.0
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: WMITF v2.6.3
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: RAM usage: 1,1 GB
[23:34:39] [.NET ThreadPool Worker/INFO] [tML]: Загрузка рецептов модов...
[23:35:13] [.NET ThreadPool Worker/INFO] [tML]: Чтение свойств: AutoOpener
[23:35:13] [.NET ThreadPool Worker/INFO] [tML]: Сборка: AutoOpener
[23:35:13] [.NET ThreadPool Worker/INFO] [tML]: Компиляция AutoOpener.dll
[23:35:15] [.NET ThreadPool Worker/INFO] [tML]: Компиляция завершена с 0 ошибками(-ой) и 0 предупреждениями(-ем)
[23:35:15] [.NET ThreadPool Worker/INFO] [tML]: Упаковка: AutoOpener
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Enabling Mod: AutoOpener
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Unloading mods
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Which Mod Is This From (WMITF)
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Simple Levels
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Quick research
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Ore Excavator - The 1.4 Successor to Vein Miner
[23:35:17] [.NET ThreadPool Worker/DEBUG] [tML]: Unloaded 0 hooks, 2 detours and 2 native detours from OreExcavator in Ore Excavator - The 1.4 Successor to Vein Miner
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Magic Storage
[23:35:17] [.NET ThreadPool Worker/DEBUG] [tML]: Unloaded 3 hooks, 4 detours and 4 native detours from MagicStorage in Magic Storage
[23:35:17] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck_ApplyHoldStyle_Inner(float, Item, Rectangle) unmodified by MagicStorage
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: imkSushi's Reborn
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Creative tools
[23:35:17] [.NET ThreadPool Worker/DEBUG] [tML]: Unloaded 3 hooks, 3 detours and 3 native detours from Creativetools in Creative tools
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Compare Item Stats
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Cheat Sheet (for 1.4)
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Chat Source
[23:35:17] [.NET ThreadPool Worker/DEBUG] [tML]: Unloaded 1 hooks, 1 detours and 1 native detours from ChatSource in Chat Source
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Auto Opener
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: Autofish
[23:35:17] [.NET ThreadPool Worker/DEBUG] [tML]: Unloaded 0 hooks, 1 detours and 1 native detours from Autofish in Autofish
[23:35:17] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Projectile::FishingCheck() unmodified by Autofish
[23:35:17] [.NET ThreadPool Worker/INFO] [tML]: Выгрузка мода: tModLoader
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "Autofish" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #2 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "AutoOpener" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #3 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "ChatSource" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #4 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "CheatSheet" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #5 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "CompareItemStats" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #6 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "Creativetools" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #7 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "imkreborn" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #8 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "MagicStorage" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #9 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "OreExcavator" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #10 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "QuickResearch" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #11 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "SimpleLevels" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #12 refused to finalize
[23:35:18] [.NET ThreadPool Worker/WARN] [tML]: "WMITF" Terraria.ModLoader.Core.AssemblyManager+ModLoadContext #13 refused to finalize
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Поиск модов...
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: Autofish
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: AutoOpener
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: ChatSource
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: CheatSheet
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: CompareItemStats
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: Creativetools
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: imkreborn
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: MagicStorage
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: OreExcavator
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: QuickResearch
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: SimpleLevels
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Загрузка сборки: WMITF
[23:35:18] [.NET ThreadPool Worker/INFO] [tML]: Инстанция модов...
[23:35:19] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: ModLoader v0.12
[23:35:19] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: Autofish v0.2.2
[23:35:19] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Projectile::FishingCheck() modified by Autofish
[23:35:19] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: AutoOpener v0.1
[23:35:19] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: ChatSource v1.0.4
[23:35:19] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.GameContent.UI.Chat.RemadeChatMonitor::AddNewMessage(string, Color, int) added by ChatSource
[23:35:19] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: CheatSheet v0.7.0.5
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: CompareItemStats v0.1.0.4
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: Creativetools v4.4.6
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Player::RecalculateLuck() added by Creativetools
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Graphics.Renderers.LegacyPlayerRenderer::DrawPlayerInternal(Camera, Player, Vector2, float, Vector2, float, float, float, bool) added by Creativetools
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Main::DoUpdate(ref GameTime) added by Creativetools
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: imkreborn v0.1
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: MagicStorage v0.5.1.2
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.NetMessage::SendData(int, int, int, NetworkText, int, float, float, float, int, int, int) added by MagicStorage
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.MessageBuffer::GetData(int, int, out int) added by MagicStorage
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Recipe::FindRecipes(bool) added by MagicStorage
[23:35:20] [.NET ThreadPool Worker/WARN] [tML]: Granted native detouring access to MagicStorage
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck_ApplyHoldStyle_Inner(float, Item, Rectangle) modified by MagicStorage
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: OreExcavator v0.6.1
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::KillTile_PlaySounds(int, int, bool, Tile) modified by OreExcavator
[23:35:20] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::KillWall_PlaySounds(int, int, Tile) modified by OreExcavator
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: QuickResearch v1.6.2
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: SimpleLevels v2.0.0
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Инициализация мода: WMITF v2.6.3
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Настройка...
[23:35:20] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: ModLoader v0.12
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: Autofish v0.2.2
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: AutoOpener v0.1
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: ChatSource v1.0.4
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: CheatSheet v0.7.0.5
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: CompareItemStats v0.1.0.4
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: Creativetools v4.4.6
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: imkreborn v0.1
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: MagicStorage v0.5.1.2
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: OreExcavator v0.6.1
[23:35:21] [.NET ThreadPool Worker/DEBUG] [OreExcavator]: Looking for modded ores and gems to whitelist...
[23:35:21] [.NET ThreadPool Worker/DEBUG] [OreExcavator]: Saving config 'OreExcavatorConfig_Client' changes...
[23:35:21] [.NET ThreadPool Worker/DEBUG] [OreExcavator]: Config 'OreExcavatorConfig_Client' saved, and updated!
[23:35:21] [.NET ThreadPool Worker/DEBUG] [OreExcavator]: Done whitelisting modded content.
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: QuickResearch v1.6.2
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: SimpleLevels v2.0.0
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: Загрузка мода: WMITF v2.6.3
[23:35:21] [.NET ThreadPool Worker/INFO] [tML]: RAM usage: 1,1 GB
[23:35:22] [.NET ThreadPool Worker/INFO] [tML]: Загрузка рецептов модов...
[23:35:27] [.NET ThreadPool Worker/INFO] [StatusText]: Сброс игровых объектов...
[23:35:28] [.NET ThreadPool Worker/INFO] [StatusText]: Загрузка данных мира...
[23:35:28] [.NET ThreadPool Worker/INFO] [StatusText]: Настройка жидкостей...
[23:35:29] [.NET ThreadPool Worker/INFO] [StatusText]: Загрузка данных карты...
[23:35:29] [.NET ThreadPool Worker/INFO] [StatusText]: Создание карты...
[23:35:29] [Main Thread/INFO] [Terraria]: Entering world with player: Пушка, IsCloud=False, Size=4200x1200
[23:35:33] [Main Thread/WARN] [tML]: Бесшумно пойманное исключение: 
System.MissingMethodException: Method not found: 'Void Terraria.Player.QuickSpawnItem(Int32, Int32)'.
   at MagicStorage.Items.RadiantJewelBag.OpenVanillaBag(String context, Player player, Int32 arg)
   at Terraria.ModLoader.ItemLoader.OpenVanillaBag(String context, Player player, Int32 arg) in tModLoader\Terraria\ModLoader\ItemLoader.cs:line 1139
   at Terraria.Player.OpenBossBag(Int32 type) in tModLoader\Terraria\Player.cs:line 4057
   at AutoOpener.AOModPlayer.DoOpening() in AutoOpener\AOModPlayer.cs:line 30
   at Terraria.ModLoader.PlayerLoader.ProcessTriggers(Player player, TriggersSet triggersSet) in tModLoader\Terraria\ModLoader\PlayerLoader.cs:line 515
   at Terraria.GameInput.TriggersSet.CopyInto(Player p) in tModLoader\Terraria\GameInput\TriggersSet.cs:line 603
   at Terraria.Player.Update(Int32 i) in tModLoader\Terraria\Player.cs:line 17528
   at Terraria.Main.DoUpdateInWorld(Stopwatch sw) in tModLoader\Terraria\Main.cs:line 13246
   at DMD<Terraria.Main::DoUpdate>(Main this, GameTime& gameTime)
   at Creativetools.src.Tools.TimeControl.TimeControl.Main_DoUpdate(orig_DoUpdate orig, Main self, GameTime& gameTime) in Creativetools\src\Tools\TimeControl\TimeControl.cs:line 89
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12457
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 543
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 880
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 207
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 173
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 52

### Steps to reproduce

1. Compile and activate the mod
2. Bind button for "AutoOpener's" `Activate` action
3. Open any world with any character
4. Get yourself any boss loot bag
5. Press the button, you bonded on step 2

### Expected Behavior

All loot bags should disappear and player should get loot.

### Actual Behavior

It fails with exception

### Reproduction frequency

All the time

### Additional Information

Nothing else.

**Comment by Ishigh1** [comment]
That's normal, it's a magic storage issue (of it being not updated), not a tmod issue

**Comment by NuarkNoir** [comment]
> That's normal, it's a magic storage issue (of it being not updated), not a tmod issue

Yes, can confirm. Disabled all mods to test for incompatibilities but not this Magic Storage.
