### ISSUE TITLE
fatal crash 

### ISSUE THREAD

**Issue by SwarmAsylum** [bluemagic123/tModLoader#1996]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

when i select a character the game crashes 

### Log File

[00:42:00] [1/INFO] [tML]: Starting tModLoader v0.11.8.5 Windows client (11/25/2021)
[00:42:00] [1/INFO] [tML]: Running on NetFramework 4.8
[00:42:00] [1/INFO] [tML]: Executable: G:\SteamLibrary\steamapps\common\tModLoader\tModLoader.exe
[00:42:00] [1/INFO] [tML]: Working Directory: G:\SteamLibrary\steamapps\common\tModLoader
[00:42:00] [1/INFO] [tML]: Launch Parameters: 
[00:42:00] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[00:42:00] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[00:42:00] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[00:42:00] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[00:42:00] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[00:42:01] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[00:42:01] [1/INFO] [tML]: Checking Steam installation...
[00:42:01] [1/INFO] [tML]: Steam installation OK.
[00:42:01] [1/INFO] [Terraria]: Found Terraria steamapp install at: D:\Steam\steamapps\common\Terraria
[00:42:01] [1/INFO] [Terraria]: Steam Cloud Quota: 142.3 MB available
[00:42:02] [1/DEBUG] [Terraria]: Graphics Device: NVIDIA GeForce GTX 1660 Ti {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
[00:42:02] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach -> HiDef, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[00:42:03] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[00:42:03] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[00:42:03] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[00:42:03] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[00:42:04] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[00:42:04] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 720, Height: 480, Fullscreen: False -> True, Display: \\.\DISPLAY1
[00:42:05] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 720 -> 1920, Height: 480 -> 1080, Fullscreen: True, Display: \\.\DISPLAY1
[00:42:07] [16/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[00:42:07] [16/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[00:42:07] [15/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[00:42:07] [15/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[00:42:07] [7/INFO] [Terraria]: JIT loading finished
[00:42:08] [15/INFO] [tML]: Unloading mods
[00:42:08] [15/INFO] [tML]: Finding Mods...
[00:42:08] [15/INFO] [tML]: Sandboxing: AutoReroll
[00:42:08] [15/INFO] [tML]: Sandboxing: AutoTrash
[00:42:08] [15/INFO] [tML]: Sandboxing: CalamityMod
[00:42:09] [15/INFO] [tML]: Sandboxing: Bags
[00:42:09] [15/INFO] [tML]: Sandboxing: BossChecklist
[00:42:09] [15/INFO] [tML]: Sandboxing: Census
[00:42:09] [15/INFO] [tML]: Sandboxing: Fargowiltas
[00:42:09] [15/INFO] [tML]: Sandboxing: RecipeBrowser
[00:42:09] [15/INFO] [tML]: Sandboxing: SmartDoors
[00:42:09] [15/INFO] [tML]: Sandboxing: StarsAbove
[00:42:09] [15/INFO] [tML]: Instantiating Mods...
[00:42:10] [15/WARN] [tML]: Granted native detouring access to Fargowiltas_0
[00:42:10] [15/DEBUG] [tML]: Hook Terraria.ModLoader.ModContent::LoadModContent(CancellationToken, Action`1) -> Fargowiltas.Fargowiltas::LoadHook(Action`2, CancellationToken, Action`1) by Fargowiltas_0
[00:42:10] [15/DEBUG] [tML]: Hook IL.Terraria.ModLoader.ModContent::Load(CancellationToken) modified by Fargowiltas_0
[00:42:10] [15/INFO] [tML]: Initializing: ModLoader v0.11.8.5
[00:42:10] [15/INFO] [tML]: Initializing: AutoReroll v1.6.2.1
[00:42:11] [15/INFO] [tML]: Initializing: AutoTrash v0.5.2
[00:42:11] [15/INFO] [tML]: Initializing: CalamityMod v1.5.0.2
[00:42:15] [15/DEBUG] [tML]: Assembly Resolve: CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[00:42:15] [15/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[00:42:15] [15/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=19.12.19.1 -> 20.11.16.1
[00:42:15] [15/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[00:42:15] [15/WARN] [tML]: Upgraded Reference MonoMod.RuntimeDetour -> Version=19.12.19.1 -> 20.11.16.1
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook On.Terraria.NPC::ApplyTileCollision(bool, Vector2, int, int) added by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Player::Hurt(PlayerDeathReason, int, int, bool, bool, bool, int) modified by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Player::DashMovement() modified by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Player::Update_NPCCollision() modified by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook On.Terraria.Wiring::Teleport() added by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Main::DrawInterface_40_InteractItemIcon() modified by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook On.Terraria.Item::AffixName() added by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook On.Terraria.Projectile::NewProjectile(float, float, float, float, int, int, float, int, float, float) added by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook On.Terraria.Main::DrawCursor(Vector2, bool) added by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Player::QuickHeal() modified by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Player::QuickMana() modified by CalamityMod_0
[00:42:15] [15/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck(int) modified by CalamityMod_0
[00:42:16] [15/DEBUG] [tML]: Hook IL.Terraria.Player::AddBuff(int, int, bool) modified by CalamityMod_0
[00:42:16] [15/DEBUG] [tML]: Hook IL.Terraria.Main::DoDraw(GameTime) modified by CalamityMod_0
[00:42:16] [15/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by CalamityMod_0
[00:42:16] [15/DEBUG] [tML]: Hook IL.Terraria.Main::DrawTiles(bool, int) modified by CalamityMod_0
[00:42:17] [15/DEBUG] [tML]: Hook IL.Terraria.GameContent.Liquid.LiquidRenderer::InternalDraw(SpriteBatch, Vector2, int, float, bool) modified by CalamityMod_0
[00:42:17] [15/DEBUG] [tML]: Hook IL.Terraria.Main::oldDrawWater(bool, int, float) modified by CalamityMod_0
[00:42:17] [15/DEBUG] [tML]: Hook IL.Terraria.WaterfallManager::DrawWaterfall(SpriteBatch, int, float) modified by CalamityMod_0
[00:42:17] [15/DEBUG] [tML]: Hook On.Terraria.NPC::Collision_DecideFallThroughPlatforms() added by CalamityMod_0
[00:42:17] [15/DEBUG] [tML]: Hook IL.Terraria.Main::DamageVar(float) modified by CalamityMod_0
[00:42:17] [15/DEBUG] [tML]: Hook IL.Terraria.NPC::scaleStats() modified by CalamityMod_0
[00:42:18] [15/DEBUG] [tML]: Hook IL.Terraria.Projectile::Damage() modified by CalamityMod_0
[00:42:18] [15/DEBUG] [tML]: Hook IL.Terraria.Projectile::AI_001() modified by CalamityMod_0
[00:42:18] [15/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateJumpHeight() modified by CalamityMod_0
[00:42:18] [15/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[00:42:18] [15/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[00:42:19] [15/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[00:42:19] [15/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateManaRegen() modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Pyramid(int, int) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.WorldGen::DungeonHalls(int, int, ushort, int, bool) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook On.Terraria.WorldGen::SmashAltar(int, int) added by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.WorldGen::hardUpdateWorld(int, int) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Chlorophyte(int, int) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.Item::Prefix(int) modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.NPC::SpawnNPC() modified by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook On.Terraria.Main::InitLifeBytes() added by CalamityMod_0
[00:42:20] [15/DEBUG] [tML]: Hook IL.Terraria.NPC::NPCLoot() modified by CalamityMod_0
[00:42:21] [15/INFO] [tML]: Initializing: Bags v2.7.3
[00:42:21] [15/INFO] [tML]: Initializing: BossChecklist v1.1.6.1
[00:42:21] [15/DEBUG] [tML]: Hook On.Terraria.GameContent.Events.DD2Event::WinInvasionInternal() added by BossChecklist_0
[00:42:21] [15/INFO] [BossChecklist]: Boss Log integration messages will not be logged.
[00:42:21] [15/INFO] [tML]: Initializing: Census v0.3.1
[00:42:21] [15/DEBUG] [tML]: Assembly Resolve: Census_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.5.19.1, Culture=neutral, PublicKeyToken=null
[00:42:21] [15/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=19.5.19.1 -> 20.11.16.1
[00:42:21] [15/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime_SpawnTownNPCs() modified by Census_0
[00:42:21] [15/DEBUG] [tML]: Assembly Resolve: Census_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.10.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[00:42:21] [15/WARN] [tML]: Upgraded Reference Mono.Cecil -> Version=0.10.3.0 -> 0.11.3.0
[00:42:22] [15/INFO] [tML]: Initializing: RecipeBrowser v0.8.9
[00:42:22] [15/DEBUG] [tML]: Hook On.Terraria.Recipe::FindRecipes() added by RecipeBrowser_0
[00:42:22] [15/DEBUG] [tML]: Hook On.Terraria.Player::AdjTiles() added by RecipeBrowser_0
[00:42:22] [15/INFO] [tML]: Initializing: SmartDoors v1.3.3
[00:42:22] [15/DEBUG] [tML]: Assembly Resolve: SmartDoors_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[00:42:22] [15/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=20.5.14.1 -> 20.11.16.1
[00:42:22] [15/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by SmartDoors_0
[00:42:22] [15/DEBUG] [tML]: Assembly Resolve: SmartDoors_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[00:42:22] [15/WARN] [tML]: Upgraded Reference Mono.Cecil -> Version=0.11.2.0 -> 0.11.3.0
[00:42:22] [15/DEBUG] [tML]: Hook IL.Terraria.Player::DashMovement() modified by SmartDoors_0
[00:42:22] [15/INFO] [tML]: Initializing: StarsAbove v0.9.6
[00:42:26] [15/INFO] [StarsAbove]: 'I've always wanted to write text in crash logs.' -A
[00:42:26] [15/INFO] [StarsAbove]: 'Eh? Doesn't that make you look like you caused it..?' -E
[00:42:26] [15/INFO] [tML]: Initializing: Fargowiltas v2.4.2
[00:42:27] [15/INFO] [tML]: Setting up...
[00:42:27] [15/INFO] [tML]: Loading: ModLoader v0.11.8.5
[00:42:27] [15/INFO] [tML]: Loading: AutoReroll v1.6.2.1
[00:42:27] [15/INFO] [tML]: Loading: AutoTrash v0.5.2
[00:42:27] [15/INFO] [tML]: Loading: CalamityMod v1.5.0.2
[00:42:28] [15/INFO] [CalamityMod]: ModLoader version > 0.11.7.7 detected. Mechworm UUID workaround is disabled.
[00:42:28] [15/INFO] [tML]: Loading: Bags v2.7.3
[00:42:28] [15/DEBUG] [tML]: Assembly Resolve: Bags_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[00:42:28] [15/INFO] [tML]: Loading: BossChecklist v1.1.6.1
[00:42:28] [15/INFO] [tML]: Loading: Census v0.3.1
[00:42:28] [15/INFO] [tML]: Loading: RecipeBrowser v0.8.9
[00:42:28] [15/INFO] [tML]: Loading: SmartDoors v1.3.3
[00:42:28] [15/INFO] [tML]: Loading: StarsAbove v0.9.6
[00:42:29] [15/INFO] [tML]: Loading: Fargowiltas v2.4.2
[00:42:29] [15/INFO] [tML]: RAM usage: 2.6 GB
[00:42:29] [15/INFO] [tML]: Adding Recipes...
[00:42:29] [15/DEBUG] [tML]: Assembly Resolve:  -> RecipeBrowser_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[00:42:29] [15/DEBUG] [tML]: Assembly Resolve:  -> RecipeBrowser_0, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[00:42:32] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.GameContent.UI.States.UIWorldSelect.<>c.<UpdateWorldsList>b__13_0(WorldFileData x, WorldFileData y)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList()
   at Terraria.GameContent.UI.States.UIWorldSelect.OnActivate()
   at Terraria.UI.UIElement.Activate()
   at Terraria.UI.UserInterface.SetState(UIState state)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at DMD<Terraria.Main::DoDraw>(Main this, GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[00:42:32] [1/WARN] [tML]: Silently Caught Exception: 
System.InvalidOperationException: Failed to compare two elements in the array.
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList()
   at Terraria.GameContent.UI.States.UIWorldSelect.OnActivate()
   at Terraria.UI.UIElement.Activate()
   at Terraria.UI.UserInterface.SetState(UIState state)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at DMD<Terraria.Main::DoDraw>(Main this, GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[00:42:32] [1/ERROR] [Terraria]: System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.GameContent.UI.States.UIWorldSelect.<>c.<UpdateWorldsList>b__13_0(WorldFileData x, WorldFileData y)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList()
   at Terraria.GameContent.UI.States.UIWorldSelect.OnActivate()
   at Terraria.UI.UIElement.Activate()
   at Terraria.UI.UserInterface.SetState(UIState state)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at DMD<Terraria.Main::DoDraw>(Main this, GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
[00:42:32] [1/FATAL] [Terraria]: Main engine crash
System.InvalidOperationException: Failed to compare two elements in the array. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.GameContent.UI.States.UIWorldSelect.<>c.<UpdateWorldsList>b__13_0(WorldFileData x, WorldFileData y)
   at System.Array.FunctorComparer`1.Compare(T x, T y)
   at System.Collections.Generic.ArraySortHelper`1.SwapIfGreater(T[] keys, IComparer`1 comparer, Int32 a, Int32 b)
   at System.Collections.Generic.ArraySortHelper`1.IntroSort(T[] keys, Int32 lo, Int32 hi, Int32 depthLimit, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.IntrospectiveSort(T[] keys, Int32 left, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   --- End of inner exception stack trace ---
   at System.Collections.Generic.ArraySortHelper`1.Sort(T[] keys, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList()
   at Terraria.GameContent.UI.States.UIWorldSelect.OnActivate()
   at Terraria.UI.UIElement.Activate()
   at Terraria.UI.UserInterface.SetState(UIState state)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at DMD<Terraria.Main::DoDraw>(Main this, GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()

### Steps to reproduce

1. start the game 
2. click single player 
3. select character 

### Expected Behavior

it should be bringing me to world select 

### Actual Behavior

game crashes 

### Reproduction frequency

100% of the time

**Comment by Solxanich** [comment]
Same root cause of #1993

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
