### ISSUE TITLE
Pressing Esc on "Load Failed!" Message Causes a Crash

### ISSUE THREAD

**Issue by absoluteAquarian** [bluemagic123/tModLoader#2064]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### Description

When loading a world, should the load and backup load fail (resulting in the "Load Failed! No Backup Found." message appearing) and you press the Escape key, the game crashes due to trying to create the `client.log` file when it already exists.

### Log File

```
[12:48:54] [1/WARN] [tML]: Silently Caught Exception: 
System.IO.IOException: Cannot create "C:\Users\jruss\OneDrive\Documents\My Games\Terraria\ModLoader\Logs\client.log" because a file or directory with the same name already exists.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   at System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   at System.IO.Directory.CreateDirectory(String path)
   at Terraria.Utils.TryCreatingDirectory(String folderPath)
   at Terraria.Utils.OpenFolder(String folderPath)
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)
```

### Steps to reproduce

1. Write faulty code in `ModWorld.Load()` which would cause the "Load Failed! No Backup Found." message to appear.  Example:  Calling `Last()` on an `IEnumerable<T>` instance with zero elements.
2. Get the aforementioned message to appear ingame.
3. Press the `Esc` key.
4. Crash

### Expected Behavior

Preferable behaviour would be booting the player back to the world selection menu.

### Actual Behavior

The game crashes.

### Reproduction frequency

100% of the time

### Additional Information

n/a

**Comment by JavidPack** [comment]
I don't know when, but this is fixed. I think I remember it being hooked up to a file path instead of the folder path.
