### ISSUE TITLE
MacOS server hangs

### ISSUE THREAD

**Issue by piecubed** [bluemagic123/tModLoader#2066]
### Version

Latest public-1.4-alpha

### OS

Mac

### Platform

Steam

### Description

Not able to host a game through steam on MacOS

### Log File

[01:17:59] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "/path/to/tModLoader/dotnet/6.0" tModLoader.dll -server -autoshutdown -password "" -lang 1 -world "/path/to/Terraria/ModLoader/Beta/Worlds/apathetic_pain.wld" -worldrollbackstokeep 2 -modpath "/path/to/Terraria/ModLoader/Beta/Mods" -steam -localsteamid 76561198308983749 -lobby friends
[01:17:59] [TCP Client Thread/INFO] [Terraria]: Connecting to 127.0.0.1:7777
The file /path/to/tModLoader/dotnet/6.0 does not exist.
Connection refused [::ffff:127.0.0.1]:7777 (see client.log for full trace)
[01:18:00] [TCP Client Thread/WARN] [tML]: Silently Caught Exception: 
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Connection refused [::ffff:127.0.0.1]:7777
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at Terraria.Net.Sockets.TcpSocket.Terraria.Net.Sockets.ISocket.Connect(RemoteAddress address) in tModLoader\Terraria\Net\Sockets\TcpSocket.cs:line 51
   at Terraria.Netplay.TcpClientLoop() in tModLoader\Terraria\Netplay.cs:line 411
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

### Steps to reproduce

1.  Open tModLoader on MacOS.
2. Start a Host and Play server with any player/world/settings/password.
3. Watch the sun not move for the rest of your life.

### Expected Behavior

Server should be started

### Actual Behavior

Indefinitely hangs

### Reproduction frequency

Always, tested on other computer with fresh installation as well

**Comment by Solxanich** [comment]
Fixed in #2084
