### ISSUE TITLE
Teach modders correct usage of Main.NewText and BroadcastChatMessage in Multiplayer

### ISSUE THREAD

**Issue by AlexanderDMoon** [bluemagic123/tModLoader#2067]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### Description

My mod, Ancient's Arsenal (internally called AlexsAssortedArsenal) uses CheckDead on Eye of Cthulhu, Queen Bee, Queen Slime and all of the Mechanical Bosses (through MechBossAny) to display a one-off text broadcast using Main.NewText. I was told that the issue seems to be directly connected to using Main.NewText, but they were unsure why it was being thrown in the first place. Also, killing the relevant bosses with the Butcher function in Cheat Sheet makes them vanish entirely. Killing them with a weapon, however, still causes their gores and the text to appear, but in either case, no loot drops.

### Log File

[22:23:00] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.UI.Chat.ChatMessageContainer.Refresh() in tModLoader\Terraria\UI\Chat\ChatMessageContainer.cs:line 55
   at Terraria.UI.Chat.ChatMessageContainer.SetContents(String text, Color color, Int32 widthLimitInPixels) in tModLoader\Terraria\UI\Chat\ChatMessageContainer.cs:line 29
   at Terraria.GameContent.UI.Chat.RemadeChatMonitor.AddNewMessage(String text, Color color, Int32 widthLimitInPixels) in tModLoader\Terraria\GameContent\UI\Chat\RemadeChatMonitor.cs:line 32
   at Terraria.GameContent.UI.Chat.RemadeChatMonitor.NewText(String newText, Byte R, Byte G, Byte B) in tModLoader\Terraria\GameContent\UI\Chat\RemadeChatMonitor.cs:line 23
   at Terraria.Main.NewText(String newText, Byte R, Byte G, Byte B) in tModLoader\Terraria\Main.cs:line 50670
   at Terraria.Main.NewText(Object o, Nullable`1 color) in tModLoader\Terraria\Main.cs:line 50666
   at AlexsAssortedArsenal.AAAGlobalNPC.CheckDead(NPC npc) in AlexsAssortedArsenal\AAAGlobalNPC.cs:line 33
   at Terraria.ModLoader.NPCLoader.CheckDead(NPC npc) in tModLoader\Terraria\ModLoader\NPCLoader.cs:line 367
   at Terraria.NPC.checkDead() in tModLoader\Terraria\NPC.cs:line 55953
   at Terraria.NPC.StrikeNPC(Int32 Damage, Single knockBack, Int32 hitDirection, Boolean crit, Boolean noEffect, Boolean fromNet) in tModLoader\Terraria\NPC.cs:line 64233
   at DMD<Terraria.MessageBuffer::GetData>(MessageBuffer this, Int32 start, Int32 length, Int32& messageType)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex) in tModLoader\Terraria\NetMessage.cs:line 2188
   at Terraria.Netplay.UpdateServerInMainThread() in tModLoader\Terraria\Netplay.cs:line 64
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 12700
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12589
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods) in tModLoader\Terraria\Main.cs:line 4578
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4114
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 210
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 174
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 60
   at System.Threading.Thread.StartCallback()

[22:23:00] [Main Thread/WARN] [Terraria]: Error on message Terraria.MessageBuffer

### Steps to reproduce

1. Start a Multiplayer server with Ancient's Arsenal active.
2. Summon Eye of Cthulhu, Queen Bee, the Mechanical Bosses or Queen Slime with either Cheat Sheet or with their summons.
3. Kill the boss with a weapon or by butchering it with Cheat Sheet.

### Expected Behavior

What SHOULD be happening is that text should be appearing when one of the aforementioned bosses is killed. For example, killing the Queen Bee broadcasts "Crystalline slime resonates throughout the Hallow...", and the other three also display a message.

### Actual Behavior

When butchered with Cheat Sheet, the boss vanishes and no text displays. When killed with a weapon, the boss's gores appear and the text that should broadcast, _does_ broadcast, but in both cases, no loot is dropped and the broadcast will repeat on successive kills.

### Reproduction frequency

100% of the time when in Multiplayer. Does not require multiple people to be connected; You can be entirely alone in your own server.

### Additional Information

This error log that I was provided was most likely grabbed from a failed Queen Bee kill.

**Comment by Solxanich** [comment]
From discussing in Discord on a fix option:

"should use a forwarder method instead that takes a bool for BroadcastAll. Internalize both Main.NewText and Broadcast message.
if you had a forwarder method then,
client, true = broadcast all
client, false = display to the client only
server, true = broadcast all
server, false = throws exception or safe noop"

The last case is the cause of the exception. Main.newtext shouldn't be called on the server. This exception reflects that.

Please use Worldgen.BroadcastText/appropriate checks of Main.dedServ in the interim

**Comment by JavidPack** [comment]
Seems like the fix to this is to show correct usage in ExampleMod and documentation of `Main.NewText` and `BroadcastChatMessage`

**Comment by Chicken-Bones** [comment]
I'd be happy to make `Main.NewText` no-op on server. Better than a crash.

**Comment by Chicken-Bones** [comment]
Done in cbeea118d0eab392550d3bba0173a4b77cd1e8ff
