### ISSUE TITLE
Cannot connect to server - works from a sample app

### ISSUE THREAD

**Issue by Breakable** [bluemagic123/tModLoader#2134]
### Version

Latest Official

### OS

Windows

### Platform

GOG

### This bug affects

Mod capability as a Modder

### Description

Connection to web server is not working when trying to access the mod browser or upload a mod. I tried reproducing an issue form another .net application and it seems to work fine. I also compared wireshark logs and the request seems to be identical, but the one from TML is not replied to by the server. It is possible the issue is on the cloudfare firewall fingerprinting identifying the requests from TML as an attack.
Tried on both steam and gog versions also tried on different PC

### Log File

[20:41:59] [1/INFO] [tML]: Starting tModLoader v0.11.8.6 Windows client (05/02/2022)
[20:41:59] [1/INFO] [tML]: Running on NetFramework 4.8
[20:41:59] [1/INFO] [tML]: Executable: D:\GOG Games\Terraria\tModLoader.exe
[20:41:59] [1/INFO] [tML]: Working Directory: D:\GOG Games\Terraria
[20:41:59] [1/INFO] [tML]: Launch Parameters: 
[20:41:59] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[20:41:59] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[20:41:59] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[20:41:59] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[20:41:59] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[20:41:59] [1/INFO] [tML]: Checking GOG or manual installation...
[20:42:00] [1/INFO] [tML]: GOG or manual installation OK.
[20:42:00] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[20:42:01] [1/DEBUG] [Terraria]: Graphics Device: Intel(R) HD Graphics 620 {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
[20:42:01] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach -> HiDef, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[20:42:02] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[20:42:02] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[20:42:03] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[20:42:03] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[20:42:03] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[20:42:04] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800, Height: 480 -> 600, Fullscreen: False, Display: \\.\DISPLAY1
[20:42:06] [9/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[20:42:06] [9/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[20:42:07] [9/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[20:42:07] [9/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[20:42:07] [6/INFO] [Terraria]: JIT loading finished
[20:42:08] [9/INFO] [tML]: Unloading mods
[20:42:08] [9/INFO] [tML]: Finding Mods...
[20:42:08] [9/INFO] [tML]: Instantiating Mods...
[20:42:08] [9/INFO] [tML]: Initializing: ModLoader v0.11.8.6
[20:42:10] [9/INFO] [tML]: Setting up...
[20:42:10] [9/INFO] [tML]: Loading: ModLoader v0.11.8.6
[20:42:10] [9/INFO] [tML]: RAM usage: 852.1 MB
[20:42:10] [9/INFO] [tML]: Adding Recipes...
[20:42:12] [6/DEBUG] [tML]: Web Request: http://javid.ddns.net/tModLoader/listmods.php
[20:42:34] [15/WARN] [tML]: Silently Caught Exception: 
System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallbackWrapper(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

[20:42:34] [15/WARN] [tML]: Silently Caught Exception: 
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallbackWrapper(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

[20:42:34] [15/WARN] [tML]: Silently Caught Exception: 
System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.CompleteCallback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.HttpWebRequest.SetResponse(Exception E)
   at System.Net.HttpWebRequest.SetAndOrProcessResponse(Object responseOrException)
   at System.Net.ConnectionReturnResult.SetResponses(ConnectionReturnResult returnResult)
   at System.Net.Connection.ReadComplete(Int32 bytesRead, WebExceptionStatus errorStatus)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallbackWrapper(IAsyncResult asyncResult)
   at System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   at System.Net.ContextAwareResult.Complete(IntPtr userToken)
   at System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   at System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)

### Steps to reproduce

1. start TMD
2. open mod browser 

### Expected Behavior

Showing list of mods

### Actual Behavior

Timeout

### Reproduction frequency

Always

**Comment by ignas-g** [comment]
Could I get an update on this?

**Comment by JavidPack** [comment]
As far as I know, it is working for others. I'm not seeing anything strange in the log that could explain the issue.

**Comment by Breakable** [comment]
Could you point me to the particular code on latest version that is making the request, so I could debug it myself @JavidPack

**Comment by JavidPack** [comment]
On 1.3, this is where things start <https://github.com/tModLoader/tModLoader/blob/1.3/patches/tModLoader/Terraria.ModLoader.UI.ModBrowser/UIModBrowser.cs#L242>

**Comment by Breakable** [comment]
Any idea where the 1.4 version does it - it seems the code is very different. I think that is required for current Terraria or not?

**Comment by JavidPack** [comment]
1.4 retrieves the data directly from the steam interop, so it's not relevant to this issue.

**Comment by Chicken-Bones** [comment]
Closing due to inactivity. Please re-open if you want to work on this, but no more updates for tML 1.3 are planned.
