### ISSUE TITLE
System.Exception: Could not get a proper content length for DownloadFile

### ISSUE THREAD

**Issue by NathanNeverDreams** [bluemagic123/tModLoader#2156]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Using the Mod Browser it is not possible to download one specific mod. (Maybe the issue is present with other mods as well?) Me and my friends tried about 10 popular mods, all downloaded and installed just fine, except this one.

The issue manifested with the mod MagicStorage.tmod

tModLoader Mod Browser initiates the download progress but then immediately returns back to the Mod Browser and the mod appears there as before(available for download). Tried several times(including restarting tModLoader) and two of my friends tried several times(on different networks and different Steam accounts). Same exact issue with the exact same error in **client.log**:

```
[19:31:44] [1/DEBUG] [tML]: Web Request: http://javid.ddns.net/tModLoader/download.php?Down=mods/MagicStorage.tmod&tls12=y
[19:31:44] [1/DEBUG] [tML]: Web Request: http://javid.ddns.net/tModLoader/download.php?Down=mods/MagicStorage.tmod&tls12=y
[19:31:44] [21/DEBUG] [tML]: Web Request: https://www.dropbox.com/s/0sqd5tkth8no61k/MagicStorage.tmod?dl=1
[19:31:44] [21/DEBUG] [tML]: Web Request: https://www.dropbox.com/s/dl/0sqd5tkth8no61k/MagicStorage.tmod
[19:31:45] [21/DEBUG] [tML]: Web Request: https://uca52c2ead4781591cefbe56baff.dl.dropboxusercontent.com/cd/0/get/Bf4zNeeu9Jq_mRUfoD03zRuOP2o8YKU4PWL_zqbbkeGug1VM1qt8hwFLrc-nMzAr9bJyEDNKOgIYkWCKSW3mf04Xpy94wiSLoI58xMD5EItubzMWSQ3Q0Gszxsw6OrpHqE7nueFQ12PgMmOQuQ_T7rls/file?dl=1#
[19:31:45] [10/ERROR] [tML]: Could not get a proper content length for DownloadFile[Magic Storage]
[19:31:45] [10/WARN] [tML]: Silently Caught Exception: 
System.Exception: Could not get a proper content length for DownloadFile[Magic Storage]
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.HandleResponse(WebResponse response, CancellationToken token)
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.<>c__DisplayClass21_0.<Download>b__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[19:31:45] [10/ERROR] [tML]: There was a problem downloading the mod Magic Storage
System.AggregateException: One or more errors occurred. ---> System.Exception: Could not get a proper content length for DownloadFile[Magic Storage]
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.HandleResponse(WebResponse response, CancellationToken token)
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.<>c__DisplayClass21_0.<Download>b__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.Exception: Could not get a proper content length for DownloadFile[Magic Storage]
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.HandleResponse(WebResponse response, CancellationToken token)
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.<>c__DisplayClass21_0.<Download>b__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---
```

It is possible to download the file by copying the Dropbox URL from the log to a web browser. But I wanted to understand why this happens rather then actually get the mod? 

I'm attaching the full log file too.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/8093352/client.log)

### Steps to reproduce

1. Find 'Magic Storage' in Mod Browser
2. Press Download button
3. Download stops with no warning and user is returned to Mod Browser as if nothing happened

### Expected Behavior

Successfully downloaded and installed mod

### Actual Behavior

Download cancels with no warning to the user

### Reproduction frequency

Every time

### Additional Information

I've reported the issue also to the mod author:

https://forums.terraria.org/index.php?threads/magic-storage.56294/post-2611701

But got instructed to report to the tModLoader team instead.

**Comment by Wittano** [comment]
I think, this problem on author side, because downloading files from one link(https://uca52c2ead4781591cefbe56baff.dl.dropboxusercontent.com/cd/0/get/Bf4zNeeu9Jq_mRUfoD03zRuOP2o8YKU4PWL_zqbbkeGug1VM1qt8hwFLrc-nMzAr9bJyEDNKOgIYkWCKSW3mf04Xpy94wiSLoI58xMD5EItubzMWSQ3Q0Gszxsw6OrpHqE7nueFQ12PgMmOQuQ_T7rls/file?dl=1#) is ended 410 status. It's meant, author removed or hide some files and he didn't update himself manifest

**Comment by NathanNeverDreams** [comment]
> **I think, this problem on author side, because downloading files from one link(https://uca52c2ead4781591cefbe56baff.dl.dropboxusercontent.com/cd/0/get/Bf4zNeeu9Jq_mRUfoD03zRuOP2o8YKU4PWL_zqbbkeGug1VM1qt8hwFLrc-nMzAr9bJyEDNKOgIYkWCKSW3mf04Xpy94wiSLoI58xMD5EItubzMWSQ3Q0Gszxsw6OrpHqE7nueFQ12PgMmOQuQ_T7rls/file?dl=1#) is ended 410 status. It's meant, author removed or hide some files and he didn't update himself manifest**



It might not be the authors fault.... I've reported it to him/them on the forum:
https://forums.terraria.org/index.php?threads/magic-storage.56294/page-80

And people there say it happens with other mods too....

That Dropbox address is I believe randomly generated every time... At least in my tests... if I repeatedly try requesting the same mod in Mod Browser, that final Dropbox address is always random... So it is expected for that link to give 410 status as it is only a temporary one... But the one before(also in log) is static, this one:

https://www.dropbox.com/s/dl/0sqd5tkth8no61k/MagicStorage.tmod

And that one can be used for downloading the mod manually through the web browser(Chrome for example), but it still does not explain why the download fails through the Mod Browser in tModLoader

**Comment by JavidPack** [comment]
This should be fixed in the latest.
