### ISSUE TITLE
Can't Update a Mod (Dragon Ball Terraria)

### ISSUE THREAD

**Issue by DarkJDL** [bluemagic123/tModLoader#2231]
### Version

Latest Official

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I go to the Mod Browser, There is the Update all button, I click on it, I see "Dragon Ball Terraria" but the Bar doesn't fill up and the process is completed instantly. 

No update actually happens and the Log File shows an error.

I also tried to download the mod manually, However it seems tModLoader decides to revert to the previous version on its own whenever I launch the game through steam.

### Log File

[13:49:47] [1/DEBUG] [tML]: Web Request: http://javid.ddns.net/tModLoader/download.php?Down=mods/DBZMOD.tmod&tls12=y
[13:49:47] [21/ERROR] [tML]: There was a problem downloading the mod Dragon Ball Terraria
System.AggregateException: One or more errors occurred. ---> System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.<>c__DisplayClass21_0.<Download>b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.<>c__DisplayClass21_0.<Download>b__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.<>c__DisplayClass21_0.<Download>b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.<>c__DisplayClass21_0.<Download>b__1(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
---> (Inner Exception #0) System.Net.WebException: The remote server returned an error: (503) Server Unavailable.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at Terraria.ModLoader.UI.DownloadManager.DownloadFile.<>c__DisplayClass21_0.<Download>b__0(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)<---

### Steps to reproduce

1. download Terraria on Steam
2. download tModLoader 1.3[Beta] on steam
3. launch tModLoader
4. go to the Mod Browser and download Dragon Ball Terraria Mod (There hasn't been an update for nearly 2 years so I was on version 1.0.9.4 for a long time it has recently updated to 1.0.9.8) I do not know whether or not it will download 1.0.9.4 or if it will just not work the same way I cannot update to 1.0.9.8
5. Check your Log file for the same error I got?

### Expected Behavior

I'm thinking the mod should just download,
Right now it seems like there's a mirror issue? or something?
Other mods seem to download properly, so I don't know.

### Actual Behavior

The Mod browser shows "Dragon Ball Terraria" trying to download to the next version, but the bar never fills up and the error in the log file is created.

### Reproduction frequency

Every single time I click on "Update All"  or on the actual "Update" button of Dragon Ball Terraria Mod itself.

### Additional Information

I'm using these other mods
[
  "AccessoryProgress",
  "AccessorySlotsPlus",
  "AccessorySwapper",
  "AutoReroll",
  "AutoTrash",
  "BaseLibrary",
  "BetterManaRegenFixed",
  "BetterTaxes",
  "Boss_Unconsumables",
  "BossChecklist",
  "BrighterTorches",
  "Census",
  "FluidLibrary",
  "ContainerLibrary",
  "DBZMOD",
  "DoubleOreDrop",
  "EmblemMod",
  "EZWorkshop",
  "FlowerNPC",
  "fortunemod",
  "GlobalTrinkets",
  "GoldensMisc",
  "HeroSickle",
  "ItemChecklist",
  "WebmilioCommons",
  "Leveled",
  "LeveledRPGForever",
  "worldtilesflags",
  "LumberjackNPC",
  "MaxStackPlus",
  "MoreAccessories",
  "MoreEndlessAmmo",
  "MoreEndlessAmmoPlus",
  "NoFishTimer",
  "OreConvert",
  "PrefixesPlus",
  "RecipeBrowser",
  "ReducedGrinding",
  "ReforgeArmor",
  "Scabbards",
  "ShopExpander",
  "ShorterRespawn",
  "TPUnchained",
  "UpgradedAccessories",
  "Wireless",
  "XItemStats",
  "MechTransfer"
]

**Comment by JavidPack** [comment]
This issue relates to 1.3 tModLoader, which is now legacy and will not receive any further non-critical updates or bug fixes. Please give 1.4 tModLoader a try, there is a good chance this issue might be resolved there already. If you find that 1.4 tModLoader has a similar issue, feel free to open a new issue and fill out the issue template so we can once again track this issue. This issue will now be closed.
