### ISSUE TITLE
UIModItem.DeleteMod doesn't work anymore with new paths

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#2240]
### Version

Latest public-1.4-alpha

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Due to the .tmod being nested in a folder now, it seems the logic here is wrong, needs to be fixed.

Causes the game to flicker when attempted.

Example error:

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.UI.UIModItem.DeleteMod(UIMouseEvent evt, UIElement listeningElement) in tModLoader\Terraria\ModLoader\UI\UIModItem.cs:line 495
   at Terraria.UI.UIElement.Click(UIMouseEvent evt) in tModLoader\Terraria\UI\UIElement.cs:line 377
   at Terraria.UI.UserInterface.Update(GameTime time) in tModLoader\Terraria\UI\UserInterface.cs:line 141
   at Terraria.Main.UpdateUIStates(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 13140
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 12789
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12557
```

**Comment by Solxanich** [comment]
fixed in https://github.com/tModLoader/tModLoader/commit/49bea95dae222c12a0409c8bc8fa73be7953180a
