### ISSUE TITLE
Latest build fails to start on Linux (Ubuntu 18.04 + 20.04) - Error Message: Fatal error. Internal CLR error. (0x80131506)

### ISSUE THREAD

**Issue by Bizzaro** [bluemagic123/tModLoader#2394]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

OS: Ubuntu 18.04
Spun up fresh Ubuntu 20.04 VM, same issue

Fresh copy of terraria server overlayed with tModLoader won't start when executing `./start-tModLoaderServer.sh`

### Log File

Verifying .NET....
Logging to /opt/terraria-modded/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
Success!
Verifying .NET platform specific libraries are correctly deployed
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/opt/terraria-modded/dotnet/6.0.0"
Launched Using Local Dotnet
Fatal error. Internal CLR error. (0x80131506)
   at System.Delegate.CreateDelegateNoSecurityCheck(System.Type, System.Object, System.RuntimeMethodHandle)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(System.Type)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetMethodHandle(System.Reflection.MethodBase)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.GetIdentifiable(System.Reflection.MethodBase)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform.GetIdentifiable(System.Reflection.MethodBase)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform.Pin(System.Reflection.MethodBase)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCore30Platform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNET60Platform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.Hook..ctor(System.Reflection.MethodBase, System.Reflection.MethodInfo, System.Object, MonoMod.RuntimeDetour.HookConfig ByRef)
   at MonoMod.RuntimeDetour.Hook..ctor(System.Reflection.MethodBase, System.Reflection.MethodInfo, System.Object, MonoMod.RuntimeDetour.HookConfig)
   at MonoMod.RuntimeDetour.Hook..ctor(System.Reflection.MethodBase, System.Reflection.MethodInfo, System.Object)
   at MonoMod.RuntimeDetour.Hook..ctor(System.Reflection.MethodBase, System.Delegate)
   at Terraria.ModLoader.Core.LoggingHooks.PrettifyStackTraceSources()
   at Terraria.ModLoader.Logging.LogStartup(Boolean)
   at Terraria.Program.LaunchGame(System.String[], Boolean)
   at MonoLaunch+<>c__DisplayClass2_0.<Main>b__0()
   at MonoLaunch.Main(System.String[])
[02:57:15] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[02:57:15] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.04.62.6|1.4-stable|Stable|20e1af7dfac9ac9be84e8e2409e3359e0e750aa7|5249556388522342804 built 5/1/2022 9:23 PM
[02:57:15] [Main Thread/INFO] [tML]: Log date: 5/19/2022
[02:57:15] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[02:57:15] [Main Thread/INFO] [tML]: Executable: /opt/terraria-modded/tModLoader.dll
[02:57:15] [Main Thread/INFO] [tML]: Working Directory: /opt/terraria-modded
[02:57:15] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt -steam -lobby private
[02:57:15] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt -steam -lobby private
[02:57:15] [Main Thread/DEBUG] [tML]: Assembly Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null
[02:13:32] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[02:13:32] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.04.62.6|1.4-stable|Stable|20e1af7dfac9ac9be84e8e2409e3359e0e750aa7|5249556388522342804 built 5/1/2022 9:23 PM
[02:13:32] [Main Thread/INFO] [tML]: Log date: 5/19/2022
[02:13:32] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[02:13:32] [Main Thread/INFO] [tML]: Executable: /opt/terraria-modded/tModLoader.dll
[02:13:32] [Main Thread/INFO] [tML]: Working Directory: /opt/terraria-modded
[02:13:32] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt -steam -lobby friends
[02:13:32] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt -steam -lobby friends
[02:13:32] [Main Thread/DEBUG] [tML]: Assembly Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null
[02:18:34] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[02:18:34] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.04.62.6|1.4-stable|Stable|20e1af7dfac9ac9be84e8e2409e3359e0e750aa7|5249556388522342804 built 5/1/2022 9:23 PM
[02:18:34] [Main Thread/INFO] [tML]: Log date: 5/19/2022
[02:18:34] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[02:18:34] [Main Thread/INFO] [tML]: Executable: /opt/terraria-modded/tModLoader.dll
[02:18:34] [Main Thread/INFO] [tML]: Working Directory: /opt/terraria-modded
[02:18:34] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt -steam -lobby friends
[02:18:34] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt -steam -lobby friends
[02:18:34] [Main Thread/DEBUG] [tML]: Assembly Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null
[02:18:37] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[02:18:37] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.04.62.6|1.4-stable|Stable|20e1af7dfac9ac9be84e8e2409e3359e0e750aa7|5249556388522342804 built 5/1/2022 9:23 PM
[02:18:37] [Main Thread/INFO] [tML]: Log date: 5/19/2022
[02:18:37] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[02:18:37] [Main Thread/INFO] [tML]: Executable: /opt/terraria-modded/tModLoader.dll
[02:18:37] [Main Thread/INFO] [tML]: Working Directory: /opt/terraria-modded
[02:18:37] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt -steam -lobby private
[02:18:37] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt -steam -lobby private
[02:18:37] [Main Thread/DEBUG] [tML]: Assembly Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null
[02:19:10] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[02:19:10] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.04.62.6|1.4-stable|Stable|20e1af7dfac9ac9be84e8e2409e3359e0e750aa7|5249556388522342804 built 5/1/2022 9:23 PM
[02:19:10] [Main Thread/INFO] [tML]: Log date: 5/19/2022
[02:19:10] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[02:19:10] [Main Thread/INFO] [tML]: Executable: /opt/terraria-modded/tModLoader.dll
[02:19:10] [Main Thread/INFO] [tML]: Working Directory: /opt/terraria-modded
[02:19:10] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt -steam -lobby friends
[02:19:10] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt -steam -lobby friends
[02:19:10] [Main Thread/DEBUG] [tML]: Assembly Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null
[02:55:52] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[02:55:52] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.04.62.6|1.4-stable|Stable|20e1af7dfac9ac9be84e8e2409e3359e0e750aa7|5249556388522342804 built 5/1/2022 9:23 PM
[02:55:52] [Main Thread/INFO] [tML]: Log date: 5/19/2022
[02:55:52] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[02:55:52] [Main Thread/INFO] [tML]: Executable: /opt/terraria-modded/tModLoader.dll
[02:55:52] [Main Thread/INFO] [tML]: Working Directory: /opt/terraria-modded
[02:55:52] [Main Thread/INFO] [tML]: Launch Parameters: -config serverconfig.txt -server -steam -lobby friends
[02:55:52] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -config serverconfig.txt -server -steam -lobby friends
[02:55:52] [Main Thread/DEBUG] [tML]: Assembly Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null
[02:57:11] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[02:57:11] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.04.62.6|1.4-stable|Stable|20e1af7dfac9ac9be84e8e2409e3359e0e750aa7|5249556388522342804 built 5/1/2022 9:23 PM
[02:57:11] [Main Thread/INFO] [tML]: Log date: 5/19/2022
[02:57:11] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[02:57:11] [Main Thread/INFO] [tML]: Executable: /opt/terraria-modded/tModLoader.dll
[02:57:11] [Main Thread/INFO] [tML]: Working Directory: /opt/terraria-modded
[02:57:11] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt
[02:57:11] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[02:57:12] [Main Thread/DEBUG] [tML]: Assembly Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.3.0.0, Culture=neutral, PublicKeyToken=null

### Steps to reproduce

1. Download fresh terraria server
2. Download fresh copy of 1.4 stable
3. Overlay tModLoader onto terraria server files
4. Execute the script `start-tModLoaderServer.sh`

### Expected Behavior

The server should start

### Actual Behavior

Crashing, script exits with `core dumped`
./start-tModLoader.sh: line 5: 16316 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh "$@"

### Reproduction frequency

100% of the time

**Comment by JavidPack** [comment]
> Fresh copy of terraria server overlayed with tModLoader won't start when executing `./start-tModLoaderServer.sh`

I'm not sure why you are downloading Terraria server and overlaying them together. I don't think we tell people to do that. If we are, tell me where and I'll fix the instructions.

Try only installing the tmodloader files to a fresh directory. If that doesn't work, we recently made big changes that might help your issue on the 1.4 Preview branch, give that a try.

**Comment by Chicken-Bones** [comment]
> Fresh copy of terraria server overlayed with tModLoader

This has been reported with the same bug a few times. We might see if there's anything we can do to auto-detect (ideally the problematic file) and put out a sensible error message

**Comment by Bizzaro** [comment]
Just got some time to come back to this. Thanks, it works now once I only use tMod files.

I think this page needs some edits to make it more beginner friendly - https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server, I'll create a PR once I get around to it. There's not really steps A-Z on how to configure a fresh install of Linux -> tMod server running.

I think this part is the most confusing - "desiredPath is the installation folder path name of your Terraria Server patched with tModLoader", it implies that you need to patch the stock server install.

**Comment by Chicken-Bones** [comment]
once upon a time, there was a one click setup server script. Solxan has added some instructions and a setup shell script in DedicatedServerUtils folder in your steamapps/tModLoader folder. Can you take a look and give your opinion on that?
