### ISSUE TITLE
[Critical - 1.4 preview] Sound-reliant enemies print errors and disappear

### ISSUE THREAD

**Issue by Ouroel** [bluemagic123/tModLoader#2430]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Anything sound-related prints errors

### Log File

[13:48:45] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.ModContent.SplitName(String name, String& domain, String& subName) in tModLoader\Terraria\ModLoader\ModContent.cs:line 65
   at Terraria.ModLoader.ModContent.Request[T](String name, AssetRequestMode mode) in tModLoader\Terraria\ModLoader\ModContent.cs:line 104
   at Terraria.Audio.SoundStyle.GetRandomSound() in tModLoader\Terraria\Audio\SoundStyle.TML.cs:line 229
   at Terraria.Audio.ActiveSound.Play() in tModLoader\Terraria\Audio\ActiveSound.cs:line 60
   at Terraria.Audio.SoundPlayer.Play(SoundStyle& style, Nullable`1 position) in tModLoader\Terraria\Audio\SoundPlayer.cs:line 63
   at Terraria.Audio.SoundEngine.PlaySound(Int32 type, Int32 x, Int32 y, Int32 Style, Single volumeScale, Single pitchOffset) in tModLoader\Terraria\Audio\SoundEngine.TML.cs:line 63
   at Terraria.Player.WOFTongue() in tModLoader\Terraria\Player.cs:line 16354
   at Terraria.Player.Update(Int32 i) in tModLoader\Terraria\Player.cs:line 20191
   at DMD<Terraria.Main::DoUpdateInWorld>(Main this, Stopwatch sw)
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 13018
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12573
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 485
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 886
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 223
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 188
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 60
   at System.Threading.Thread.StartCallback()

[13:49:45] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.ModContent.SplitName(String name, String& domain, String& subName) in tModLoader\Terraria\ModLoader\ModContent.cs:line 65
   at Terraria.ModLoader.ModContent.Request[T](String name, AssetRequestMode mode) in tModLoader\Terraria\ModLoader\ModContent.cs:line 104
   at Terraria.Audio.SoundStyle.GetRandomSound() in tModLoader\Terraria\Audio\SoundStyle.TML.cs:line 229
   at Terraria.Audio.ActiveSound.Play() in tModLoader\Terraria\Audio\ActiveSound.cs:line 60
   at Terraria.Audio.SoundPlayer.Play(SoundStyle& style, Nullable`1 position) in tModLoader\Terraria\Audio\SoundPlayer.cs:line 63
   at Terraria.Audio.SoundEngine.PlaySound(Int32 type, Int32 x, Int32 y, Int32 Style, Single volumeScale, Single pitchOffset) in tModLoader\Terraria\Audio\SoundEngine.TML.cs:line 63
   at Terraria.NPC.VanillaAI_Inner() in tModLoader\Terraria\NPC.cs:line 15718
   at Terraria.NPC.VanillaAI() in tModLoader\Terraria\NPC.cs:line 11210
   at Terraria.ModLoader.NPCLoader.NPCAI(NPC npc) in tModLoader\Terraria\ModLoader\NPCLoader.cs:line 241
   at Terraria.NPC.UpdateNPC_Inner(Int32 i) in tModLoader\Terraria\NPC.cs:line 69244
   at DMD<Terraria.Main::DoUpdateInWorld>(Main this, Stopwatch sw)
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 13018
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12573
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 485
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 886
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 223
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 188
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 60
   at System.Threading.Thread.StartCallback()

[13:49:45] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.DivideByZeroException: Attempted to divide by zero.
   at Terraria.NPC.VanillaAI_Inner() in tModLoader\Terraria\NPC.cs:line 16228
   at Terraria.NPC.VanillaAI() in tModLoader\Terraria\NPC.cs:line 11210
   at Terraria.ModLoader.NPCLoader.NPCAI(NPC npc) in tModLoader\Terraria\ModLoader\NPCLoader.cs:line 241
   at Terraria.NPC.UpdateNPC_Inner(Int32 i) in tModLoader\Terraria\NPC.cs:line 69244
   at DMD<Terraria.Main::DoUpdateInWorld>(Main this, Stopwatch sw)
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 13018
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12573
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 485
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 886
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 223
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 188
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 60
   at System.Threading.Thread.StartCallback()

### Steps to reproduce

Spawn WoF (when you have projectiles)
minions will despawn

After a while WoF will despawn

**Comment by Mirsario** [comment]
Fixed in #2432, thanks for reporting.
