### ISSUE TITLE
Tmodloader 1.4 wont launch

### ISSUE THREAD

**Issue by Wyattx46** [bluemagic123/tModLoader#2491]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

whenever i launch the game i get an error instead of the game

### Log File

6/3/2022 3:47:35 PM
System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Terraria.Main.InitTMLContentManager() in tModLoader\Terraria\Main.TML.cs:line 175
   at Terraria.Main.Initialize() in tModLoader\Terraria\Main.cs:line 5036
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 787
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 407
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 229

### Steps to reproduce

launch the game

### Expected Behavior

the game functioning

### Actual Behavior

an error pop up

### Reproduction frequency

always

### Additional Information

none

**Comment by Wyattx46** [comment]
forgot to add i have no mods installed

**Comment by xianhui3** [comment]
Does your vanilla game function? Your error log indicates it might be an issue with your vanilla installation.

**Comment by Wyattx46** [comment]
> Does your vanilla game function? Your error log indicates it might be an issue with your vanilla installation.

yes, 1,4 vanilla works just fine, as does 1.3 legacy tmodloader

**Comment by xianhui3** [comment]
Interesting... Can you upload the full logs file? The line of code that the error points to should just be fetching the Terraria installation directory folder.

`vanillaContentFolder = Path.Combine(Steam.GetSteamTerrariaInstallDir(), "Content");`

**Comment by Wyattx46** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/8856686/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/8856688/Launch.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/8856689/terrariasteamclient.log)

if this isnt what ur talking about i dont really understand :L

**Comment by xianhui3** [comment]
Your problem is that when tModLoader makes a call to the Steam API it can't find the Terraria installation directory. This is causing it to return a null value, which causes a fatal error due to the importance of located the vanilla installation folder. 

Have you checked if your Terraria installation is where it should be? Verifying the integrity of the base game should fix your issue.

**Comment by Wyattx46** [comment]
> Your problem is that when tModLoader makes a call to the Steam API it can't find the Terraria installation directory. This is causing it to return a null value, which causes a fatal error due to the importance of located the vanilla installation folder.
> 
> Have you checked if your Terraria installation is where it should be? Verifying the integrity of the base game should fix your issue.

i have tried verifying the game files for both tmodloader and base terraria, reinstallation of both, and moving which drive i have them installed on, nothing has worked

**Comment by xianhui3** [comment]
What's the file path for your Terraria installation? You can find it through steam using the browse local files function.

**Comment by Wyattx46** [comment]
C:\Program Files (x86)\Steam\steamapps\common\Terraria

**Comment by xianhui3** [comment]
Your tModLoader installation is on your D drive.

>Working Directory: D:\SteamLibrary\steamapps\common\tModLoader

**Comment by Wyattx46** [comment]
> Your tModLoader installation is on your D drive.
> 
> > Working Directory: D:\SteamLibrary\steamapps\common\tModLoader

i moved both to my c drive trying to fix, they are both as of this moment on my cdrive, and at the time of original message were both on my d drive, the same issue is persisting

**Comment by xianhui3** [comment]
Have you checked to ensure your Terraria installation has a folder called "Content"? Otherwise this is an issue on Steam's end, the line that's throwing the error is just a call to Steam's API.

**Comment by Wyattx46** [comment]
> Have you checked to ensure your Terraria installation has a folder called "Content"? Otherwise this is an issue on Steam's end, the line that's throwing the error is just a call to Steam's API.

there is a content folder

**Comment by xianhui3** [comment]
Your issue is on Steam's end then. There's not much anyone can do about it if it's a problem due to Steam's API.

**Comment by Wyattx46** [comment]
thats like a kick in the teeth, but thank you for your time, have a nice day

**Comment by Chicken-Bones** [comment]
@Wyattx46 a new build should be live in about 15 minutes. Please let me know if it fixes the issue for you.

**Comment by Wyattx46** [comment]
> @Wyattx46 a new build should be live in about 15 minutes. Please let me know if it fixes the issue for you.

there's new errors this time Dx
[20:22:46] [Main Thread/FATAL] [Terraria]: Main engine crash
System.ArgumentNullException: Value cannot be null. (Parameter 'path')
   at System.IO.Directory.GetParent(String path)
   at Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.GetListOfSubscribedItemsPaths() in tModLoader\Terraria\Social\Steam\WorkshopHelper.cs:line 65
   at Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh(WorkshopIssueReporter issueReporter) in tModLoader\Terraria\Social\Steam\WorkshopHelper.cs:line 113
   at Terraria.Social.Steam.WorkshopSocialModule.RefreshSubscriptionsAndPublishings() in tModLoader\Terraria\Social\Steam\WorkshopSocialModule.cs:line 54
   at Terraria.Social.Steam.WorkshopSocialModule.LoadEarlyContent() in tModLoader\Terraria\Social\Steam\WorkshopSocialModule.cs:line 50
   at Terraria.Main.LoadContent() in tModLoader\Terraria\Main.cs:line 8548
   at Terraria.Main.Initialize() in tModLoader\Terraria\Main.cs:line 5098
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 787
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 407
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 229
[20:22:46] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown
(im not subscribed to anything on the workshop for either game)

**Comment by Chicken-Bones** [comment]
15 mins again

**Comment by Wyattx46** [comment]
thank you for your time mr bones

**Comment by Wyattx46** [comment]
it worked! @Chicken-Bones
