### ISSUE TITLE
[1.4] Crash on entering world

### ISSUE THREAD

**Issue by sgkoishi** [bluemagic123/tModLoader#2531]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The game crashed when trying to enter a world with a message box:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Graphics.Shaders.MiscShaderData.Apply(Nullable`1 drawData) in tModLoader\Terraria\Graphics\Shaders\MiscShaderData.cs:line 30
   at Terraria.GameContent.Shaders.WaterShaderData.DrawWaves() in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 150
   at Terraria.GameContent.Shaders.WaterShaderData.StepLiquids() in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 104
   at Terraria.GameContent.Shaders.WaterShaderData.PreDraw(GameTime gameTime) in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 282
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48517
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48460
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 559
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 886
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 229
```

Tried with new world & player, but the problem persists.

### Log File

<details>
  <summary>Click to expand</summary>

```
[12:57:35] [Main Thread/INFO] [tML]: Save Are Located At: C:\Users\*** (username)\Documents\My Games\Terraria\tModLoader
[12:57:35] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.05.103.25|1.4-stable|Stable|1fe641ede62f30103912885d3997c2439c61832f|5249589079751535603 built 2022/6/9 1:28
[12:57:35] [Main Thread/INFO] [tML]: Log date: 2022/6/9
[12:57:35] [Main Thread/INFO] [tML]: Running on Windows X64 NetCore 6.0.0
[12:57:35] [Main Thread/INFO] [tML]: Executable: D:\SteamLibrary\steamapps\common\tModLoader\tModLoader.dll
[12:57:35] [Main Thread/INFO] [tML]: Working Directory: D:\SteamLibrary\steamapps\common\tModLoader
[12:57:35] [Main Thread/INFO] [tML]: Developer mode enabled
[12:57:36] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[12:57:36] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "D:\SteamLibrary\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" tModLoader.dll -terrariasteamclient 1304
[12:57:36] [Main Thread/DEBUG] [TerrariaSteamClient]: Recv: init_success
[12:57:36] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: acknowledged
[12:57:37] [Main Thread/INFO] [FNA]: Controller 0: Controller (Xbox One For Windows), GUID: 5e04ff02, Mapping: 030000005e040000ff02000000007200,*,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,platform:Windows
[12:57:37] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 115.3 MB available
[12:57:37] [Main Thread/INFO] [FNA]: FNA3D Driver: D3D11
[12:57:37] [Main Thread/INFO] [FNA]: D3D11 Adapter: NVIDIA GeForce RTX 3050 Ti Laptop GPU
[12:57:38] [Main Thread/DEBUG] [Terraria]: Device Created, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: Reach, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[12:57:38] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: Reach, Width: 800 -> 1920, Height: 480 -> 1001, Fullscreen: False, Display: \\.\DISPLAY1
[12:57:55] [.NET ThreadPool Worker/INFO] [tML]: Unloading mods
[12:57:56] [.NET ThreadPool Worker/INFO] [tML]: Finding Mods...
[12:57:56] [.NET ThreadPool Worker/INFO] [tML]: Instantiating Mods...
[12:57:56] [.NET ThreadPool Worker/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.5.103.25
[12:57:57] [.NET ThreadPool Worker/INFO] [tML]: Setting up...
[12:57:57] [.NET ThreadPool Worker/INFO] [tML]: Loading: ModLoader (tModLoader) v2022.5.103.25
[12:57:57] [.NET ThreadPool Worker/INFO] [tML]: RAM usage: 754.6 MB
[12:57:57] [.NET ThreadPool Worker/INFO] [tML]: Adding Recipes...
[12:58:22] [.NET ThreadPool Worker/INFO] [StatusText]: Loading world data:
[12:58:22] [.NET ThreadPool Worker/INFO] [StatusText]: Settling liquids
[12:58:22] [Main Thread/INFO] [Terraria]: Entering world with player: ..., IsCloud=False, Size=4200x1200
[12:58:23] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Graphics.Shaders.MiscShaderData.Apply(Nullable`1 drawData) in tModLoader\Terraria\Graphics\Shaders\MiscShaderData.cs:line 30
   at Terraria.GameContent.Shaders.WaterShaderData.DrawWaves() in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 150
   at Terraria.GameContent.Shaders.WaterShaderData.StepLiquids() in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 104
   at Terraria.GameContent.Shaders.WaterShaderData.PreDraw(GameTime gameTime) in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 282
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48517
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48449
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 559
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 886
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 229
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 194
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at System.Threading.Thread.StartCallback()

[12:58:23] [Main Thread/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Graphics.Shaders.MiscShaderData.Apply(Nullable`1 drawData) in tModLoader\Terraria\Graphics\Shaders\MiscShaderData.cs:line 30
   at Terraria.GameContent.Shaders.WaterShaderData.DrawWaves() in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 150
   at Terraria.GameContent.Shaders.WaterShaderData.StepLiquids() in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 104
   at Terraria.GameContent.Shaders.WaterShaderData.PreDraw(GameTime gameTime) in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 282
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48517
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48460
[12:58:23] [Main Thread/FATAL] [Terraria]: Main engine crash
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Graphics.Shaders.MiscShaderData.Apply(Nullable`1 drawData) in tModLoader\Terraria\Graphics\Shaders\MiscShaderData.cs:line 30
   at Terraria.GameContent.Shaders.WaterShaderData.DrawWaves() in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 150
   at Terraria.GameContent.Shaders.WaterShaderData.StepLiquids() in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 104
   at Terraria.GameContent.Shaders.WaterShaderData.PreDraw(GameTime gameTime) in tModLoader\Terraria\GameContent\Shaders\WaterShaderData.cs:line 282
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48517
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48460
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 559
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 886
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 415
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 229
[12:58:23] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown
```
</details>

### Steps to reproduce

Launch the game, select or create a world, select or create a player, enter the world

### Expected Behavior

Enter the game

### Actual Behavior

Crashed with the message box

### Reproduction frequency

Always

### Additional Information

Repost from user @977690305
No mods enabled (as shown in the log); no resource pack.
Tried un-re-installing tML and verifying the integrity of vanilla Terraria but no luck.
From the logs it seems to have a controller (`Xbox One For Windows`)

**Comment by Zmedaris** [comment]
Stopping by to add that I just ran into the same problem on my first time trying to load a world in tmodloader. As it was a very new and large update, I decided to run the game with no mods first to scratch any potential issues. I can't find much other information on this problem, so leaving a comment here to reinforce the existence of the problem is all I can think to do.

![dotnet_O5TPJK7qDr](https://user-images.githubusercontent.com/12032854/177032288-0ddf1dad-924b-453c-ac80-99d7edd950e0.png)

As you can see, the content of the error message is very similar aside from some code lines changing and probably other stuff my lame brain can't pick up. I cannot figure out the problem. I've fiddled with graphic settings and a couple other things, but I'm just not smart enough to do anything else. It's a brand new install in 1.4 with no mods. I've reinstalled twice for good measure.

Thanks for reading!

**Comment by JavidPack** [comment]
I was able to replicate this issue by putting the 1.3 version of PixelShader.xnb in the Terraria install folder. My guess is all reports of this error are caused by a similar situation.

Anyone having this issue should completely delete the tModLoader and Terraria install folders and reinstall via steam. If the issue still persists, check client.log and find "Terraria Steam Install Location assumed to be:" and confirm that that folder matches the steam install folder of Terraria, if it doesn't you likely installed Terraria in 2 places and tModLoader is reading those out of date files.
