### ISSUE TITLE
tModLoader server not work with `CalamityMod`

### ISSUE THREAD

**Issue by hxzhao527** [bluemagic123/tModLoader#2640]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

with  `CalamityMod` enabled,  i start the server by `./start-tModLoaderServer.sh`, a `System.IndexOutOfRangeException` occur.

then i can access this server, but in game item not matched with itemID.

### Log File

[06:35:39] [Main Thread/INFO] [tML]: Save Are Located At: /home/hxzhao/.local/share/Terraria/tModLoader
[06:35:39] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.05.103.34|1.4-stable|Stable|3e55752ca78debad58596ddaafbffb3b744e0470|5249600284767593499 built 6/22/2022 12:43 AM
[06:35:39] [Main Thread/INFO] [tML]: Log date: 6/28/2022
[06:35:39] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[06:35:39] [Main Thread/INFO] [tML]: Executable: /home/hxzhao/.local/share/Steam/steamapps/common/tModLoader/tModLoader.dll
[06:35:39] [Main Thread/INFO] [tML]: Working Directory: /home/hxzhao/.local/share/Steam/steamapps/common/tModLoader
[06:35:39] [Main Thread/INFO] [tML]: Launch Parameters: --help -server -config serverconfig.txt
[06:35:39] [Main Thread/INFO] [tML]: Parsed Launch Parameters: --help -server -config serverconfig.txt
[06:35:39] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[06:35:39] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[06:35:39] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null -> steam_api
[06:35:39] [Main Thread/DEBUG] [tML]: 	attempting load /home/hxzhao/.local/share/Steam/steamapps/common/tModLoader/Libraries/Native/Linux/libsteam_api64.so
[06:35:39] [Main Thread/DEBUG] [tML]: 	success
[06:35:39] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ComponentModel.Win32Exception: Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Terraria.Initializers.LaunchInitializer.LoadServerParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 116
   at Terraria.Initializers.LaunchInitializer.LoadParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 17
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 226
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 194
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72

[06:35:41] [Main Thread/INFO] [tML]: Unloading mods
[06:35:41] [Main Thread/INFO] [tML]: Finding Mods...
[06:35:42] [Main Thread/INFO] [tML]: Sandboxing: CalamityMod
[06:35:42] [Main Thread/INFO] [tML]: Instantiating Mods...
[06:35:42] [Main Thread/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.5.103.34
[06:35:42] [Main Thread/INFO] [tML]: Initializing: CalamityMod (Calamity Mod) v2.0.0.2
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::ApplyTileCollision(bool, Vector2, int, int) added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::ShouldEmpressBeEnraged() added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Hurt(PlayerDeathReason, int, int, bool, bool, bool, int) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::DashMovement() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::GiveImmuneTimeForCollisionAttack(int) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update_NPCCollision() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Wiring::Teleport() added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::DrawInterface_40_InteractItemIcon() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Item::AffixName() added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Projectile::NewProjectile(IEntitySource, float, float, float, float, int, int, float, int, float, float) added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::DrawCursor(Vector2, bool) added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::QuickHeal() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::QuickMana() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck_Inner(int) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::SortDrawCacheWorms() added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Drawing.TileDrawing::DrawPartialLiquid(Tile, Vector2, Rectangle, int, Color) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Liquid.LiquidRenderer::InternalDraw(SpriteBatch, Vector2, int, float, bool) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::oldDrawWater(bool, int, float) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::Collision_DecideFallThroughPlatforms() added by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::DamageVar(float, float) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::ScaleStats_ApplyExpertTweaks() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::AI_001() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateJumpHeight() modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[06:35:48] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Initializers.WingStatsInitializer::Load() modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::WingMovement() modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateBuffs(int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateLifeRegen() modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateManaRegen() modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Pyramid(int, int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::DungeonHalls(int, int, ushort, int, bool) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int, bool) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::SmashAltar(int, int) added by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::hardUpdateWorld(int, int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Chlorophyte(int, int) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.UI.States.UIWorldCreation::SetDefaultOptions() modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.UI.States.UIWorldCreation::AddWorldSizeOptions(UIElement, float, MouseEvent, string, float) modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Events.Sandstorm::HasSufficientWind() modified by CalamityMod
[06:35:49] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Item::Prefix(int) modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::SpawnNPC() modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::IsTileTypeInInteractionRange(int) modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::CanExplodeTile(int, int) modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateWindyDayState() modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime_StartNight(ref bool) modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::AttemptFossilShattering(int, int, Tile, bool) modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::Damage() modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Player::GetPickaxeDamage(int, int, int, int, Tile) added by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook On.Terraria.GameContent.ItemDropRules.CommonCode::ModifyItemDropFromNPC(NPC, int) added by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::NPCLoot() modified by CalamityMod
[06:35:50] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Item::Prefix(int) added by CalamityMod
[06:35:50] [Main Thread/INFO] [tML]: Setting up...
[06:35:50] [Main Thread/INFO] [tML]: Loading: ModLoader (tModLoader) v2022.5.103.34
[06:35:50] [Main Thread/INFO] [tML]: Loading: CalamityMod (Calamity Mod) v2.0.0.2
[06:35:50] [Main Thread/INFO] [tML]: RAM usage: 386.5 MB
[06:35:51] [Main Thread/INFO] [tML]: Adding Recipes...
[06:35:58] [.NET ThreadPool Worker/INFO] [Terraria]: Loading World: test, IsCloud=False, Size=4200x1200
[06:35:58] [.NET ThreadPool Worker/INFO] [StatusText]: Loading world data
[06:35:59] [.NET ThreadPool Worker/INFO] [StatusText]: Settling liquids
[06:35:59] [Main Thread/INFO] [Terraria]: Running one update...
[06:35:59] [Main Thread/INFO] [tML]: Server starting with AllowVanillaClients set to False
[06:36:00] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Player.GetModPlayer[T](T baseInstance) in tModLoader\Terraria\Player.TML.cs:line 34
   at CalamityMod.Systems.WorldMiscUpdateSystem.PostUpdateWorld() in CalamityMod\Systems\WorldMiscUpdateSystem.cs:line 52
   at Terraria.ModLoader.SystemLoader.PostUpdateWorld() in tModLoader\Terraria\ModLoader\SystemLoader.cs:line 296
   at Terraria.WorldGen.UpdateWorld() in tModLoader\Terraria\WorldGen.cs:line 46826
   at Terraria.Main.DoUpdateInWorld(Stopwatch sw) in tModLoader\Terraria\Main.cs:line 13606
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 13063
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12618
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods) in tModLoader\Terraria\Main.cs:line 4573
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4144
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 194
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72

[06:36:00] [Main Thread/INFO] [Terraria]: Listening on port 7777

### Steps to reproduce

1. enable `CalamityMod`
2. start server by `~.steam/steam/steamapps/common/tModLoader/start-tModLoaderServer.sh` 
3. select a world, start, then
```
Running one update...
Index was outside the bounds of the array. (see server.log for full trace)
Terraria Server v1.4.3.6

Listening on port 7777
Type 'help' for a list of commands.

Server started
```

### Additional Information

```json
// enabled.json
[
  "CalamityMod"
]
```

`tModloader` and `CalamityMod` both got from steam.

**Comment by nvainR** [comment]
yep same！
