### ISSUE TITLE
Object reference not set to an instance of an object - Docker

### ISSUE THREAD

**Issue by hkiang01** [bluemagic123/tModLoader#2644]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

System.ComponentModel.Win32Exception: Permission denied

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/8998297/server.log)

### Steps to reproduce

1. Create Dockerfile like below (wip)
    ```Dockerfile
    FROM ubuntu:20.04
    
    # install ca-certificates to be able to pull https traffic to...
    # install git, unzip, wget to install vanilla server, tModLoader
    # hadolint ignore=DL3008
    RUN apt-get update && apt-get install --no-install-recommends -y \
      ca-certificates \
      curl \
      git \
      unzip \
      wget \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*
    
    # update certs
    RUN update-ca-certificates
    
    # install dotnet, required for start-tModLoaderServer.sh
    # see https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2204
    ENV DEBIAN_FRONTEND=noninteractive
    # hadolint ignore=DL3008
    RUN wget --progress=dot:giga https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
      && dpkg -i packages-microsoft-prod.deb \
      && rm packages-microsoft-prod.deb \
      && apt-get update \
      && apt-get install --no-install-recommends -y apt-transport-https \
      && apt-get update \
      && apt-get install --no-install-recommends -y dotnet-sdk-6.0 \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*
    
    # install mono
    # see https://www.mono-project.com/download/stable/#download-lin
    SHELL ["/bin/bash", "-o", "pipefail", "-c"]
    # hadolint ignore=DL3008
    RUN apt-get update \
      && apt-get install --no-install-recommends -y gnupg ca-certificates \
      && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
      && echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list \
      && apt-get update \
      && apt-get install  --no-install-recommends -y mono-complete \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*
    
    # install steamcmd
    # Insert Steam prompt answers
    RUN echo steam steam/question select "I AGREE" | debconf-set-selections \
      && echo steam steam/license note '' | debconf-set-selections
    # hadolint ignore=DL3008
    RUN apt-get update \
      && apt-get install -y --no-install-recommends  software-properties-common \
      && add-apt-repository multiverse \
      && dpkg --add-architecture i386 \
      && apt-get update \
      && echo "I AGREE" | apt-get install -y --no-install-recommends lib32gcc-s1 steamcmd \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/*
    
    # non-root user
    ARG USERNAME=terraria
    ARG USER_UID=1000
    ARG USER_GID=$USER_UID
    # hadolint ignore=DL3008
    RUN groupadd --gid $USER_GID $USERNAME \
      && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
      #
      # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
      && apt-get update \
      && apt-get install --no-install-recommends -y sudo \
      && apt-get clean \
      && rm -rf /var/lib/apt/lists/* \
      && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
      && chmod 0440 /etc/sudoers.d/$USERNAME
    USER $USERNAME
    WORKDIR /home/${USERNAME}
    
    # see https://github.com/ldericher/tmodloader-docker/blob/e24ae0950544a27fe4dc383058218766d0ecf16f/Dockerfile
    # get vanilla server \
    RUN wget --progress=dot:giga https://terraria.org/api/download/pc-dedicated-server/terraria-server-1436.zip \
      && unzip terraria-server-*.zip \
      && rm terraria-server-*.zip \
      && cp --verbose -a 1436/. . \
      && rm -rf 1436 Mac Windows \
      && mv Linux Terraria
    WORKDIR /home/${USERNAME}/
    # clone tModLoader
    # see https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server
    ARG TMOD_LOADER_GIT_TAG=v2022.05.103.34
    RUN wget --progress=dot:giga https://github.com/tModLoader/tModLoader/releases/download/v2022.05.103.34/tModLoader.zip \
      && unzip tModLoader.zip -d tModLoader \
      && rm tModLoader.zip \
      && chmod u+x tModLoader/start-tModLoader* \
      && chmod u+x tModLoader/LaunchUtils/ScriptCaller.sh 
    
    # follow instructions at https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server#starting-server-headless
    
    EXPOSE 7777
    CMD ["./tModLoader/start-tModLoader.sh"]
    ```

1. Create docker-compose.yaml like below
    
    ```yaml
    version: '3.8'
    services:
      terraria:
        platform: linux/amd64
        build: .
        ports:
          - 7777:7777
        command:
          - ./tModLoader/LaunchUtils/ScriptCaller.sh 
          - -server
          - -config
          - /home/terraria/serverconfig.txt
        volumes:
          - ./serverconfig.txt:/home/terraria/serverconfig.txt:ro
          - ./worlds:/home/terraria/worlds/
          - ./logs:/home/terraria/tModLoader/tModLoader-Logs/
          - ./dotnet:/home/terraria/tModLoader/dotnet/
    ```

1. Copy serverconfig.txt below

    ```
    #this is an example config file for TerrariaServer.exe
    #use the command 'TerrariaServer.exe -config serverconfig.txt' to use this configuration or run start-server.bat
    #please report crashes by emailing crashlog.txt to support@terraria.org
    
    #the following is a list of available command line parameters:
    
    #-config <config file>                                      Specifies the configuration file to use.
    #-port <port number>                                          Specifies the port to listen on.
    #-players <number> / -maxplayers <number>       Sets the max number of players
    #-pass <password> / -password <password>        Sets the server password
    #-world <world file>                                          Load a world and automatically start the server.
    #-autocreate <#>                                                Creates a world if none is found in the path specified by -world. World size is specified by: 1(small), 2(medium), and 3(large).
    #-banlist <path>                                                Specifies the location of the banlist. Defaults to "banlist.txt" in the working directory.
    #-worldname <world name>                                Sets the name of the world when using -autocreate.
    #-secure                                                                Adds addition cheat protection to the server.
    #-noupnp                                                                Disables automatic port forwarding
    #-steam                                                                 Enables Steam Support
    #-lobby <friends> or <private>             Allows friends to join the server or sets it to private if Steam is enabled
    #-ip <ip address>       Sets the IP address for the server to listen on
    #-forcepriority <priority>      Sets the process priority for this task. If this is used the "priority" setting below will be ignored.
    #-disableannouncementbox   Disables the text announcements Announcement Box makes when pulsed from wire.
    #-announcementboxrange <number>   Sets the announcement box text messaging range in pixels, -1 for serverwide announcements.
    #-seed <seed> Specifies the world seed when using -autocreate
    
    #remove the # in front of commands to enable them.
    
    #Load a world and automatically start the server.
    world=/home/terraria/worlds/world1.wld
    
    #Creates a new world if none is found. World size is specified by: 1(small), 2(medium), and 3(large).
    autocreate=1
    
    #Sets the world seed when using autocreate
    #seed=AwesomeSeed
    
    #Sets the name of the world when using autocreate
    worldname=Terraria
    
    #Sets the difficulty of the world when using autocreate 0(normal), 1(expert)
    difficulty=1
    
    #Sets the max number of players allowed on a server.  Value must be between 1 and 255
    maxplayers=8
    
    #Set the port number
    port=7777
    
    #Set the server password
    password=assass
    
    #Set the message of the day
    #motd=Please don�t cut the purple trees!
    
    #Sets the folder where world files will be stored
    #worldpath=/home/terraria/worlds/
    
    #The location of the banlist. Defaults to "banlist.txt" in the working directory.
    #banlist=banlist.txt
    
    #Adds addition cheat protection.
    secure=1
    
    #Sets the server language from its language code. 
    #English = en-US, German = de-DE, Italian = it-IT, French = fr-FR, Spanish = es-ES, Russian = ru-RU, Chinese = zh-Hans, Portuguese = pt-BR, Polish = pl-PL,
    language=en-US
    
    #Automatically forward ports with uPNP
    #upnp=1
    
    #Reduces enemy skipping but increases bandwidth usage. The lower the number the less skipping will happen, but more data is sent. 0 is off.
    #npcstream=60
    
    #Default system priority 0:Realtime, 1:High, 2:AboveNormal, 3:Normal, 4:BelowNormal, 5:Idle
    priority=3
    ```  

  
1. Build and run with the local mounts unpopulated

    ```bash
    docker-compose up --build -d && docker-compose logs -f
    ```

### Expected Behavior

Server starts and I can connect via tModLoader at 0.0.0.0:7777

### Actual Behavior

1. Observe error in log tail

    ```bash
    terraria-terraria-1  | : Object reference not set to an instance of an object. (see server.log for full trace)
    ```

1. Observe error in `./logs/server.log`
    
    ```
    [06:26:09] [Main Thread/ERROR] [tML]: Steam Game Server failed to Init. Steam Workshop downloading on GoG is unavailable. Make sure Steam is installed
    [06:26:10] [Main Thread/WARN] [tML]: Silently Caught Exception: 
    System.ComponentModel.Win32Exception: Permission denied
       at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
       at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
       at Terraria.Initializers.LaunchInitializer.LoadServerParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 116
       at Terraria.Initializers.LaunchInitializer.LoadParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 17
       at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 226
       at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 194
       at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
       at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72
    ```
    
    This is despite having installed `steamcmd` per https://github.com/tModLoader/tModLoader/blob/1.4/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/Instructions.txt#L4
  
    ```bash
    $ docker-compose exec terraria bash
    terraria@76751768096b:~$ apt list | grep steam
    
    WARNING: apt does not have a stable CLI interface. Use with caution in scripts.
    
    steamcmd/now 0~20180105-3 i386 [installed,local]
    ```
  
### Reproduction frequency

100%

### Additional Information

Tested with macOS Monterey
MacBook Pro (16-inch, 2021)
Chip Apple M1 Pro
Memory 32 GB

Docker Desktop Version 4.9.1 (81317)
Engine: 20.10.16
Compose: v2.6.0
Credential Helper: v0.6.4
Kubernetes: v1.24.0
Snyk: v1.827.0

**Comment by hkiang01** [comment]
still an issue in v2022.06.96.1 even after installing steam and steamcmd and granting the runtime user's ownership of both

Updated Dockerfile
```Dockerfile
FROM ubuntu:20.04

# install ca-certificates to be able to pull https traffic to...
# install git, unzip, wget to install vanilla server, tModLoader
# hadolint ignore=DL3008
RUN apt-get update && apt-get install --no-install-recommends -y \
  ca-certificates \
  curl \
  git \
  unzip \
  wget \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# update certs
RUN update-ca-certificates

# install dotnet, required for start-tModLoaderServer.sh
# see https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2204
ENV DEBIAN_FRONTEND=noninteractive
# hadolint ignore=DL3008
RUN wget --progress=dot:giga https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && rm packages-microsoft-prod.deb \
  && apt-get update \
  && apt-get install --no-install-recommends -y apt-transport-https \
  && apt-get update \
  && apt-get install --no-install-recommends -y dotnet-sdk-6.0 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# install mono
# see https://www.mono-project.com/download/stable/#download-lin
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get install --no-install-recommends -y gnupg ca-certificates \
  && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
  && echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list \
  && apt-get update \
  && apt-get install  --no-install-recommends -y mono-complete \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# install steam, steamcmd
# Insert Steam prompt answers
RUN echo steam steam/question select "I AGREE" | debconf-set-selections \
  && echo steam steam/license note '' | debconf-set-selections
# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get install -y --no-install-recommends  software-properties-common \
  && add-apt-repository multiverse \
  && dpkg --add-architecture i386 \
  && apt-get update \
  && apt-get install -y --no-install-recommends steam \
  && echo "I AGREE" | apt-get install -y --no-install-recommends lib32gcc-s1 steamcmd \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
ENV PATH="/usr/games:${PATH}"

# non-root user
ARG USERNAME=terraria
ARG USER_UID=1000
ARG USER_GID=$USER_UID
# hadolint ignore=DL3008
RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
  #
  # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
  && apt-get update \
  && apt-get install --no-install-recommends -y sudo \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME
# grant non-root user access to run steamcmd
# RUN chown ${USER_GID}:${USER_UID} /usr/games/steamcmd
# switch to non-root user
USER $USERNAME
WORKDIR /home/${USERNAME}

# see https://github.com/ldericher/tmodloader-docker/blob/e24ae0950544a27fe4dc383058218766d0ecf16f/Dockerfile
# get vanilla server \
RUN wget --progress=dot:giga https://terraria.org/api/download/pc-dedicated-server/terraria-server-1436.zip \
  && unzip terraria-server-*.zip \
  && rm terraria-server-*.zip \
  && cp --verbose -a 1436/. . \
  && rm -rf 1436 Mac Windows \
  && mv Linux Terraria
WORKDIR /home/${USERNAME}/
# clone tModLoader
# see https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server
ARG TMOD_LOADER_GIT_TAG=v2022.06.96.1
RUN wget --progress=dot:giga "https://github.com/tModLoader/tModLoader/releases/download/${TMOD_LOADER_GIT_TAG}/tModLoader.zip" \
  && unzip tModLoader.zip -d tModLoader \
  && rm tModLoader.zip \
  && chmod u+x tModLoader/start-tModLoader* \
  && chmod u+x tModLoader/LaunchUtils/ScriptCaller.sh \
  && sudo chown ${USER_GID}:${USER_UID} /usr/games/steamcmd \
  && sudo chown ${USER_GID}:${USER_UID} /usr/games/steam \
  && sudo chmod u+x /usr/games/steamcmd \
  && sudo chmod u+x /usr/games/steam

# follow instructions at https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server#starting-server-headless

EXPOSE 7777
CMD ["./tModLoader/start-tModLoader.sh"]
```

note permissions from steam and steamcmd

```
$ docker-compose exec terraria bash
terraria@54f617cc9e46:~$ ls -la /usr/games
total 28
drwxr-xr-x 1 root     root     4096 Jul  1 15:46 .
drwxr-xr-x 1 root     root     4096 Jul  1 15:45 ..
-rwxr-xr-x 1 terraria terraria 4136 Jul 16  2019 steam
-rwxr-xr-x 1 terraria terraria  695 Nov 17  2018 steamcmd

**Comment by Tamaized** [comment]
I'm getting the same `System.NullReferenceException: Object reference not set to an instance of an object.` error trying to launch from a docker container.

log:
https://gist.github.com/Tamaized/3d7f8d5266db930d6b5af077fec96ceb

**Comment by hkiang01** [comment]
whoops, still open

still an issue in v2022.06.96.4

**Comment by Solxanich** [comment]
If someone wants to test a fix for this, 
I've queued up a build on https://github.com/tModLoader/tModLoader/actions/runs/2603823880

Download the release build and check if setting up a server with those files allows to enter a world.
Specifically, would want to swap the tmodloader.dll from that file for whatever is currently present and see if it then 'works'.

I've been told this is an issue specific to running with Docker, so any direct running of start-tmodloader.sh would work fine otherwise, complicating testing.

**Comment by hkiang01** [comment]
Thanks [that](https://github.com/tModLoader/tModLoader/issues/2644#issuecomment-1173008862) seems to fix the bug, but I think I'll have to test an actual release to verify

last few lines of server.log
```
[18:38:08] [Main Thread/INFO] [StatusText]: 100.0% - Finalizing world - 0.
[18:38:08] [Main Thread/INFO] [StatusText]: 100.0% - Finalizing world - 0.
[18:38:08] [Main Thread/INFO] [StatusText]: 100.0% - Finalizing world - 0.
[18:38:08] [Main Thread/INFO] [Terraria]: Running one update...
[18:38:08] [Main Thread/INFO] [tML]: Server starting with AllowVanillaClients set to False
[18:38:11] [Main Thread/INFO] [Terraria]: Listening on port 7777
[18:39:07] [TCP Listen Thread/INFO] [Terraria]: 172.21.0.1:56594 is connecting...
[18:39:07] [Main Thread/INFO] [Terraria]: 172.21.0.1:56594 was booted: You are not using the same version as this server.
(You are on tModLoader v2022.6.96.4, server is on tModLoader v9999.0 Fix2644-ServerCrash-DockerCompat Dev)
```

updated Dockerfile

```Dockerfile
FROM ubuntu:20.04

# install ca-certificates to be able to pull https traffic to...
# install git, unzip, wget to install vanilla server, tModLoader
# hadolint ignore=DL3008
RUN apt-get update && apt-get install --no-install-recommends -y \
  ca-certificates \
  curl \
  git \
  unzip \
  wget \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# update certs
RUN update-ca-certificates

# install dotnet, required for start-tModLoaderServer.sh
# see https://docs.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2204
ENV DEBIAN_FRONTEND=noninteractive
# hadolint ignore=DL3008
RUN wget --progress=dot:giga https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb \
  && dpkg -i packages-microsoft-prod.deb \
  && rm packages-microsoft-prod.deb \
  && apt-get update \
  && apt-get install --no-install-recommends -y apt-transport-https \
  && apt-get update \
  && apt-get install --no-install-recommends -y dotnet-sdk-6.0 \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# install mono
# see https://www.mono-project.com/download/stable/#download-lin
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get install --no-install-recommends -y gnupg ca-certificates \
  && apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF \
  && echo "deb https://download.mono-project.com/repo/ubuntu stable-focal main" | tee /etc/apt/sources.list.d/mono-official-stable.list \
  && apt-get update \
  && apt-get install  --no-install-recommends -y mono-complete \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

# install steam, steamcmd
# Insert Steam prompt answers
RUN echo steam steam/question select "I AGREE" | debconf-set-selections \
  && echo steam steam/license note '' | debconf-set-selections
# hadolint ignore=DL3008
RUN apt-get update \
  && apt-get install -y --no-install-recommends  software-properties-common \
  && add-apt-repository multiverse \
  && dpkg --add-architecture i386 \
  && apt-get update \
  && apt-get install -y --no-install-recommends steam \
  && echo "I AGREE" | apt-get install -y --no-install-recommends lib32gcc-s1 steamcmd \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*
ENV PATH="/usr/games:${PATH}"

# non-root user
ARG USERNAME=terraria
ARG USER_UID=1000
ARG USER_GID=$USER_UID
# hadolint ignore=DL3008
RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
  #
  # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
  && apt-get update \
  && apt-get install --no-install-recommends -y sudo \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* \
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  && chmod 0440 /etc/sudoers.d/$USERNAME
# grant non-root user access to run steamcmd
# RUN chown ${USER_GID}:${USER_UID} /usr/games/steamcmd
# switch to non-root user
USER $USERNAME
WORKDIR /home/${USERNAME}

# see https://github.com/ldericher/tmodloader-docker/blob/e24ae0950544a27fe4dc383058218766d0ecf16f/Dockerfile
# get vanilla server \
RUN wget --progress=dot:giga https://terraria.org/api/download/pc-dedicated-server/terraria-server-1436.zip \
  && unzip terraria-server-*.zip \
  && rm terraria-server-*.zip \
  && cp --verbose -a 1436/. . \
  && rm -rf 1436 Mac Windows \
  && mv Linux Terraria
WORKDIR /home/${USERNAME}/

# clone tModLoader
ARG TMOD_LOADER_GIT_TAG=v2022.06.96.4
RUN wget --progress=dot:giga "https://github.com/tModLoader/tModLoader/releases/download/${TMOD_LOADER_GIT_TAG}/tModLoader.zip" \
  && unzip tModLoader.zip -d tModLoader \
  && rm tModLoader.zip \
  && chmod u+x tModLoader/start-tModLoader* \
  && chmod u+x tModLoader/LaunchUtils/ScriptCaller.sh \
  && sudo chown ${USER_GID}:${USER_UID} /usr/games/steamcmd \
  && sudo chown ${USER_GID}:${USER_UID} /usr/games/steam \
  && sudo chmod u+x /usr/games/steamcmd \
  && sudo chmod u+x /usr/games/steam

# resolve docker specific bug by replacing tModLoader.dll per https://github.com/tModLoader/tModLoader/issues/2644#issuecomment-1173008862
RUN mkdir Release-Build
WORKDIR /home/${USERNAME}/Release-Build
# REQUIRED: Please download Release Build.zip from the corresponding build job
# hadolint ignore=DL3020
ADD Release-Build.zip .
RUN unzip Release-Build.zip
RUN cp tModLoader.dll /home/${USERNAME}/tModLoader/tModLoader.dll
WORKDIR /home/${USERNAME}/

# follow instructions at https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server#starting-server-headless

EXPOSE 7777
CMD ["./tModLoader/start-tModLoader.sh"]
```

**Comment by Solxanich** [comment]
I'm not sure when this will be pushed to stable - might take a few days to get a new stable build put together and released. 
Thanks for testing!

**Comment by Chicken-Bones** [comment]
https://itnext.io/net-console-apps-preparation-for-docker-b72c9dfc1ded

I guess docker running in non-interactive mode?

**Comment by Pomegranate123** [comment]
I was having this exact problem, and the fix worked! However, when will this be released? It's been over 2 weeks, and looking at the past release schedule, isn't a new one long overdue?

**Comment by Chicken-Bones** [comment]
@Pomegranate123 a fix is already on preview, and will be on stable at the start of next month. Please DM me in discord I'd like you to test an alternate fix for me.

**Comment by Dark-Arcana** [comment]
Is that within 2 weeks? We have a lot of users (Akliz Hosting) looking for this update! Thanks :).

**Comment by Chicken-Bones** [comment]
@Dark-Arcana If you can test, there's an alternate fix I'd appreciate help with, please DM me on the discord.

**Comment by Dark-Arcana** [comment]
@Tamaized might be able to help test if you need it. We'd like to help this get up and running in our system. I'll pass it along to him.

**Comment by Tamaized** [comment]
Yeah i'll get in touch tomorrow about it.

**Comment by Pomegranate123** [comment]
@Chicken-Bones I'd love to help test, but what's your discord? I can't find it in your profile
