### ISSUE TITLE
Game freezes, has no audio then crashes.

### ISSUE THREAD

**Issue by Kyzra** [bluemagic123/tModLoader#2646]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I load up my world, I can move around for roughly 5-60secs then it crashes randomly, no matter where I am. I tried reinstalling the game, removing some mods and checking the files and still nothing.

### Log File

[16:18:09] [Main Thread/INFO] [TerrariaSteamClient]: Working Directory: D:\Program Files\Steam\steamapps\common\tModLoader
[16:18:09] [Main Thread/INFO] [TerrariaSteamClient]: Args: D:\Program Files\Steam\steamapps\common\tModLoader\tModLoader.dll -terrariasteamclient 1440
[16:18:09] [Main Thread/INFO] [TerrariaSteamClient]: Setting steam app id to 105600
[16:18:09] [Main Thread/INFO] [TerrariaSteamClient]: SteamAPI.Init()
[16:18:09] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: init_success
[16:18:09] [Main Thread/DEBUG] [TerrariaSteamClient]: Recv: acknowledged
[16:23:01] [Main Thread/FATAL] [TerrariaSteamClient]: Unhandled error
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.Engine.TerrariaSteamClient.<>c__DisplayClass12_0.<Run>b__0() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\TerrariaSteamClient.cs:line 107
   at Terraria.ModLoader.Engine.TerrariaSteamClient.Run() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\TerrariaSteamClient.cs:line 132
[16:23:02] [Main Thread/INFO] [TerrariaSteamClient]: SteamAPI.Shutdown()

### Steps to reproduce

No clue.

**Comment by Chicken-Bones** [comment]
Hi, please send us `client.log`

**Comment by Kyzra** [comment]
I got this from this directory D:\Program Files\Steam\steamapps\common\tModLoader\tModLoader-Logs
[client.log](https://github.com/tModLoader/tModLoader/files/9010255/client.log)

**Comment by Chicken-Bones** [comment]
and `natives.log`?

**Comment by Kyzra** [comment]
this is from today
[Natives.log](https://github.com/tModLoader/tModLoader/files/9012829/Natives.log)

**Comment by Chicken-Bones** [comment]
Calamity Bug
