### ISSUE TITLE
Crashing System.Globalization.CultureNotFoundException

### ISSUE THREAD

**Issue by olivatooo** [bluemagic123/tModLoader#2654]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Can't open tModLoader in archlinux

### Steps to reproduce

1. Have ArchLinux
2. Install Steam
3. Install Terraria
4. Install tModLoader
5. Open tModLoader

### Expected Behavior

tModLoader should run with a default localization

### Actual Behavior

tModLoader crashes with:
```
[21:35:09] [Main Thread/ERROR] [tML]: Unhandled Exception
System.TypeInitializationException: The type initializer for 'Terraria.Localization.LanguageManager' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Terraria.Localization.GameCulture' threw an exception.
 ---> System.Globalization.CultureNotFoundException: Only the invariant culture is supported in globalization-invariant mode. See https://aka.ms/GlobalizationInvariantMode for more information. (Parameter 'name')
en-US is an invalid culture identifier.
   at System.Globalization.CultureInfo..ctor(String name, Boolean useUserOverride)
   at System.Globalization.CultureInfo..ctor(String name)
   at Terraria.Localization.GameCulture..ctor(String name, Int32 legacyId) in tModLoader\Terraria\Localization\GameCulture.cs:line 72
   at Terraria.Localization.GameCulture..cctor() in tModLoader\Terraria\Localization\GameCulture.cs:line 57
   --- End of inner exception stack trace ---
   at Terraria.Localization.GameCulture.get_DefaultCulture() in tModLoader\Terraria\Localization\GameCulture.cs:line 29
   at Terraria.Localization.LanguageManager..ctor() in tModLoader\Terraria\Localization\LanguageManager.cs:line 25
   at Terraria.Localization.LanguageManager..cctor() in tModLoader\Terraria\Localization\LanguageManager.cs:line 22
   --- End of inner exception stack trace ---
   at Terraria.Localization.Language.GetTextValue(String key, Object arg0) in tModLoader\Terraria\Localization\Language.cs:line 12
   at Terraria.ModLoader.Logging.FirstChanceExceptionHandler(Object sender, FirstChanceExceptionEventArgs args) in tModLoader\Terraria\ModLoader\Logging.ExceptionHandling.cs:line 108
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 194
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72
   ```

### Additional Information

DOT NET VERSION: 6.0.102

**Comment by olivatooo** [comment]
fixed by replacing tModLoader.runtimeconfig.json with the following content:

```
{
  "runtimeOptions": {
    "tfm": "net6.0",
    "framework": {
      "name": "Microsoft.NETCore.App",
      "version": "6.0.0"
    },
    "configProperties": {
      "System.Globalization.Invariant": false,
      "DEFAULT_STACK_SIZE": "400000",
      "System.Reflection.Metadata.MetadataUpdater.IsSupported": false
    }
  }
}
```

**Comment by Chicken-Bones** [comment]
Can you give us more information about this issue, and a `client.log` file?

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
