### ISSUE TITLE
Save Enabled as New Mod Pack crashes

### ISSUE THREAD

**Issue by muniategui** [bluemagic123/tModLoader#2661]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Like the tittle says when trying to save modpack the game crashes and the mdopack is corrupted. Seems like a file was already copied and instead of overwritting it throws exception which is not caught?

### Log File

7/1/2022 7:06:52 PM
System.IO.IOException: The file 'C:\Users\muniategui\Documents\My Games\Terraria\tModLoader\Mods\ModPacks\GitIssue\configs\FargowiltasSouls_Toggles.json' already exists.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Terraria.ModLoader.UI.UIModPacks.SaveModPack(String filename) in tModLoader\Terraria\ModLoader\UI\UIModPacks.cs:line 141
   at Terraria.GameContent.UI.States.UIVirtualKeyboard.InternalSubmit() in tModLoader\Terraria\GameContent\UI\States\UIVirtualKeyboard.cs:line 801
   at Terraria.GameContent.UI.States.UIVirtualKeyboard.Submit() in tModLoader\Terraria\GameContent\UI\States\UIVirtualKeyboard.cs:line 794
   at Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(SpriteBatch spriteBatch) in tModLoader\Terraria\GameContent\UI\States\UIVirtualKeyboard.cs:line 570
   at Terraria.UI.UIElement.Draw(SpriteBatch spriteBatch) in tModLoader\Terraria\UI\UIElement.cs:line 196
   at Terraria.Main.DrawMenu(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 39732
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48978
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48564
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 557
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 883
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 414
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 234

### Steps to reproduce

1.  Download Fargo's Mutant Mod (v2.8.2), Fargo's Souls Mod (v1.4.0.3) and Fargo's Music Mod (v0.1.1.2)
2. Try to create a modpack with this 3 mods by pressing Save Enabled as New Mod Pack
3. Insert any name
4. Press submit

### Expected Behavior

The modpack should be created

### Actual Behavior

Game crashes

### Reproduction frequency

100% reproducible and constant

### Additional Information

If Fargo's Music is not enable when the button is pressed games does not crash but once the name of modpack is set and you press submit, it does not return you to the menu but if you press cancel you return to the menu and you can see how the modpacks manager says the modpack creation had an error durint the creation and it might be corrupted. Eneabling Music makes the client crash and the modpack is not created neither.

**Comment by gradientogames** [comment]
im experiencing the same problem

**Comment by muniategui** [comment]
> im experiencing the same problem

If you really need to create the modpack you can add the buged ones manually. Disable the mods giving problems, create de modpack, open the modpack folder and edit the eneabled.json and install.txt manually, you can get the steamid and the mod name by going into modfolder and checking the folders id of the mods + the name of the modfile (for enabled.json). Copy the config files of the mod if missing to the config folder (you can find them in my documents/my games/terraria/TModLoader/ModConfigs.

**Comment by AbzZero** [comment]
I also had this problem, but it stopped happening if I deleted the pre-existing modpack of the same name before saving enabled as a modpack.
