### ISSUE TITLE
tModLoader refusing to launch and giving error code

### ISSUE THREAD

**Issue by Fr0styMango** [bluemagic123/tModLoader#2666]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Whenever I launch the game through steam or with the .sh file I get this error:

System.EntryPointNotFoundException: Unable to find an entry point named 'SteamAPI_ISteamClient_GetISteamGameSearch' in shared library 'steam_api'.
   at Steamworks.NativeMethods.ISteamClient_GetISteamGameSearch(IntPtr instancePtr, HSteamUser hSteamuser, HSteamPipe hSteamPipe, UTF8StringHandle pchVersion)
   at Steamworks.SteamClient.GetISteamGameSearch(HSteamUser hSteamuser, HSteamPipe hSteamPipe, String pchVersion)
   at Steamworks.CSteamAPIContext.Init()
   at Steamworks.SteamAPI.Init()
   at Terraria.Social.Steam.CoreSocialModule.Initialize() in tModLoader\Terraria\Social\Steam\CoreSocialModule.cs:line 36
   at Terraria.Social.SocialAPI.LoadSteam() in tModLoader\Terraria\Social\SocialAPI.cs:line 113
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode) in tModLoader\Terraria\Social\SocialAPI.cs:line 56
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 230

Before I was able to solve this error by overwriting the steam provided Libraries folder with the github proved one, but nothing I do is getting rid of this error 

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/9031828/client.log)

**Comment by Fr0styMango** [comment]
Okay now steam isn't giving the error, BUT now getting a new one:

[16:03:05] [Main Thread/INFO] [tML]: Save Are Located At: /home/korbin/.local/share/Terraria/tModLoader
[16:03:05] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.06.96.4|1.4-stable|Stable|6ee86304725fa4ac713d981d17a87d1b1d0e014a|5249609086868104401 built 07/01/2022 15:14
[16:03:05] [Main Thread/INFO] [tML]: Log date: 07/01/2022
[16:03:05] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[16:03:05] [Main Thread/INFO] [tML]: Executable: /home/korbin/.local/share/Steam/steamapps/common/tModLoader/tModLoader.dll
[16:03:05] [Main Thread/INFO] [tML]: Working Directory: /home/korbin/.local/share/Steam/steamapps/common/tModLoader
[16:03:06] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[16:03:06] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "/home/korbin/.local/share/Steam/steamapps/common/tModLoader/dotnet/6.0.0/dotnet" tModLoader.dll -terrariasteamclient 160
[16:03:06] [Main Thread/FATAL] [tML]: The terraria steam client process exited unexpectedly

**Comment by Solxanich** [comment]
Is your issue related to? https://github.com/tModLoader/tModLoader/issues/2660

If so, than the workaround that was established due to Steam issues is to delete all the files in the install, and than let Steam re-verify the files and install again.

Steam is bugged on Linux and doesn't properly deploy updates with respect to case-sensitivity, which, you know, matters on Linux.

**Comment by Fr0styMango** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/9031887/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9031888/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/9031889/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/9031890/terrariasteamclient.log)
I tried reinstalling, deleting everything and reinstalling by verifying, and tried replacing everything with the newest upload on github and the logs always end up like this

**Comment by Fr0styMango** [comment]
https://user-images.githubusercontent.com/106934901/176974468-d9327095-b5ad-4032-9785-58ff410ae9c6.mp4

Here is a video of what happens when trying to run tModLoader. What happened before when the game ran was it would say running and stop for tModLoader, running and then stop for Terraira, and then after about 1 or 2 seconds tModLoader would start. Now nothing happens

**Comment by Solxanich** [comment]
~~Weird, never seen this issue before; may take more than a few minutes.
Do you know anything about that perchance?

(zenity:16481): Gtk-WARNING **: 16:27:04.542: Unable to locate theme engine in module_path: "adwaita",
This option is not available. Please see --help for all possible usages.~~

Never mind, the issue posted just moved to terraria steam thing.

**Comment by Solxanich** [comment]
Any rate, your core issue is: System.EntryPointNotFoundException: Unable to find an entry point named 'SteamAPI_ISteamClient_GetISteamGameSearch' in shared library 'steam_api'.

The fix for this is to update Steam. 
If you don't have an update queued, you can install steam on itself to typically fix the issue - specifically don't uninstall it. Just run the installer again and install it to the same location

**Comment by Fr0styMango** [comment]
What about the Client and Launch logs? I just opted out of the Steam Beta to force an update and the same issues are there
[client.log](https://github.com/tModLoader/tModLoader/files/9031938/client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9031939/Launch.log)

**Comment by Solxanich** [comment]
Nothing new.
It's refusing to launch since it can't load the steam api and thus validate ownership of Terraria. 

Only way to fix this is fix Steam. 
I would suggest launching via start-tmodloader.sh if you want to keep the errors to just client.log. 

I think you have to install on itself, which isn't fun, but seems needed?

**Comment by Fr0styMango** [comment]
If it means anything I got the 1.3 version to work without any issues but the 1.4/alpha are having these issues. Gonna try to completely wipe and reinstall steam and see if that works

**Comment by Fr0styMango** [comment]
Update: I have tried every version starting from v2022.04.62.1 to v2022.06.96.4. Only v2022.04.62.1 to v2022.04.62.6 work. If I delete libraries and verify, or even just verify after a fresh install from the previously mentioned four versions that work, it borks the game from working and gives the steamapi error. I have not tried wiping everything steam of my system as it's not worth deleting the local saves for some games

**Comment by Solxanich** [comment]
Thanks for the testing - yes uninstalling steam is highly discouraged and apologies for missing you were planning to attempt that. 

I'll take a look and see what changed in 2022.5 to break steam. 

In the interim, @direwolf420 has suggested reading the following about steamapi entry point issues:
https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#unable-to-find-an-entry-point-named-steamapi_manualdispatch_init-in-dll-steam_api64

**Comment by JavidPack** [comment]
Fr0styMango did you ever get this to work?

**Comment by Solxanich** [comment]
Issue has gone stale with no response for a long period. Closing as stale
