### ISSUE TITLE
Error at start and failed to load any mod

### ISSUE THREAD

**Issue by rubynt** [bluemagic123/tModLoader#2685]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When i start it it throws an error and after starting if i try to use a mod it fails and throws and error

### Log File

[02:43:16] [Main Thread/INFO] [tML]: Save Are Located At: /home/ruby/.local/share/Terraria/tModLoader
[02:43:16] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.06.96.4|1.4-stable|Stable|6ee86304725fa4ac713d981d17a87d1b1d0e014a|5249609086868104401 built 7/1/2022 11:14 PM
[02:43:16] [Main Thread/INFO] [tML]: Log date: 7/5/2022
[02:43:16] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[02:43:16] [Main Thread/INFO] [tML]: Executable: /home/ruby/.local/share/Steam/steamapps/common/tModLoader/tModLoader.dll
[02:43:16] [Main Thread/INFO] [tML]: Working Directory: /home/ruby/.local/share/Steam/steamapps/common/tModLoader
[02:43:16] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt
[02:43:16] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[02:43:16] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[02:43:17] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[02:43:17] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null -> steam_api
[02:43:17] [Main Thread/DEBUG] [tML]: 	attempting load /home/ruby/.local/share/Steam/steamapps/common/tModLoader/Libraries/Native/Linux/libsteam_api64.so
[02:43:17] [Main Thread/DEBUG] [tML]: 	success
[02:43:17] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ComponentModel.Win32Exception: Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Terraria.Initializers.LaunchInitializer.LoadServerParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 116
   at Terraria.Initializers.LaunchInitializer.LoadParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 17
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 195
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72

[02:43:19] [Main Thread/INFO] [tML]: Unloading mods
[02:43:20] [Main Thread/INFO] [tML]: Finding Mods...
[02:43:20] [Main Thread/WARN] [tML]: Ignoring CheatSheet found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/CheatSheet_v0.6.6.4.tmod. A mod with the same name already exists.
[02:43:20] [Main Thread/WARN] [tML]: Ignoring MagicStorage found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/MagicStorage_v0.4.3.6.tmod. A mod with the same name already exists.
[02:43:20] [Main Thread/WARN] [tML]: Ignoring CalamityMod found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/CalamityMod_v1.5.1.6.tmod. A mod with the same name already exists.
[02:43:20] [Main Thread/INFO] [tML]: Instantiating Mods...
[02:43:20] [Main Thread/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.6.96.4
[02:43:20] [Main Thread/INFO] [tML]: Setting up...
[02:43:21] [Main Thread/INFO] [tML]: Loading: ModLoader (tModLoader) v2022.6.96.4
[02:43:21] [Main Thread/INFO] [tML]: RAM usage: 253.3 MB
[02:43:21] [Main Thread/INFO] [tML]: Adding Recipes...
[02:43:33] [Main Thread/INFO] [tML]: Enabling Mod: CheatSheet
[02:43:34] [Main Thread/INFO] [tML]: Unloading mods
[02:43:35] [Main Thread/INFO] [tML]: Finding Mods...
[02:43:35] [Main Thread/WARN] [tML]: Ignoring CheatSheet found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/CheatSheet_v0.6.6.4.tmod. A mod with the same name already exists.
[02:43:35] [Main Thread/WARN] [tML]: Ignoring MagicStorage found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/MagicStorage_v0.4.3.6.tmod. A mod with the same name already exists.
[02:43:35] [Main Thread/WARN] [tML]: Ignoring CalamityMod found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/CalamityMod_v1.5.1.6.tmod. A mod with the same name already exists.
[02:43:35] [Main Thread/INFO] [tML]: Sandboxing: CheatSheet
[02:43:35] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ArgumentNullException: Buffer cannot be null. (Parameter 'buffer')
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssembly(Byte[] code, Byte[] pdb) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 75
   at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssemblies() in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 60
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 249
   at Terraria.ModLoader.Core.ModOrganizer.LoadMods(CancellationToken token) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 243
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 116
   at Terraria.ModLoader.ModLoader.Reload() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 189
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4155
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 236
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 195
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72

[02:43:35] [Main Thread/ERROR] [tML]: An error occurred while loading CheatSheet v0.6.6.4
It has been detected that this mod was built for tModLoader v0.11.8.3
However, you are using tModLoader v2022.6.96.4
The mod(s) have been automatically disabled.
System.ArgumentNullException: Buffer cannot be null. (Parameter 'buffer')
   at System.IO.MemoryStream..ctor(Byte[] buffer, Boolean writable)
   at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssembly(Byte[] code, Byte[] pdb) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 75
   at Terraria.ModLoader.Core.AssemblyManager.ModLoadContext.LoadAssemblies() in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 60
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 249
   at Terraria.ModLoader.Core.ModOrganizer.LoadMods(CancellationToken token) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 243
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 116
[02:43:35] [Main Thread/INFO] [tML]: Disabling Mod: CheatSheet
[02:43:35] [Main Thread/INFO] [tML]: Unloading mods
[02:43:36] [Main Thread/INFO] [tML]: Finding Mods...
[02:43:36] [Main Thread/WARN] [tML]: Ignoring CheatSheet found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/CheatSheet_v0.6.6.4.tmod. A mod with the same name already exists.
[02:43:36] [Main Thread/WARN] [tML]: Ignoring MagicStorage found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/MagicStorage_v0.4.3.6.tmod. A mod with the same name already exists.
[02:43:36] [Main Thread/WARN] [tML]: Ignoring CalamityMod found at: /home/ruby/.local/share/Terraria/tModLoader/Mods/CalamityMod_v1.5.1.6.tmod. A mod with the same name already exists.
[02:43:36] [Main Thread/INFO] [tML]: Instantiating Mods...
[02:43:36] [Main Thread/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.6.96.4
[02:43:36] [Main Thread/INFO] [tML]: Setting up...
[02:43:36] [Main Thread/INFO] [tML]: Loading: ModLoader (tModLoader) v2022.6.96.4
[02:43:36] [Main Thread/INFO] [tML]: RAM usage: 255.8 MB
[02:43:36] [Main Thread/INFO] [tML]: Adding Recipes...

**Comment by rubynt** [comment]
nvm i used a mirror to download mods.
