### ISSUE TITLE
TML Server Crashes: Object reference not set to an instance of an object. at Terraria.Main.get_worldPathName()

### ISSUE THREAD

**Issue by itzTheMeow** [bluemagic123/tModLoader#2693]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When i start my server, it crashes after loading mods:
```
System.NullReferenceException: Object reference not set to an instance of an object.
--
27 | at Terraria.Main.get_worldPathName() in tModLoader\Terraria\Main.cs:line 2327
28 | at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods) in tModLoader\Terraria\Main.cs:line 4162
29 | at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4156
30 | at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 236
```
It still crashes if i don't have any mods installed.

### Log File

[23:59:18] [Main Thread/INFO] [tML]: Log date: 7/5/2022
[23:59:18] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[23:59:18] [Main Thread/INFO] [tML]: Executable: /root/terra/tModLoader.dll
[23:59:18] [Main Thread/INFO] [tML]: Working Directory: /root/terra
[23:59:18] [Main Thread/INFO] [tML]: Launch Parameters: -server -config /root/terra/serverconfig.txt
[23:59:18] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config /root/terra/serverconfig.txt
[23:59:19] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.3.6_B.exe not found nearby
[23:59:19] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[23:59:19] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null -> steam_api
[23:59:19] [Main Thread/DEBUG] [tML]:   attempting load /root/terra/Libraries/Native/Linux/libsteam_api64.so
[23:59:19] [Main Thread/DEBUG] [tML]:   success
[23:59:19] [Main Thread/ERROR] [tML]: Steam Game Server failed to Init. Steam Workshop downloading on GoG is unavailable. Make sure Steam is installed
[23:59:19] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.FormatException: Expected Re-Logic file format.
   at Terraria.IO.FileMetadata.Read(BinaryReader reader) in tModLoader\Terraria\IO\FileMetadata.cs:line 48
   at Terraria.IO.FileMetadata.Read(BinaryReader reader, FileType expectedType) in tModLoader\Terraria\IO\FileMetadata.cs:line 38
   at Terraria.IO.WorldFile.GetAllMetadata(String file, Boolean cloudSave) in tModLoader\Terraria\IO\WorldFile.cs:line 137
   at Terraria.Main.LoadDedConfig(String configPath) in tModLoader\Terraria\Main.cs:line 3912
   at Terraria.Initializers.LaunchInitializer.LoadServerParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 199
   at Terraria.Initializers.LaunchInitializer.LoadParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 17
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 195
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72

[23:59:20] [Main Thread/INFO] [tML]: Unloading mods
[23:59:21] [Main Thread/INFO] [tML]: Finding Mods...
[23:59:21] [Main Thread/INFO] [tML]: Sandboxing: Census
[23:59:21] [Main Thread/INFO] [tML]: Sandboxing: CalamityMod
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: CalamityModMusic
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: AlchemistNPCLite
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: AutoReroll
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: AutoTrash
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: BetterMultiplayer
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: CalamityInterludes
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: CalValEX
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: DisableCorruptionSpread
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: Fargowiltas
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: FargowiltasSouls
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: FargowiltasMusic
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: LansUncraftItems
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: LavalessLavaSlime
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: MagicStorage
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: NoLakeSizePenalty
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: OneStopNPCShop
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: OreExcavator
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: RecipeBrowser
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: ShopExpander
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: TownNPCHome
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: UnCalamityModMusic
[23:59:22] [Main Thread/INFO] [tML]: Sandboxing: WingSlotExtra
[23:59:22] [Main Thread/INFO] [tML]: Instantiating Mods...
[23:59:23] [Main Thread/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.6.96.1
[23:59:23] [Main Thread/INFO] [tML]: Initializing: Census (Census - Town NPC Checklist) v0.4.1
[23:59:23] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime_SpawnTownNPCs() modified by Census
[23:59:23] [Main Thread/INFO] [tML]: Initializing: CalamityMod (Calamity Mod) v2.0.0.3
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::ApplyTileCollision(bool, Vector2, int, int) added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::ShouldEmpressBeEnraged() added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Hurt(PlayerDeathReason, int, int, bool, bool, bool, int) modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::DashMovement() modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::GiveImmuneTimeForCollisionAttack(int) modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update_NPCCollision() modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Wiring::Teleport() added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::DrawInterface_40_InteractItemIcon() modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Item::AffixName() added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Projectile::NewProjectile(IEntitySource, float, float, float, float, int, int, float, int, float, float) added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::DrawCursor(Vector2, bool) added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::QuickHeal() modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::QuickMana() modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck_Inner(int) modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::SortDrawCacheWorms() added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Drawing.TileDrawing::DrawPartialLiquid(Tile, Vector2, Rectangle, int, Color) modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Liquid.LiquidRenderer::InternalDraw(SpriteBatch, Vector2, int, float, bool) modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::oldDrawWater(bool, int, float) modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::Collision_DecideFallThroughPlatforms() added by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::DamageVar(float, float) modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::ScaleStats_ApplyExpertTweaks() modified by CalamityMod
[23:59:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::AI_001() modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateJumpHeight() modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Initializers.WingStatsInitializer::Load() modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::WingMovement() modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateBuffs(int) modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateLifeRegen() modified by CalamityMod
[23:59:31] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateManaRegen() modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Pyramid(int, int) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::DungeonHalls(int, int, ushort, int, bool) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int, bool) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::SmashAltar(int, int) added by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::hardUpdateWorld(int, int) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Chlorophyte(int, int) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.UI.States.UIWorldCreation::SetDefaultOptions() modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.UI.States.UIWorldCreation::AddWorldSizeOptions(UIElement, float, MouseEvent, string, float) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Events.Sandstorm::HasSufficientWind() modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Item::Prefix(int) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::SpawnNPC() modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::IsTileTypeInInteractionRange(int) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::CanExplodeTile(int, int) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateWindyDayState() modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime_StartNight(ref bool) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::AttemptFossilShattering(int, int, Tile, bool) modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::Damage() modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Player::GetPickaxeDamage(int, int, int, int, Tile) added by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook On.Terraria.GameContent.ItemDropRules.CommonCode::ModifyItemDropFromNPC(NPC, int) added by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::NPCLoot() modified by CalamityMod
[23:59:32] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Item::Prefix(int) added by CalamityMod
[23:59:32] [Main Thread/INFO] [tML]: Initializing: CalamityModMusic (Calamity Mod Music) v2.0.0.3
[23:59:33] [Main Thread/INFO] [tML]: Initializing: AlchemistNPCLite (AlchemistNPC Lite) v1.8.14
[23:59:33] [Main Thread/WARN] [tML]: AlchemistNPCLite.Items.Placeable.MateriaTransmutatorMK2 has reference fields (Calamity) that may not be safe to share between clones.
For deep-cloning, add a custom Clone override and make proper copies of these fields. If shallow (memberwise) cloning is acceptable, mark the fields with [CloneByReference] or properties with [field: CloneByReference]
[23:59:33] [Main Thread/INFO] [tML]: Initializing: AutoReroll (Auto Reforge) v2022.6.26
[23:59:33] [Main Thread/INFO] [tML]: Initializing: AutoTrash (Auto Trash) v0.6.1.2
[23:59:33] [Main Thread/INFO] [tML]: Initializing: BetterMultiplayer (Better Multiplayer) v1.6.2
[23:59:33] [Main Thread/INFO] [tML]: Initializing: CalamityInterludes (Calamity Interludes In-Game) v1.0.4
[23:59:33] [Main Thread/INFO] [tML]: Initializing: CalValEX (Calamity's Vanities) v10.0.4
[23:59:34] [Main Thread/INFO] [tML]: Initializing: DisableCorruptionSpread (Begone, Evil! (Disable Evil Biome Spread)) v1.2.1
[23:59:34] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::UpdateWorld_Inner() modified by DisableCorruptionSpread
[23:59:34] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::SmashAltar(int, int) modified by DisableCorruptionSpread
[23:59:34] [Main Thread/INFO] [tML]: Initializing: Fargowiltas (Fargo's Mutant Mod) v2.8.2
[23:59:34] [Main Thread/INFO] [tML]: Initializing: FargowiltasSouls (Fargo's Souls Mod) v1.4.0.3
[23:59:36] [Main Thread/INFO] [FargowiltasSouls]: ToggleCollections found: 4
[23:59:36] [Main Thread/INFO] [tML]: Initializing: FargowiltasMusic (Fargo's Music Mod) v0.1.1.2
[23:59:36] [Main Thread/INFO] [tML]: Initializing: LansUncraftItems (Lan's Uncraft Items) v2022.6.27
[23:59:36] [Main Thread/INFO] [tML]: Initializing: LavalessLavaSlime (Lava Slime Spawn No Lava) v1.1
[23:59:36] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::VanillaHitEffect_Inner(int, double) modified by LavalessLavaSlime
[23:59:37] [Main Thread/INFO] [tML]: Initializing: MagicStorage (Magic Storage) v0.5.5.2
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [.NET ThreadPool Worker/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> RecursiveCraft, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[23:59:37] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Player::QuickSpawnItem(IEntitySource, int, int) added by MagicStorage
[23:59:37] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Recipe::FindRecipes(bool) added by MagicStorage
[23:59:37] [Main Thread/WARN] [tML]: Granted native detouring access to MagicStorage
[23:59:37] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck_ApplyHoldStyle_Inner(float, Item, Rectangle) modified by MagicStorage
[23:59:37] [Main Thread/INFO] [tML]: Initializing: NoLakeSizePenalty (No Lake Size Penalty) v1.0
[23:59:37] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Projectile::GetFishingPondState(int, int, out bool, out bool, out int, out int) added by NoLakeSizePenalty
[23:59:37] [Main Thread/INFO] [tML]: Initializing: OneStopNPCShop (The Shop Market) v1.2.1.1
[23:59:37] [Main Thread/INFO] [tML]: Initializing: OreExcavator (Ore Excavator - The Successor to VeinMiner) v0.6.9
[23:59:37] [Main Thread/INFO] [tML]: Initializing: RecipeBrowser (Recipe Browser) v0.9.4
[23:59:37] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Player::AdjTiles() added by RecipeBrowser
[23:59:37] [Main Thread/INFO] [tML]: Initializing: ShopExpander (Shop Expander) v1.2.1
[23:59:37] [Main Thread/INFO] [tML]: Initializing: TownNPCHome (Teleport All NPC Home) v1.2.1
[23:59:37] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::moveRoom(int, int, int) added by TownNPCHome
[23:59:37] [Main Thread/INFO] [tML]: Initializing: UnCalamityModMusic (Unofficial Calamity Mod Music) v1.0.7.2
[23:59:38] [Main Thread/INFO] [tML]: Initializing: WingSlotExtra (Wing Slot Extra) v1.3.1
[23:59:38] [Main Thread/INFO] [tML]: Setting up...
[23:59:38] [Main Thread/INFO] [tML]: Loading: ModLoader (tModLoader) v2022.6.96.1
[23:59:38] [Main Thread/INFO] [tML]: Loading: Census (Census - Town NPC Checklist) v0.4.1
[23:59:38] [Main Thread/INFO] [tML]: Loading: CalamityMod (Calamity Mod) v2.0.0.3
[23:59:39] [Main Thread/INFO] [tML]: Loading: CalamityModMusic (Calamity Mod Music) v2.0.0.3
[23:59:39] [Main Thread/INFO] [tML]: Loading: AlchemistNPCLite (AlchemistNPC Lite) v1.8.14
[23:59:39] [Main Thread/INFO] [tML]: Loading: AutoReroll (Auto Reforge) v2022.6.26
[23:59:39] [Main Thread/INFO] [tML]: Loading: AutoTrash (Auto Trash) v0.6.1.2
[23:59:39] [Main Thread/INFO] [tML]: Loading: BetterMultiplayer (Better Multiplayer) v1.6.2
[23:59:39] [Main Thread/INFO] [tML]: Loading: CalamityInterludes (Calamity Interludes In-Game) v1.0.4
[23:59:39] [Main Thread/INFO] [tML]: Loading: CalValEX (Calamity's Vanities) v10.0.4
[23:59:39] [Main Thread/INFO] [tML]: Loading: DisableCorruptionSpread (Begone, Evil! (Disable Evil Biome Spread)) v1.2.1
[23:59:39] [Main Thread/INFO] [tML]: Loading: Fargowiltas (Fargo's Mutant Mod) v2.8.2
[23:59:39] [Main Thread/INFO] [tML]: Loading: FargowiltasSouls (Fargo's Souls Mod) v1.4.0.3
[23:59:39] [Main Thread/INFO] [tML]: Loading: FargowiltasMusic (Fargo's Music Mod) v0.1.1.2
[23:59:39] [Main Thread/INFO] [tML]: Loading: LansUncraftItems (Lan's Uncraft Items) v2022.6.27
[23:59:39] [Main Thread/INFO] [tML]: Loading: LavalessLavaSlime (Lava Slime Spawn No Lava) v1.1
[23:59:40] [Main Thread/INFO] [tML]: Loading: MagicStorage (Magic Storage) v0.5.5.2
[23:59:40] [Main Thread/INFO] [tML]: Loading: NoLakeSizePenalty (No Lake Size Penalty) v1.0
[23:59:40] [Main Thread/INFO] [tML]: Loading: OneStopNPCShop (The Shop Market) v1.2.1.1
[23:59:40] [Main Thread/INFO] [tML]: Loading: OreExcavator (Ore Excavator - The Successor to VeinMiner) v0.6.9
[23:59:40] [Main Thread/INFO] [tML]: Loading: RecipeBrowser (Recipe Browser) v0.9.4
[23:59:40] [Main Thread/INFO] [tML]: Loading: ShopExpander (Shop Expander) v1.2.1
[23:59:40] [Main Thread/DEBUG] [tML]: Hook On.Terraria.ModLoader.NPCLoader::SetupShop(int, Chest, ref int) added by ShopExpander
[23:59:40] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Chest::AddItemToShop(Item) added by ShopExpander
[23:59:40] [Main Thread/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::HandleShopSlot(Item[], int, bool, bool) added by ShopExpander
[23:59:40] [Main Thread/INFO] [tML]: Loading: TownNPCHome (Teleport All NPC Home) v1.2.1
[23:59:40] [Main Thread/INFO] [tML]: Loading: UnCalamityModMusic (Unofficial Calamity Mod Music) v1.0.7.2
[23:59:40] [Main Thread/INFO] [tML]: Loading: WingSlotExtra (Wing Slot Extra) v1.3.1
[23:59:41] [Main Thread/INFO] [tML]: RAM usage: 405.8 MB
[23:59:41] [Main Thread/INFO] [tML]: Adding Recipes...
[23:59:42] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.get_worldPathName() in tModLoader\Terraria\Main.cs:line 2327
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods) in tModLoader\Terraria\Main.cs:line 4162
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4156
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 236
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 195
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72

[23:59:42] [Main Thread/FATAL] [Terraria]: Main engine crash
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.get_worldPathName() in tModLoader\Terraria\Main.cs:line 2327
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods) in tModLoader\Terraria\Main.cs:line 4162
   at Terraria.Main.DedServ() in tModLoader\Terraria\Main.cs:line 4156
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 236

### Steps to reproduce

Download latest release from repo.
Run `./start-tModLoader.sh -server`.

### Expected Behavior

The server should not crash.

### Reproduction frequency

This happens every time.

**Comment by Chicken-Bones** [comment]
The world you tried to load is corrupt. I've added some logging and handling in the new version so servers won't crash and will go to the world load screen instead.

**Comment by itzTheMeow** [comment]
I figured it out, this is because i used `/path/to/world.twld` and not `/path/to/world.wld`.

**Comment by Chicken-Bones** [comment]
ah, yes, this will be easier to see in logs in the future
