### ISSUE TITLE
System.Net.Sockets.SocketException: Permission denied

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#2732]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I also tried to run the server by root, it would always show permission denied.

### Log File

[23:07:42] [Main Thread/INFO] [tML]: Save Are Located At: /home/server/.local/share/Terraria/tModLoader
[23:07:42] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.06.96.4|1.4-stable|Stable|6ee86304725fa4ac713d981d17a87d1b1d0e014a|5249609086868104401 built 7/2/2022 5:14 AM
[23:07:42] [Main Thread/INFO] [tML]: Log date: 7/19/2022
[23:07:42] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[23:07:42] [Main Thread/INFO] [tML]: Executable: /home/server/tModLoader/tModLoader.dll
[23:07:42] [Main Thread/INFO] [tML]: Working Directory: /home/server/tModLoader
[23:07:42] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt
[23:07:42] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[23:07:44] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.3.6_B.exe not found nearby
[23:07:44] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[23:07:44] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null -> steam_api
[23:07:44] [Main Thread/DEBUG] [tML]: 	attempting load /home/server/tModLoader/Libraries/Native/Linux/libsteam_api64.so
[23:07:44] [Main Thread/DEBUG] [tML]: 	success
[23:07:47] [Main Thread/INFO] [tML]: Unloading mods
[23:07:50] [Main Thread/INFO] [tML]: Finding Mods...
[23:07:50] [Main Thread/INFO] [tML]: Instantiating Mods...
[23:07:50] [Main Thread/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.6.96.4
[23:07:50] [Main Thread/INFO] [tML]: Setting up...
[23:07:50] [Main Thread/INFO] [tML]: Loading: ModLoader (tModLoader) v2022.6.96.4
[23:07:51] [Main Thread/INFO] [tML]: RAM usage: 243.7 MB
[23:07:51] [Main Thread/INFO] [tML]: Adding Recipes...
[23:08:13] [.NET ThreadPool Worker/INFO] [Terraria]: Loading World: Test World, IsCloud=False, Size=4200x1200
[23:08:13] [.NET ThreadPool Worker/INFO] [StatusText]: Loading world data
[23:08:15] [.NET ThreadPool Worker/INFO] [StatusText]: Settling liquids
[23:08:16] [Main Thread/INFO] [Terraria]: Running one update...
[23:08:16] [Main Thread/INFO] [tML]: Server starting with AllowVanillaClients set to False
[23:08:18] [Main Thread/INFO] [Terraria]: Listening on port 7777
**[23:08:19] [14/WARN] [tML]: Silently Caught Exception: 
System.Net.Sockets.SocketException: Permission denied
   at System.Net.Sockets.Socket.UpdateStatusAfterSocketErrorAndThrowException(SocketError error, String callerName)
   at System.Net.Sockets.Socket.SendTo(Byte[] buffer, Int32 offset, Int32 size, SocketFlags socketFlags, EndPoint remoteEP)
   at System.Net.Sockets.UdpClient.Send(Byte[] dgram, Int32 bytes, IPEndPoint endPoint)
   at Terraria.Netplay.BroadcastThread() in tModLoader\Terraria\Netplay.cs:line 749
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()**

**Comment by Chicken-Bones** [comment]
There's very little info here, you didn't fill out most of the questions. Please post your log as a file, rather than text.

Does anything bad happen other than a message in the logs?
