### ISSUE TITLE
Not catching directory removel exception

### ISSUE THREAD

**Issue by Lanboost** [bluemagic123/tModLoader#2741]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I may or may not have published my mod with local built tModLoader (version 9999.0). Now when I want to publish it with the correct (stable) version the following happens.

The problem is because of the lines:

```
// This eliminates version 9999 in case someone bypasses the IsDev Check for testing or whatever
string devRemnant = Path.Combine(workshopFolderPath, "9999.0");
if (Directory.Exists(devRemnant)) {
	Directory.Delete(devRemnant, true);
}
```

I cannot say exactly why it fails, but I assume the file is being checked with "new WorkshopHelper.ModManager" so a file lock is active. (Or the lock have not yet had time to be released).

A simple catch/retry/wait should solve the issue I believe.

### Log File

`[12:43:41] [Main Thread/ERROR] [Terraria]: System.IO.IOException: The directory is not empty. : 'E:\steam\steamapps\workshop\content\1281930\2824438392\9999.0'
   at System.IO.FileSystem.RemoveDirectoryInternal(String fullPath, Boolean topLevel, Boolean allowDirectoryNotEmpty)
   at System.IO.FileSystem.RemoveDirectory(String fullPath, Boolean recursive)
   at Terraria.Social.Steam.WorkshopSocialModule.PublishMod(TmodFile modFile, NameValueCollection buildData, WorkshopItemPublishSettings settings) in tModLoader\Terraria\Social\Steam\WorkshopSocialModule.TML.cs:line 88
   at Terraria.GameContent.UI.States.WorkshopPublishInfoStateForMods.GoToPublishConfirmation() in tModLoader\Terraria\GameContent\UI\States\WorkshopPublishInfoStateForMods.TML.cs:line 39
   at Terraria.GameContent.UI.States.AWorkshopPublishInfoState`1.Click_Publish(UIMouseEvent evt, UIElement listeningElement) in tModLoader\Terraria\GameContent\UI\States\AWorkshopPublishInfoState.cs:line 580
   at Terraria.UI.UIElement.Click(UIMouseEvent evt) in tModLoader\Terraria\UI\UIElement.cs:line 381
   at Terraria.UI.UserInterface.Update(GameTime time) in tModLoader\Terraria\UI\UserInterface.cs:line 251
   at Terraria.Main.UpdateUIStates(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 13227
   at Terraria.Main.DoUpdate(GameTime& gameTime) in tModLoader\Terraria\Main.cs:line 12863
   at Terraria.Main.Update(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 12631`

### Steps to reproduce

File lock race condition / might be hard to reproduce
1. Upload a mod with version 9999.0 tModLoader (dev version)
2. use normal tModLoader and try to publish
3. Hope that the file lock has not been released

### Expected Behavior

To be able to publish a mod (even if I do bad stuff as publishing with dev tModLoader)

### Actual Behavior

Publishing fails

### Reproduction frequency

100%

**Comment by Lanboost** [comment]
Current work-arounds, Manually hack away the 9999.0 version etc, publish to a new workshop item.

**Comment by Solxanich** [comment]
I fixed this at somepoint, and I don't remember when. 
The issue was that I didn't have recursive = true in the .Delete parameters. 

Doesn't look like the commit made it to stable in July: https://github.com/tModLoader/tModLoader/commit/23399923871ec0634dc8d6f9fedd534ea61bc799
