### ISSUE TITLE
Tmod server crashes when anyone uses the clentaminator

### ISSUE THREAD

**Issue by OttersThoth** [bluemagic123/tModLoader#2767]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

The server crashes when anyone uses the clentaminator at any time. For the no host players they describe a surge of massive lag.

### Log File

[23:23:59] [Main Thread/INFO] [tML]: Save Are Located At: C:\Users\arons\OneDrive\Dokument\My Games\Terraria\tModLoader
[23:23:59] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.06.96.4|1.4-stable|Stable|6ee86304725fa4ac713d981d17a87d1b1d0e014a|5249609086868104401 built 2022-07-01 23:14
[23:23:59] [Main Thread/INFO] [tML]: Log date: 2022-07-27
[23:23:59] [Main Thread/INFO] [tML]: Running on Windows X64 NetCore 6.0.0
[23:23:59] [Main Thread/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.dll
[23:23:59] [Main Thread/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader
[23:24:01] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[23:24:01] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" tModLoader.dll -terrariasteamclient 1448
[23:24:01] [Main Thread/DEBUG] [TerrariaSteamClient]: Recv: init_success
[23:24:01] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: acknowledged
[23:24:02] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 110.0 MB available
[23:24:02] [Main Thread/INFO] [FNA]: FNA3D Driver: D3D11
[23:24:02] [Main Thread/INFO] [FNA]: D3D11 Adapter: NVIDIA GeForce GTX 1060 6GB
[23:24:03] [Main Thread/DEBUG] [Terraria]: Device Created, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: Reach, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[23:24:03] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: Reach, Width: 800 -> 1920, Height: 480 -> 1027, Fullscreen: False, Display: \\.\DISPLAY1
[23:24:29] [.NET ThreadPool Worker/INFO] [tML]: Unloading mods
[23:24:30] [.NET ThreadPool Worker/INFO] [tML]: Finding Mods...
[23:24:30] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: BossChecklist
[23:24:31] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: BossCursor
[23:24:31] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: CalamityMod
[23:24:32] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: CalamityModMusic
[23:24:32] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: ClamExtraMusic
[23:24:32] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: ShowBody
[23:24:33] [.NET ThreadPool Worker/INFO] [tML]: Instantiating Mods...
[23:24:33] [.NET ThreadPool Worker/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.6.96.4
[23:24:33] [.NET ThreadPool Worker/INFO] [tML]: Initializing: BossChecklist (Boss Checklist) v1.3.6
[23:24:34] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.GameContent.Events.DD2Event::WinInvasionInternal() added by BossChecklist
[23:24:34] [.NET ThreadPool Worker/INFO] [BossChecklist]: Boss Log integration messages will not be logged.
[23:24:34] [.NET ThreadPool Worker/INFO] [tML]: Initializing: BossCursor (Boss Cursor) v2.0.0
[23:24:34] [.NET ThreadPool Worker/INFO] [tML]: Initializing: CalamityMod (Calamity Mod) v2.0.0.3
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.NPC::ApplyTileCollision(bool, Vector2, int, int) added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.NPC::ShouldEmpressBeEnraged() added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::Hurt(PlayerDeathReason, int, int, bool, bool, bool, int) modified by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::DashMovement() modified by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::GiveImmuneTimeForCollisionAttack(int) modified by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::Update_NPCCollision() modified by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Wiring::Teleport() added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Main::DrawInterface_40_InteractItemIcon() modified by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Item::AffixName() added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Projectile::NewProjectile(IEntitySource, float, float, float, float, int, int, float, int, float, float) added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Main::DrawCursor(Vector2, bool) added by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::QuickHeal() modified by CalamityMod
[23:24:41] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::QuickMana() modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck_Inner(int) modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Main::SortDrawCacheWorms() added by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.GameContent.Drawing.TileDrawing::DrawPartialLiquid(Tile, Vector2, Rectangle, int, Color) modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.GameContent.Liquid.LiquidRenderer::InternalDraw(SpriteBatch, Vector2, int, float, bool) modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Main::oldDrawWater(bool, int, float) modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.NPC::Collision_DecideFallThroughPlatforms() added by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Main::DamageVar(float, float) modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.NPC::ScaleStats_ApplyExpertTweaks() modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Projectile::AI_001() modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateJumpHeight() modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:24:42] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Initializers.WingStatsInitializer::Load() modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::WingMovement() modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateBuffs(int) modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateLifeRegen() modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateManaRegen() modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Pyramid(int, int) modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod
[23:24:43] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::DungeonHalls(int, int, ushort, int, bool) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int, bool) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.WorldGen::SmashAltar(int, int) added by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::hardUpdateWorld(int, int) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Chlorophyte(int, int) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.GameContent.UI.States.UIWorldCreation::SetDefaultOptions() modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.GameContent.UI.States.UIWorldCreation::AddWorldSizeOptions(UIElement, float, MouseEvent, string, float) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.GameContent.Events.Sandstorm::HasSufficientWind() modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Item::Prefix(int) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.NPC::SpawnNPC() modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Player::IsTileTypeInInteractionRange(int) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Projectile::CanExplodeTile(int, int) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateWindyDayState() modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime_StartNight(ref bool) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.WorldGen::AttemptFossilShattering(int, int, Tile, bool) modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.Projectile::Damage() modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Player::GetPickaxeDamage(int, int, int, int, Tile) added by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.GameContent.ItemDropRules.CommonCode::ModifyItemDropFromNPC(NPC, int) added by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook IL.Terraria.NPC::NPCLoot() modified by CalamityMod
[23:24:44] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Item::Prefix(int) added by CalamityMod
[23:24:46] [.NET ThreadPool Worker/INFO] [tML]: Initializing: CalamityModMusic (Calamity Mod Music) v2.0.0.3
[23:24:46] [.NET ThreadPool Worker/INFO] [tML]: Initializing: ClamExtraMusic (Calamity Mod Extra Music) v1.1.0
[23:24:46] [.NET ThreadPool Worker/INFO] [tML]: Initializing: ShowBody (显示boss身体) v0.2
[23:24:46] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Graphics.Renderers.NPCHeadRenderer::DrawWithOutlines(Entity, int, Vector2, Color, float, float, SpriteEffects) added by ShowBody
[23:24:47] [.NET ThreadPool Worker/INFO] [tML]: Setting up...
[23:24:47] [.NET ThreadPool Worker/INFO] [tML]: Loading: ModLoader (tModLoader) v2022.6.96.4
[23:24:47] [.NET ThreadPool Worker/INFO] [tML]: Loading: BossChecklist (Boss Checklist) v1.3.6
[23:24:47] [.NET ThreadPool Worker/INFO] [tML]: Loading: BossCursor (Boss Cursor) v2.0.0
[23:24:48] [.NET ThreadPool Worker/INFO] [tML]: Loading: CalamityMod (Calamity Mod) v2.0.0.3
[23:24:50] [.NET ThreadPool Worker/INFO] [tML]: Loading: CalamityModMusic (Calamity Mod Music) v2.0.0.3
[23:24:50] [.NET ThreadPool Worker/INFO] [tML]: Loading: ClamExtraMusic (Calamity Mod Extra Music) v1.1.0
[23:24:50] [.NET ThreadPool Worker/INFO] [tML]: Loading: ShowBody (显示boss身体) v0.2
[23:24:50] [.NET ThreadPool Worker/INFO] [tML]: RAM usage: 1.3 GB
[23:24:51] [.NET ThreadPool Worker/INFO] [tML]: Adding Recipes...
[23:24:51] [.NET ThreadPool Worker/INFO] [BossChecklist]: AddBoss calls for the following either not utilizing Boss Log features or is using an old call method for it. Mod developers should update mod calls with proper information to improve user experience. AddBoss entries include: [Desert Scourge, Crabulon, Hive Mind, The Perforators, Slime God, Cryogen, Aquatic Scourge, Brimstone Elemental, Calamitas, Leviathan, Astrum Aureus, Plaguebringer Goliath, Ravager, Astrum Deus, Profaned Guardians, Dragonfolly, Providence, Ceaseless Void, Storm Weaver, Signus, Polterghast, Old Duke, Devourer of Gods, Yharon, Exo Mechs, Supreme Calamitas, Adult Eidolon Wyrm]
[23:24:51] [.NET ThreadPool Worker/INFO] [BossChecklist]: AddMiniBoss calls for the following either not utilizing Boss Log features or is using an old call method for it. Mod developers should update mod calls with proper information to improve user experience. AddMiniBoss entries include: [Giant Clam, Great Sand Shark]
[23:24:51] [.NET ThreadPool Worker/INFO] [BossChecklist]: AddEventWithInfo calls for the following either not utilizing Boss Log features or is using an old call method for it. Mod developers should update mod calls with proper information to improve user experience. AddEventWithInfo entries include: [Acid Rain, Acid Rain (Post-AS), Acid Rain (Post-Polter)]
[23:24:51] [.NET ThreadPool Worker/INFO] [BossChecklist]: Updated Mod.Call documentation for BossChecklist can be found here: https://github.com/JavidPack/BossChecklist/wiki/%5B1.4-alpha%5D-Mod-Call-Structure
[23:25:18] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" tModLoader.dll -server -autoshutdown -password "" -lang 1 -world "C:\Users\arons\OneDrive\Dokument\My Games\Terraria\tModLoader\Worlds\911_AU.wld" -worldrollbackstokeep 2 -modpath "C:\Users\arons\OneDrive\Dokument\My Games\Terraria\tModLoader\Mods" -showserverconsole -steam -localsteamid 76561198269206916 -lobby friends
[23:25:18] [TCP Client Thread/INFO] [Terraria]: Connecting to 127.0.0.1:7777
[23:25:20] [TCP Client Thread/WARN] [tML]: Silently Caught Exception: 
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Det gick inte att göra en anslutning eftersom måldatorn aktivt nekade det. [::ffff:127.0.0.1]:7777
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at Terraria.Net.Sockets.TcpSocket.Terraria.Net.Sockets.ISocket.Connect(RemoteAddress address) in tModLoader\Terraria\Net\Sockets\TcpSocket.cs:line 51
   at Terraria.Netplay.TcpClientLoop() in tModLoader\Terraria\Netplay.cs:line 410
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

[23:25:53] [Main Thread/INFO] [tML]: Server reports AllowVanillaClients set to False
[23:25:53] [TCP Client Thread/INFO] [StatusText]: Loading map data
[23:25:54] [TCP Client Thread/INFO] [StatusText]: Drawing map
[23:25:54] [TCP Client Thread/INFO] [StatusText]: Receiving tile data
[23:25:55] [Main Thread/INFO] [Terraria]: Entering world with player: Iacul, IsCloud=False, Size=8400x2400
[23:26:31] [TCP Client Thread/INFO] [StatusText]: Receiving tile data
[23:26:31] [TCP Client Thread/INFO] [StatusText]: Receiving tile data
[23:26:34] [TCP Client Thread/INFO] [StatusText]: Receiving tile data

### Steps to reproduce

1. host a world (with calamity)
2. use a  clentaminator
3. profit

### Expected Behavior

teh corrupted blocks return to normal

### Actual Behavior

server crashes. Non host players game crashes and host loses connection

### Reproduction frequency

every time.

### Additional Information

Maybe calamity?

**Comment by JavidPack** [comment]
since the server is crashing, we need to see server.log

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.

**Comment by TheAverageFox** [comment]
I had the exact same issue, turning OFF frame skip fixed this issue for me, I don't know why.
