### ISSUE TITLE
Use a simple script to open tmodServer

### ISSUE THREAD

**Issue by yishuiwang** [bluemagic123/tModLoader#2803]
### Version

tModLoader v2022.6.96.4

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I am trying to adapt a background website management for tmod. This is my frontend [project](https://github.com/yishuiwang/Tmod-Server-Manager). But when I use golang script to start tmodServer, it always faied to start.
When I turn it on manually  thorough **./start-tModLoaderServer.sh** , it works fine. I know it doesn't look like a bug and maybe there is an error in my program. So could  help me point out my error. 

### Log File

[17:34:56] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[17:34:56] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.06.96.4|1.4-stable|Stable|6ee86304725fa4ac713d981d17a87d1b1d0e014a|5249609086868104401 built 7/2/2022 5:14 AM
[17:34:56] [Main Thread/INFO] [tML]: Log date: 8/4/2022
[17:34:56] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[17:34:56] [Main Thread/INFO] [tML]: Executable: /root/terraria/tModLoader/tModLoader.dll
[17:34:56] [Main Thread/INFO] [tML]: Working Directory: /root/terraria/tModLoader
[17:34:56] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt
[17:34:56] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[17:34:57] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.3.6_B.exe not found nearby
[17:34:57] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[17:34:57] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null -> steam_api
[17:34:57] [Main Thread/DEBUG] [tML]: 	attempting load /root/terraria/tModLoader/Libraries/Native/Linux/libsteam_api64.so
[17:34:57] [Main Thread/DEBUG] [tML]: 	success
[17:34:57] [Main Thread/ERROR] [tML]: Steam Game Server failed to Init. Steam Workshop downloading on GoG is unavailable. Make sure Steam is installed
[17:35:00] [Main Thread/INFO] [tML]: Unloading mods
[17:35:02] [Main Thread/INFO] [tML]: Finding Mods...
[17:35:03] [Main Thread/INFO] [tML]: Instantiating Mods...
[17:35:03] [Main Thread/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.6.96.4
[17:35:03] [Main Thread/INFO] [tML]: Setting up...
[17:35:03] [Main Thread/INFO] [tML]: Loading: ModLoader (tModLoader) v2022.6.96.4
[17:35:03] [Main Thread/INFO] [tML]: RAM usage: 216.6 MB
[17:35:03] [Main Thread/INFO] [tML]: Adding Recipes...
[17:35:04] [.NET ThreadPool Worker/INFO] [Terraria]: Loading World: Finally, IsCloud=False, Size=8400x2400
[17:35:04] [.NET ThreadPool Worker/INFO] [StatusText]: Loading world data
[17:35:06] [.NET ThreadPool Worker/INFO] [StatusText]: Settling liquids
[17:35:08] [Main Thread/INFO] [Terraria]: Running one update...
[17:35:08] [Main Thread/INFO] [tML]: Server starting with AllowVanillaClients set to False
[17:35:09] [Main Thread/INFO] [Terraria]: Listening on port 7777
[17:35:09] [Server Input Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.ExecuteCommand(String text, CommandCaller commandCaller) in tModLoader\Terraria\Main.cs:line 4661
   at Terraria.Main.startDedInputCallBack() in tModLoader\Terraria\Main.cs:line 4655
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

[17:35:09] [Server Input Thread/ERROR] [tML]: Unhandled Exception
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.ExecuteCommand(String text, CommandCaller commandCaller) in tModLoader\Terraria\Main.cs:line 4661
   at Terraria.Main.startDedInputCallBack() in tModLoader\Terraria\Main.cs:line 4655
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

### Steps to reproduce

1. soure code
```
package main

import (
	"fmt"
	"io"
	"log"
	"os"
	"os/exec"
	"strings"
)

func main() {
	path := `./start-tModLoaderServer.sh`
	proc := exec.Command("/bin/bash", "-c", path, "-config", "server.config")
	stdout, _ := proc.StdoutPipe()
	stderr, _ := proc.StderrPipe()
	//stdin, _ := proc.StdinPipe()

	if err := proc.Start(); err != nil {
		log.Printf("Error starting command: %s......", err.Error())
		os.Exit(1)
	}

	go asyncLog(stdout)
	go asyncLog(stderr)

	if err := proc.Wait(); err != nil {
		log.Printf("Error waiting for command execution: %s......", err.Error())
	}

}

func asyncLog(reader io.ReadCloser) error {
	cache := ""
	buf := make([]byte, 1024, 1024)
	for {
		num, err := reader.Read(buf)
		if err != nil {
			if err == io.EOF || strings.Contains(err.Error(), "closed") {
				err = nil
			}
		}
		if num > 0 {
			oByte := buf[:num]
			oSlice := strings.Split(string(oByte), "\n")
			line := strings.Join(oSlice[:len(oSlice)-1], "\n")
			fmt.Println(cache, line)
			cache = oSlice[len(oSlice)-1]
		}
	}
	return nil
}

```

2. go run main.go

### Expected Behavior

The server starts normally and does not exit immediately

### Actual Behavior

An error is reported immediately after the server starts.  My program caught the Linux signal variable **SIGABRT** on the last line

```
 Settling liquids 49%
 Settling liquids 50%
 Running one update...
 Terraria Server v1.4.3.6

Listening on port 7777
 Type 'help' for a list of commands.


:  Object reference not set to an instance of an object. (see server.log for full trace)
 ./start-tModLoaderServer.sh: line 25: 2440609 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args
2022/08/04 17:35:09 Error waiting for command execution: exit status 134......
```

### Reproduction frequency

100%

**Comment by Chicken-Bones** [comment]
Can you try again with the latest tModLoader preview?

**Comment by yishuiwang** [comment]
Thanks for your help.  Now,  my script works normally! By the way, it looks like my program can not run before this version **v2022.07.58.8**  . What's the problem do you think.

**Comment by yishuiwang** [comment]
> Can you try again with the latest tModLoader preview?
Thanks for your help. Now, my script works normally! By the way, it looks like my program can not run before this version v2022.07.58.8 . What's the problem do you think.

**Comment by yishuiwang** [comment]
> Can you try again with the latest tModLoader preview?

Thanks for your help. Now, my script works normally! By the way, it looks like my program can not run before this version v2022.07.58.8 . What's the problem do you think.

**Comment by Chicken-Bones** [comment]
I think the issue is that the way you're spawning your process, stdin gets disconnected somehow. But not sure
