### ISSUE TITLE
Server gets stuck then closes itself

### ISSUE THREAD

**Issue by SeGby** [bluemagic123/tModLoader#2804]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

After initializing a few mods the tmodServer closes itself after giving this error
./start-tModLoaderServer.sh: line 25: 3826725 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args

### Log File

[20:33:19] [Main Thread/INFO] [tML]: Save Are Located At: /home/tmod/.local/share/Terraria/tModLoader
[20:33:19] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.06.96.4|1.4-stable|Stable|6ee86304725fa4ac713d981d17a87d1b1d0e014a|5249609086868104401 built 7/1/2022 9:14 PM
[20:33:19] [Main Thread/INFO] [tML]: Log date: 8/3/2022
[20:33:19] [Main Thread/INFO] [tML]: Running on Linux X64 NetCore 6.0.0
[20:33:19] [Main Thread/INFO] [tML]: Executable: /home/tmod/.local/share/Terraria/tModLoader/tModLoader.dll
[20:33:19] [Main Thread/INFO] [tML]: Working Directory: /home/tmod/.local/share/Terraria/tModLoader
[20:33:19] [Main Thread/INFO] [tML]: Launch Parameters: -server -config serverconfig.txt
[20:33:19] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[20:33:20] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.3.6_B.exe not found nearby
[20:33:20] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[20:33:20] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null -> steam_api
[20:33:20] [Main Thread/DEBUG] [tML]: 	attempting load /home/tmod/.local/share/Terraria/tModLoader/Libraries/Native/Linux/libsteam_api64.so
[20:33:20] [Main Thread/DEBUG] [tML]: 	success
[20:33:21] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ComponentModel.Win32Exception: Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Terraria.Initializers.LaunchInitializer.LoadServerParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 116
   at Terraria.Initializers.LaunchInitializer.LoadParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 17
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 195
   at MonoLaunch.<>c__DisplayClass2_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 65
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 72

[20:33:24] [Main Thread/INFO] [tML]: Unloading mods
[20:33:25] [Main Thread/INFO] [tML]: Finding Mods...
[20:33:27] [Main Thread/INFO] [tML]: Sandboxing: AnimeOverhaul
[20:33:27] [Main Thread/INFO] [tML]: Sandboxing: AutoReroll
[20:33:27] [Main Thread/INFO] [tML]: Sandboxing: CalamityMod
[20:33:28] [Main Thread/INFO] [tML]: Sandboxing: CalamityModMusic
[20:33:28] [Main Thread/INFO] [tML]: Sandboxing: CalValEX
[20:33:28] [Main Thread/INFO] [tML]: Sandboxing: CheatSheet
[20:33:28] [Main Thread/DEBUG] [tML]: Assembly Resolve: CheatSheet, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null
[20:33:28] [Main Thread/INFO] [tML]: Sandboxing: Fargowiltas
[20:33:28] [Main Thread/DEBUG] [tML]: Assembly Resolve: Fargowiltas, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: FullHPWhenRespawn
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: TeaFramework
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: HappinessRemoval
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: HEROsMod
[20:33:29] [Main Thread/DEBUG] [tML]: Assembly Resolve: HEROsMod, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: ImproveGame
[20:33:29] [Main Thread/DEBUG] [tML]: Assembly Resolve: ImproveGame, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null
[20:33:29] [Main Thread/DEBUG] [tML]: Assembly Resolve:  -> FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: LansAutoSummon
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: MagicStorage
[20:33:29] [Main Thread/DEBUG] [tML]: Assembly Resolve: MagicStorage, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: NoFishingQuests
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: OreExcavator
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: RecipeBrowser
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: ShorterRespawn
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: SubworldLibrary
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: StarsAbove
[20:33:29] [Main Thread/DEBUG] [tML]: Assembly Resolve: StarsAbove, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null
[20:33:29] [Main Thread/DEBUG] [tML]: Assembly Resolve:  -> FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: TooManyAccessories14
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: UnlimitedBuffSlots
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: UsefulVanity
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: WeaponDisplay
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: WingSlotExtra
[20:33:29] [Main Thread/INFO] [tML]: Sandboxing: XenVanitySets
[20:33:29] [Main Thread/INFO] [tML]: Instantiating Mods...
[20:33:30] [Main Thread/WARN] [tML]: Granted native detouring access to TeaFramework
[20:33:30] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.ModLoader.ModContent::LoadModContent(CancellationToken, Action`1) modified by MonoMod.Utils
[20:33:31] [Main Thread/INFO] [tML]: Initializing: ModLoader (tModLoader) v2022.6.96.4
[20:33:31] [Main Thread/INFO] [tML]: Initializing: AnimeOverhaul (Anime Vanity & Pets | HololiveEN Update) v2.2
[20:33:32] [Main Thread/INFO] [tML]: Initializing: AutoReroll (Auto Reforge) v2022.6.26
[20:33:32] [Main Thread/INFO] [tML]: Initializing: CalamityMod (Calamity Mod) v2.0.0.3
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::ApplyTileCollision(bool, Vector2, int, int) added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::ShouldEmpressBeEnraged() added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Hurt(PlayerDeathReason, int, int, bool, bool, bool, int) modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::DashMovement() modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::GiveImmuneTimeForCollisionAttack(int) modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update_NPCCollision() modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Wiring::Teleport() added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::DrawInterface_40_InteractItemIcon() modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Item::AffixName() added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Projectile::NewProjectile(IEntitySource, float, float, float, float, int, int, float, int, float, float) added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::DrawCursor(Vector2, bool) added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::QuickHeal() modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::QuickMana() modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::ItemCheck_Inner(int) modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::SortDrawCacheWorms() added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Main::SetDisplayMode(int, int, bool) added by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Drawing.TileDrawing::DrawPartialLiquid(Tile, Vector2, Rectangle, int, Color) modified by CalamityMod
[20:33:54] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Liquid.LiquidRenderer::InternalDraw(SpriteBatch, Vector2, int, float, bool) modified by CalamityMod
[20:33:55] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::oldDrawWater(bool, int, float) modified by CalamityMod
[20:33:55] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::Collision_DecideFallThroughPlatforms() added by CalamityMod
[20:33:55] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod
[20:33:55] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::DamageVar(float, float) modified by CalamityMod
[20:33:55] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::ScaleStats_ApplyExpertTweaks() modified by CalamityMod
[20:33:55] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::AI_001() modified by CalamityMod
[20:33:55] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateJumpHeight() modified by CalamityMod
[20:33:55] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[20:33:56] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[20:33:56] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Initializers.WingStatsInitializer::Load() modified by CalamityMod
[20:33:57] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[20:33:57] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[20:33:57] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::WingMovement() modified by CalamityMod
[20:33:57] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateBuffs(int) modified by CalamityMod
[20:33:58] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateLifeRegen() modified by CalamityMod
[20:33:58] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::Update(int) modified by CalamityMod
[20:33:58] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::UpdateManaRegen() modified by CalamityMod
[20:33:58] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Pyramid(int, int) modified by CalamityMod
[20:33:58] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod
[20:33:58] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::DungeonHalls(int, int, ushort, int, bool) modified by CalamityMod
[20:33:58] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int, bool) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook On.Terraria.WorldGen::SmashAltar(int, int) added by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::hardUpdateWorld(int, int) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::Chlorophyte(int, int) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.UI.States.UIWorldCreation::SetDefaultOptions() modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.UI.States.UIWorldCreation::AddWorldSizeOptions(UIElement, float, MouseEvent, string, float) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.GameContent.Events.Sandstorm::HasSufficientWind() modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Item::Prefix(int) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::SpawnNPC() modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Player::IsTileTypeInInteractionRange(int) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::CanExplodeTile(int, int) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateWindyDayState() modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime_StartNight(ref bool) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.WorldGen::AttemptFossilShattering(int, int, Tile, bool) modified by CalamityMod
[20:33:59] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.Projectile::Damage() modified by CalamityMod
[20:34:00] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Player::GetPickaxeDamage(int, int, int, int, Tile) added by CalamityMod
[20:34:00] [Main Thread/DEBUG] [tML]: Hook On.Terraria.GameContent.ItemDropRules.CommonCode::ModifyItemDropFromNPC(NPC, int) added by CalamityMod
[20:34:00] [Main Thread/DEBUG] [tML]: Hook IL.Terraria.NPC::NPCLoot() modified by CalamityMod
[20:34:00] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Item::Prefix(int) added by CalamityMod
[20:34:00] [Main Thread/INFO] [tML]: Initializing: CalamityModMusic (Calamity Mod Music) v2.0.0.3
[20:34:00] [Main Thread/INFO] [tML]: Initializing: CalValEX (Calamity's Vanities) v10.0.5
[20:34:03] [Main Thread/INFO] [tML]: Initializing: CheatSheet (Cheat Sheet) v0.7.3.4

### Steps to reproduce

Download latest tmodServer
Install mods as instructed here https://github.com/tModLoader/tModLoader/wiki/Starting-a-modded-server
Run ./start-tModLoaderServer.sh
Get stuck

### Expected Behavior

Server should start and run normally

### Actual Behavior

Server closes itself

### Reproduction frequency

100%

**Comment by Chicken-Bones** [comment]
Please test if this happens with no mods installed. If so, send me a message on Discord after Monday and I'll try and help you resolve it

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
