### ISSUE TITLE
Texture2D creation failed: After entering the world with Calamity Mod installed, the game crashes and exits

### ISSUE THREAD

**Issue by Vincentule** [bluemagic123/tModLoader#2809]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

After entering the world with Calamity Mod installed, the game crashes and exits

### Log File

2022/8/7 下午10:38:58
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.TryDisposingEverything() in tModLoader\Terraria\Main.cs:line 37036
   at Terraria.Main.Main_Exiting(Object sender, EventArgs e) in tModLoader\Terraria\Main.cs:line 37027
   at Microsoft.Xna.Framework.Game.OnExiting(Object sender, EventArgs args) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 711
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 235

2022/8/7 下午10:50:05
Creating world - Seed: 1543383419 Width: 6400, Height: 1800, Evil: -1, IsExpert: False
System.InvalidOperationException: Texture2D creation failed! Error Code:  (0x8007000E)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateTexture2D(IntPtr device, SurfaceFormat format, Int32 width, Int32 height, Int32 levelCount, Byte isRenderTarget)
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat format) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\Texture2D.cs:line 68
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 165
   at CalamityMod.Particles.FusableParticleManager.LoadParticleRenderSets(Boolean reload, Int32 width, Int32 height) in CalamityMod\Particles\FusableParticleManager.cs:line 71
   at CalamityMod.ILEditing.ILChanges.ResetRenderTargetSizes(orig_SetDisplayMode orig, Int32 width, Int32 height, Boolean fullscreen) in CalamityMod\ILEditing\MechanicILChanges.cs:line 663
   at Terraria.Main.UpdateDisplaySettings() in tModLoader\Terraria\Main.cs:line 52487
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48685
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48630
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 235

2022/8/7 下午11:03:36
System.InvalidOperationException: Texture2D creation failed! Error Code:  (0x8007000E)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateTexture2D(IntPtr device, SurfaceFormat format, Int32 width, Int32 height, Int32 levelCount, Byte isRenderTarget)
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat format) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\Texture2D.cs:line 68
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 165
   at CalamityMod.Particles.FusableParticleManager.LoadParticleRenderSets(Boolean reload, Int32 width, Int32 height) in CalamityMod\Particles\FusableParticleManager.cs:line 71
   at CalamityMod.ILEditing.ILChanges.ResetRenderTargetSizes(orig_SetDisplayMode orig, Int32 width, Int32 height, Boolean fullscreen) in CalamityMod\ILEditing\MechanicILChanges.cs:line 663
   at Terraria.Main.UpdateDisplaySettings() in tModLoader\Terraria\Main.cs:line 52487
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48685
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48630
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 235

2022/8/7 下午11:07:48
System.InvalidOperationException: Texture2D creation failed! Error Code:  (0x8007000E)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateTexture2D(IntPtr device, SurfaceFormat format, Int32 width, Int32 height, Int32 levelCount, Byte isRenderTarget)
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat format) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\Texture2D.cs:line 68
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 165
   at CalamityMod.Particles.FusableParticleManager.LoadParticleRenderSets(Boolean reload, Int32 width, Int32 height) in CalamityMod\Particles\FusableParticleManager.cs:line 71
   at CalamityMod.ILEditing.ILChanges.ResetRenderTargetSizes(orig_SetDisplayMode orig, Int32 width, Int32 height, Boolean fullscreen) in CalamityMod\ILEditing\MechanicILChanges.cs:line 663
   at Terraria.Main.UpdateDisplaySettings() in tModLoader\Terraria\Main.cs:line 52487
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48685
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48630
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 235

### Steps to reproduce

1.create a world
2.enter the world
3.after a while, the game becomes slower and then crashs and exits

### Expected Behavior

play normally

### Actual Behavior

crashs and exits

### Reproduction frequency

Every time

**Comment by JavidPack** [comment]
I believe you are just running out of video ram, but I'm not sure how to fix that. It would help if you posted client.log directly

This issue comes up everyday on our discord support, we should look into what is causing it. Most reports are from very weak computers, but one was a rtx3080 iirc, so I'm not sure. They pretty much all are Calamity related. I'll add more reports here as they come in. 

Our upcoming change to enforce not using the Reach graphics profile might compound this issue.

**Comment by Chicken-Bones** [comment]
Needs more reproduction info, maybe we (or calamity) need to implement some unloading of giant textures?

**Comment by Vincentule** [comment]
> 需要更多的再现信息，也许我们（或灾难）需要实现一些巨型纹理的卸载？

It seems a Calamity's problem, a Strange thing is that if I enter the game at a smaller resolution the game won't crash and exit, even if I adjust it to high resolution again in the settings, thanks so much

**Comment by Phoupraw** [comment]
A same crash. Just post log for record.
[client.log](https://github.com/user-attachments/files/20299531/client.log)
16GB memory and RTX 3060 Ti.

**Comment by JavidPack** [comment]
> A same crash. Just post log for record. [client.log](https://github.com/user-attachments/files/20299531/client.log) 16GB memory and RTX 3060 Ti.

```
[23:01:27.861] [Main Thread/INFO] [tML]: tModLoader RAM usage has increased: 42.4 GB
[23:02:27.870] [Main Thread/INFO] [tML]: tModLoader RAM usage has increased: 44.2 GB
[23:03:27.869] [Main Thread/INFO] [tML]: tModLoader RAM usage has increased: 46.2 GB
[23:04:27.875] [Main Thread/INFO] [tML]: tModLoader RAM usage has increased: 48.0 GB
[23:05:27.883] [Main Thread/INFO] [tML]: tModLoader RAM usage has increased: 50.0 GB
[23:06:27.887] [Main Thread/INFO] [tML]: tModLoader RAM usage has increased: 52.1 GB
[23:07:27.890] [Main Thread/INFO] [tML]: tModLoader RAM usage has increased: 54.0 GB
```
Seems like you have a different issue, most likely a memory leak from a mod you enabled. Disable mods until you figure it out and leave that mod disabled until the author fixes it. You can see in your client.log that RAM usage is increasing rapidly every minute, you'll need to figure out which mod is causing this and remove it.
