### ISSUE TITLE
Fatal shutdown with Terraria Overhaul (v5.0 Beta 11E)

### ISSUE THREAD

**Issue by KiwisOBS34** [bluemagic123/tModLoader#2838]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When I press Configuration, Terraria is shutdown
![6786869](https://user-images.githubusercontent.com/103123372/184666519-a417fc66-ddfa-4441-b84d-d79848abb7e7.PNG)

### Log File

[22:14:03.824] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:/Users/User\Documents\My Games\Terraria\tModLoader-preview\TerrariaOverhaul\Config.json" 
[22:14:04.156] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:/Users/User\Documents\My Games\Terraria\tModLoader-preview\TerrariaOverhaul\Config.json' with working directory 'D:\Steam\steamapps\common\tModLoader'. Указанному файлу не сопоставлено ни одно приложение для выполнения данной операции.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Terraria.ModLoader.Engine.LoggingHooks.<>c.<HookProcessStart>b__1_0(Func`2 orig, Process self) in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 21
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at TerrariaOverhaul.Common.MainMenuOverlays.ConfigurationMenuButton.OnClicked() in TerrariaOverhaul\Common\MainMenuOverlays\ConfigurationMenuButton.cs:line 12
   at TerrariaOverhaul.Common.MainMenuOverlays.MenuLine.Update(Vector2 position) in TerrariaOverhaul\Common\MainMenuOverlays\MenuLine.cs:line 43
   at TerrariaOverhaul.Common.MainMenuOverlays.MainMenuOverlaySystem.DrawOverlay(SpriteBatch sb) in TerrariaOverhaul\Common\MainMenuOverlays\MainMenuOverlaySystem.cs:line 85
   at DMD<Terraria.Main::DrawMenu>(Main this, GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 49044
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48619
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at System.Threading.Thread.StartCallback()

[22:14:04.157] [Main Thread/ERROR] [Terraria]: System.ComponentModel.Win32Exception (1155): An error occurred trying to start process 'C:/Users/User\Documents\My Games\Terraria\tModLoader-preview\TerrariaOverhaul\Config.json' with working directory 'D:\Steam\steamapps\common\tModLoader'. Указанному файлу не сопоставлено ни одно приложение для выполнения данной операции.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Terraria.ModLoader.Engine.LoggingHooks.<>c.<HookProcessStart>b__1_0(Func`2 orig, Process self) in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 21
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at TerrariaOverhaul.Common.MainMenuOverlays.ConfigurationMenuButton.OnClicked() in TerrariaOverhaul\Common\MainMenuOverlays\ConfigurationMenuButton.cs:line 12
   at TerrariaOverhaul.Common.MainMenuOverlays.MenuLine.Update(Vector2 position) in TerrariaOverhaul\Common\MainMenuOverlays\MenuLine.cs:line 43
   at TerrariaOverhaul.Common.MainMenuOverlays.MainMenuOverlaySystem.DrawOverlay(SpriteBatch sb) in TerrariaOverhaul\Common\MainMenuOverlays\MainMenuOverlaySystem.cs:line 85
   at DMD<Terraria.Main::DrawMenu>(Main this, GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 49044
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48630
[22:14:04.176] [Main Thread/FATAL] [tML]: Main engine crash

System.ComponentModel.Win32Exception (1155): An error occurred trying to start process 'C:/Users/User\Documents\My Games\Terraria\tModLoader-preview\TerrariaOverhaul\Config.json' with working directory 'D:\Steam\steamapps\common\tModLoader'. Указанному файлу не сопоставлено ни одно приложение для выполнения данной операции.
   at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   at Terraria.ModLoader.Engine.LoggingHooks.<>c.<HookProcessStart>b__1_0(Func`2 orig, Process self) in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 21
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at TerrariaOverhaul.Common.MainMenuOverlays.ConfigurationMenuButton.OnClicked() in TerrariaOverhaul\Common\MainMenuOverlays\ConfigurationMenuButton.cs:line 12
   at TerrariaOverhaul.Common.MainMenuOverlays.MenuLine.Update(Vector2 position) in TerrariaOverhaul\Common\MainMenuOverlays\MenuLine.cs:line 43
   at TerrariaOverhaul.Common.MainMenuOverlays.MainMenuOverlaySystem.DrawOverlay(SpriteBatch sb) in TerrariaOverhaul\Common\MainMenuOverlays\MainMenuOverlaySystem.cs:line 85
   at DMD<Terraria.Main::DrawMenu>(Main this, GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 49044
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48630
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
[22:14:04.181] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

### Steps to reproduce

1. Click to the text "Configuration Mod"
2. Shutdown

### Expected Behavior

Should be activating menu of configuration of Terraria Overhaul

### Actual Behavior

Fatal error

### Reproduction frequency

More times

**Comment by Chicken-Bones** [comment]
This is for tModLoader bugs, not Terraria Overhaul. Please find a way to report the bug to the mod author.
