### ISSUE TITLE
'Tile' does not contain a definition for 'type' and no accessible extension method 'type' accepting a first argument of type 'Tile' could be found.

### ISSUE THREAD

**Issue by QUIDD60x** [bluemagic123/tModLoader#2873]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

When using the provided code in Examplemod/ExampleOre.cs in line 79 the provided tile/Tile type and tile/Tile active do not work. Even copy pasting the code straight from the mod it will not function correctly, provided all issues of just copy pasting the code are fixed.

### Log File

[00:17:19.669] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: HEROsMod (HERO's Mod) v0.4.7.2
[00:17:19.734] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: ModdersToolkit (Modders Toolkit) v0.18.5
[00:17:19.952] [.NET ThreadPool Worker/INFO] [tML]: Sandboxing: YourTale (Your Tale) v0.4.9
[00:17:20.035] [.NET ThreadPool Worker/INFO] [tML]: Constructing Mods...
[00:17:20.368] [.NET ThreadPool Worker/INFO] [tML]: Adding Content: ModLoader (tModLoader) v2022.7.58.9
[00:17:20.461] [.NET ThreadPool Worker/INFO] [tML]: Adding Content: CheatExtensions (Cheat Extensions for Hero's/Cheat Sheet) v0.1.7.1
[00:17:20.513] [.NET ThreadPool Worker/INFO] [tML]: Adding Content: HEROsMod (HERO's Mod) v0.4.7.2
[00:17:21.452] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Player::ChatColor() added by HEROsMod
[00:17:21.521] [.NET ThreadPool Worker/INFO] [tML]: Adding Content: ModdersToolkit (Modders Toolkit) v0.18.5
[00:17:21.641] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Projectile::AI_061_FishingBobber_DoASplash() added by ModdersToolkit
[00:17:24.635] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.NPC::NewNPC(IEntitySource, int, int, int, int, float, float, float, float, int) added by ModdersToolkit
[00:17:24.641] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.Audio.SoundPlayer::Play(ref SoundStyle, Nullable`1) added by ModdersToolkit
[00:17:24.657] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.UI.UIElement::Draw(SpriteBatch) added by ModdersToolkit
[00:17:24.660] [.NET ThreadPool Worker/DEBUG] [tML]: Hook On.Terraria.UI.UIElement::Click(UIMouseEvent) added by ModdersToolkit
[00:17:24.723] [.NET ThreadPool Worker/INFO] [tML]: Adding Content: YourTale (Your Tale) v0.4.9
[00:17:24.845] [.NET ThreadPool Worker/INFO] [tML]: Resizing...
[00:17:25.163] [.NET ThreadPool Worker/INFO] [tML]: Configuring Content: ModLoader (tModLoader) v2022.7.58.9
[00:17:25.231] [.NET ThreadPool Worker/INFO] [tML]: Configuring Content: CheatExtensions (Cheat Extensions for Hero's/Cheat Sheet) v0.1.7.1
[00:17:25.301] [.NET ThreadPool Worker/INFO] [tML]: Configuring Content: HEROsMod (HERO's Mod) v0.4.7.2
[00:17:25.360] [.NET ThreadPool Worker/INFO] [tML]: Configuring Content: ModdersToolkit (Modders Toolkit) v0.18.5
[00:17:25.427] [.NET ThreadPool Worker/INFO] [tML]: Configuring Content: YourTale (Your Tale) v0.4.9
[00:17:25.607] [.NET ThreadPool Worker/INFO] [tML]: Finalizing Content: ModLoader (tModLoader) v2022.7.58.9
[00:17:25.685] [.NET ThreadPool Worker/INFO] [tML]: Finalizing Content: CheatExtensions (Cheat Extensions for Hero's/Cheat Sheet) v0.1.7.1
[00:17:25.971] [.NET ThreadPool Worker/INFO] [tML]: Finalizing Content: HEROsMod (HERO's Mod) v0.4.7.2
[00:17:26.041] [.NET ThreadPool Worker/INFO] [tML]: Finalizing Content: ModdersToolkit (Modders Toolkit) v0.18.5
[00:17:26.109] [.NET ThreadPool Worker/INFO] [tML]: Finalizing Content: YourTale (Your Tale) v0.4.9
[00:17:26.188] [.NET ThreadPool Worker/INFO] [tML]: RAM usage: 932.5 MB
[00:17:26.234] [.NET ThreadPool Worker/INFO] [tML]: Adding Recipes...
[00:17:28.352] [.NET ThreadPool Worker/INFO] [tML]: Reading properties: YourTale
[00:17:28.360] [.NET ThreadPool Worker/INFO] [tML]: Building: YourTale
[00:17:28.360] [.NET ThreadPool Worker/INFO] [tML]: Compiling YourTale.dll
[00:17:30.877] [.NET ThreadPool Worker/INFO] [tML]: Compilation finished with 2 errors and 4 warnings
[00:17:30.891] [.NET ThreadPool Worker/ERROR] [tML]: C:\Users\travi\OneDrive\Documents\My Games\Terraria\tModLoader\..\tModLoader\ModSources\YourTale\Tiles\Ores\Cryolite.cs(86,16): error CS1061: 'Tile' does not contain a definition for 'active' and no accessible extension method 'active' accepting a first argument of type 'Tile' could be found (are you missing a using directive or an assembly reference?)
[00:17:30.892] [.NET ThreadPool Worker/ERROR] [tML]: C:\Users\travi\OneDrive\Documents\My Games\Terraria\tModLoader\..\tModLoader\ModSources\YourTale\Tiles\Ores\Cryolite.cs(86,33): error CS1061: 'Tile' does not contain a definition for 'type' and no accessible extension method 'type' accepting a first argument of type 'Tile' could be found (are you missing a using directive or an assembly reference?)
[00:17:30.894] [.NET ThreadPool Worker/WARN] [tML]: C:\Users\travi\OneDrive\Documents\My Games\Terraria\tModLoader\..\tModLoader\ModSources\YourTale\ServerConfig.cs(42,22): warning CS0649: Field 'ServerConfig.ExtractSpeedMultiplier' is never assigned to, and will always have its default value 0
[00:17:30.895] [.NET ThreadPool Worker/WARN] [tML]: C:\Users\travi\OneDrive\Documents\My Games\Terraria\tModLoader\..\tModLoader\ModSources\YourTale\ServerConfig.cs(36,21): warning CS0649: Field 'ServerConfig.ToolTweaks' is never assigned to, and will always have its default value false
[00:17:30.896] [.NET ThreadPool Worker/WARN] [tML]: C:\Users\travi\OneDrive\Documents\My Games\Terraria\tModLoader\..\tModLoader\ModSources\YourTale\ServerConfig.cs(49,20): warning CS0649: Field 'ServerConfig.MolotovBlueGelCraft' is never assigned to, and will always have its default value 0
[00:17:30.897] [.NET ThreadPool Worker/WARN] [tML]: C:\Users\travi\OneDrive\Documents\My Games\Terraria\tModLoader\..\tModLoader\ModSources\YourTale\ServerConfig.cs(55,21): warning CS0649: Field 'ServerConfig.CoinRecipesAtEndofList' is never assigned to, and will always have its default value false
[00:17:31.106] [.NET ThreadPool Worker/ERROR] [tML]: Compiling YourTale.dll failed with 2 errors and 4 warnings
Error: C:\Users\travi\OneDrive\Documents\My Games\Terraria\tModLoader\..\tModLoader\ModSources\YourTale\Tiles\Ores\Cryolite.cs(86,16): error CS1061: 'Tile' does not contain a definition for 'active' and no accessible extension method 'active' accepting a first argument of type 'Tile' could be found (are you missing a using directive or an assembly reference?)
Terraria.ModLoader.Exceptions.BuildException: Compiling YourTale.dll failed with 2 errors and 4 warnings
Error: C:\Users\travi\OneDrive\Documents\My Games\Terraria\tModLoader\..\tModLoader\ModSources\YourTale\Tiles\Ores\Cryolite.cs(86,16): error CS1061: 'Tile' does not contain a definition for 'active' and no accessible extension method 'active' accepting a first argument of type 'Tile' could be found (are you missing a using directive or an assembly reference?)
   at Terraria.ModLoader.Core.ModCompile.CompileMod(BuildingMod mod, Byte[]& code, Byte[]& pdb) in tModLoader\Terraria\ModLoader\Core\ModCompile.cs:line 413
   at Terraria.ModLoader.Core.ModCompile.BuildMod(BuildingMod mod, Byte[]& code, Byte[]& pdb) in tModLoader\Terraria\ModLoader\Core\ModCompile.cs:line 347
   at Terraria.ModLoader.Core.ModCompile.Build(BuildingMod mod) in tModLoader\Terraria\ModLoader\Core\ModCompile.cs:line 211
   at Terraria.ModLoader.Core.ModCompile.Build(String modFolder) in tModLoader\Terraria\ModLoader\Core\ModCompile.cs:line 185
   at Terraria.ModLoader.UI.UIBuildMod.<>c__DisplayClass5_0.<Build>b__0(ModCompile mc) in tModLoader\Terraria\ModLoader\UI\UIBuildMod.cs:line 31
   at Terraria.ModLoader.UI.UIBuildMod.BuildMod(Action`1 buildAction, Boolean reload) in tModLoader\Terraria\ModLoader\UI\UIBuildMod.cs:line 67
[00:17:32.085] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs"

### Steps to reproduce

1. write/copy the code from ExampleOre.cs 
2. unmark line 78 - 82
3. error unfolds. and the mod can no longer compile.

### Expected Behavior

The tile.active and tile.type should be readable and equate to the proper TileID, but for some reason they aren't in the Tile extension method.

### Reproduction frequency

every time.

**Comment by JavidPack** [comment]
I've updated the code for you. https://github.com/tModLoader/tModLoader/commit/49e9130a89b32989ed37785689bc71ab62490c29
