### ISSUE TITLE
Mysterious "No process is on the other end of the pipe" error

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#2925]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

For some reason, it seems like Console.Write is failing for some users. This error seems to have various effects, this particular user couldn't generate a world without crashing.

```
System.IO.IOException: No process is on the other end of the pipe.
   at System.ConsolePal.WindowsConsoleStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Write(String value)
   at System.IO.TextWriter.SyncTextWriter.Write(String value)
   at System.Console.Write(String value)
   at log4net.Appender.ConsoleAppender.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)
```

[client (6).log](https://github.com/tModLoader/tModLoader/files/9563491/client.6.log)

In this issue, we'll need to collect more information on similar issues as they come up in the discord. This user had an RGB keyboard that might be related, time will tell.

**Comment by Chicken-Bones** [comment]
You can see from the logs that `log4net` normally catches this and swallows it, but it looks like we have a few direct calls to `Console.WriteLine` on the client, which are failing more heavily.

We need to find the root cause for this, why does it happen to some users and not others.

**Comment by Chicken-Bones** [comment]
https://github.com/dotnet/runtime/pull/75734
