### ISSUE TITLE
Various ModConfig bugs

### ISSUE THREAD

**Issue by Spiky-73** [bluemagic123/tModLoader#2942]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

I've discovered many bugs with CustomModItemElement and arrays in the config while make my own UI.

 - ~~Properties always appear after fields~~ - [C#/.Net limitation](https://github.com/tModLoader/tModLoader/issues/2942#issuecomment-1250260399)

Bugs with genric arguments
ConfigElements in collection trying to get generic args will not get the ones of their "own" list, but the ones of the 1st list.
(e.g. with a field `List<Dictionary<int, bool>>`, the generic argument gotten by the dictionary will be `Dictionary<int, bool>` and not `[int, bool]`)
 - `object[]` crash as it tries to get a non existant generic arg
 - Collection of Dictionnary crashes as it tries to get the generic arg of root the collection

Bugs with UIModConfig.WrapIt
It uses `Membreinfo.Type` and not `MemberInfo.GetValue(item).GetType()`, an so does not get the correct attributes of ConfigElement
 - Reflexion crash when drawing an field of type `object` (e.g. `public object obj = new MyClass()`)
 - Custom UI is not used in arrays, collections (e.g. `List<ClassWithCustomUI>`) 
 - Causses a crash when using a custom UI to draw any array (in class or as attribute)

Visual bug
 - classes or collections with 1 item have a padding error at the bottom

### Log File

see `steps to reproduce`

### Steps to reproduce

Add any of the field with the same structure as the one in the config class bellow

```csharp
using System;
using System.Collections;
using System.Collections.Generic;
using Terraria.ModLoader.Config;
using Terraria.ModLoader.Config.UI;

namespace BugShowcase;


public class BugExamples : ModConfig {

    public class PropVsField {
        public int a;
        public string C { get; set; }
        public bool B { get; set; }
        public byte d;
    }

    public PropVsField elementOrder = new();
    // The ordre of the fields are preserved, same for properties but fields are always before all properties 

    public class DummyClass {
        public int a;
        public string s;
    }
    public DummyClass[] objectArray = new DummyClass[5];
    // System.IndexOutOfRangeException: Index was outside the bounds of the array.
    //  at Terraria.ModLoader.Config.UI.ObjectElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\ObjectElement.cs:line 38
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.ArrayElement.SetupList() in tModLoader\Terraria\ModLoader\Config\UI\ArrayElement.cs:line 38
    //  at Terraria.ModLoader.Config.UI.CollectionElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 72
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.UIModConfig.OnActivate() in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 489
    //  ...

    public Dictionary<int, bool>[] dictionaryArray = new Dictionary<int, bool>[1];
    // System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.Int32,System.Boolean][]' to type 'System.Collections.IDictionary'.
    //  at Terraria.ModLoader.Config.UI.DictionaryElement.SetupList() in tModLoader\Terraria\ModLoader\Config\UI\DictionaryElement.cs:line 166
    //  at Terraria.ModLoader.Config.UI.CollectionElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 72
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.ArrayElement.SetupList() in tModLoader\Terraria\ModLoader\Config\UI\ArrayElement.cs:line 38
    //  at Terraria.ModLoader.Config.UI.CollectionElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 72
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.UIModConfig.OnActivate() in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 489
    //  ...

    public List<Dictionary<DummyClass, bool>> dictionaryList = new(){ new() };
    // System.IndexOutOfRangeException: Index was outside the bounds of the array.
    //  at Terraria.ModLoader.Config.UI.DictionaryElement.PrepareTypes() in tModLoader\Terraria\ModLoader\Config\UI\DictionaryElement.cs:line 95
    //  at Terraria.ModLoader.Config.UI.CollectionElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 70
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.ListElement.SetupList() in tModLoader\Terraria\ModLoader\Config\UI\ListElement.cs:line 40
    //  at Terraria.ModLoader.Config.UI.CollectionElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 72
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.UIModConfig.OnActivate() in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 489
    //  ...

    public object dummyObject = new DummyClass();
    // System.Reflection.TargetParameterCountException: Parameter count mismatch.
    //  at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    //  at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
    //  at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
    //  at Terraria.ModLoader.Config.UI.ConfigElement.GetObject() in tModLoader\Terraria\ModLoader\Config\UI\ConfigElement.cs:line 115
    //  at Terraria.ModLoader.Config.UI.ConfigElement`1.get_Value() in tModLoader\Terraria\ModLoader\Config\UI\ConfigElement.cs:line 16
    //  at Terraria.ModLoader.Config.UI.ObjectElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\ObjectElement.cs:line 66
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.ObjectElement.SetupList() in tModLoader\Terraria\ModLoader\Config\UI\ObjectElement.cs:line 252
    //  at Terraria.ModLoader.Config.UI.ObjectElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\ObjectElement.cs:line 176
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.UIModConfig.OnActivate() in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 489
    //  ...

    public class EmptyElement : ConfigElement { } // Does nothing, meaning the item should display an empty field

    [CustomModConfigItem(typeof(EmptyElement))]
    public class EmptyClass { // No field should be visible in the config
        public int i;
        public string s;
    }

    public EmptyClass emptyClass = new();
    public List<EmptyClass> emmtyClassArray = new() {
        new() // All the fiels of the element displays
    };

    public class ListValuesElement : ConfigElement { // Draws an list like a class
        public override void OnBind() {
            base.OnBind();
            IList list = MemberInfo.GetValue(Item) as IList;
            int top = 5;
            int i = 0;
            // Tries to wrap all the element ot the list normaly
            foreach (object value in list) ConfigManager.WrapIt(this, ref top, MemberInfo, list, 0, list, list.GetType().GetGenericArguments()[0], i++);
        }
    }

    // Would also work with a class implementing IList and having the same attribute
    [CustomModConfigItem(typeof(ListValuesElement))]
    public List<int> ListWithCustomUI = new(){ 1,2,3,4,5 };
    // System.ArgumentException: Field 'ListWithCustomUI' defined on type 'BugShowcase.BugExamples' is not a field on the target object which is of type 'System.Collections.Generic.List`1[System.Int32]'.
    //  at System.Reflection.RtFieldInfo.GetValue(Object obj)
    //  at BugShowcase.BugExamples.ListValuesElement.OnBind() in SPIC\Configs\BugShowCase.cs:line 72
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.ConfigManager.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\ConfigManager.cs:line 307
    //  at BugShowcase.BugExamples.ListValuesElement.OnBind() in SPIC\Configs\BugShowCase.cs:line 77
    //  at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 611
    //  at Terraria.ModLoader.Config.UI.UIModConfig.OnActivate() in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 489
    //  ...

    // There is no margin between the bottom of the list and the bottom of the class
    // Only happens when there is 1 element in the collection
    public List<DummyClass> paddingError = new();


    public override ConfigScope Mode => ConfigScope.ClientSide;
}
```

### Expected Behavior

No exception shoud occur, everything shoud dislay normaly.

### Actual Behavior

Exceptions and visual bugs

### Reproduction frequency

Always

**Comment by ExterminatorX99** [comment]
> Properties always appear after fields

This is a C#/.NET limitation. You can only get field and properties of a class separately and then the choice we have is which we want sorted first. The workaround is to only use one, either properties or fields, and be consistent
