### ISSUE TITLE
CoreCLR version 0.0 is not supported error

### ISSUE THREAD

**Issue by Isaaccool12** [bluemagic123/tModLoader#2996]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Hello, I ran into a problem when running tmodloader after the last update
![image](https://user-images.githubusercontent.com/114794938/193393962-03d998aa-bc64-4bb5-9238-4bfa54b69ae6.png)
![image](https://user-images.githubusercontent.com/114794938/193394020-5fcc4243-adc3-418b-bb6f-a7d872a5a9b0.png)

### Log File

[environment.log](https://github.com/tModLoader/tModLoader/files/9689609/environment.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/9689610/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/9689611/Natives.log)

### Steps to reproduce

1. loading last update tmodloader
2. launch tmodloader from steam

### Expected Behavior

start terraria

### Actual Behavior

terraria does not start

### Reproduction frequency

At any moment

**Comment by Isaaccool12** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/9689625/client.log)

**Comment by JavidPack** [comment]
We will look into this, but in the meantime I suggest that if you are on `1.4-preview` that you switch back to the default tModLoader branch. 

To switch to normal `stable` tModLoader, close the game, right click on tModLoader in Steam, click properties, then betas, then select `None` in the dropdown. Steam will now download the files. 

This [video](https://gfycat.com/idolizedfarhapuka) shows these instructions.

**Comment by JavidPack** [comment]
If anyone would like to help us debug this, we are looking into this issue on this thread on the discord. We have instructions that will generate useful logs for us to look through.: https://discord.com/channels/103110554649894912/1025635991362469928/1025694798830633000

**Comment by Salovar** [comment]
Yesterday 30.09.2022 I lost in terraria , I ran it through the tmoloader for several hours and everything was fine . Today, on 01.10.2022 , I decided to play and the game started to run through a modloader installed via steam , like the terraria game itself , they were all updated with the latest updates and the game gave the error tModLoader
[12:21:35.784] [Main Thread/INFO] [tML]: Save Are Located At: C:\Users\drako\Documents\My Games\Terraria\tModLoader-preview
[12:21:35.791] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.10.0.0|1.4-preview|Preview|a10475f1423c92cd556627e3a84ff8fbc3cc1b0b|5249687838568838226 built 01.10.2022 7:46
[12:21:35.792] [Main Thread/INFO] [tML]: Log date: 01.10.2022
[12:21:35.792] [Main Thread/INFO] [tML]: Running on Windows (v10.0.22000.0) X64 NetCore 6.0.0
[12:21:35.792] [Main Thread/INFO] [tML]: Executable: W:\SteamLibrary\steamapps\common\tModLoader\tModLoader.dll
[12:21:35.792] [Main Thread/INFO] [tML]: Working Directory: W:\SteamLibrary\steamapps\common\tModLoader
[12:21:35.928] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.ArgumentException: Version string portion was too short or too long. (Parameter 'input')
at System.Version.ParseVersion(ReadOnlySpan`1 input, Boolean throwOnFailure)
at System.Version.Parse(String input)
at System.Version..ctor(String version)
at MonoMod.Core.Utils.PlatformDetection.DetermineRuntimeInfo() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/PlatformDetection.cs:line 355
at MonoMod.Core.Utils.PlatformDetection.EnsureRuntimeInitialized() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/PlatformDetection.cs:line 261
at MonoMod.Core.Utils.PlatformDetection.get_Runtime() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/PlatformDetection.cs:line 271
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentRuntime(ISystem system) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 16
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 54
at MonoMod.Core.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/Helpers.cs:line 145
at MonoMod.Core.Platforms.PlatformTriple.get_Current() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 50
at MonoMod.Core.DetourFactory.CreateDefaultFactory() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/IDetourFactory.cs:line 32
at MonoMod.Core.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/Helpers.cs:line 136
at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/DetourContext.cs:line 43
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 139
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 130
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 112
at Terraria.ModLoader.Engine.LoggingHooks.FixBrokenConsolePipeError() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 32
at Terraria.ModLoader.Engine.LoggingHooks.Init() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 14
at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in tModLoader\Terraria\ModLoader\Logging.cs:line 86
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 185
at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
at System.Threading.Thread.StartCallback()

[12:21:36.035] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.PlatformNotSupportedException: CoreCLR version 0.0 is not supported
at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.CreateForVersion(Version version, ISystem system) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/Runtimes/CoreBaseRuntime.cs:line 46
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentRuntime(ISystem system) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 18
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 54
at MonoMod.Core.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/Helpers.cs:line 145
at MonoMod.Core.Platforms.PlatformTriple.get_Current() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 50
at MonoMod.Core.DetourFactory.CreateDefaultFactory() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/IDetourFactory.cs:line 32
at MonoMod.Core.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/Helpers.cs:line 136
at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/DetourContext.cs:line 43
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 139
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 130
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 112
at Terraria.ModLoader.Engine.LoggingHooks.FixBrokenConsolePipeError() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 32
at Terraria.ModLoader.Engine.LoggingHooks.Init() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 14
at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in tModLoader\Terraria\ModLoader\Logging.cs:line 86
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 185
at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
at System.Threading.Thread.StartCallback()

[12:21:36.040] [Main Thread/FATAL] [tML]: Failed to handle save data

System.PlatformNotSupportedException: CoreCLR version 0.0 is not supported
at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.CreateForVersion(Version version, ISystem system) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/Runtimes/CoreBaseRuntime.cs:line 46
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentRuntime(ISystem system) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 18
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 54
at MonoMod.Core.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/Helpers.cs:line 145
at MonoMod.Core.Platforms.PlatformTriple.get_Current() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 50
at MonoMod.Core.DetourFactory.CreateDefaultFactory() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/IDetourFactory.cs:line 32
at MonoMod.Core.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.Core/Utils/Helpers.cs:line 136
at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/DetourContext.cs:line 43
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 139
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 130
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in Z:/Users/aaron/Source/Repos/MonoModReorg/MonoMod/src/MonoMod.RuntimeDetour.New/Hook.cs:line 112
at Terraria.ModLoader.Engine.LoggingHooks.FixBrokenConsolePipeError() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 32
at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 14
at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 86
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 185
In the afternoon there was an update of the tmode, an unsuccessful update is possible, after it the game stopped starting from the latest version of the tmodloader and giving this error.

**Comment by Solxanich** [comment]
All, this has been confirmed as a design flaw with a new monomod version that we have to use. 

This monomod version currently does not support Mac, but will add support before the next stable release. 

Please use the stable build/ no beta option of tmodloader in the interim. 

As an aside, Preview will soon contain a significant number of breaking changes. 
We recommend against being on it this month

**Comment by Kratchet6** [comment]
Any new about the bug?

**Comment by Chicken-Bones** [comment]
Waiting for build of https://github.com/MonoMod/MonoMod/pull/108
