### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by TeddyBrosevlt** [bluemagic123/tModLoader#3007]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Hello, I'm trying to boot tModLoader and I keep getting the same error and can't find a solution, please help

### Log File

[21:13:24] [1/INFO] [tML]: Starting tModLoader v0.11.8.4 Windows client (10/2/2022)
[21:13:24] [1/INFO] [tML]: Running on NetFramework 4.8
[21:13:24] [1/INFO] [tML]: Executable: F:\Steam\steamapps\common\Terraria\Terraria.exe
[21:13:24] [1/INFO] [tML]: Working Directory: F:\Steam\steamapps\common\Terraria
[21:13:24] [1/INFO] [tML]: Launch Parameters: 
[21:13:24] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[21:13:24] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[21:13:24] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:13:24] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[21:13:24] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[21:13:25] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[21:13:25] [1/INFO] [tML]: Checking Steam installation...
[21:13:25] [1/WARN] [tML]: Silently Caught Exception: 
System.DllNotFoundException: Unable to load DLL 'CSteamworks': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize() in tModLoader\Terraria.Social.Steam\CoreSocialModule.cs:line 26
   at Terraria.Social.SocialAPI.LoadSteam() in tModLoader\Terraria.Social\SocialAPI.cs:line 76
   at Terraria.ModLoader.Engine.InstallVerifier.CheckSteam() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 99
   at Terraria.ModLoader.Engine.InstallVerifier.InstallCheck() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 90
   at Terraria.ModLoader.Engine.InstallVerifier.get_IsValid() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 19
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode) in tModLoader\Terraria.Social\SocialAPI.cs:line 28
   at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 246
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 228
   at Terraria.WindowsLaunch.Main(String[] args) in tModLoader\Terraria\WindowsLaunch.cs:line 74

[21:13:25] [1/FATAL] [Terraria]: Main engine crash
System.DllNotFoundException: Unable to load DLL 'CSteamworks': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Steamworks.NativeMethods.SteamAPI_RestartAppIfNecessary(AppId_t unOwnAppID)
   at Terraria.Social.Steam.CoreSocialModule.Initialize() in tModLoader\Terraria.Social.Steam\CoreSocialModule.cs:line 26
   at Terraria.Social.SocialAPI.LoadSteam() in tModLoader\Terraria.Social\SocialAPI.cs:line 76
   at Terraria.ModLoader.Engine.InstallVerifier.CheckSteam() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 99
   at Terraria.ModLoader.Engine.InstallVerifier.InstallCheck() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 88
   at Terraria.ModLoader.Engine.InstallVerifier.get_IsValid() in tModLoader\Terraria.ModLoader.Engine\InstallVerifier.cs:line 19
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode) in tModLoader\Terraria.Social\SocialAPI.cs:line 28
   at Terraria.Program.LaunchGame_() in tModLoader\Terraria\Program.cs:line 245
[21:13:33] [1/DEBUG] [tML]: Process.Start (UseShellExecute = True): "https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#systemdllnotfoundexception-unable-to-load-dllcsteamworks"

**Comment by JavidPack** [comment]
You posted a 1.3 log, but you said you are on 1.4 stable, which is it? You also are in F:\Steam\steamapps\common\Terraria, that is not the correct tmodloader install location.

Please install tModLoader from steam and launch it from there, do not attempt to install into the Terraria directory, that is not supported.

**Comment by TeddyBrosevlt** [comment]
So I tried a fresh install of Tmod and Terraria and I got an error on launch which is why I tried a manual install and i guess it got more scuffed. so I did a fresh install AGAIN and got the same error as before
[14:43:49.469] [Main Thread/FATAL] [tML]: Failed to handle save data

System.TypeLoadException: Could not load type 'ReLogic.OS.IPathService' from assembly 'ReLogic, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'.
   at Terraria.Program.SetSavePath()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 184

**Comment by JavidPack** [comment]
full logs please, or just come to discord for live help

**Comment by TeddyBrosevlt** [comment]
That is literally the full log tMod gives me per the file path but I'll get on the discord to get this sorted faster

**Comment by TeddyBrosevlt** [comment]
Nevermind I just did a fresh install again and the error didn't show up this time
