### ISSUE TITLE
MonoMod issue with detouring Main.Update

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3015]
### Version

Latest 1.4-preview

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

```cs
public class TestMod : Mod
{
	public override void Load()
	{
		On.Terraria.Main.Update += Main_Update;
	}

	private void Main_Update(On.Terraria.Main.orig_Update orig, Main self, GameTime gameTime)
	{
		orig(self, gameTime);
	}
}
```

This code currently works on stable. On preview however, if you launch it via Visual Studio (or your preferred IDE), shortly after the detour registers (visible in the log) random errors crop up, such as assets not being found/loaded.

![Screenshot_3](https://user-images.githubusercontent.com/15894498/193815312-15b712c6-21ab-4053-b5a7-ef4264e9e904.png)

This does NOT seem to happen when launching the game directly through steam, and then building the mod ingame. The dotnet versions are matching in both variants

### Log File

Relevant snippets:

[14:07:34.140] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.10.9.0|1.4-preview|Preview|e4efa262e33189856fc894a855739adf6ec146d3|5249689456985263874 built 02.10.2022 23:44

[14:07:34.159] [Main Thread/INFO] [tML]: Running on Windows (v6.1.7601.0) X64 NetCore 6.0.9
[14:07:34.170] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.9

[14:07:46.469] [.NET ThreadPool Worker/DEBUG] [tML]: Hook Terraria.Main::Update(GameTime) added by TestMod
[14:07:46.509] [.NET ThreadPool Worker/INFO] [tML]: Resizing...
[14:07:46.680] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.ArgumentNullException: Value cannot be null.
   at System.Threading.Monitor.ReliableEnter(Object obj, Boolean& lockTaken)
   at Microsoft.Xna.Framework.Game.Update(GameTime gameTime) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 688
   at DMD<Terraria.Main::Update>(Main this, GameTime gameTime)
   at TestMod.TestMod.Main_Update(orig_Update orig, Main self, GameTime gameTime) in TestMod.cs:line 20
   at SyncProxy<System.Void Terraria.Main::Update(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Collections.Generic.Dictionary`2.ContainsKey(TKey key)
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Dynamic.Utils.ExpressionVisitorUtils.VisitArguments(ExpressionVisitor visitor, IArgumentProvider nodes)
   at System.Linq.Expressions.ExpressionVisitor.VisitMethodCall(MethodCallExpression node)
   at System.Linq.Expressions.MethodCallExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitUnary(UnaryExpression node)
   at System.Linq.Expressions.UnaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at Terraria.ModLoader.TileLoader.ResizeArrays(Boolean unloading) in tModLoader\Terraria\ModLoader\TileLoader.cs:line 199
   at Terraria.ModLoader.ModContent.ResizeArrays(Boolean unloading) in tModLoader\Terraria\ModLoader\ModContent.cs:line 533
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 323
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 125
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

### Steps to reproduce

See code posted above, use it on a template mod

### Reproduction frequency

100% if launched in Visual Studio

### Additional Information

I tried using `Main.QueueMainThreadAction` for the detour application, same issue happens. Originally I noticed this issue because in a mod of mine I initialize a RenderTarget2D when the resolution changes. This worked properly up until now where it now says that FNA3D operations should happen on the main thread. Wrapping said code on the main thread then causes random chain reactions of errors, after the mod load hangs for a few seconds on the detour step

I've also tried detouring `Microsoft.Xna.Framework.Game::Update` manually, and while it registered, the method I appended was never called.

**Comment by direwolf420** [comment]
Update: still happens on https://github.com/tModLoader/tModLoader/commit/10ed42347f59ffc926959e5fda8abd1acbe621a9

**Comment by direwolf420** [comment]
Doesn't happen on ([1e61b8f](https://github.com/tModLoader/tModLoader/commit/1e61b8f177503cfc7d341ce8d0cf3fb3002f5ec3)), checked by me and another person

**Comment by direwolf420** [comment]
Closing as it seems to be fixed by the above commit
