### ISSUE TITLE
.Net leaving error everytime I launch the game.

### ISSUE THREAD

**Issue by kingsleych** [bluemagic123/tModLoader#3019]
### Version

Latest 1.4-preview

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Breaks when I try to start up the game. (I use a intel based macbook pro)

### Log File

Failed to handle save data

System.NotImplementedException: The method or operation is not implemented.
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem()
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent()
at MonoMod.Core.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj)
at MonoMod.Core.Platforms.PlatformTriple.get_Current()
at MonoMod.Core.DetourFactory.CreateDefaultFactory()
at MonoMod.Core.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj)
at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory()
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault)
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config)
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target)
at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 63
at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 15
at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 88
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 185

**Comment by kingsleych** [comment]
after switching to 1.4.3 it worked fine
