### ISSUE TITLE
[1.4.4/Dev Build] [Bug] You can't maximize the window + Deleting world or player causes game to crash/close

### ISSUE THREAD

**Issue by Setnour6** [bluemagic123/tModLoader#3082]
### Version

Other (Latest 1.4.4-dev)

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description 1: You can't maximize the window

- [x] Handled.

Clicking on the "restore" tab or what you might call it when you want the game to cover the whole front window/screen of the computer.
![image](https://user-images.githubusercontent.com/70764728/200093779-5b711b82-42df-4c0a-b215-d8809ed7148b.png)
When I click on that button (the top middle button in the screenshot beside the minimize and close button), it only works for 1-2 ticks and the screen flashes dark and then nothing actually happens as it expects to be.
![image](https://user-images.githubusercontent.com/70764728/200093890-201a054a-35f7-4d0a-b98b-a28b8274a85f.png)

### Description 2: Deleting world or player causes game to crash/close
- [x] Handled.

Clicking on the delete button for the world and going through the process by clicking "yes" freezes the game and ultimately forces the game to close.
**Temporary solution:** Delete the world/character within the file directory instead of in the game.

### Log File (both problems)

2022-11-04 8:59 PM log [TO USE]: [client.log](https://github.com/tModLoader/tModLoader/files/9942630/client.log)
Old/Other logs:
2022-11-04 8:35 PM log: [environment.log](https://github.com/tModLoader/tModLoader/files/9942631/environment.log)
2022-11-04 8:35 PM log: [client.log](https://github.com/tModLoader/tModLoader/files/9942629/client.log)

### Steps to reproduce (both problems)

At the time of testing, I enabled one of my mods from the 1.4-stable build and it loaded.

**WINDOW PROBLEM:**
1. Open tModLoader on the dev build
2. Click on the button that maximizes/changes the window
3. It didn't actually maximize, as the middle button (top right corner beside the close and minimize button) shows it as one window icon, not as a conjoined window icon (which indicates the window is maximized)

**DELETING WORLD PROBLEM:**
1. Open tModLoader on the dev build
2. Create a character and world
3. Enter the world
4. Exit the world
5. Go to the world selection
6. Try to delete the world
7. After clicking "yes" on the confirmation, the game freezes and crashes shortly after.

### Expected Behavior (both problems)

The game window should maximize completely as expected like the 1.4-stable version. The world should be deleted and the player is brought to the character selection screen

### Actual Behavior (both problems)

The game window isn't maximized, as the window icon button would show whether it is maximized or not, and should be in this circumstance. The world is not deleted after reopening the game.

### Reproduction frequency (both problems)

100% of the time for the window problem
100% of the time for the world deletion problem

### Additional Information

I am very sure that this problem will be resolved, but I made this bug report just in case. I might update this bug report to seperate the problem descriptions, or add more problems that I found regarding the 1.4.4 developer branch testing.

**Comment by Rijam** [comment]
I can confirm that both issues happen for me too.

For the deleting issue, I get a `System.AccessViolationException` in Natives.log
```
Fatal error. System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
Repeat 2 times:
--------------------------------
   at ReLogic.OS.Windows.NativeMethods.SHFileOperation(SHFILEOPSTRUCT ByRef)
--------------------------------
   at ReLogic.OS.Windows.NativeMethods.Send(System.String, FileOperationFlags)
   at ReLogic.OS.Windows.NativeMethods.MoveToRecycleBin(System.String)
   at ReLogic.OS.Windows.PathService.MoveToRecycleBin(System.String)
   at Terraria.Utilities.FileUtilities.Delete(System.String, Boolean, Boolean)
   at Terraria.Main.ErasePlayer(Int32)
   at Terraria.Main.DrawMenu(Microsoft.Xna.Framework.GameTime)
   at Terraria.Main.DoDraw(Microsoft.Xna.Framework.GameTime)
   at Terraria.Main.Draw(Microsoft.Xna.Framework.GameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean)
   at Terraria.Program.LaunchGame(System.String[], Boolean)
   at MonoLaunch+<>c__DisplayClass1_0.<Main>b__0()
   at System.Threading.Thread.StartCallback()
```

**Comment by Chicken-Bones** [comment]
Please confirm if the deletion crash happens in vanilla Terraria

**Comment by Rijam** [comment]
> Please confirm if the deletion crash happens in vanilla Terraria

Vanilla works as intended for me. For both deleting players and for maximizing the window.

**Comment by Mirsario** [comment]
I'm not too happy my last referenced commit, but both issues are equally gone. Reopen if needed.
