### ISSUE TITLE
Current MonoMod Reorg doesn't work on MacOS

### ISSUE THREAD

**Issue by rgcjhn** [bluemagic123/tModLoader#3093]
### Version

Latest 1.4-preview

### OS

Mac

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When I launch the game with mac OS it shows me this error:

### Log File

```
Failed to handle save data

System.NotImplementedException: The method or operation is not implemented.
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 37
at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 53
at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Utils\Helpers.cs:line 167
at MonoMod.Core.Platforms.PlatformTriple.get_Current() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 50
at MonoMod.Core.DetourFactory.CreateDefaultFactory() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\IDetourFactory.cs:line 32
at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Utils\Helpers.cs:line 158
at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour.New\DetourContext.cs:line 43
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour.New\Hook.cs:line 138
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour.New\Hook.cs:line 129
at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour.New\Hook.cs:line 111
at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 63
at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 15
at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 88
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 185

A client.log file containing error information has been generated in
```

### Steps to reproduce

1. Download base terraria game
2. Download tmodloader with version 1.4

### Expected Behavior

Should launch the game normally

### Actual Behavior

Game wont launch

**Comment by direwolf420** [comment]
Current version of MonoMod used on 1.4-preview does not work on mac. Switch to the "None" beta in steam properties for tModLoader.

**Comment by haohanyuzmx** [comment]
i switch to "None" beta in steam properties, but it also can't run
```
tModLoader v2022.9.47.15 Fatal Error
Failed to handle save data

System.ComponentModel.Win32Exception (13): Permission denied
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.DetourHelper.MakeWritable(IDetourNativePlatform plat, NativeDetourData detour)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase method, Delegate to)
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 61
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 14
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 87
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 185
```

**Comment by Kying-star** [comment]
you say right,but I can run it in m1 mac with monterey 12.0.1.
```
(base) ➜  tModLoader bash start-tModLoader.sh
start-tModLoader.sh: line 6: PPID: readonly variable
You are on platform: "Darwin"
Verifying .NET....
This may take a few moments.
(base) ➜  tModLoader Logging to /Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
/Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/Libraries/Steamworks.NET -> /Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/Libraries/steamworks.net
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/dotnet/6.0.0"
cat: /Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/cli-argsConfig.txt: No such file or directory
Loaded Custom Arguments:
Attempting Launch...
sed: /proc/1/cmdline: No such file or directory
Launched Using Local Dotnet
[13:32:18.455] [Main Thread/INFO] [tML]: Save Are Located At: /Users/linqixing/Library/Application Support/Terraria/tModLoader
[13:32:18.488] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.09.47.15|1.4-stable|Stable|5192bce81f9762d62c6b154ea3c1514ab73f3d78|5249732551006666390 built 2022/11/22 上午2:47
[13:32:18.491] [Main Thread/INFO] [tML]: Log date: 2022/11/27
[13:32:18.492] [Main Thread/INFO] [tML]: Running on OSX (v12.0.1) X64 NetCore 6.0.0
[13:32:18.493] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[13:32:18.494] [Main Thread/INFO] [tML]: Executable: /Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/tModLoader.dll
[13:32:18.494] [Main Thread/INFO] [tML]: Working Directory: /Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader
[13:32:18.602] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.GetJitObject()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase method, Delegate to)
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 61
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 15
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in tModLoader\Terraria\ModLoader\Logging.cs:line 88
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 185
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

[13:32:19.082] [Main Thread/DEBUG] [FNA]: Querying linked library versions...
[13:32:19.089] [Main Thread/DEBUG] [FNA]: SDL v2.24.0
[13:32:19.091] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.9.1.0, Culture=neutral, PublicKeyToken=null -> FNA3D
[13:32:19.092] [Main Thread/DEBUG] [tML]: 	attempting to load '/Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/Libraries/Native/OSX/libFNA3D.0.dylib'...
[13:32:19.093] [Main Thread/DEBUG] [tML]: 	success
[13:32:19.094] [Main Thread/DEBUG] [FNA]: FNA3D v22.8.0
[13:32:19.095] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.9.1.0, Culture=neutral, PublicKeyToken=null -> FAudio
[13:32:19.095] [Main Thread/DEBUG] [tML]: 	attempting to load '/Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/Libraries/Native/OSX/libFAudio.0.dylib'...
[13:32:19.096] [Main Thread/DEBUG] [tML]: 	success
[13:32:19.096] [Main Thread/DEBUG] [FNA]: FAudio v22.8.0
[13:32:19.296] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[13:32:19.305] [Main Thread/DEBUG] [TerrariaSteamClient]: Disabled. Launched outside steam client.
[13:32:19.313] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[13:32:19.892] [Main Thread/DEBUG] [tML]: Native Resolve: Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null -> steam_api
[13:32:19.895] [Main Thread/DEBUG] [tML]: 	attempting to load '/Users/linqixing/Library/Application Support/Steam/steamapps/common/tModLoader/Libraries/Native/OSX/libsteam_api64.dylib'...
[13:32:19.896] [Main Thread/DEBUG] [tML]: 	success
[13:32:20.024] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 152.6 MB available
[13:32:20.056] [Main Thread/WARN] [FNA]: Non-standard D32S8 window depth format!
[13:32:20.058] [Main Thread/INFO] [FNA]: FNA3D Driver: OpenGL
[13:32:20.059] [Main Thread/INFO] [FNA]: OpenGL Renderer: Apple M1
[13:32:20.059] [Main Thread/INFO] [FNA]: OpenGL Driver: 2.1 Metal - 76.1
[13:32:20.059] [Main Thread/INFO] [FNA]: OpenGL Vendor: Apple
[13:32:20.059] [Main Thread/INFO] [FNA]: MojoShader Profile: glsl120
[13:32:20.076] [Main Thread/INFO] [tML]: Terraria Steam Install Location assumed to be: /Users/linqixing/Library/Application Support/Steam/steamapps/common/Terraria/Terraria.app/Contents/Resources
[13:32:20.593] [Main Thread/INFO] [tML]: Maximum Resolution is 2560 x 1600
[13:32:20.609] [Main Thread/DEBUG] [Terraria]: Device Created, Adapter: 0, DisplayMode: {{Width:1440 Height:900 Format:Color}}, Profile: HiDef, Width: 1280, Height: 800, Fullscreen: False, Display: \\.\DISPLAY1
Resolution changed to: 1280x800.
[13:32:21.530] [Main Thread/DEBUG] [tML]: Native Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> RzChromaSDK64.dll
```

**Comment by Chicken-Bones** [comment]
Fixed in d728de6b694815fa0072f28c452a3dc61d1e2c9b

**Comment by tmuaprep** [comment]
i'm still getting the error?

**Comment by JavidPack** [comment]
Can you post your log files for 1.4.4-preview. This is fixed in 1.4.4, not 1.4

**Comment by direwolf420** [comment]
(1.4 does not have the Reorg one)

**Comment by tmuaprep** [comment]
Hey, I'm using GOG so I'm using the latest release - i hope that's fine ?
this is the client.log file generated

```
[20:42:26.836] [Main Thread/INFO] [tML]: Save Are Located At: /Users/arham/Library/Application Support/Terraria/tModLoader
[20:42:26.865] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.09.47.39|stable|Stable|de5531345dc2461239bb5c42cff6ab4654ba9c26|5249832940587195328 built 17/03/2023 23:23
[20:42:26.869] [Main Thread/INFO] [tML]: Log date: 14/05/2023
[20:42:26.869] [Main Thread/INFO] [tML]: Running on OSX (v12.5.0) Arm64 NetCore 6.0.0
[20:42:26.870] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[20:42:26.870] [Main Thread/INFO] [tML]: Executable: /Users/arham/Library/Application Support/tModLoader/tModLoader.dll
[20:42:26.870] [Main Thread/INFO] [tML]: Working Directory: /Users/arham/Library/Application Support/tModLoader
[20:42:26.982] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.PlatformNotSupportedException: Operation is not supported on this platform.
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.GetJitObject()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase method, Delegate to)
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 61
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 15
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in tModLoader\Terraria\ModLoader\Logging.cs:line 88
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 185
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

[20:42:27.108] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.ComponentModel.Win32Exception: Permission denied
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.DetourHelper.MakeWritable(IDetourNativePlatform plat, NativeDetourData detour)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase method, Delegate to)
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 61
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 15
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in tModLoader\Terraria\ModLoader\Logging.cs:line 88
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 185
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

[20:42:27.109] [Main Thread/FATAL] [tML]: Failed to handle save data

System.ComponentModel.Win32Exception (13): Permission denied
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.SetMemPerms(IntPtr start, UInt64 len, MmapProts prot)
   at MonoMod.RuntimeDetour.Platforms.DetourNativeLibcPlatform.MakeWritable(IntPtr src, UInt32 size)
   at MonoMod.RuntimeDetour.DetourHelper.MakeWritable(IDetourNativePlatform plat, NativeDetourData detour)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform._HookSelftest(MethodInfo from, MethodInfo to)
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeILPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETPlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform..ctor()
   at MonoMod.RuntimeDetour.Platforms.DetourRuntimeNETCorePlatform.Create()
   at MonoMod.RuntimeDetour.DetourHelper.get_Runtime()
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig& config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target, HookConfig config)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase from, MethodInfo to, Object target)
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase method, Delegate to)
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 61
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 14
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 87
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 185
[20:42:27.116] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.9.1.0, Culture=neutral, PublicKeyToken=null -> SDL2
[20:42:27.118] [Main Thread/DEBUG] [tML]: 	attempting to load '/Users/arham/Library/Application Support/tModLoader/Libraries/Native/OSX/libSDL2-2.0.0.dylib'...
[20:42:27.118] [Main Thread/DEBUG] [tML]: 	failure - TryLoad returned null
[20:42:27.120] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the DYLD_PRINT_LIBRARIES environment variable: dlopen(libSDL2, 0x0001): tried: '/Users/arham/Library/Application Support/tModLoader/Libraries/Native/OSX/libSDL2' (no such file), 'libSDL2' (no such file), '/usr/local/lib/libSDL2' (no such file), '/usr/lib/libSDL2' (no such file), '/Users/arham/Library/Application Support/tModLoader/Libraries/Native/OSX/libSDL2' (no such file), '/Users/arham/Library/Application Support/tModLoader/libSDL2' (no such file)
   at SDL2.SDL.INTERNAL_SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, Byte* title, Byte* message, IntPtr window)
   at SDL2.SDL.INTERNAL_SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, Byte* title, Byte* message, IntPtr window)
   at SDL2.SDL.SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, String title, String message, IntPtr window) in D:\a\tModLoader\tModLoader\FNA\lib\SDL2-CS\src\SDL2.cs:line 1326
   at Terraria.ModLoader.Engine.ErrorReporting.MessageBoxShow(String message) in tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 26
   at Terraria.ModLoader.Engine.ErrorReporting.FatalExit(String message) in tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 38
   at Terraria.ModLoader.Engine.ErrorReporting.FatalExit(String message, Exception e) in tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 66
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 185
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

```

**Comment by direwolf420** [comment]
That's not the same error. I would suggest opening a new issue with that log attached. Also, try updating tml to 2022.09.47.49, yours is a few versions behind

**Comment by Chicken-Bones** [comment]
tModLoader does not work on ARM, somehow you've downloaded the wrong version of `dotnet`

**Comment by Chicken-Bones** [comment]
The x64 version which should be automatically installed by tML when you try and launch it, uses Rosetta to run on newer macs correctly

**Comment by tmuaprep** [comment]
yeah, deleted dotnet and it uses the x64 version but it still doesn't run. used the latest release, error again. i've been trying for days at this point. seems the fixed versions haven't been released yet for GOG

**Comment by JavidPack** [comment]
I've updated the install instructions on the wiki for manually installing 1.4.4-preview for GOG users: https://github.com/tModLoader/tModLoader/wiki/tModLoader-guide-for-players#manual-installation

You can give it a try if you want. Remember that 1.4.4 is still in beta and most mods haven't updated to it yet.

**Comment by tmuaprep** [comment]
got further this time, but got an error saying steam needs to be logged in and running, even though it was - tried clean install of terraria and the release build folders, restarting, everything.

**Comment by Chicken-Bones** [comment]
You need to post all the logs in your logs folder, maybe as a zip

**Comment by tmuaprep** [comment]
[logs.zip](https://github.com/tModLoader/tModLoader/files/11494812/logs.zip)

**Comment by tmuaprep** [comment]
looked around for support on this steam issue, seems like it's just never really been resolved. any idea for what's causing it?

**Comment by tmuaprep** [comment]
hello ?

**Comment by Chicken-Bones** [comment]
@L1ghtn1ng-cmd this is not the right thread, for support with GoG tML, but your log says `[07:24:49.251] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_v1.4.4.9.exe not found nearby`

You need to install tML next to (or inside) your GoG Terraria install.

**Comment by tmuaprep** [comment]
Holy christ this actually worked, I put the tmodloader folder in the applications folder and it ran using the 1.4.4 dev build. Thanks a lot haha
also might wanna make the GOG instructions a bit clearer as I thought I was installing it next to the Terraria folder inside Application Support. but anyway, thanks again
