### ISSUE TITLE
Crashing on startup / not launching

### ISSUE THREAD

**Issue by atlas1205** [bluemagic123/tModLoader#3115]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

tModLoader either crashes at launch with an error popup stating "quickeditdisable has stopped working", or nothing at all if it's run in the administrator mode. All fixes possible have been attempted and the issue persists.

Edit: quickeditdisable.exe can be bypassed with some edit to ScriptCaller.sh, but the game still crashes. Also occasionally shows the ".NET Host has stopped working" error popup.

Client log mentions System.ArgumentException: String contains invalid Unicode code points. See attached.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/10128555/client.log)
[environment.log](https://github.com/tModLoader/tModLoader/files/10136895/environment.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/10136896/Launch.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/10136898/terrariasteamclient.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/10136897/Natives.log)

### Steps to reproduce

1. Launch tModLoader through Steam
2. It crashes with "quickeditdisable has stopped working" pop-up or nothing at all in admin mode.

### Expected Behavior

1. The game launches.

### Actual Behavior

Crashing with a popup or silently, producing a Unicode-related exception in the log.

### Reproduction frequency

100%

### Additional Information

1.4 preview also crashes. The 1.3 version of TML runs fine.

**Comment by JavidPack** [comment]
Just a reminder to myself: Most the exceptions in the log are caught, but the exception during SetDisplayMode is the cause of the crash, we can try trycatching that?:
```
   at System.Console.WriteLine(String value)
   at Terraria.Main.SetDisplayMode(Int32 width, Int32 height, Boolean fullscreen) in tModLoader\Terraria\Main.cs:line 52492
   at Terraria.Main.LoadSettings() in tModLoader\Terraria\Main.cs:line 3401
   ```

**Comment by atlas1205** [comment]
### Late update:
A few days after this report, I got a suggestion from the official tML Discord server.
I was able to work around this crash by using either the command prompt or a batch file to launch the game - bypassing other launch shenanigans. It doesn't fix the issue, but I can at least play.

Below is called from the tML's root folder (either with the command prompt, or a batch file for quick access):
 `"dotnet/6.0.0/dotnet.exe" tModLoader.dll`

**Comment by Chicken-Bones** [comment]
What happens if you double-click `start-tModLoader.bat`?

**Comment by Chicken-Bones** [comment]
Also, please come to the Discord and send me a DM. I'll try and investigate this a bit more

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
