### ISSUE TITLE
Mod name does not match assembly name

### ISSUE THREAD

**Issue by Aceplante** [bluemagic123/tModLoader#3229]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Why is this happening? I also cannot find the name it claims is wrong. Please help

### Log File

[20:07:34.689] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading CustomRace v1.0.2
The mod(s) have been automatically disabled.
System.Exception: Mod name CustomRace does not match assembly name TianicExampleRace
   at Terraria.ModLoader.Core.AssemblyManager.VerifyMod(String modName, Assembly assembly, Type& modType) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 210
   at Terraria.ModLoader.Core.AssemblyManager.Instantiate(ModLoadContext mod) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 204
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at Terraria.ModLoader.Core.AssemblyManager.InstantiateMods(List`1 modsToLoad, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\AssemblyManager.cs:line 258
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 118
[20:07:34.690] [.NET ThreadPool Worker/INFO] [tML]: Disabling Mod: CustomRace

### Steps to reproduce

1. Make a custom mod
2. Try to load it

### Expected Behavior

It should work

### Actual Behavior

It does not load

### Reproduction frequency

Always?

**Comment by steviegt6** [comment]
This is an issue with your mod.

**Comment by Aceplante** [comment]
How do I fix it? where is the issue?

**Comment by JavidPack** [comment]
You might have an extra .dll file in your mod sources, or your assembly name in your csproj file might not match the folder name, or maybe the Mod classname doesn't match the folder name. If you are still having issues, come to the tmodloader discord, this is not the place.

This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
