### ISSUE TITLE
tmodloader audio gets bad after playing for a couple hours

### ISSUE THREAD

**Issue by AbyssalBlackFlame** [bluemagic123/tModLoader#3261]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

the tmodloader audio gets bad after playing for a couple hours, the only way to fix it is restarting my pc. i dont know if this is related, but my friend who also plays is saying the enemies are on 2x speed when he watches me.

https://user-images.githubusercontent.com/117153518/219269177-915cf587-cebc-43f5-af87-11d8539cad69.mp4

### Log File

[21:08:13] [1/INFO] [tML]: Starting tModLoader v0.11.8.5 Windows client (9/13/2021)
[21:08:13] [1/INFO] [tML]: Running on NetFramework 4.8
[21:08:13] [1/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.exe
[21:08:13] [1/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader
[21:08:13] [1/INFO] [tML]: Launch Parameters: 
[21:08:13] [1/DEBUG] [tML]: Assembly Resolve:  -> MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[21:08:13] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null
[21:08:13] [1/DEBUG] [tML]: Assembly Resolve: MonoMod.RuntimeDetour, Version=20.11.16.1, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:08:13] [1/DEBUG] [tML]: Assembly Resolve:  -> Ionic.Zip.Reduced, Version=1.9.1.8, Culture=neutral, PublicKeyToken=edbe51ad942a3f5c
[21:08:14] [1/DEBUG] [tML]: Assembly Resolve:  -> Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed
[21:08:14] [1/DEBUG] [tML]: Assembly Resolve:  -> Steamworks.NET, Version=9.1.0.0, Culture=neutral, PublicKeyToken=null
[21:08:14] [1/INFO] [tML]: Checking Steam installation...
[21:08:14] [1/INFO] [tML]: Steam installation OK.
[21:08:14] [1/INFO] [Terraria]: Found Terraria steamapp install at: C:\Program Files (x86)\Steam\steamapps\common\Terraria
[21:08:14] [1/INFO] [Terraria]: Steam Cloud Quota: 129.3 MB available
[21:08:15] [1/DEBUG] [Terraria]: Graphics Device: NVIDIA GeForce GTX 1050 Ti {Width:1920 Height:1080 Format:Color AspectRatio:1.777778}
[21:08:15] [1/DEBUG] [Terraria]: Device Reset, Profile: Reach -> HiDef, Width: 800, Height: 480, Fullscreen: False, Display: \\.\DISPLAY1
[21:08:23] [1/INFO] [Terraria]: Loaded 1000 vanilla assets
[21:08:24] [1/INFO] [Terraria]: Loaded 2000 vanilla assets
[21:08:25] [1/INFO] [Terraria]: Loaded 3000 vanilla assets
[21:08:25] [1/INFO] [Terraria]: Loaded 4000 vanilla assets
[21:08:26] [1/INFO] [Terraria]: Loaded 5000 vanilla assets
[21:08:29] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 1920, Height: 480 -> 1057, Fullscreen: False, Display: \\.\DISPLAY1
[21:08:30] [7/DEBUG] [tML]: Assembly Resolve:  -> MP3Sharp, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
[21:08:30] [7/DEBUG] [tML]: Assembly Resolve:  -> NVorbis, Version=0.8.4.0, Culture=neutral, PublicKeyToken=null
[21:08:30] [13/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Pdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:08:30] [12/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:08:30] [13/DEBUG] [tML]: Assembly Resolve:  -> Mono.Cecil.Mdb, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:08:30] [7/INFO] [Terraria]: JIT loading finished
[21:08:33] [13/INFO] [tML]: Unloading mods
[21:08:33] [13/INFO] [tML]: Finding Mods...
[21:08:33] [13/INFO] [tML]: Sandboxing: CalamityMod
[21:08:34] [13/INFO] [tML]: Instantiating Mods...
[21:08:35] [13/INFO] [tML]: Initializing: ModLoader v0.11.8.5
[21:08:36] [13/INFO] [tML]: Initializing: CalamityMod v1.4.5.7
[21:08:40] [13/DEBUG] [tML]: Assembly Resolve: CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=20.5.14.1, Culture=neutral, PublicKeyToken=null
[21:08:40] [13/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=20.5.14.1 -> 20.11.16.1
[21:08:40] [13/DEBUG] [tML]: Assembly Resolve: CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null
[21:08:40] [13/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[21:08:40] [13/WARN] [tML]: Upgraded Reference MonoMod.Utils -> Version=19.12.19.1 -> 20.11.16.1
[21:08:40] [13/DEBUG] [tML]: Assembly Resolve: TerrariaHooks, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.RuntimeDetour, Version=19.12.19.1, Culture=neutral, PublicKeyToken=null
[21:08:40] [13/WARN] [tML]: Upgraded Reference MonoMod.RuntimeDetour -> Version=19.12.19.1 -> 20.11.16.1
[21:08:40] [13/DEBUG] [tML]: Hook IL.Terraria.Wiring::HitWireSingle(int, int) modified by CalamityMod_0
[21:08:40] [13/DEBUG] [tML]: Assembly Resolve: CalamityMod_0, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null -> Mono.Cecil, Version=0.11.2.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e
[21:08:40] [13/WARN] [tML]: Upgraded Reference Mono.Cecil -> Version=0.11.2.0 -> 0.11.3.0
[21:08:41] [13/DEBUG] [tML]: Hook On.Terraria.Main::InitLifeBytes() added by CalamityMod_0
[21:08:41] [13/DEBUG] [tML]: Hook On.Terraria.NPC::SlimeRainSpawns(int) added by CalamityMod_0
[21:08:41] [13/DEBUG] [tML]: Hook IL.Terraria.WorldGen::MakeDungeon(int, int) modified by CalamityMod_0
[21:08:41] [13/DEBUG] [tML]: Hook IL.Terraria.WorldGen::GrowLivingTree(int, int) modified by CalamityMod_0
[21:08:41] [13/DEBUG] [tML]: Hook On.Terraria.WorldGen::OpenDoor(int, int, int) added by CalamityMod_0
[21:08:41] [13/DEBUG] [tML]: Hook On.Terraria.WorldGen::CloseDoor(int, int, bool) added by CalamityMod_0
[21:08:41] [13/DEBUG] [tML]: Hook IL.Terraria.Main::UpdateTime() modified by CalamityMod_0
[21:08:41] [13/DEBUG] [tML]: Hook On.Terraria.Main::UpdateTime_SpawnTownNPCs() added by CalamityMod_0
[21:08:41] [13/INFO] [tML]: Setting up...
[21:08:41] [13/INFO] [tML]: Loading: ModLoader v0.11.8.5
[21:08:41] [13/INFO] [tML]: Loading: CalamityMod v1.4.5.7
[21:08:41] [1/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Main.LoadBackground(Int32 i)
   at Terraria.Main.DrawSurfaceBG()
   at Terraria.Main.DrawBG()
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[21:08:42] [13/INFO] [CalamityMod]: ModLoader version > 0.11.7.7 detected. Mechworm UUID workaround is disabled.
[21:08:42] [13/INFO] [tML]: RAM usage: 1.8 GB
[21:08:42] [13/INFO] [tML]: Adding Recipes...
[21:09:02] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920 -> 800, Height: 1057 -> 480, Fullscreen: False, Display: \\.\DISPLAY1
[21:09:02] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 800 -> 1920, Height: 480 -> 1080, Fullscreen: False, Display: \\.\DISPLAY1
[21:09:03] [1/WARN] [tML]: Silently Caught Exception: 
System.IO.IOException: The process cannot access the file 'C:\Users\megan\OneDrive\Documents\My Games\Terraria\ModLoader\input profiles.json' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   at System.IO.File.WriteAllText(String path, String contents)
   at Terraria.IO.Preferences.Save(Boolean createFile)
   at Terraria.GameInput.PlayerInput.Save()
   at Terraria.Main.SaveSettings()
   at Terraria.Main.DrawMenu(GameTime gameTime)
   at Terraria.Main.DoDraw(GameTime gameTime)
   at Terraria.Main.Draw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DrawFrame()
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame_()
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

[21:09:13] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: False -> True, Display: \\.\DISPLAY1
[21:09:27] [1/DEBUG] [tML]: Process.Start (UseShellExecute = False): "tModLoaderServer.exe" -autoshutdown -password "bruh" -lang 1 -world "C:\Users\megan\OneDrive\Documents\My Games\Terraria\ModLoader\Worlds\nou.wld" -modpath "C:\Users\megan\OneDrive\Documents\My Games\Terraria\ModLoader\Mods" -steam -localsteamid 76561199168735226 -lobby friends
[21:09:27] [3/INFO] [Terraria]: Connecting to 127.0.0.1:7777
[21:09:29] [3/WARN] [tML]: Silently Caught Exception: 
System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:7777
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Connect(EndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPEndPoint remoteEP)
   at System.Net.Sockets.TcpClient.Connect(IPAddress address, Int32 port)
   at Terraria.Net.Sockets.TcpSocket.Terraria.Net.Sockets.ISocket.Connect(RemoteAddress address)
   at Terraria.Netplay.TcpClientLoop(Object threadContext)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

[21:09:42] [1/INFO] [tML]: Server reports AllowVanillaClients set to False
[21:09:42] [3/INFO] [StatusText]: Receiving tile data
[21:09:42] [1/INFO] [Terraria]: Entering world with player: nou, IsCloud=False
[21:10:38] [3/INFO] [StatusText]: Receiving tile data
[21:11:05] [3/INFO] [StatusText]: Receiving tile data
[21:12:23] [3/INFO] [StatusText]: Receiving tile data
[21:13:17] [3/INFO] [StatusText]: Receiving tile data
[21:13:33] [3/INFO] [StatusText]: Receiving tile data
[21:13:54] [3/INFO] [StatusText]: Receiving tile data
[21:14:36] [3/INFO] [StatusText]: Receiving tile data
[21:14:51] [3/INFO] [StatusText]: Receiving tile data
[21:15:00] [3/INFO] [StatusText]: Receiving tile data
[21:16:13] [3/INFO] [StatusText]: Receiving tile data
[21:16:56] [3/INFO] [StatusText]: Receiving tile data
[21:20:50] [1/INFO] [Terraria]: Loaded 6000 vanilla assets
[21:24:27] [3/INFO] [StatusText]: Receiving tile data
[21:25:27] [1/DEBUG] [Terraria]: Device Reset, Profile: HiDef, Width: 1920, Height: 1080, Fullscreen: True, Display: \\.\DISPLAY1
[21:26:01] [24/INFO] [StatusText]: Saving map data

### Steps to reproduce

i just play for a couple hours and this happens every time.

### Expected Behavior

audio shouldnt be messed up

### Actual Behavior

audio is messed up

### Reproduction frequency

100% of the time

### Additional Information

if i close and open tmodloader the audio is still messed up. if close tmodloader and open terraria though, the audio on terraria is fine. only way to fix it for a couple hours is to restart my pc. its not the mods since i just have calamity and a couple others that my friend uses and his games fine.

**Comment by AbyssalBlackFlame** [comment]
pc specs:
gigabyte 3070 ti
intel i9 11900K 11th gen
2 nvme ssds

**Comment by thenarmed** [comment]
i have that problem too

**Comment by thenarmed** [comment]
i update drivers that most people said to do but it doesnt work :/
