### ISSUE TITLE
tModLoader v2022.9.47.44 Fatal Error

### ISSUE THREAD

**Issue by tab960562** [bluemagic123/tModLoader#3352]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

[tModLoader v2022.9.47.44 Fatal Error](url)
Main engine crash

Tip: Restart the game. If this issue persists, try uninstalling Terraria completely, then reinstalling through Steam, and then reinstalling tModLoader

System.TypeInitializationException: The type initializer for 'Microsoft.Xna.Framework.FNAPlatform' threw an exception.
 ---> System.Exception: SDL_Init failed: No available video device
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit(LaunchParameters args) in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 217
   at Microsoft.Xna.Framework.FNAPlatform..cctor() in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\FNAPlatform.cs:line 150
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 264
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 5063
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 225

A client.log file containing error information has been generated in
/home/myuser/tModLoader/tModLoader-Logs
(You will need to share this file if asking for help)
[client.log](https://github.com/tModLoader/tModLoader/files/11074945/client.log)

**Comment by JavidPack** [comment]
Hm, aside from the message "No available video device" suggesting that your video driver is not being detected, there isn't much else to go on. 

Do you have a weird video device? If it's rare, it might be an issue relating to that. Do other video games work on this computer?

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
