### ISSUE TITLE
when i use tmodloader_server,  

### ISSUE THREAD

**Issue by nz2463123401** [bluemagic123/tModLoader#3366]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

when i add some mods ,it will get error and exist.but when i don't add mod, it runs right

### Log File

[00:39:03.317] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[00:39:03.325] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.09.47.44|stable|Stable|acbf04fe10872a3667e2b4f21147b3a799bfa98e|5249838120919804380 built 3/24/2023 7:17 AM
[00:39:03.326] [Main Thread/INFO] [tML]: Log date: 4/1/2023
[00:39:03.327] [Main Thread/INFO] [tML]: Running on Linux (v3.10.0.1160) X64 NetCore 6.0.0
[00:39:03.327] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[00:39:03.327] [Main Thread/INFO] [tML]: Executable: /taila/tModLoader.dll
[00:39:03.327] [Main Thread/INFO] [tML]: Working Directory: /taila
[00:39:03.328] [Main Thread/INFO] [tML]: Launch Parameters:  -server -config serverconfig.txt
[00:39:03.331] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[00:39:03.924] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.4.9.exe not found nearby
[00:39:03.937] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[00:39:05.550] [Main Thread/DEBUG] [tML]: Network compatibility version is 2022.9.47
[00:39:06.704] [Main Thread/INFO] [tML]: Finding Mods...
[00:39:06.724] [Main Thread/INFO] [tML]: Sandboxing: AlchemistNPCLite (AlchemistNPC Lite) v1.8.16
[00:39:06.802] [Main Thread/INFO] [tML]: Sandboxing: Antisocial (Antisocial) v1.5
[00:39:06.807] [Main Thread/INFO] [tML]: Sandboxing: ArmorReforge (Armor Modifiers & Reforging) v1.3.8
[00:39:06.837] [Main Thread/INFO] [tML]: Sandboxing: BAM (Basic Automated Mining) v1.1.8
[00:39:06.844] [Main Thread/INFO] [tML]: Sandboxing: BossChecklist (Boss Checklist) v1.4.0
[00:39:06.854] [Main Thread/INFO] [tML]: Sandboxing: BossHealthBar (BossHealthBar(Boss血条)) v0.1
[00:39:06.859] [Main Thread/INFO] [tML]: Sandboxing: Fargowiltas (Fargo's Mutant Mod) v2.8.7
[00:39:06.889] [Main Thread/INFO] [tML]: Sandboxing: ImproveGame ([Version 1.4.4 PreView] Quality of Life 更好的体验) v1.6.3.99
[00:39:06.910] [Main Thread/DEBUG] [tML]: Assembly Resolve: ImproveGame, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> tModLoader, Version=1.4.4.9, Culture=neutral, PublicKeyToken=null
[00:39:06.911] [Main Thread/DEBUG] [tML]: Assembly Resolve:  -> tModLoader, Version=1.4.4.9, Culture=neutral, PublicKeyToken=null
[00:39:06.928] [Main Thread/INFO] [tML]: Sandboxing: MagicStorage (Magic Storage) v0.5.7.10
[00:39:06.961] [Main Thread/INFO] [tML]: Sandboxing: MoreAccessories (More Accessory Slots (More Accessories)) v1.3
[00:39:06.965] [Main Thread/INFO] [tML]: Sandboxing: RecipeBrowser (Recipe Browser) v0.9.6.1
[00:39:06.978] [Main Thread/INFO] [tML]: Sandboxing: ThoriumMod (Thorium Mod) v1.7.0.1
[00:39:07.432] [Main Thread/INFO] [tML]: Sandboxing: WingSlotExtra (Wing Slot Extra) v1.3.4
[00:39:07.443] [Main Thread/INFO] [tML]: Constructing Mods...
[00:39:08.104] [Main Thread/INFO] [tML]: Adding Content: ModLoader (tModLoader) v2022.9.47.44
[00:39:08.208] [Main Thread/INFO] [tML]: Adding Content: AlchemistNPCLite (AlchemistNPC Lite) v1.8.16
[00:39:08.777] [Main Thread/INFO] [tML]: Adding Content: Antisocial (Antisocial) v1.5
[00:39:08.800] [Main Thread/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::MouseHover(Item[], int, int) added by Antisocial
[00:39:08.850] [Main Thread/INFO] [tML]: Adding Content: ArmorReforge (Armor Modifiers & Reforging) v1.3.8
[00:39:08.863] [Main Thread/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::MouseHover(Item[], int, int) added by ArmorReforge
[00:39:08.917] [Main Thread/INFO] [tML]: Adding Content: BAM (Basic Automated Mining) v1.1.8
[00:39:09.038] [Main Thread/INFO] [tML]: Adding Content: BossChecklist (Boss Checklist) v1.4.0
[00:39:09.378] [Main Thread/DEBUG] [tML]: Hook On.Terraria.GameContent.Events.DD2Event::WinInvasionInternal() added by BossChecklist
[00:39:09.383] [Main Thread/INFO] [BossChecklist]: Progression values for vanilla entries have been last updated on BossChecklist v1.4.0
[00:39:09.383] [Main Thread/INFO] [BossChecklist]: Boss Log integration messages will not be logged.
[00:39:09.426] [Main Thread/INFO] [tML]: Adding Content: BossHealthBar (BossHealthBar(Boss血条)) v0.1
[00:39:09.507] [Main Thread/INFO] [tML]: Adding Content: Fargowiltas (Fargo's Mutant Mod) v2.8.7
[00:39:10.160] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Recipe::FindRecipes(bool) added by Fargowiltas
[00:39:10.223] [Main Thread/INFO] [tML]: Adding Content: ImproveGame ([Version 1.4.4 PreView] Quality of Life 更好的体验) v1.6.3.99
[00:39:10.263] [Main Thread/DEBUG] [tML]: Assembly Resolve: ImproveGame, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=22.11.9.0, Culture=neutral, PublicKeyToken=null

### Steps to reproduce

1.add some mods
[00:39:03.317] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[00:39:03.325] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.09.47.44|stable|Stable|acbf04fe10872a3667e2b4f21147b3a799bfa98e|5249838120919804380 built 3/24/2023 7:17 AM
[00:39:03.326] [Main Thread/INFO] [tML]: Log date: 4/1/2023
[00:39:03.327] [Main Thread/INFO] [tML]: Running on Linux (v3.10.0.1160) X64 NetCore 6.0.0
[00:39:03.327] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[00:39:03.327] [Main Thread/INFO] [tML]: Executable: /taila/tModLoader.dll
[00:39:03.327] [Main Thread/INFO] [tML]: Working Directory: /taila
[00:39:03.328] [Main Thread/INFO] [tML]: Launch Parameters:  -server -config serverconfig.txt
[00:39:03.331] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[00:39:03.924] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.4.9.exe not found nearby
[00:39:03.937] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[00:39:05.550] [Main Thread/DEBUG] [tML]: Network compatibility version is 2022.9.47
[00:39:06.704] [Main Thread/INFO] [tML]: Finding Mods...
[00:39:06.724] [Main Thread/INFO] [tML]: Sandboxing: AlchemistNPCLite (AlchemistNPC Lite) v1.8.16
[00:39:06.802] [Main Thread/INFO] [tML]: Sandboxing: Antisocial (Antisocial) v1.5
[00:39:06.807] [Main Thread/INFO] [tML]: Sandboxing: ArmorReforge (Armor Modifiers & Reforging) v1.3.8
[00:39:06.837] [Main Thread/INFO] [tML]: Sandboxing: BAM (Basic Automated Mining) v1.1.8
[00:39:06.844] [Main Thread/INFO] [tML]: Sandboxing: BossChecklist (Boss Checklist) v1.4.0
[00:39:06.854] [Main Thread/INFO] [tML]: Sandboxing: BossHealthBar (BossHealthBar(Boss血条)) v0.1
[00:39:06.859] [Main Thread/INFO] [tML]: Sandboxing: Fargowiltas (Fargo's Mutant Mod) v2.8.7
[00:39:06.889] [Main Thread/INFO] [tML]: Sandboxing: ImproveGame ([Version 1.4.4 PreView] Quality of Life 更好的体验) v1.6.3.99
[00:39:06.910] [Main Thread/DEBUG] [tML]: Assembly Resolve: ImproveGame, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> tModLoader, Version=1.4.4.9, Culture=neutral, PublicKeyToken=null
[00:39:06.911] [Main Thread/DEBUG] [tML]: Assembly Resolve:  -> tModLoader, Version=1.4.4.9, Culture=neutral, PublicKeyToken=null
[00:39:06.928] [Main Thread/INFO] [tML]: Sandboxing: MagicStorage (Magic Storage) v0.5.7.10
[00:39:06.961] [Main Thread/INFO] [tML]: Sandboxing: MoreAccessories (More Accessory Slots (More Accessories)) v1.3
[00:39:06.965] [Main Thread/INFO] [tML]: Sandboxing: RecipeBrowser (Recipe Browser) v0.9.6.1
[00:39:06.978] [Main Thread/INFO] [tML]: Sandboxing: ThoriumMod (Thorium Mod) v1.7.0.1
[00:39:07.432] [Main Thread/INFO] [tML]: Sandboxing: WingSlotExtra (Wing Slot Extra) v1.3.4
[00:39:07.443] [Main Thread/INFO] [tML]: Constructing Mods...
[00:39:08.104] [Main Thread/INFO] [tML]: Adding Content: ModLoader (tModLoader) v2022.9.47.44
[00:39:08.208] [Main Thread/INFO] [tML]: Adding Content: AlchemistNPCLite (AlchemistNPC Lite) v1.8.16
[00:39:08.777] [Main Thread/INFO] [tML]: Adding Content: Antisocial (Antisocial) v1.5
[00:39:08.800] [Main Thread/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::MouseHover(Item[], int, int) added by Antisocial
[00:39:08.850] [Main Thread/INFO] [tML]: Adding Content: ArmorReforge (Armor Modifiers & Reforging) v1.3.8
[00:39:08.863] [Main Thread/DEBUG] [tML]: Hook On.Terraria.UI.ItemSlot::MouseHover(Item[], int, int) added by ArmorReforge
[00:39:08.917] [Main Thread/INFO] [tML]: Adding Content: BAM (Basic Automated Mining) v1.1.8
[00:39:09.038] [Main Thread/INFO] [tML]: Adding Content: BossChecklist (Boss Checklist) v1.4.0
[00:39:09.378] [Main Thread/DEBUG] [tML]: Hook On.Terraria.GameContent.Events.DD2Event::WinInvasionInternal() added by BossChecklist
[00:39:09.383] [Main Thread/INFO] [BossChecklist]: Progression values for vanilla entries have been last updated on BossChecklist v1.4.0
[00:39:09.383] [Main Thread/INFO] [BossChecklist]: Boss Log integration messages will not be logged.
[00:39:09.426] [Main Thread/INFO] [tML]: Adding Content: BossHealthBar (BossHealthBar(Boss血条)) v0.1
[00:39:09.507] [Main Thread/INFO] [tML]: Adding Content: Fargowiltas (Fargo's Mutant Mod) v2.8.7
[00:39:10.160] [Main Thread/DEBUG] [tML]: Hook On.Terraria.Recipe::FindRecipes(bool) added by Fargowiltas
[00:39:10.223] [Main Thread/INFO] [tML]: Adding Content: ImproveGame ([Version 1.4.4 PreView] Quality of Life 更好的体验) v1.6.3.99
[00:39:10.263] [Main Thread/DEBUG] [tML]: Assembly Resolve: ImproveGame, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null -> MonoMod.Utils, Version=22.11.9.0, Culture=neutral, PublicKeyToken=null

### Reproduction frequency

every times when I run it with mods

**Comment by nz2463123401** [comment]
sorry ,i upload  wrong steps to reproduce.  this is its respond 
 ./start-tModLoaderServer.sh 
Use steam server (y/n): n
You are on platform: "Linux"
Verifying .NET....
This may take a few moments.
Logging to /taila/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/taila/dotnet/6.0.0"
cat: /taila/cli-argsConfig.txt: No such file or directory
Loaded Custom Arguments: 
Attempting Launch...
Launched Using Local Dotnet
Finding Mods...
Sandboxing: AlchemistNPC Lite v1.8.16
Sandboxing: Antisocial v1.5
Sandboxing: Armor Modifiers & Reforging v1.3.8
Sandboxing: Basic Automated Mining v1.1.8
Sandboxing: Boss Checklist v1.4.0
Sandboxing: BossHealthBar(Boss血条) v0.1
Sandboxing: Fargo's Mutant Mod v2.8.7
Sandboxing: Magic Storage v0.5.7.10
Sandboxing: More Accessory Slots (More Accessories) v1.3
Sandboxing: Recipe Browser v0.9.6.1
Sandboxing: Thorium Mod v1.7.0.1
Sandboxing: Wing Slot Extra v1.3.4
Constructing Mods...
Adding Content: tModLoader v2022.9.47.44
Adding Content: AlchemistNPC Lite v1.8.16
Adding Content: Antisocial v1.5
Adding Content: Armor Modifiers & Reforging v1.3.8
Adding Content: Basic Automated Mining v1.1.8
Adding Content: Boss Checklist v1.4.0
Adding Content: BossHealthBar(Boss血条) v0.1
Adding Content: Fargo's Mutant Mod v2.8.7
Adding Content: Magic Storage v0.5.7.10
./start-tModLoaderServer.sh: line 55:   680 Aborted                 ./LaunchUtils/ScriptCaller.sh $launch_args
and then it closed

**Comment by nz2463123401** [comment]
dotnet tModLoader.dll 
[01:24:18.585] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[01:24:18.602] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.09.47.44|stable|Stable|acbf04fe10872a3667e2b4f21147b3a799bfa98e|5249838120919804380 built 3/24/2023 7:17 AM
[01:24:18.604] [Main Thread/INFO] [tML]: Log date: 4/1/2023
[01:24:18.605] [Main Thread/INFO] [tML]: Running on Linux (v3.10.0.1160) X64 NetCore 6.0.0
[01:24:18.605] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[01:24:18.605] [Main Thread/INFO] [tML]: Executable: /taila/tModLoader.dll
[01:24:18.605] [Main Thread/INFO] [tML]: Working Directory: /taila
[01:24:18.850] [Main Thread/DEBUG] [FNA]: Querying linked library versions...
[01:24:18.851] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.9.1.0, Culture=neutral, PublicKeyToken=null -> SDL2
[01:24:18.851] [Main Thread/DEBUG] [tML]: 	attempting to load '/taila/Libraries/Native/Linux/libSDL2-2.0.so.0'...
[01:24:18.852] [Main Thread/DEBUG] [tML]: 	success
[01:24:18.852] [Main Thread/DEBUG] [FNA]: SDL v2.24.0
[01:24:18.853] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.9.1.0, Culture=neutral, PublicKeyToken=null -> FNA3D
[01:24:18.853] [Main Thread/DEBUG] [tML]: 	attempting to load '/taila/Libraries/Native/Linux/libFNA3D.so.0'...
[01:24:18.853] [Main Thread/DEBUG] [tML]: 	success
[01:24:18.853] [Main Thread/DEBUG] [FNA]: FNA3D v22.8.0
[01:24:18.854] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.9.1.0, Culture=neutral, PublicKeyToken=null -> FAudio
[01:24:18.854] [Main Thread/DEBUG] [tML]: 	attempting to load '/taila/Libraries/Native/Linux/libFAudio.so.0'...
[01:24:18.854] [Main Thread/DEBUG] [tML]: 	success
[01:24:18.854] [Main Thread/DEBUG] [FNA]: FAudio v22.8.0
[01:24:19.166] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.4.9.exe not found nearby
[01:24:19.175] [Main Thread/DEBUG] [TerrariaSteamClient]: Disabled. Launched outside steam client.
[01:24:19.183] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
pci id for fd 140: 1013:00b8, driver (null)
gbm: failed to open any driver (search paths /usr/lib64/dri)
gbm: Last dlopen error: /usr/lib64/dri/kms_swrast_dri.so: cannot open shared object file: No such file or directory
failed to load driver: kms_swrast
gbm: failed to open any driver (search paths /usr/lib64/dri)
gbm: Last dlopen error: /usr/lib64/dri/swrast_dri.so: cannot open shared object file: No such file or directory
failed to load swrast driver
[01:24:19.425] [Main Thread/WARN] [tML]: Silently Caught Exception: 
Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: EGL not initialized
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow() in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 388
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 274
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 5063
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 225
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

[01:24:19.427] [Main Thread/FATAL] [tML]: Main engine crash

Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: EGL not initialized
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow() in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 388
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 274
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 5063
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 225
tModLoader v2022.9.47.44 Fatal Error
Main engine crash

Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: EGL not initialized
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow() in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 388
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 274
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 5063
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 225

A client.log file containing error information has been generated in
/taila/tModLoader-Logs
(You will need to share this file if asking for help)

**Comment by JavidPack** [comment]
Can you identify the single mod that causes it to fail?

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
