### ISSUE TITLE
Error reported by startup server

### ISSUE THREAD

**Issue by GhostarDragon** [bluemagic123/tModLoader#3368]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

root@orangepi4-lts:~/tmod1.4# chmod 777 start-tModLoaderServer.sh 
root@orangepi4-lts:~/tmod1.4# ./start-tModLoaderServer.sh 
Use steam server (y/n): n
You are on platform: "Linux"
Verifying .NET....
This may take a few moments.
Logging to /root/tmod1.4/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/root/tmod1.4/dotnet/6.0.0"
cat: /root/tmod1.4/cli-argsConfig.txt: 没有那个文件或目录
Loaded Custom Arguments: 
Attempting Launch...
Launched Using Local Dotnet
Unable to load one or more of the requested types.
Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.
 (see server.log for full trace)
tModLoader v2022.9.47.46 Fatal Error
Main engine crash

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Terraria.ModLoader.LoaderManager.AutoLoad() in tModLoader\Terraria\ModLoader\Loader.cs:line 79
   at Terraria.ModLoader.ModLoader.EngineInit() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 93
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 222
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'

A server.log file containing error information has been generated in
/root/tmod1.4/tModLoader-Logs
(You will need to share this file if asking for help)
Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory (see server.log for full trace)

### Log File

[00:51:19.591] [Main Thread/INFO] [tML]: Save Are Located At: /root/.local/share/Terraria/tModLoader
[00:51:19.621] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.09.47.46|stable|Stable|a1a140f5efc26d35fb815462ed76ec93fd5070b9|5249845615329017268 built 2023/4/1 23:28
[00:51:19.628] [Main Thread/INFO] [tML]: Log date: 2023/4/2
[00:51:19.630] [Main Thread/INFO] [tML]: Running on Linux (v5.18.5.3399) Arm64 NetCore 6.0.0
[00:51:19.631] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[00:51:19.631] [Main Thread/INFO] [tML]: Executable: /root/tmod1.4/tModLoader.dll
[00:51:19.631] [Main Thread/INFO] [tML]: Working Directory: /root/tmod1.4
[00:51:19.632] [Main Thread/INFO] [tML]: Launch Parameters:  -server -config serverconfig.txt
[00:51:19.640] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[00:51:21.813] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.4.9.exe not found nearby
[00:51:21.866] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[00:51:22.139] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Terraria.ModLoader.LoaderManager.AutoLoad() in tModLoader\Terraria\ModLoader\Loader.cs:line 79
   at Terraria.ModLoader.ModLoader.EngineInit() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 94
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 224
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

[00:51:22.187] [Main Thread/FATAL] [tML]: Main engine crash

System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types.
Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.Assembly.GetTypes()
   at Terraria.ModLoader.LoaderManager.AutoLoad() in tModLoader\Terraria\ModLoader\Loader.cs:line 79
   at Terraria.ModLoader.ModLoader.EngineInit() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 93
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 222
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
System.BadImageFormatException: Could not load file or assembly 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'. An attempt was made to load a program with an incorrect format.

File name: 'Steamworks.NET, Version=20.1.0.0, Culture=neutral, PublicKeyToken=null'
[00:51:22.198] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.9.1.0, Culture=neutral, PublicKeyToken=null -> SDL2
[00:51:22.199] [Main Thread/DEBUG] [tML]: 	attempting to load '/root/tmod1.4/Libraries/Native/Linux/libSDL2-2.0.so.0'...
[00:51:22.199] [Main Thread/DEBUG] [tML]: 	failure - TryLoad returned null
[00:51:22.201] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.DllNotFoundException: Unable to load shared library 'SDL2' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libSDL2: cannot open shared object file: No such file or directory
   at SDL2.SDL.INTERNAL_SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, Byte* title, Byte* message, IntPtr window)
   at SDL2.SDL.INTERNAL_SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, Byte* title, Byte* message, IntPtr window)
   at SDL2.SDL.SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, String title, String message, IntPtr window) in D:\a\tModLoader\tModLoader\FNA\lib\SDL2-CS\src\SDL2.cs:line 1326
   at Terraria.ModLoader.Engine.ErrorReporting.MessageBoxShow(String message) in tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 26
   at Terraria.ModLoader.Engine.ErrorReporting.FatalExit(String message) in tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 38
   at Terraria.ModLoader.Engine.ErrorReporting.FatalExit(String message, Exception e) in tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 66
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 224
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

**Comment by JavidPack** [comment]
tModLoader does not work on ARM CPUs. There is some discussion on supporting it in #2639 and some people talking about workarounds that might still work in #2681

You can upvote (👍 ) to indicate that you want it.

**Comment by GhostarDragon** [comment]
> 

Is the tml version for arm64 only available in 22.6.96.4? If I want to play some other mod, he will prompt me to update to 22.9.45.

> tModLoader does not work on ARM CPUs. There is some discussion on supporting it in #2639 and some people talking about workarounds that might still work in #2681
> 
> You can upvote (👍 ) to indicate that you want it.

Is the tml version for arm64 only available in 22.6.96.4? If I want to play some other mod, he will prompt me to update to 22.9.45.

**Comment by dotabillie** [comment]
> Is the tml version for arm64 only available in 22.6.96.4? If I want to play some other mod, he will prompt me to update to 22.9.45.

i believe the answer is yes. the new version of tModLoader won't work on ARM64 cpu. so you have to find the old mods that work on 22.6.96.4

**Comment by JavidPack** [comment]
An arm64 workaround has been added to the FAQ: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#arm64-linux-workaround

**Comment by AlexTu2** [comment]
> 

> (This workaround is 1.4.3 only, it will not work on 1.4.4)

Is this being worked on for 1.4.4?

**Comment by JavidPack** [comment]
> > 
> 
> > (This workaround is 1.4.3 only, it will not work on 1.4.4)
> 
> Is this being worked on for 1.4.4?

We need to wait for MonoMod to support arm64 again. It was rewritten but the arm64 support hasn't been restored yet, https://github.com/MonoMod/MonoMod/issues/90

**Comment by Kuurama** [comment]
> > > 
> > 
> > 
> > > (This workaround is 1.4.3 only, it will not work on 1.4.4)
> > 
> > 
> > Is this being worked on for 1.4.4?
> 
> We need to wait for MonoMod to support arm64 again. It was rewritten but the arm64 support hasn't been restored yet, [MonoMod/MonoMod#90](https://github.com/MonoMod/MonoMod/issues/90)

I think this mono thing is done now, any news relating to it? I tried running it today on 1.4.4 and got the same error obviously.

**Comment by Chicken-Bones** [comment]
See #2639
