### ISSUE TITLE
tModLoader crashing [SteamP2PWriter.cs]

### ISSUE THREAD

**Issue by ghost** [bluemagic123/tModLoader#3422]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

Application: dotnet.exe
CoreCLR Version: 6.0.1122.52304
.NET Version: 6.0.11
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentException: Source array was not long enough. Check the source index, length, and the array's lower bounds. (Parameter 'sourceArray')
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length, Boolean reliable)
   at System.Array.Copy(Array sourceArray, Int32 sourceIndex, Array destinationArray, Int32 destinationIndex, Int32 length)
   at System.Collections.Generic.Queue`1.SetCapacity(Int32 capacity)
   at Terraria.Social.Steam.SteamP2PWriter.SendAll() in tModLoader\Terraria\Social\Steam\SteamP2PWriter.cs:line 88
   at Terraria.Social.Steam.CoreSocialModule.SteamTickLoop(Object context) in tModLoader\Terraria\Social\Steam\CoreSocialModule.cs:line 83
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/11263845/client.log)

### Steps to reproduce

1. Join P2P Steam Multiplayer Server
2. Randomly crash

### Expected Behavior

No crashes

### Actual Behavior

Crashing

### Reproduction frequency

Had it happen in less than 5 minutes every time.

**Comment by Chicken-Bones** [comment]
Hi, please come to the Discord and DM me. I will need to send you test builds to investigate this

**Comment by ghost** [comment]
[client.log](https://github.com/tModLoader/tModLoader/files/11288322/client.log)

**Comment by JavidPack** [comment]
Was this ever resolved?

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.

**Comment by stefnotch** [comment]
I just stumbled upon this crash in a multiplayer world. I have no idea how to reproduce it though.

[server.log](https://github.com/tModLoader/tModLoader/files/14623577/server.log)

[client.log](https://github.com/tModLoader/tModLoader/files/14623579/client.log)

**Comment by stefnotch** [comment]
Okay, it happened again. Let me know if I can do anything to help narrow it down.

Info: Windows 11, I was hosting a Terraria server (Host and Play) and playing with 2 friends over Steam.
