### ISSUE TITLE
tModLoader Server fail to create new world and host on arm64 server with x86_64 emulator (FEXBash)

### ISSUE THREAD

**Issue by kurokawaikki** [bluemagic123/tModLoader#3429]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

My setup:
Arm64 12 gb ram on oracle remote server running on ubuntu 22.04 aarch64.
To get steamcmd to work, I installed FEXBash x86_64 user space emulator.
The tModLoader can be run without problem to the menu of creating worlds. The mods can also be loaded.
However, if the world is creating, it will run into fatal error at some time point.
Also, if I let it load up the world that I created, it will also crashed.

I tried the patch on the older tModLoader. That one will work but I want the latest build to work with the steam version on my PC and my MAC. I want to host the remote mod server so that I can play with the latest MOD. Or can you show me how to recompile or build the .dll for arm64 for the latest release build (just the similar patch for the older version v2022.06.96.4 arm64/arm32 (jank) fix)?
Thank you very much!

### Log File

Environment log:
LESSOPEN=| /usr/bin/lesspipe %s
XDG_SESSION_ID=194
USER=ubuntu
LD_LIBRARY_PATH=/home/ubuntu/Steam/steamapps/common/tModLoader/Libraries/Native/Linux
DOTNET_ROOT=/home/ubuntu/.dotnet
SSH_CLIENT=114.158.79.51 11053 22
MOTD_SHOWN=pam
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/ubuntu/.dotnet:/home/ubuntu/.local/share/Steam
install_dir=/home/ubuntu/Steam/steamapps/common/tModLoader/dotnet/6.0.0
XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
SHELL=/bin/bash
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
LOGNAME=ubuntu
HOME=/home/ubuntu
SHLVL=3
LESSCLOSE=/usr/bin/lesspipe %s %s
XDG_RUNTIME_DIR=/run/user/1001
PWD=/home/ubuntu/Steam/steamapps/common/tModLoader
FNA_WORKAROUND_WINDOW_RESIZABLE=1
dotnet_version=6.0.0
dotnet_dir=/home/ubuntu/Steam/steamapps/common/tModLoader/dotnet
SSH_TTY=/dev/pts/1
OLDPWD=/home/ubuntu/Steam/steamapps/common/tModLoader/LaunchUtils
XDG_SESSION_CLASS=user
SSH_CONNECTION=114.158.79.51 11053 10.0.0.162 22
TERM=xterm-256color
LANG=C.UTF-8
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/1001/bus
XDG_SESSION_TYPE=tty

The server.log:

[13:00:34.586] [Main Thread/INFO] [tML]: Save Are Located At: /home/ubuntu/.local/share/Terraria/tModLoader
[13:00:34.700] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.09.47.47|stable|Stable|18e44636f17da1c201f87f9f74af1afd60b29e1e|5249851903069401163 built 04/08/2023 22:07
[13:00:34.725] [Main Thread/INFO] [tML]: Log date: 04/23/2023
[13:00:34.733] [Main Thread/INFO] [tML]: Running on Linux (v5.15.0.0) X64 NetCore 6.0.0
[13:00:34.742] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[13:00:34.744] [Main Thread/INFO] [tML]: Executable: /home/ubuntu/Steam/steamapps/common/tModLoader/tModLoader.dll
[13:00:34.745] [Main Thread/INFO] [tML]: Working Directory: /home/ubuntu/Steam/steamapps/common/tModLoader
[13:00:34.756] [Main Thread/INFO] [tML]: Launch Parameters:  -server -config serverconfig.txt
[13:00:34.788] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[13:00:43.133] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[13:00:43.396] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[13:00:44.760] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.ComponentModel.Win32Exception: Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Terraria.Initializers.LaunchInitializer.LoadServerParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 117
   at Terraria.Initializers.LaunchInitializer.LoadParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 18
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 228
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

[13:00:59.210] [Main Thread/DEBUG] [tML]: Network compatibility version is 2022.9.47
[13:01:07.880] [Main Thread/WARN] [tML]: Did not find enabled.json file
[13:01:07.894] [Main Thread/INFO] [tML]: Finding Mods...
[13:01:07.990] [Main Thread/INFO] [tML]: Constructing Mods...
[13:01:08.419] [Main Thread/INFO] [tML]: Adding Content: ModLoader (tModLoader) v2022.9.47.47
[13:01:09.243] [Main Thread/INFO] [tML]: Resizing...
[13:01:10.213] [Main Thread/INFO] [tML]: Configuring Content: ModLoader (tModLoader) v2022.9.47.47
[13:01:12.001] [Main Thread/INFO] [tML]: Finalizing Content: ModLoader (tModLoader) v2022.9.47.47
[13:01:13.032] [Main Thread/INFO] [tML]: RAM usage: 447.6 MB
[13:01:14.120] [Main Thread/INFO] [tML]: Adding Recipes...
[13:01:52.751] [Main Thread/INFO] [StatusText]: 0.0% -  - 0.
[13:01:54.737] [.NET ThreadPool Worker/INFO] [Terraria]: Generating World: test
[13:01:55.355] [Main Thread/INFO] [StatusText]: 0.0% - Generating world terrain - 0.
[13:01:55.472] [Main Thread/INFO] [StatusText]: 0.0% - Generating world terrain - 1.
[13:01:55.552] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.GameContent.Biomes.TerrainPass.ApplyPass(GenerationProgress progress, GameConfiguration configuration) in tModLoader\Terraria\GameContent\Biomes\TerrainPass.cs:line 162
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30
   at Terraria.WorldGen.GenerateWorld(Int32 seed, GenerationProgress customProgressObject) in tModLoader\Terraria\WorldGen.cs:line 12385
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2345
   at Terraria.WorldGen.worldGenCallback(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2335
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()

[13:01:55.577] [.NET ThreadPool Worker/ERROR] [tML]: A problem was encountered during world generation
Terrain
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.GameContent.Biomes.TerrainPass.ApplyPass(GenerationProgress progress, GameConfiguration configuration) in tModLoader\Terraria\GameContent\Biomes\TerrainPass.cs:line 162
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30
[13:01:55.610] [.NET ThreadPool Worker/ERROR] [Terraria]: A problem was encountered during world generation
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 60
   at Terraria.WorldGen.GenerateWorld(Int32 seed, GenerationProgress customProgressObject) in tModLoader\Terraria\WorldGen.cs:line 12385
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2345
   at Terraria.WorldGen.worldGenCallback(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2335
[13:16:54.249] [Main Thread/INFO] [StatusText]: 0.0% -  - 0.
./start-tModLoaderServer.sh: line 55: 42307 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args

The launch.log:

Verifying .NET....
Logging to /home/ubuntu/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/home/ubuntu/Steam/steamapps/common/tModLoader/dotnet/6.0.0"
Loaded Custom Arguments: 
Launched Using Local Dotnet

### Steps to reproduce

1. start server by ./start-tModLoaderServer.sh 
2. create a new world with n or load a world
3. any parameter with creating a world
4. Crashed after a few seconds

### Expected Behavior

Start the server and playable

### Actual Behavior

Crashed with error

### Reproduction frequency

Every time

### Additional Information

The FEXBash x86_64 emulator install on arm64 architecture
Every command was run with FEXBash.

**Comment by Ariaspect** [comment]
same here with crash message:
`start-tModLoaderServer.sh: line 55:  3315 Aborted`

Edit: turns out to be irrelevant with op's issue, sry

**Comment by SuspectWorkers** [comment]
You can run native , just compile dotnet for arm64.
It will work perfectly with better performance on native and no problem in world generation.

**Comment by Gimer-Studios** [comment]
HOW TO COMPILE FOR ARM 64.

**Comment by EamonnER** [comment]
@SuspectWorkers I've been losing hair trying to run a tModLoader dedicated server on arm64, and everywhere I've seen says it's not possible. 

Please can you share how exactly you've done it? I've got dotnet runtime installed, but I'm not exactly sure what to do with it. I tried running /server/tModLoader.dll with the same arguments that the management script uses, but that crashes too.

Any help would be useful! :smile: :sweat_smile:

**Comment by SuspectWorkers** [comment]
Hi! Find me on discord: wasteoflife. We can speak about that on next week.

**Comment by EamonnER** [comment]
Thanks! I have sent a friend request.

**Comment by DuckMan0111** [comment]
@EamonnER @SuspectWorkers Did you manage to solve this issue; i and many others have been trying to deal with this for a while and it would be quite appreciated to share the solution if it has been found.

**Comment by EamonnER** [comment]
@DuckMan0111 No, unfortunately not, my friend request was never accepted. @SuspectWorkers either forgot about it, or the discord username included the full stop at the end (which I haven't considered could be a possibility until now), or the username "wasteoflife" was a jab at me instead of being helpful haha

I never solved the problem, I just ended up getting lucky by finding an old x64 Windows PC with enough processing power to run the server. Sorry I couldn't help more. It is a shame because it's such common issue.

**Comment by SuspectWorkers** [comment]
@EamonnER 

I'm alive. Did you sent me the message in the discord ? We could try that at this Saturday/Sunday,  but write me please, I could easily forget it. Also need arm64 server for the operation. After we can host docker repository with fixes

**Comment by EamonnER** [comment]
@SuspectWorkers It's alright, I have a solution so I don't need help anymore. Thanks for offering though!

Maybe if you get in touch with @DuckMan0111 in case they still want help.

**Comment by SuspectWorkers** [comment]
@DuckMan0111 

Do you still have problem with Terraria arm64 ? The idea is in running dotnet and compiling server from arm64 , so you could run in natively , without emulating x64 environment.

I think I will write a guide here in a comment , but still I don't have an arm64 server to proof and check.

**Comment by DuckMan0111** [comment]
@SuspectWorkers we still have the problem, if you write a guide i will share it with some to try it out as currently I don't have the time to fix and try it myself.

Much appreciated.

**Comment by fariskazmi** [comment]
@SuspectWorkers I would also appreciate a guide :) Would love to get tModLoader working on ARM

**Comment by TheHenkGameKing** [comment]
@SuspectWorkers Hey, sorry for the necro, any news?

**Comment by Chicken-Bones** [comment]
See #2639
