### ISSUE TITLE
Upgrade to .NET 7

### ISSUE THREAD

**Issue by dominicwild** [bluemagic123/tModLoader#3515]
### Do you intend to personally contribute/program this feature?

No

### I would like to see this change made to improve my experience with

Gameplay as a Player

### Description

Instead of using .NET 6, upgrade to .NET 7

### What does this proposal attempt to solve or improve?

I cannot run the game on .NET 6 for some reason, it breaks. But it works on .NET 7. I'm not sure how hard it is to upgrade or the complication that would come with upgrading however.

### Which (other) solutions should be considered?

Or to even give the option to run tmodloader with tje .NET 7 runtime for those who cannot run it on .NET 6 for whatever reason.

**Comment by Mirsario** [comment]
We will switch to either .NET 7 or 8 only after January 1st of 2024, because .NET 7 dropped support for Windows 7, and the mentioned date is when the Steam client will do the same thing and also drop 8 and 8.1.

In the meanwhile, try installing latest .Net 6 into your system and running TML via 'dotnet ./tModLoader.dll' executed in cmd/shell within TML's folder.

**Comment by Chicken-Bones** [comment]
The option to run tModLoader with a .NET 7 runtime does exist, as far as I know. If you have one installed, you can run `dotnet tModLoader.dll` and it'll quite possibly just work

**Comment by dominicwild** [comment]
@Chicken-Bones I tried this by changing `tModLoader.runtimeconfig.json` to use 7.0.0. It did run, but with issues.

Comes out with this in the client.log
```
[19:31:38.183] [Main Thread/INFO] [tML]: Save Are Located At: G:\Users\Dominic\Documents\My Games\Terraria\tModLoader
[19:31:38.190] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.3.6+2022.09.47.50|stable|Stable|6f96b70fc9433c9b6ff1aa779fe2e75e7721d0e7|5249889221083030674 built 22/05/2023 03:44
[19:31:38.193] [Main Thread/INFO] [tML]: Log date: 05/06/2023
[19:31:38.193] [Main Thread/INFO] [tML]: Running on Windows (v6.1.7601.0) X64 NetCore 7.0.0
[19:31:38.194] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 7.0.0
[19:31:38.194] [Main Thread/INFO] [tML]: Executable: G:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.dll
[19:31:38.194] [Main Thread/INFO] [tML]: Working Directory: G:\Program Files (x86)\Steam\steamapps\common\tModLoader
[19:31:39.253] [Main Thread/DEBUG] [FNA]: Querying linked library versions...
[19:31:39.308] [Main Thread/DEBUG] [FNA]: SDL v2.24.0
[19:31:39.321] [Main Thread/DEBUG] [FNA]: FNA3D v22.8.0
[19:31:39.347] [Main Thread/DEBUG] [FNA]: FAudio v22.8.0
[19:31:39.616] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[19:31:39.677] [Main Thread/DEBUG] [TerrariaSteamClient]: Disabled. Launched outside steam client.
[19:31:40.400] [Main Thread/INFO] [FNA]: Controller 0: PowerA Fusion Pro 2 Controller, GUID: d6200140, Mapping: 03000000d62000000140000000007200,*,a:b0,b:b1,x:b2,y:b3,back:b6,guide:b10,start:b7,leftstick:b8,rightstick:b9,leftshoulder:b4,rightshoulder:b5,dpup:h0.1,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,platform:Windows
[19:31:40.974] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 835.5 MB available
[19:31:41.328] [Main Thread/INFO] [FNA]: FNA3D Driver: D3D11
[19:31:41.329] [Main Thread/INFO] [FNA]: D3D11 Adapter: NVIDIA GeForce RTX 2080 Ti
[19:31:41.334] [Main Thread/INFO] [FNA]: SetStringMarker not supported!
[19:31:41.405] [Main Thread/INFO] [tML]: Terraria Steam Install Location assumed to be: G:\Program Files (x86)\Steam\steamapps\common\Terraria
[19:31:41.876] [Main Thread/INFO] [tML]: Maximum Resolution is 2816 x 1536
[19:31:41.888] [Main Thread/DEBUG] [Terraria]: Device Created, Adapter: ROG PG278QR, DisplayMode: {{Width:2560 Height:1440 Format:Color}}, Profile: HiDef, Width: 800, Height: 720, Fullscreen: False, Display: \\.\DISPLAY1
[19:31:43.590] [Main Thread/DEBUG] [tML]: Native Resolve: tModLoader, Version=1.4.3.6, Culture=neutral, PublicKeyToken=null -> RzChromaSDK64.dll
[19:31:46.835] [9/DEBUG] [tML]: SSDP search line seperator: CRLF
[19:32:05.107] [.NET ThreadPool Worker/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.Core.LoaderUtils.ResetStaticMembers(Type type, Boolean recursive) in tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 21
   at Terraria.ModLoader.ItemLoader.ResizeArrays(Boolean unloading) in tModLoader\Terraria\ModLoader\ItemLoader.cs:line 90
   at Terraria.ModLoader.ModContent.ResizeArrays(Boolean unloading) in tModLoader\Terraria\ModLoader\ModContent.cs:line 523
   at Terraria.ModLoader.ModContent.Unload() in tModLoader\Terraria\ModLoader\ModContent.cs:line 486
   at Terraria.ModLoader.ModLoader.Mods_Unload() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 232
   at Terraria.ModLoader.ModLoader.Unload() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 200
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 113
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass48_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 105
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[19:32:05.109] [.NET ThreadPool Worker/FATAL] [tML]: One or more errors occured while unloading and tModLoader must be restarted to prevent further issues.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.ModLoader.Core.LoaderUtils.ResetStaticMembers(Type type, Boolean recursive) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Core\LoaderUtils.cs:line 21
   at Terraria.ModLoader.ItemLoader.ResizeArrays(Boolean unloading) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ItemLoader.cs:line 90
   at Terraria.ModLoader.ModContent.ResizeArrays(Boolean unloading) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 523
   at Terraria.ModLoader.ModContent.Unload() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModContent.cs:line 486
   at Terraria.ModLoader.ModLoader.Mods_Unload() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModLoader.cs:line 232
   at Terraria.ModLoader.ModLoader.Unload() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\ModLoader.cs:line 200
[19:32:07.981] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs" 
```

Surprisingly, if I run `dotnet tModLoader.dll" though it comes with the same error as 6.0.0 which is `Failed to create CoreCLR, HRESULT: 0x80004005` for me.

I try running it like with both the binaries and installing it locally.

**Comment by steviegt6** [comment]
Obligatory, but try entirely uninstalling all .NET runtimes and SDKs, delete the `dotnet` directories in both Program Files folders, and then reinstall. See if that helps.

**Comment by JavidPack** [comment]
Since progress is underway on porting to .net 8, we will close this issue.
