### ISSUE TITLE
Update FNA3D to latest

### ISSUE THREAD

**Issue by BAFAT76** [bluemagic123/tModLoader#3537]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

hello I can't launch it, each time i try it open cmd and after that an error, i don't have any mods on it.
please i really want to play on it again. 

### Log File

[16:32:45.049] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.4.9+2023.06.23.0|2022.09|preview|Preview|5952f4eb397287e8ac3f246f6945c1a5348de3ad|5249906444923372851 built 11/06/2023 03:10
[16:32:45.072] [Main Thread/INFO] [tML]: Log date: 12/06/2023
[16:32:45.072] [Main Thread/INFO] [tML]: Running on Windows (v10.0.19044.0) X64 NetCore 6.0.0
[16:32:45.073] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[16:32:45.073] [Main Thread/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.dll
[16:32:45.073] [Main Thread/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader
[16:32:45.074] [Main Thread/INFO] [tML]: Launch Parameters:  /gldevice:openGL
[16:32:45.076] [Main Thread/INFO] [tML]: Parsed Launch Parameters: 
[16:32:45.972] [Main Thread/INFO] [tML]: Saves Are Located At: C:\Users\Boby_le_bob\Documents\My Games\Terraria\tModLoader-preview
[16:32:46.053] [Main Thread/INFO] [tML]: Display DPI: Diagonal DPI is 96. Vertical DPI is 96. Horizontal DPI is 96
[16:32:46.053] [Main Thread/INFO] [tML]: High DPI Display detected: setting FNA to highdpi mode
[16:32:46.056] [Main Thread/DEBUG] [FNA]: Querying linked library versions...
[16:32:46.056] [Main Thread/DEBUG] [FNA]: SDL v2.24.0
[16:32:46.070] [Main Thread/DEBUG] [FNA]: FNA3D v22.8.0
[16:32:46.087] [Main Thread/DEBUG] [FNA]: FAudio v22.9.1
[16:32:47.095] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[16:32:47.181] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" tModLoader.dll -terrariasteamclient 1600
[16:32:47.621] [Main Thread/DEBUG] [TerrariaSteamClient]: Recv: init_success
[16:32:47.621] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: acknowledged
[16:32:48.322] [Main Thread/ERROR] [FNA]: No supported FNA3D driver found!
[16:32:48.572] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.InvalidOperationException: No supported FNA3D driver found!
   at Hook<System.Void Terraria.ModLoader.Engine.LoggingHooks::Hook_StackTrace_CaptureStackTrace(Terraria.ModLoader.Engine.LoggingHooks+orig_StackTrace_CaptureStackTrace,System.Diagnostics.StackTrace,System.Int32,System.Boolean,System.Exception)>(StackTrace , Int32 , Boolean , Exception )
   at SyncProxy<System.Void System.Diagnostics.StackTrace:CaptureStackTrace(System.Int32, System.Boolean, System.Exception)>(StackTrace , Int32 , Boolean , Exception )
   at System.Diagnostics.StackTrace..ctor(Boolean fNeedFileInfo)
   at Terraria.ModLoader.Logging.FirstChanceExceptionHandler(Object sender, FirstChanceExceptionEventArgs args) in tModLoader\Terraria\ModLoader\Logging.ExceptionHandling.cs:line 105
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_PrepareWindowAttributes()
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_PrepareWindowAttributes()
   at Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_PrepareWindowAttributes() in D:\a\tModLoader\tModLoader\FNA\src\Graphics\FNA3D_SafeAccess.cs:line 17
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow() in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 315
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 274
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 5432
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 262
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 245
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 220
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 71
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 57
   at System.Threading.Thread.StartCallback()

[16:32:48.575] [Main Thread/FATAL] [tML]: Main engine crash

Tip: This is likely a mod's fault. Disable mods one by one and check if the issue persists

System.InvalidOperationException: No supported FNA3D driver found!
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_PrepareWindowAttributes()
   at Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_PrepareWindowAttributes() in D:\a\tModLoader\tModLoader\FNA\src\Graphics\FNA3D_SafeAccess.cs:line 17
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow() in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 315
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 274
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 5432
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 262
[16:32:48.576] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

**Comment by LittleJay1985** [comment]
Your issue will be related to:
[16:32:45.074] [Main Thread/INFO] [tML]: Launch Parameters: /gldevice:openGL

Can you post your Launch.log ?

Do you have the file 'cli-argsConfig.txt' in your terraria folder?
Or have you set /gldevice:openGL in your Steam TModLoader Launch options? (Right click TModLoader in your library and select Properties. On the General Tab near the bottom will be your Launch options)

Edit: Just tested adding /gldevice:openGL to my Steam TModLoader Launch options and it causes this error. After removing again everything works fine.
Same thing if i added it to my cli-argsConfig.txt

**Comment by LittleJay1985** [comment]
This shouldn't happen due to FNAFixes.cs
I'll have a look into it and create a fix

https://github.com/tModLoader/tModLoader/labels/OS-Windows

**Comment by JavidPack** [comment]
/gldevice:openGL is also causing the error on my end. Just confirming the issue.

**Comment by LittleJay1985** [comment]
Looks to be a FNA3D issue. '/gldevice:openGL' won't work, as FNA3D does a SDL_strcmp instead of a SDL_strcasecmp. It will only work if its '/gldevice:OpenGL'

**Comment by LittleJay1985** [comment]
[Pull request sent https://github.com/FNA-XNA/FNA3D/pull/170
And Merged https://github.com/FNA-XNA/FNA3D/commit/d30147935f4b93f59e73952b713fc6116b263d6d](https://github.com/tModLoader/tModLoader/pull/3540#issuecomment-1588378921)

**Comment by BAFAT76** [comment]
Windows Version 10.0
Quick Edit Disabled
Verifying .NET....
Logging to C:/Program Files (x86)/Steam/steamapps/common/tModLoader/tModLoader-Logs/Launch.log
Verifying installation directory...
Fixing .NET SDL PATH issues
mv: can't rename 'C:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/Steamworks.NET': Permission denied
'C:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/Steamworks.NET' -> 'C:/Program Files (x86)/Steam/steamapps/common/tModLoader/Libraries/steamworks.net/Steamworks.NET'
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "C:/Program Files (x86)/Steam/steamapps/common/tModLoader/dotnet/6.0.0"
Loaded Custom Arguments: 
Launched Using Local Dotnet

**Comment by BAFAT76** [comment]
thx everyone it's work 🥳

**Comment by LittleJay1985** [comment]
I'm glad we could help.

**Comment by JavidPack** [comment]
Seems to be fixed now. Not sure if the fix is in 2023.9 or it'll show up in 2023.10, but it will be fixed. Anyone on 2023.8 should make sure to type out the `/gldevice:OpenGL` exactly in the meantime.
