### ISSUE TITLE
New download of tModLoader server on Linux fails to start

### ISSUE THREAD

**Issue by tedosuji** [bluemagic123/tModLoader#3573]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I apologize for the basic ticket, but I seem to be missing something obvious. Everytime I try to set up a new tModLoader server, it looks like it gets through all the configuration and downloading of dependencies, but fails right before actually starting. 

```[terraria@tmod ~]$ cd tmodloader/
[terraria@tmod tmodloader]$ ls
Content                  serverconfig.txt                  start-tModLoader.sh   tModLoader.runtimeconfig.dev.json
DedicatedServerUtils     start-tModLoader.bat              tMLMod.targets        tModLoader.runtimeconfig.json
dotnet                   start-tModLoader-FamilyShare.bat  tModLoader.deps.json  tModLoader.xml
LaunchUtils              start-tModLoader-FamilyShare.sh   tModLoader.dll        tModLoader.zip
Libraries                start-tModLoaderServer.bat        tModLoader-Logs       tModPorter
RecentGitHubCommits.txt  start-tModLoaderServer.sh         tModLoader.pdb
[terraria@tmod tmodloader]$ ./start-tModLoaderServer.sh
Use steam server (y/n): n
You are on platform: "Linux"
Verifying .NET....
This may take a few moments.
Logging to /home/terraria/tmodloader/tModLoader-Logs/Launch.log
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success!
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/home/terraria/tmodloader/dotnet/6.0.0"
cat: /home/terraria/tmodloader/cli-argsConfig.txt: No such file or directory
Loaded Custom Arguments:
Attempting Launch...
Launched Using Local Dotnet
./start-tModLoaderServer.sh: line 55:  8842 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args
[terraria@tmod tmodloader]$
```

### Log File

no client.log file is ever made

### Steps to reproduce

1. Follow normal guide for server setup
2. Download latest release zip
3. extract to a folder
4. chmod 770 on start-tModLoaderServer.sh
5. execute server.sh
6. error: line 55 Aborted (core dumped) (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args

### Expected Behavior

server menu should arrive up

### Actual Behavior

after "Launched Using Local Dotnet"
./start-tModLoaderServer.sh: line 55:  8842 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args

### Reproduction frequency

Every time

### Additional Information

```[terraria@tmod tmodloader]$ cat /etc/os-release
NAME="AlmaLinux"
VERSION="8.8 (Sapphire Caracal)"
ID="almalinux"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="AlmaLinux 8.8 (Sapphire Caracal)"
ANSI_COLOR="0;34"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:almalinux:almalinux:8::baseos"
HOME_URL="https://almalinux.org/"
DOCUMENTATION_URL="https://wiki.almalinux.org/"
BUG_REPORT_URL="https://bugs.almalinux.org/"

ALMALINUX_MANTISBT_PROJECT="AlmaLinux-8"
ALMALINUX_MANTISBT_PROJECT_VERSION="8.8"
REDHAT_SUPPORT_PRODUCT="AlmaLinux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.8"
[terraria@tmod tmodloader]$
```

**Comment by tedosuji** [comment]
Wish I had worked a little bit longer on this... found out there was 1 missing dependency from my box... 

I ran the script caller last command to see any new info, this is what came out

```
[terraria@tmod tModLoader]$ exec dotnet/6.0.0/dotnet tModLoader.dll
Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
   at System.Environment.FailFast(System.String)
   at System.Globalization.GlobalizationMode+Settings..cctor()
   at System.Globalization.CultureData.CreateCultureWithInvariantData()
   at System.Globalization.CultureData.get_Invariant()
   at System.Globalization.CultureInfo..cctor()
   at System.Globalization.CultureInfo.get_CurrentCulture()
   at System.Text.RegularExpressions.Regex.Init(System.String, System.Text.RegularExpressions.RegexOptions, System.TimeSpan, System.Globalization.CultureInfo)
   at System.Text.RegularExpressions.Regex..ctor(System.String, System.Globalization.CultureInfo)
   at System.Text.RegularExpressions.Regex..ctor(System.String)
   at Terraria.ModLoader.Logging..cctor()
   at Terraria.ModLoader.Logging.Init(LogFile)
   at Terraria.Program.LaunchGame(System.String[], Boolean)
   at MonoLaunch+<>c__DisplayClass1_0.<Main>b__0()
   at MonoLaunch.Main(System.String[])
Aborted (core dumped)
[root@tmod ~]#
```

Seems I was missing libicu... so I ran `yum install libicu` and re-ran the server start script.... all is well. Apologies for the ticket, this can be closed

**Comment by keryul** [comment]
> Wish I had worked a little bit longer on this... found out there was 1 missing dependency from my box...
> 
> I ran the script caller last command to see any new info, this is what came out
> 
> ```
> [terraria@tmod tModLoader]$ exec dotnet/6.0.0/dotnet tModLoader.dll
> Process terminated. Couldn't find a valid ICU package installed on the system. Please install libicu using your package manager and try again. Alternatively you can set the configuration flag System.Globalization.Invariant to true if you want to run with no globalization support. Please see https://aka.ms/dotnet-missing-libicu for more information.
>    at System.Environment.FailFast(System.String)
>    at System.Globalization.GlobalizationMode+Settings..cctor()
>    at System.Globalization.CultureData.CreateCultureWithInvariantData()
>    at System.Globalization.CultureData.get_Invariant()
>    at System.Globalization.CultureInfo..cctor()
>    at System.Globalization.CultureInfo.get_CurrentCulture()
>    at System.Text.RegularExpressions.Regex.Init(System.String, System.Text.RegularExpressions.RegexOptions, System.TimeSpan, System.Globalization.CultureInfo)
>    at System.Text.RegularExpressions.Regex..ctor(System.String, System.Globalization.CultureInfo)
>    at System.Text.RegularExpressions.Regex..ctor(System.String)
>    at Terraria.ModLoader.Logging..cctor()
>    at Terraria.ModLoader.Logging.Init(LogFile)
>    at Terraria.Program.LaunchGame(System.String[], Boolean)
>    at MonoLaunch+<>c__DisplayClass1_0.<Main>b__0()
>    at MonoLaunch.Main(System.String[])
> Aborted (core dumped)
> [root@tmod ~]#
> ```
> 
> Seems I was missing libicu... so I ran `yum install libicu` and re-ran the server start script.... all is well. Apologies for the ticket, this can be closed

Hi tedosuji, I have the same error
```
./start-tModLoaderServer.sh: line 55:  8842 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args
```
I run the same command(`exec dotnet/6.0.0/dotnet tModLoader.dll`) but return a completely different error
```
[18:41:55.448] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.4.9+2023.06.25.31|2023.06|stable|Stable|1cf5af1a24a961fcbe0d1d7fc31dcda160496504|5249959922336091465 built 08/12/2023 06:39
[18:41:55.457] [Main Thread/INFO] [tML]: Log date: 08/27/2023
[18:41:55.459] [Main Thread/INFO] [tML]: Running on Linux (v5.4.0.153) X64 NetCore 6.0.0
[18:41:55.459] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[18:41:55.459] [Main Thread/INFO] [tML]: Executable: /root/tModLoader/tModLoader.dll
[18:41:55.460] [Main Thread/INFO] [tML]: Working Directory: /root/tModLoader
[18:41:55.672] [Main Thread/INFO] [tML]: No config.json found at /root/.local/share/Terraria/tModLoader/config.json
Assuming nothing to port
[18:41:55.672] [Main Thread/INFO] [tML]: No config.json found at /root/.local/share/Terraria/tModLoader-preview/config.json
Assuming nothing to port
[18:41:55.672] [Main Thread/INFO] [tML]: Saves Are Located At: /root/.local/share/Terraria/tModLoader
[18:41:55.675] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null -> SDL2
[18:41:55.675] [Main Thread/DEBUG] [tML]: 	attempting load /root/tModLoader/Libraries/Native/Linux/libSDL2-2.0.so.0
[18:41:55.675] [Main Thread/DEBUG] [tML]: 	success
[18:41:55.677] [Main Thread/INFO] [tML]: Display DPI: Diagonal DPI is 0. Vertical DPI is 0. Horizontal DPI is 0
[18:41:55.678] [Main Thread/DEBUG] [FNA]: Querying linked library versions...
[18:41:55.678] [Main Thread/DEBUG] [FNA]: SDL v2.24.0
[18:41:55.678] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null -> FNA3D
[18:41:55.678] [Main Thread/DEBUG] [tML]: 	attempting load /root/tModLoader/Libraries/Native/Linux/libFNA3D.so.0
[18:41:55.679] [Main Thread/DEBUG] [tML]: 	success
[18:41:55.679] [Main Thread/DEBUG] [FNA]: FNA3D v22.8.0
[18:41:55.679] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null -> FAudio
[18:41:55.679] [Main Thread/DEBUG] [tML]: 	attempting load /root/tModLoader/Libraries/Native/Linux/libFAudio.so.0
[18:41:55.679] [Main Thread/DEBUG] [tML]: 	success
[18:41:55.679] [Main Thread/DEBUG] [FNA]: FAudio v22.8.0
[18:41:55.833] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_v1.4.4.9.exe not found nearby
[18:41:55.838] [Main Thread/DEBUG] [TerrariaSteamClient]: Disabled. Launched outside steam client.
[18:41:55.847] [Main Thread/DEBUG] [tML]: ILHook Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) added by tModLoader
[18:41:55.886] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit(LaunchParameters args)
   at Microsoft.Xna.Framework.FNAPlatform..cctor()
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode)
   at Terraria.Main..ctor()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__0()
   at Terraria.MonoLaunch.Main(String[] args)

[18:41:55.887] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.TypeInitializationException: The type initializer for 'Microsoft.Xna.Framework.FNAPlatform' threw an exception.
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode)
   at Terraria.Main..ctor()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__0()
   at Terraria.MonoLaunch.Main(String[] args)

[18:41:55.887] [Main Thread/FATAL] [tML]: Main engine crash

Tip: Restart the game. If this issue persists, try uninstalling Terraria completely, then reinstalling through Steam, and then reinstalling tModLoader

System.TypeInitializationException: The type initializer for 'Microsoft.Xna.Framework.FNAPlatform' threw an exception.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit(LaunchParameters args) in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 223
   at Microsoft.Xna.Framework.FNAPlatform..cctor() in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\FNAPlatform.cs:line 150
   --- End of inner exception stack trace ---
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 264
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 5436
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 257

```

Is there any way to fix this?
