### ISSUE TITLE
Upon Launching the game, the game crashes, giving me the following client.log file. Identical to issue #3611

### ISSUE THREAD

**Issue by XFatalisX** [bluemagic123/tModLoader#3610]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

**Comment by XFatalisX** [comment]
[10:01:54.095] [Main Thread/INFO] [tML]: Cloning current Stable files to 1.4.3 save folder. Save Folder is Cloud? False
[10:01:54.453] [Main Thread/FATAL] [tML]: Failed to handle save data

tModLoader.OneDriveHint

System.IO.IOException: The cloud file provider is not running. : 'C:\Users\mborr\OneDrive\Documents\My Games\Terraria\tModLoader-1.4.3\Players\Backups\2022-09-02--D.zip'
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.File.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at Terraria.Utilities.FileUtilities.CopyExtended(String source, String destination, Boolean cloud, Boolean overwriteAlways, Boolean overwriteOld) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Utilities\FileUtilities.cs:line 46
   at Terraria.Utilities.FileUtilities.CopyFolderEXT(String sourcePath, String destinationPath, Boolean isCloud, Regex excludeFilter, Boolean overwriteAlways, Boolean overwriteOld) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Utilities\FileUtilities.cs:line 192
   at Terraria.Program.Port143FilesFromStable(String superSavePath, Boolean isCloud) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 115
   at Terraria.Program.PortFilesMaster(String savePath, Boolean isCloud) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 124
   at Terraria.Program.SetSavePath() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 137
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 180

**Comment by Solxanich** [comment]
https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#save-data-file-issues

Please take a look at the information there, that covers how to deal with onedrive issues

**Comment by XFatalisX** [comment]
> https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#save-data-file-issues
> 
> Please take a look at the information there, that covers how to deal with onedrive issues

**Comment by XFatalisX** [comment]
appreciate the help
