### ISSUE TITLE
Config directory rename didn't bring `enabled.json` or world backups across

### ISSUE THREAD

**Issue by Terrance** [bluemagic123/tModLoader#3621]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

After updating to a "legacy" branded build, some files in the previous data directory `~/.local/share/Terraria/tModLoader` (namely `enabled.json` and `Worlds/Backups/*.zip`) weren't copied to the new/legacy location `~/.local/share/Terraria/tModLoader1.4.3` on server startup.

### Log File

No client log as this affects server startup.

<details>
<summary>server.log</summary>

```
[18:51:05.042] [Main Thread/INFO] [tML]: Save Are Located At: /home/user/.local/share/Terraria/tModLoader-1.4.3
[18:51:05.050] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.3.6+2022.09.47.74|2022.09|1.4.3-legacy|Stable|aae43b1dcf2d8fed4bb1031d07bf745f00097582|5249931412638883089 built 09/07/2023 23:43
[18:51:05.051] [Main Thread/INFO] [tML]: Log date: 11/07/2023
[18:51:05.052] [Main Thread/INFO] [tML]: Running on Linux (v5.4.0.150) X64 NetCore 6.0.0
[18:51:05.052] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[18:51:05.052] [Main Thread/INFO] [tML]: Executable: /home/user/Terraria/Servers/tModLoader/tModLoader.dll
[18:51:05.052] [Main Thread/INFO] [tML]: Working Directory: /home/user/Terraria/Servers/tModLoader
[18:51:05.052] [Main Thread/INFO] [tML]: Launch Parameters:  -server -config /home/user/Terraria/Data/World/serverconfig.txt
[18:51:05.054] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config /home/user/Terraria/Data/World/serverconfig.txt
[18:51:05.640] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: Terraria.exe or Terraria_1.4.4.9.exe not found nearby
[18:51:05.657] [Main Thread/DEBUG] [tML]: Hook IL.Ionic.Zip.ZipEntry::ValidateOutput(string, Stream, out string) modified by tModLoader
[18:51:05.784] [Main Thread/WARN] [tML]: Silently Caught Exception:
System.ComponentModel.Win32Exception: Permission denied
   at System.Diagnostics.Process.set_PriorityClassCore(ProcessPriorityClass value)
   at System.Diagnostics.Process.set_PriorityClass(ProcessPriorityClass value)
   at Terraria.Initializers.LaunchInitializer.LoadServerParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 117
   at Terraria.Initializers.LaunchInitializer.LoadParameters(Main game) in tModLoader\Terraria\Initializers\LaunchInitializer.cs:line 18
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 224
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 188
   at MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
   at MonoLaunch.Main(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 64

[18:51:07.191] [Main Thread/DEBUG] [tML]: Network compatibility version is 2022.9.47
[18:51:10.595] [Main Thread/WARN] [tML]: Did not find enabled.json file
[18:51:10.596] [Main Thread/INFO] [tML]: Finding Mods...
[18:51:10.608] [Main Thread/INFO] [tML]: Constructing Mods...
[18:51:10.705] [Main Thread/INFO] [tML]: Adding Content: ModLoader (tModLoader) v2022.9.47.74
[18:51:10.806] [Main Thread/INFO] [tML]: Resizing...
[18:51:10.936] [Main Thread/INFO] [tML]: Configuring Content: ModLoader (tModLoader) v2022.9.47.74
[18:51:11.088] [Main Thread/INFO] [tML]: Finalizing Content: ModLoader (tModLoader) v2022.9.47.74
[18:51:11.145] [Main Thread/INFO] [tML]: RAM usage: 295.3 MB
[18:51:11.205] [Main Thread/INFO] [tML]: Adding Recipes...
[18:51:11.317] [.NET ThreadPool Worker/INFO] [Terraria]: Loading World: World, IsCloud=False, Size=6400x1800
[18:51:11.466] [.NET ThreadPool Worker/INFO] [StatusText]: Loading world data
[18:51:12.828] [.NET ThreadPool Worker/INFO] [StatusText]: Settling liquids
[18:51:13.550] [Main Thread/INFO] [Terraria]: Running one update...
[18:51:13.550] [Main Thread/INFO] [tML]: Server starting with AllowVanillaClients set to False
[18:51:14.228] [Main Thread/INFO] [Terraria]: Listening on port 7778
[18:51:14.234] [Server Input Thread/WARN] [tML]: Console input not connected, ignoring...
[18:51:14.284] [.NET ThreadPool Worker/DEBUG] [tML]: SSDP search line seperator: CRLF
[18:53:53.405] [.NET Signal Handler/INFO] [tML]: Signal SIGTERM, Closing Server...
[18:53:53.405] [.NET Signal Handler/INFO] [tML]: Signal SIGTERM, Closing Server...
[18:53:53.982] [Main Thread/INFO] [StatusText]: Saving world data
[18:53:54.337] [Main Thread/INFO] [StatusText]: Validating world save
```
</details>

### Steps to reproduce

1. Update tModLoader via SteamCMD (I'm assuming from a 1.4.3 to a 1.4.3-legacy build)
    ```
    ~/Steam/steamcmd.sh \
      +force_install_dir ~/Terraria/Servers/tModLoader \
      +login "$STEAM_USER" \
      +app_update 1281930 \
      +quit
    ```
2. Start the server

### Expected Behavior

Existing mods configured before the update to continue working on the server.

### Actual Behavior

No mods were loaded.

After spotting `Did not find enabled.json file` in the log, and trying to link the file in other locations in case it now wanted it elsewhere, I eventually found that the config directory was quietly renamed from tModLoader to tModLoader-1.4.3 (presumably in preparation for 1.4.4).

It looks like some files were copied to the new location (including mod data in `aA Mods`), but not the `enabled.json` file listing my mods, nor backups under `Worlds/Backups`.

### Additional Information

It would be useful to show some kind of warning/hint in the logs that a) the path has been changed, and b) that 1.4.4 is incoming (as I later found the game itself now shows).  It wasn't until I started listing parent directories for other signs of changes that I noticed there were two data directories.

**Comment by JavidPack** [comment]
That is strange, I was just looking at the code and it should only be filtering out the "Workshop" and "ModSources" folders. Do you have the log file from when the migration actually happened (There is an Old folder in the logs folder with older logs)? The log you posted seems to be a later log after the fact.

**Comment by Terrance** [comment]
Hm, that should be the right log, it came from `Old/2023-07-11-1.zip` (i.e. the first startup today after doing the update).

I restarted a few more times whilst tinkering but the logs all appear to be the same, both for the initial migration and the subsequent startups -- no sign of any migration log lines.

**Comment by JavidPack** [comment]
Well, we are looking into making it more reliable, in the meantime if anyone has this issue they can manually copy the files over from the old folder to the new.
