### ISSUE TITLE
[Docker] Server does not start

### ISSUE THREAD

**Issue by PassiveLemon** [bluemagic123/tModLoader#3625]
### Version

Latest 1.4.4-preview

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

When starting the 1.4.4 version of the server in my Docker container, it does not start successfully. It appears to happen with all of the 1.4.4 previews.

### Log File

[server.log](https://github.com/tModLoader/tModLoader/files/12041636/server.log)

```
[16:20:01.153] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.IO.DirectoryNotFoundException: Could not find a part of the path '/tmodloader/server/Libraries/Native/Linux/*/tmp'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
```
This path just looks weird.

### Steps to reproduce

My Docker container here: https://github.com/PassiveLemon/tmodloader1.4-docker/tree/2.0-Development
1. Start the container in a way which will use a 1.4.4 version. (Files are fetched automatically)
2. Observe error in console

### Expected Behavior

Like with the 1.4.3 versions, it should successfully start the server.

### Actual Behavior

It fails from a missing path.

### Reproduction frequency

Every single time. It appears to happen with all of the 1.4.4 previews.

### Additional Information

I tried creating that weird path within my entrypoint script but that does not seem to have done anything.

I also can't test client functionality because my game doesn't start either for a different reason.

**Comment by Chicken-Bones** [comment]
Hi, can you run it successfully outside of docker? Perhaps it's a permissions issue in the tML working directory.

**Comment by PassiveLemon** [comment]
I'm trying to get it to work outside of Docker but I encounter way more issues. First off is it complaining about cli-argsConfig.txt not being in its install directory. I made that file and now the dotnets/6.0.0/dotnet binary can not be executed: `required file not found` when it is present at that location and has execution permission.

**Comment by Chicken-Bones** [comment]
It seems like you're the first person to try the 1.4.4.9 preview server on Linux, this is valuable troubleshooting for us. Please come to the Discord and send me a direct message.

**Comment by PassiveLemon** [comment]
Solution: Giving the container 755 privileges for the TML installl directory allows it to execute the dotnet binary, and therefore continue launching the server.

**Comment by PassiveLemon** [comment]
This patch doesn't seem to work anymore? Even with the version where I tested that it worked. It's possible I accidentally tested this with a 2022 version and not the 2023 where the issue was present.

**Comment by PassiveLemon** [comment]
Tried a bunch of different permissions for various folders, and I'm fairly certain at this point that it isn't a permission issue anymore. I'm going to assume that I forgot to set it to download the 1.4.4+ version so I wrongly thought I solved it.

**Comment by Chicken-Bones** [comment]
You may wish to test/compare with the official tML docker files. They are in `DedicatedServerUtils/Docker` in the tML install dir. Take a look at the `DedicatedServerUtils/README.md` too

**Comment by Mego** [comment]
This also happens with the bundled docker setup in tModLoader when downloaded from Steam. Full stacktrace:

```
2023-08-03 12:09:15 System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/tml/tModLoader/Libraries/Native/Linux/*/tmp'.
2023-08-03 12:09:15    at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
2023-08-03 12:09:15    at System.IO.Enumeration.FileSystemEnumerator`1.Init()
2023-08-03 12:09:15    at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
2023-08-03 12:09:15    at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
2023-08-03 12:09:15    at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
2023-08-03 12:09:15    at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
2023-08-03 12:09:15    at System.IO.Directory.GetFiles(String path, String searchPattern, EnumerationOptions enumerationOptions)
2023-08-03 12:09:15    at System.IO.Directory.GetFiles(String path, String searchPattern, SearchOption searchOption)
2023-08-03 12:09:15    at Terraria.MonoLaunch.ResolveNativeLibrary(Assembly assembly, String name) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 96
2023-08-03 12:09:15    at System.Runtime.Loader.AssemblyLoadContext.GetResolvedUnmanagedDll(Assembly assembly, String unmanagedDllName)
2023-08-03 12:09:15    at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDllUsingEvent(String unmanagedDllName, Assembly assembly, IntPtr gchManagedAssemblyLoadContext)
2023-08-03 12:09:15    at System.Runtime.InteropServices.NativeLibrary.LoadByName(String libraryName, QCallAssembly callingAssembly, Boolean hasDllImportSearchPathFlag, UInt32 dllImportSearchPathFlag, Boolean throwOnError)
2023-08-03 12:09:15    at System.Runtime.InteropServices.NativeLibrary.LoadLibraryByName(String libraryName, Assembly assembly, Nullable`1 searchPath, Boolean throwOnError)
2023-08-03 12:09:15    at System.Runtime.InteropServices.NativeLibrary.Load(String libraryName, Assembly assembly, Nullable`1 searchPath)
2023-08-03 12:09:15    at MonoMod.Utils.DynDll.OpenLibrary(String name, Boolean skipMapping) in /_/src/MonoMod.Utils/DynDll.CoreNativeLibrary.cs:line 18
2023-08-03 12:09:15    at MonoMod.Core.Platforms.Systems.PosixExceptionHelper.CreateHelper(IArchitecture arch, String filename) in /_/src/MonoMod.Core/Platforms/Systems/PosixExceptionHelper.cs:line 23
2023-08-03 12:09:15    at MonoMod.Core.Platforms.Systems.LinuxSystem.CreateNativeExceptionHelper() in /_/src/MonoMod.Core/Platforms/Systems/LinuxSystem.cs:line 322
2023-08-03 12:09:15    at MonoMod.Core.Platforms.Systems.LinuxSystem.get_NativeExceptionHelper() in /_/src/MonoMod.Core/Platforms/Systems/LinuxSystem.cs:line 280
2023-08-03 12:09:15    at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.get_NativeExceptionHelper() in /_/src/MonoMod.Core/Platforms/Runtimes/CoreBaseRuntime.cs:line 99
2023-08-03 12:09:15    at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.EHManagedToNative(IntPtr target, IDisposable& handle) in /_/src/MonoMod.Core/Platforms/Runtimes/CoreBaseRuntime.cs:line 108
2023-08-03 12:09:15    at MonoMod.Core.Platforms.Runtimes.Core21Runtime.InstallJitHook(IntPtr jit) in /_/src/MonoMod.Core/Platforms/Runtimes/Core21Runtime.cs:line 87
2023-08-03 12:09:15    at MonoMod.Core.Platforms.Runtimes.CoreBaseRuntime.MonoMod.Core.Utils.IInitialize.Initialize() in /_/src/MonoMod.Core/Platforms/Runtimes/CoreBaseRuntime.cs:line 66
2023-08-03 12:09:15    at MonoMod.Core.Platforms.PlatformTriple.InitIfNeeded(Object obj) in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 195
2023-08-03 12:09:15    at MonoMod.Core.Platforms.PlatformTriple..ctor(IArchitecture architecture, ISystem system, IRuntime runtime) in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 184
2023-08-03 12:09:15    at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 119
2023-08-03 12:09:15    at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in /_/src/MonoMod.Utils/Helpers.cs:line 167
2023-08-03 12:09:15    at MonoMod.Core.Platforms.PlatformTriple.get_Current() in /_/src/MonoMod.Core/Platforms/PlatformTriple.cs:line 113
2023-08-03 12:09:15    at MonoMod.Core.DetourFactory.CreateDefaultFactory() in /_/src/MonoMod.Core/IDetourFactory.cs:line 80
2023-08-03 12:09:15    at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in /_/src/MonoMod.Utils/Helpers.cs:line 158
2023-08-03 12:09:15    at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in /_/src/MonoMod.RuntimeDetour/DetourContext.cs:line 103
2023-08-03 12:09:15    at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 409
2023-08-03 12:09:15    at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 377
2023-08-03 12:09:15    at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in /_/src/MonoMod.RuntimeDetour/Hook.cs:line 319
2023-08-03 12:09:15    at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 73
2023-08-03 12:09:15    at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 17
2023-08-03 12:09:15    at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 92
2023-08-03 12:09:15    at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 277```

**Comment by shinysocks** [comment]
I'm facing the same error as @Mego  using the currently published Dockerfile

**Comment by benjamin051000** [comment]
Experiencing the same issue. Any updates?

**Comment by shinysocks** [comment]
![image](https://github.com/tModLoader/tModLoader/assets/91911303/1b681a6e-df50-485b-a78a-294f5d532941)
this might be relevant...

**Comment by benjamin051000** [comment]
Not available. Sad. Hopefully it gets fixed soon

**Comment by Chicken-Bones** [comment]
There is currently an issue where MonoMod doesn't work on MUSL/Alpine, we'll be fixing it in upcoming releases. For now you can run a ubuntu based container.

**Comment by GedasFX** [comment]
Any ideas on how to change it to ubuntu container? I was trying to get it to work, and this is the Dockerfile I was able to get it at least build:
```Dockerfile
FROM steamcmd/steamcmd:ubuntu

# Install prerequisites
RUN apt update \
  && apt install -y bash curl unzip
#tmux libstdc++ libgcc icu-libs
 # && rm -rf /var/cache/apk/*

# Fix 32 and 64 bit library conflicts
#RUN mkdir /steamlib \
# && mv /lib/libstdc++.so.6 /steamlib \
# && mv /lib/libgcc_s.so.1 /steamlib
#ENV LD_LIBRARY_PATH /steamlib

# Create tModLoader user and drop root permissions
ARG UID
ARG GID
RUN addgroup --gid $GID tml \
 && adduser tml --uid $UID --gid $GID
USER tml
ENV USER tml
ENV HOME /home/tml
WORKDIR $HOME

# Update SteamCMD and verify latest version
RUN steamcmd +quit

RUN curl -O https://raw.githubusercontent.com/tModLoader/tModLoader/1.4.4/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils/manage-tModLoaderServer.sh \
 && chmod u+x manage-tModLoaderServer.sh \
 && ./manage-tModLoaderServer.sh install --github --skip-mods \
 && chmod u+x $HOME/tModLoader/start-tModLoaderServer.sh

EXPOSE 7777

# RUN mkdir -p /home/tml/tModLoader && ln -s /terraria/dotnet /home/tml/tModLoader/dotnet

ENTRYPOINT [ "/bin/bash", "-c", "./manage-tModLoaderServer.sh docker --folder /terraria" ]
```

but now I end up with the following error:
```bash
... ommited dotnet 6.0.0 install and such ...
tml-tml-1  | Attempting Launch...
tml-tml-1  | Launched Using Local Dotnet
tml-tml-1  | ./start-tModLoaderServer.sh: line 55:   109 Aborted                 (core dumped) ./LaunchUtils/ScriptCaller.sh $launch_args
tml-tml-1 exited with code 134
```

Before I continued debugging I was thinking of checking back here to see if someone could suggest any leads 😅

**Comment by GedasFX** [comment]
I am almost certain its because I didn't download all dependencies, but some of the dependencies just did not exist in apt, so I left them out.

**Comment by PassiveLemon** [comment]
> There is currently an issue where MonoMod doesn't work on MUSL/Alpine, we'll be fixing it in upcoming releases. For now you can run a ubuntu based container.

Thanks for the info, I guess I'll switch my Docker system to Ubuntu until this can get fixed. I won't close this for issue tracking purposes

**Comment by Chicken-Bones** [comment]
The fix for this is now available on preview. I'm not sure if there's a way to back-port this fix to stable in an experimental manner

**Comment by jvanvalkenburgh** [comment]
I am still having this issue with both Stable and preview releases. Any suggested steps?
