### ISSUE TITLE
Index was outside the bounds of the array. (Fargo's souls mod)

### ISSUE THREAD

**Issue by lfjg** [bluemagic123/tModLoader#3627]
### Version

Latest 1.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

As the title suggests, the error 'Index was outside the bounds of the array' occurs. As a result of checking all mods, it occurs when Fargo's souls mod is applied. This error occurred when creating the map. Can you tell me if this mod is not available now or if the problem is somewhere else?

The mod I'm using is: 
1 Replace String
2 Boss Checklist
3 Fargo's Mutant Mod
4 Fargo's Music Mod
5 Fargo's Souls Mod
6 Lights and Shadows
7 Recipe Browser

### Log File

Index was outside the bounds of the array. (see server.log for full trace)
ERROR: A problem was encountered during world generation
Smooth World
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.Player.GetModPlayer[T](T baseInstance) in tModLoader\Terraria\Player.TML.cs:line 41
   at FargowiltasSouls.Projectiles.FargoSoulsGlobalProjectile.OnSpawn(Projectile projectile, IEntitySource source) in FargowiltasSouls\Projectiles\FargoSoulsGlobalProjectile.cs:line 184
   at Terraria.ModLoader.ProjectileLoader.OnSpawn(Projectile projectile, IEntitySource source) in tModLoader\Terraria\ModLoader\ProjectileLoader.cs:line 127
   at Terraria.Projectile.NewProjectile(IEntitySource spawnSource, Single X, Single Y, Single SpeedX, Single SpeedY, Int32 Type, Int32 Damage, Single KnockBack, Int32 Owner, Single ai0, Single ai1) in tModLoader\Terraria\Projectile.cs:line 8462
   at Terraria.WorldGen.KillTile(Int32 i, Int32 j, Boolean fail, Boolean effectOnly, Boolean noItem) in tModLoader\Terraria\WorldGen.cs:line 41222
   at Terraria.WorldGen.<>c.<GenerateWorld>b__362_55(GenerationProgress progress, GameConfiguration passConfig) in tModLoader\Terraria\WorldGen.cs:line 8820
   at Terraria.WorldBuilding.WorldGenerator.GenerateWorld(GenerationProgress progress) in tModLoader\Terraria\WorldBuilding\WorldGenerator.cs:line 30

**Comment by direwolf420** [comment]
This has to do with certain vanilla tiles potentially spawning projectiles as they are broken during worldgen. Not sure who to blame here. Modders for not concidering this a possibility, or TML for not safeguarding this.

**Comment by Chicken-Bones** [comment]
Seems like tML could add a 'no projectile spawn' safeguard during world-gen

**Comment by lugia19** [comment]
I've run into this exact bug as well - the kicker is that it appears to be platform-specific.
Only fargo's souls (and mutant) are enabled.

Windows, works fine.
Debian VM (not using docker, but the management script), crash.
100% reproducible.

Attached is my [server.log](https://github.com/tModLoader/tModLoader/files/12787138/server.log).

**Comment by Chicken-Bones** [comment]
Fixed in 5bbf98c will bring to stable soon
