### ISSUE TITLE
an error occurred while loading

### ISSUE THREAD

**Issue by Koob14** [bluemagic123/tModLoader#3648]
### Version

Latest 1.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

this keeps popping up as soon as i open tmod, weird part is that i dont even have any mods! ive uninstalled both tmod and terraria but it still does this, any ideas on how to fix?

### Log File

[21:35:07.215] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading 
The mod responsible is unknown and tModLoader must be restarted.
System.UnauthorizedAccessException: Access to the path 'C:\Users\koobm\OneDrive\Documents\My Games\Terraria\tModLoader-1.4.3\LastLaunchedMods.txt' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Terraria.ModLoader.Core.ModOrganizer.SaveLastLaunchedMods() in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 265
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 367
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 126
[21:35:07.656] [.NET ThreadPool Worker/INFO] [tML]: Unloading: ModLoader (tModLoader) v2022.9.47.76
[21:35:08.405] [.NET ThreadPool Worker/INFO] [tML]: Cancelling loading...
[21:35:08.405] [.NET ThreadPool Worker/INFO] [tML]: Constructing Mods...
[21:35:08.485] [.NET ThreadPool Worker/INFO] [tML]: Adding Content: ModLoader (tModLoader) v2022.9.47.76
[21:35:08.575] [.NET ThreadPool Worker/INFO] [tML]: Resizing...
[21:35:08.686] [.NET ThreadPool Worker/INFO] [tML]: Configuring Content: ModLoader (tModLoader) v2022.9.47.76
[21:35:08.807] [.NET ThreadPool Worker/INFO] [tML]: Finalizing Content: ModLoader (tModLoader) v2022.9.47.76
[21:35:08.869] [.NET ThreadPool Worker/INFO] [tML]: RAM usage: 1.0 GB
[21:35:08.907] [.NET ThreadPool Worker/INFO] [tML]: Adding Recipes...
[21:35:08.977] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading 
The mod responsible is unknown and tModLoader must be restarted.
System.UnauthorizedAccessException: Access to the path 'C:\Users\koobm\OneDrive\Documents\My Games\Terraria\tModLoader-1.4.3\LastLaunchedMods.txt' is denied.
   at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize)
   at System.IO.Strategies.FileStreamHelpers.ChooseStrategy(FileStream fileStream, String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, Int64 preallocationSize)
   at System.IO.StreamWriter.ValidateArgsAndOpenPath(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.File.WriteAllText(String path, String contents)
   at Terraria.ModLoader.Core.ModOrganizer.SaveLastLaunchedMods() in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 265
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 367
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 126
[21:35:09.701] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs" 

### Reproduction frequency

everytime i open tmod

### Additional Information

i have NO mods INSTALLED

**Comment by direwolf420** [comment]
Try this fix on the FAQ: <https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#systemunauthorizedaccessexception-access-to-the-path-is-denied>
