### ISSUE TITLE
main engine crash

### ISSUE THREAD

**Issue by aaa0770** [bluemagic123/tModLoader#3696]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

main engine crashed 
![스크린샷 2023-08-06 130343](https://github.com/tModLoader/tModLoader/assets/141538522/fb190903-7b40-49f7-9ff1-64d1bc114d7c)
![스크린샷 2023-08-06 130432](https://github.com/tModLoader/tModLoader/assets/141538522/7c58b2e1-4561-4137-92b6-b6e0e5c08481)

### Log File

[12:51:19.068] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.4.9+2023.06.25.28|2023.06|stable|Stable|60f361fa5c22801c7b331d06d8b0796a9c5d59ce|5249952896631181120 built 2023-08-04 04:30
[12:51:19.073] [Main Thread/INFO] [tML]: Log date: 2023-08-06
[12:51:19.073] [Main Thread/INFO] [tML]: Running on Windows (v10.0.22621.0) X64 NetCore 6.0.0
[12:51:19.073] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[12:51:19.073] [Main Thread/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.dll
[12:51:19.073] [Main Thread/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader
[12:51:19.353] [Main Thread/INFO] [tML]: Saves Are Located At: C:\Users\My\Documents\My Games\Terraria\tModLoader
[12:51:19.354] [Main Thread/INFO] [tML]: Controlled Folder Access feature detected. If game fails to launch make sure to add "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" to the "Allow an app through Controlled folder access" menu found in the "Ransomware protection" menu.
[12:51:19.359] [Main Thread/INFO] [tML]: Display DPI: Diagonal DPI is 120. Vertical DPI is 120. Horizontal DPI is 120
[12:51:19.359] [Main Thread/INFO] [tML]: High DPI Display detected: setting FNA to highdpi mode
[12:51:19.360] [Main Thread/DEBUG] [FNA]: Querying linked library versions...
[12:51:19.360] [Main Thread/DEBUG] [FNA]: SDL v2.24.0
[12:51:19.361] [Main Thread/DEBUG] [FNA]: FNA3D v22.8.0
[12:51:19.361] [Main Thread/DEBUG] [FNA]: FAudio v22.9.1
[12:51:19.497] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[12:51:19.502] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" tModLoader.dll -terrariasteamclient 1672
[12:51:19.816] [Main Thread/DEBUG] [TerrariaSteamClient]: Recv: init_success
[12:51:19.816] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: acknowledged
[12:51:19.905] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.IO.FileNotFoundException: Could not find file 'C:\Users\My\Documents\My Games\Terraria\tModLoader'.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Terraria.ModLoader.Engine.FolderShortcutSupport.CreateLogsFolderShortcut() in tModLoader\Terraria\ModLoader\Engine\FolderShortcutSupport.cs:line 43
   at Terraria.ModLoader.Engine.FolderShortcutSupport.UpdateFolderShortcuts() in tModLoader\Terraria\ModLoader\Engine\FolderShortcutSupport.cs:line 17
   at Terraria.ModLoader.ModLoader.EngineInit() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 92
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 255
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 215
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 71
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 57
   at System.Threading.Thread.StartCallback()

[12:51:19.906] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "explorer.exe" "https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#controlled-folder-access"
[12:51:19.909] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.Exception: 

Controlled Folder Access feature detected.

If game fails to launch make sure to add "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" to the "Allow an app through Controlled folder access" menu found in the "Ransomware protection" menu.

More instructions can be found in the website that just opened.

   at Terraria.ModLoader.Engine.FolderShortcutSupport.UpdateFolderShortcuts() in tModLoader\Terraria\ModLoader\Engine\FolderShortcutSupport.cs:line 17
   at Terraria.ModLoader.ModLoader.EngineInit() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 92
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 255
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 215
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 71
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__0() in tModLoader\Terraria\MonoLaunch.cs:line 57
   at System.Threading.Thread.StartCallback()

[12:51:19.909] [Main Thread/FATAL] [tML]: Main engine crash

System.Exception: 

Controlled Folder Access feature detected.

If game fails to launch make sure to add "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\6.0.0\dotnet.exe" to the "Allow an app through Controlled folder access" menu found in the "Ransomware protection" menu.

More instructions can be found in the website that just opened.

   at Terraria.ModLoader.Engine.FolderShortcutSupport.UpdateFolderShortcuts() in tModLoader\Terraria\ModLoader\Engine\FolderShortcutSupport.cs:line 22
   at Terraria.ModLoader.ModLoader.EngineInit() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 92
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 255
[12:51:19.910] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

**Comment by steviegt6** [comment]
Please read the error message. Assuming Controlled Folder Access is enabled and the local runtime hasn't been whitelisted, this behavior is expected; please follow up with more information if you're taken the instructed steps to fix the issue and it still persists.

**Comment by JavidPack** [comment]
This issue tracker is for software development and design improvements to tModLoader. We cannot provide support for individual user issues here. Please consult the [FAQ](https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ). If your issue is not listed there, come to the #support-forum channel in our [Discord chat](https://tmodloader.net/discord). Be sure to post your logs when asking for support.
