### ISSUE TITLE
System.FormatException: Input string was not in a correct format.

### ISSUE THREAD

**Issue by Z0Albert** [bluemagic123/tModLoader#3794]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

My mod should have some issues that caused me to report an error when I entered the game
System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Terraria.Localization.LanguageManager.BindFormatArgs(String key, Object[] args) in tModLoader\Terraria\Localization\LanguageManager.tML.cs:line 133
   at Terraria.ModLoader.ItemLoader.FinishSetup() in tModLoader\Terraria\ModLoader\ItemLoader.cs:line 115
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 323
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 126

### Log File

System.FormatException: Input string was not in a correct format.
   at System.Text.ValueStringBuilder.ThrowFormatError()
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Terraria.Localization.LanguageManager.BindFormatArgs(String key, Object[] args) in tModLoader\Terraria\Localization\LanguageManager.tML.cs:line 133
   at Terraria.ModLoader.ItemLoader.FinishSetup() in tModLoader\Terraria\ModLoader\ItemLoader.cs:line 115
   at Terraria.ModLoader.ModContent.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModContent.cs:line 323
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 126

**Comment by JavidPack** [comment]
Seems like some localization entry is malformed. If you could post the mod code in question, we can work to make this error easier to troubleshoot.

**Comment by JavidPack** [comment]
I'm guessing you had a { or some other unescaped special character.

For the fix, the modder will now see messages such as these:

![NVIDIA_Share_2023-09-20_16-36-01](https://github.com/tModLoader/tModLoader/assets/4522492/51fd3789-8f45-430d-9f41-2328ecb5eb59)
![NVIDIA_Share_2023-09-20_16-47-57](https://github.com/tModLoader/tModLoader/assets/4522492/bad968e5-be46-4182-926a-8004e24de171)
