### ISSUE TITLE
Collections of List-Like Collections in Configs Cannot Be Modified by Players

### ISSUE THREAD

**Issue by Antirhinnum** [bluemagic123/tModLoader#3852]
### Version

Self-Compiled (please specify branch)

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

Creating a collection of list-like\* collections in a `ModConfig` does not allow players to add items to the base collection.
\* Collections that are saved/serialized as JSON arrays (`List<T>`, `HashSet<T>`).
```cs
public Dictionary<ItemDefinition, List<ProjectileDefinition>> someItemsToProjectiles; // breaks
public List<List<ProjectileDefinition>> nestedProjLists; // breaks
public List<Dictionary<ItemDefinition, ProjectileDefinition>> listOfMaps; // works
```
Untested when the inner collection is an array.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/12773514/client.log)

Main error:
```
[22:52:50.997] [Main Thread/WARN] [tML]: Silently Caught Exception: 
Newtonsoft.Json.JsonSerializationException: Cannot populate JSON object onto type 'System.Collections.Generic.List`1[Terraria.ModLoader.Config.ItemDefinition]'. Path '', line 1, position 2.
   at Terraria.ModLoader.Logging.FirstChanceExceptionHandler(Object sender, FirstChanceExceptionEventArgs args) in tModLoader\Terraria\ModLoader\Logging.ExceptionHandling.cs:line 109
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonSerializer.PopulateInternal(JsonReader reader, Object target)
   at Newtonsoft.Json.JsonConvert.PopulateObject(String value, Object target, JsonSerializerSettings settings)
   at Terraria.ModLoader.Config.UI.CollectionElement.CreateCollectionElementInstance(Type type) in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 177
   at Terraria.ModLoader.Config.UI.DictionaryElement.AddItem() in tModLoader\Terraria\ModLoader\Config\UI\DictionaryElement.cs:line 123
   at Terraria.ModLoader.Config.UI.CollectionElement.<OnBind>b__33_1(UIMouseEvent a, UIElement b) in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 100
   at Terraria.UI.UIElement.LeftClick(UIMouseEvent evt) in tModLoader\Terraria\UI\UIElement.cs:line 367
...
```

### Steps to reproduce

Create a mod with the following `ModConfig`:
```cs
public class TestConfig : ModConfig
{
	public override ConfigScope Mode => ConfigScope.ServerSide;

	// Lists
	/* Y */ public List<int> List_Primitive;
	/* N */ public List<List<int>> List_List_Primitive;
	/* Y */ public List<ItemDefinition> List_Class;
	/* N */ public List<List<ItemDefinition>> List_List_Class;

	// Sets
	/* Y */ public HashSet<int> Set_Primitive;
	/* N */ public HashSet<HashSet<int>> Set_Set_Primitive;
	/* Y */ public HashSet<ItemDefinition> Set_Class;
	/* N */ public HashSet<HashSet<ItemDefinition>> Set_Set_Class;

	// Non-nested dicts
	/* Y */ public Dictionary<int, int> Dict_Primitive_Primitive;
	/* Y */ public Dictionary<int, ItemDefinition> Dict_Primitive_Class;
	/* Y */ public Dictionary<ItemDefinition, int> Dict_Class_Primitive;
	/* Y */ public Dictionary<ItemDefinition, ProjectileDefinition> Dict_Class_Class;
	
	// Nested lists in dicts
	/* N */ public Dictionary<List<int>, int> Dict_List_Primitive_Primitive;
	/* N */ public Dictionary<int, List<int>> Dict_Primitive_List_Primitive;
	/* N */ public Dictionary<List<int>, List<int>> Dict_List_Primitive_List_Primitive;
	/* N */ public Dictionary<List<int>, ItemDefinition> Dict_List_Primitive_Class;
	/* N */ public Dictionary<int, List<ItemDefinition>> Dict_Primitive_List_Class;
	/* N */ public Dictionary<List<int>, List<ItemDefinition>> Dict_List_Primitive_List_Class;
	/* N */ public Dictionary<List<ItemDefinition>, int> Dict_List_Class_Primitive;
	/* N */ public Dictionary<ItemDefinition, List<int>> Dict_Class_List_Primitive;
	/* N */ public Dictionary<List<ItemDefinition>, List<int>> Dict_List_Class_List_Primitive;
	/* N */ public Dictionary<List<ItemDefinition>, ProjectileDefinition> Dict_List_Class_Class;
	/* N */ public Dictionary<ItemDefinition, List<ProjectileDefinition>> Dict_Class_List_Class;
	/* N */ public Dictionary<List<ItemDefinition>, List<ProjectileDefinition>> Dict_List_Class_List_Class;

	// Nested dicts in dict
	/* Y */ public Dictionary<int, Dictionary<int, int>> Dict_Primitive_Dict_Primitive_Primitive;
	/* Y */ public Dictionary<ItemDefinition, Dictionary<int, int>> Dict_Class_Dict_Primitive_Primitive;
	/* Y */ public Dictionary<int, Dictionary<ItemDefinition, int>> Dict_Primitive_Dict_Class_Primitive;
	/* Y */ public Dictionary<int, Dictionary<int, ItemDefinition>> Dict_Primitive_Dict_Primitive_Class;
	/* Y */ public Dictionary<ItemDefinition, Dictionary<ItemDefinition, int>> Dict_Class_Dict_Class_Primitive;
	/* Y */ public Dictionary<ItemDefinition, Dictionary<int, ItemDefinition>> Dict_Class_Dict_Primitive_Class;
	/* Y */ public Dictionary<int, Dictionary<ItemDefinition, ItemDefinition>> Dict_Primitive_Dict_Class_Class;
	/* Y */ public Dictionary<ItemDefinition, Dictionary<ItemDefinition, ItemDefinition>> Dict_Class_Dict_Class_Class;
}
```
Build and reload the mod, then go to its config. The comment before each field tells if trying to add an element to the collection works.

### Expected Behavior

Clicking the "Add Item" button on the config element (of type, say `List<List<ProjectileDefinition>>`) should create a new config element of type `List<ProjectileDefinition>`.

### Actual Behavior

Clicking the "Add Item" button throws an exception, and no items are added.

### Reproduction frequency

100%.

### Additional Information

Tested using branch `1.4.4`, latest commit (https://github.com/tModLoader/tModLoader/commit/7aa3892087091190ab6c1d81f408d55fc0dbe429).
Reported to me by a friend using the latest `1.4.4-stable` branch on Steam.

I've traced the issue back to here: https://github.com/tModLoader/tModLoader/blob/7aa3892087091190ab6c1d81f408d55fc0dbe429/patches/tModLoader/Terraria/ModLoader/Config/UI/CollectionElement.cs#L175
Technically, this issue can be worked around as follows:
```cs
[JsonDefaultListValue("[]")]
public Dictionary<ItemDefinition, List<ProjectileDefinition>> itemsToProjectiles;
```

https://github.com/tModLoader/tModLoader/issues/2942 also mentions issues with nested collections in configs, but no provided error seems to mention the `JsonSerializationException` that this issue consistently gets, leading me to think this is a different issue.

**Comment by JavidPack** [comment]
I don't think we ever anticipated lists of lists being used, but if defaulting to an `[]` instead of `{}` for collection types works, that could work. We'll have to really test other things though, since it's all a bit hacky and there are assumptions in the code in various places that might break other aspects of modconfig behavior.
