### ISSUE TITLE
Error while running start-tModLoaderServer.sh

### ISSUE THREAD

**Issue by SunshinePro666** [bluemagic123/tModLoader#3877]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

ubuntu22.04. The linux kernel version is 5.16.17. The cpu architecture is aarch64(arm64). 

### Log File

[03:43:45.130] [Main Thread/INFO] [tML]: Starting tModLoader server 1.4.4.9+2023.08.3.3|2023.08|stable|Stable|c725c50989b18586417ce1169a464bdd1a5ea608|5250005828842115970 built 10/4/2023 1:50 AM
[03:43:45.176] [Main Thread/INFO] [tML]: Log date: 10/11/2023
[03:43:45.178] [Main Thread/INFO] [tML]: Running on Linux (v5.16.17.50) Arm64 NetCore 6.0.0
[03:43:45.180] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 6.0.0-rtm.21522.10
[03:43:45.180] [Main Thread/INFO] [tML]: Executable: /root/tml/tModLoader.dll
[03:43:45.180] [Main Thread/INFO] [tML]: Working Directory: /root/tml
[03:43:45.182] [Main Thread/INFO] [tML]: Launch Parameters:  -server -config serverconfig.txt
[03:43:45.196] [Main Thread/INFO] [tML]: Parsed Launch Parameters: -server -config serverconfig.txt
[03:43:45.476] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.NotImplementedException: The method or operation is not implemented.
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 83
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 116
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Utils\Helpers.cs:line 187
   at MonoMod.Core.Platforms.PlatformTriple.get_Current() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 113
   at MonoMod.Core.DetourFactory.CreateDefaultFactory() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\IDetourFactory.cs:line 80
   at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Utils\Helpers.cs:line 178
   at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\DetourContext.cs:line 104
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 410
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 378
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 320
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 73
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 17
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 93
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 284
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 211
   at Terraria.MonoLaunch.Main_End(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 78
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 64
   at Terraria.MonoLaunch.Main(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 71

[03:43:45.544] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null -> SDL2
[03:43:45.558] [Main Thread/DEBUG] [tML]: 	attempting load /root/tml/Libraries/Native/Linux/libSDL2.so
[03:43:45.562] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.DllNotFoundException: Unable to load shared library '/root/tml/Libraries/Native/Linux/libSDL2.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /root/tml/Libraries/Native/Linux/libSDL2.so: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at Terraria.MonoLaunch.ResolveNativeLibrary(Assembly assembly, String name) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 110
   at System.Runtime.Loader.AssemblyLoadContext.GetResolvedUnmanagedDll(Assembly assembly, String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDllUsingEvent(String unmanagedDllName, Assembly assembly, IntPtr gchManagedAssemblyLoadContext)
   at SDL2.SDL.INTERNAL_SDL_GetError()
   at SDL2.SDL.INTERNAL_SDL_GetError()
   at SDL2.SDL.SDL_GetError() in D:\a\tModLoader\tModLoader\FNA\lib\SDL2-CS\src\SDL2.cs:line 866
   at Terraria.ModLoader.Engine.ErrorReporting.FatalExit(String message, Exception e) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 50
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 284
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 211
   at Terraria.MonoLaunch.Main_End(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 78
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 64
   at Terraria.MonoLaunch.Main(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 71

[03:43:45.566] [Main Thread/FATAL] [tML]: An unexpected error occurred during tML startup

System.NotImplementedException: The method or operation is not implemented.
   at MonoMod.Core.Platforms.Systems.LinuxSystem..ctor() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\Systems\LinuxSystem.cs:line 46
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 83
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 116
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Utils\Helpers.cs:line 187
   at MonoMod.Core.Platforms.PlatformTriple.get_Current() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 113
   at MonoMod.Core.DetourFactory.CreateDefaultFactory() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\IDetourFactory.cs:line 80
   at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Utils\Helpers.cs:line 178
   at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\DetourContext.cs:line 104
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 410
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 378
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 320
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 73
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 16
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 92
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 284
[03:43:45.579] [Main Thread/DEBUG] [tML]: Native Resolve: FNA, Version=22.7.0.0, Culture=neutral, PublicKeyToken=null -> SDL2
[03:43:45.579] [Main Thread/DEBUG] [tML]: 	attempting load /root/tml/Libraries/Native/Linux/libSDL2.so
[03:43:45.587] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.DllNotFoundException: Unable to load shared library '/root/tml/Libraries/Native/Linux/libSDL2.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /root/tml/Libraries/Native/Linux/libSDL2.so: cannot open shared object file: No such file or directory
   at System.Runtime.InteropServices.NativeLibrary.Load(String libraryPath)
   at Terraria.MonoLaunch.ResolveNativeLibrary(Assembly assembly, String name) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 110
   at System.Runtime.Loader.AssemblyLoadContext.GetResolvedUnmanagedDll(Assembly assembly, String unmanagedDllName)
   at System.Runtime.Loader.AssemblyLoadContext.ResolveUnmanagedDllUsingEvent(String unmanagedDllName, Assembly assembly, IntPtr gchManagedAssemblyLoadContext)
   at SDL2.SDL.INTERNAL_SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, Byte* title, Byte* message, IntPtr window)
   at SDL2.SDL.INTERNAL_SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, Byte* title, Byte* message, IntPtr window)
   at SDL2.SDL.SDL_ShowSimpleMessageBox(SDL_MessageBoxFlags flags, String title, String message, IntPtr window) in D:\a\tModLoader\tModLoader\FNA\lib\SDL2-CS\src\SDL2.cs:line 1326
   at Terraria.ModLoader.Engine.ErrorReporting.MessageBoxShow(String message, Boolean fatal) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 30
   at Terraria.ModLoader.Engine.ErrorReporting.FatalExit(String message) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 43
   at Terraria.ModLoader.Engine.ErrorReporting.FatalExit(String message, Exception e) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\ErrorReporting.cs:line 91
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 284
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 211
   at Terraria.MonoLaunch.Main_End(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 78
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 64
   at Terraria.MonoLaunch.Main(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 71

**Comment by JavidPack** [comment]
ARM processors are not currently supported. There was a workaround, but it only works on 1.4.3 tmodloader : https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#arm64-linux-workaround

Closing in favor of older ARM issues.
