### ISSUE TITLE
the tmodloader opens fine but after it show the possible mods update it tries to load the modlist and it fails

### ISSUE THREAD

**Issue by aDOLLable** [bluemagic123/tModLoader#3883]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

when i open tmod loader opens it notify me about updatable mods as usual and it tries to load the existing modpack and it fails and output the logs

### Log File

[15:59:30.889] [.NET ThreadPool Worker/ERROR] [tML]: An error occurred while loading 
The mod responsible is unknown and tModLoader must be restarted.
System.UnauthorizedAccessException: Access to the path 'C:\Users\Administrator\Documents\My Games\Terraria\tModLoader\Mods\enabled.json' is denied.
   at System.IO.RandomAccess.WriteAtOffset(SafeFileHandle handle, ReadOnlySpan`1 buffer, Int64 fileOffset)
   at System.IO.Strategies.OSFileStreamStrategy.Write(ReadOnlySpan`1 buffer)
   at System.IO.Strategies.BufferedFileStreamStrategy.FlushWrite()
   at System.IO.Strategies.BufferedFileStreamStrategy.Dispose(Boolean disposing)
   at System.IO.StreamWriter.CloseStreamFromDispose(Boolean disposing)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.IO.File.WriteAllText(String path, String contents)
   at Terraria.ModLoader.Core.ModOrganizer.SaveEnabledMods() in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 535
   at Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods(IEnumerable`1 availableMods, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 331
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 119
[15:59:36.137] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "tModLoader-Logs" 

### Steps to reproduce

open tmodloader
proceed the updatable mods
mods will try to load 
and this log will output
trying to retry will lead you to the logs 

### Expected Behavior

it should load as usual and will result in the usual menu screen

### Actual Behavior

it fails to load and produce this log 

### Reproduction frequency

every time i open tmodloader

**Comment by aDOLLable** [comment]
Nvm I figured it out
