### ISSUE TITLE
[Bug] System NRE for Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw()

### ISSUE THREAD

**Issue by cyraid** [bluemagic123/tModLoader#3962]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Log File

```
[22:15:54.589] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Color color) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\SpriteBatch.cs:line 342
   at Lights.Lights.UseLightAndShadow(GraphicsDevice gd, SpriteBatch sb, RenderTarget2D rt1, RenderTarget2D rt2) in Lights.cs:line 287
   at Lights.Lights.FilterManager_EndCapture(orig_EndCapture orig, FilterManager self, RenderTarget2D finalTexture, RenderTarget2D screenTarget1, RenderTarget2D screenTarget2, Color clearColor) in Lights.cs:line 77
   at Hook<System.Void Lights.Lights::FilterManager_EndCapture(Terraria.Graphics.Effects.On_FilterManager+orig_EndCapture,Terraria.Graphics.Effects.FilterManager,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Color)>(FilterManager , RenderTarget2D , RenderTarget2D , RenderTarget2D , Color )
   at SyncProxy<System.Void Terraria.Graphics.Effects.FilterManager:EndCapture(Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Color)>(FilterManager , RenderTarget2D , RenderTarget2D , RenderTarget2D , Color )
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 53470
   at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52843
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52830
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 213
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 78
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in tModLoader\Terraria\MonoLaunch.cs:line 64
   at System.Threading.Thread.StartCallback()

[22:15:54.590] [Main Thread/ERROR] [Terraria]: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Color color) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\SpriteBatch.cs:line 360
   at Lights.Lights.UseLightAndShadow(GraphicsDevice gd, SpriteBatch sb, RenderTarget2D rt1, RenderTarget2D rt2) in Lights.cs:line 287
   at Lights.Lights.FilterManager_EndCapture(orig_EndCapture orig, FilterManager self, RenderTarget2D finalTexture, RenderTarget2D screenTarget1, RenderTarget2D screenTarget2, Color clearColor) in Lights.cs:line 77
   at Hook<System.Void Lights.Lights::FilterManager_EndCapture(Terraria.Graphics.Effects.On_FilterManager+orig_EndCapture,Terraria.Graphics.Effects.FilterManager,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Color)>(FilterManager , RenderTarget2D , RenderTarget2D , RenderTarget2D , Color )
   at SyncProxy<System.Void Terraria.Graphics.Effects.FilterManager:EndCapture(Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Color)>(FilterManager , RenderTarget2D , RenderTarget2D , RenderTarget2D , Color )
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 53470
   at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52853
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52834
[22:15:54.616] [Main Thread/FATAL] [tML]: Main engine crash

Tip: This is likely a mod's fault. Disable mods one by one and check if the issue persists

System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(Texture2D texture, Vector2 position, Color color) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\SpriteBatch.cs:line 360
   at Lights.Lights.UseLightAndShadow(GraphicsDevice gd, SpriteBatch sb, RenderTarget2D rt1, RenderTarget2D rt2) in Lights.cs:line 287
   at Lights.Lights.FilterManager_EndCapture(orig_EndCapture orig, FilterManager self, RenderTarget2D finalTexture, RenderTarget2D screenTarget1, RenderTarget2D screenTarget2, Color clearColor) in Lights.cs:line 77
   at Hook<System.Void Lights.Lights::FilterManager_EndCapture(Terraria.Graphics.Effects.On_FilterManager+orig_EndCapture,Terraria.Graphics.Effects.FilterManager,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Graphics.RenderTarget2D,Microsoft.Xna.Framework.Color)>(FilterManager , RenderTarget2D , RenderTarget2D , RenderTarget2D , Color )
   at SyncProxy<System.Void Terraria.Graphics.Effects.FilterManager:EndCapture(Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Graphics.RenderTarget2D, Microsoft.Xna.Framework.Color)>(FilterManager , RenderTarget2D , RenderTarget2D , RenderTarget2D , Color )
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 53470
   at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52853
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52834
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
[22:15:54.617] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown
```

### Steps to reproduce

1. Start game.
2. Crash.

### Expected Behavior

No crash.

### Actual Behavior

Crash.

### Reproduction frequency

First time for this one.

### Additional Information

Didn't do anything special.

**Comment by JavidPack** [comment]
The error you are showing is from a mod with the internal name of `Lights`, you'll need to bring this up with them or if you think it is a tModLoader issue replicate the issue with mods disabled and post the actual log files. Closing.
