### ISSUE TITLE
 Cannot overwrite steam env

### ISSUE THREAD

**Issue by wanghaodong514** [bluemagic123/tModLoader#3984]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Mod capability as a Modder

### Description

 Cannot overwrite steam env

### Log File

System.Exception: Cannot overwrite steam env. SteamAppId=
   at Terraria.ModLoader.Engine.Steam.SetAppId(AppId_t appId) in tModLoader\Terraria\ModLoader\Engine\Steam.cs:line 75
   at Terraria.Social.Steam.CoreSocialModule.Initialize() in tModLoader\Terraria\Social\Steam\CoreSocialModule.cs:line 41
   at Terraria.Social.SocialAPI.LoadSteam() in tModLoader\Terraria\Social\SocialAPI.cs:line 145
   at Terraria.Social.SocialAPI.Initialize(Nullable`1 mode) in tModLoader\Terraria\Social\SocialAPI.cs:line 65
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 260
[14:05:03.596] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

**Comment by JavidPack** [comment]
Not sure how that is happening, something is setting that "SteamAppId" environment variable wrong. Can you confirm that this is a normal steam launch, no family share, no GOG?

Also, please delete all the logs, try to launch, then post all the logs, the actual log files. I need all the logs to look further into this.

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
