### ISSUE TITLE
Modder error in World IO can cause softlock or "net host not responding"

### ISSUE THREAD

**Issue by direwolf420** [bluemagic123/tModLoader#3988]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

If a modder's world IO is not properly coded, and exceptions are thrown, these exceptions are not displayed via message box to the player, instead they either softlock the game (immediately after world generation is done), or freeze the game for a few seconds, then give a "net host not responding" window. This is bad for the player because he won't know what mod caused it.

### Log File

Excerpt from two mods that cause this currently

On world exit: (also mirrored in the Natives log!)
```
Silently Caught Exception: 
System.ArgumentException: An item with the same key has already been added. Key: FargowiltasSouls DeviBoss
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Terraria.ModLoader.IO.TagCompound.Set(String key, Object value, Boolean replace) in tModLoader\Terraria\ModLoader\IO\TagCompound.cs:line 74
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at BossChecklist.WorldAssist.SaveWorldData(TagCompound tag) in BossChecklist\WorldAssist.cs:line 146
   at Terraria.ModLoader.IO.WorldIO.SaveModData() in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 496
   at Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 31
   at Terraria.IO.WorldFile.InternalSaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 711
   at Terraria.IO.WorldFile.<>c__DisplayClass58_0.<SaveWorld>b__0() in tModLoader\Terraria\IO\WorldFile.cs:line 642
   at Terraria.Utilities.FileUtilities.ProtectedInvoke(Action action) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 207
   at DMD<System.Void Terraria.IO.WorldFile:SaveWorld(System.Boolean, System.Boolean)>(Boolean useCloudSaving, Boolean resetTime)
   at SyncProxy<System.Void Terraria.IO.WorldFile:SaveWorld(System.Boolean, System.Boolean)>(Boolean , Boolean )
   at Terraria.IO.WorldFile.SaveWorld() in tModLoader\Terraria\IO\WorldFile.cs:line 617
   at Terraria.WorldGen.SaveAndQuitCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2608
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

On worldgen finish
```
Silently Caught Exception: 
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at MetroidMod.Common.Systems.MSystem.SaveWorldData(TagCompound tag) in MetroidMod\Common\Systems\MSystem.cs:line 339
at Terraria.ModLoader.IO.WorldIO.SaveModData() in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 496
   at Terraria.ModLoader.IO.WorldIO.Save(String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\WorldIO.cs:line 31
   at Terraria.IO.WorldFile.InternalSaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 711
   at Terraria.IO.WorldFile.<>c__DisplayClass58_0.<SaveWorld>b__0() in tModLoader\Terraria\IO\WorldFile.cs:line 642
   at Terraria.Utilities.FileUtilities.ProtectedInvoke(Action action) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 207
   at Terraria.IO.WorldFile.SaveWorld(Boolean useCloudSaving, Boolean resetTime) in tModLoader\Terraria\IO\WorldFile.cs:line 641
   at Terraria.WorldGen.do_worldGenCallBack(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2492
   at Terraria.WorldGen.worldGenCallback(Object threadContext) in tModLoader\Terraria\WorldGen.cs:line 2480
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

### Steps to reproduce

To reproduce, make a new mod and add this in:
```cs
public class ModWorld : ModSystem
{
    public override void SaveWorldData(TagCompound tag)
    {
        throw new ArgumentException("error that can happen on tagcompounds: 'System.ArgumentException: An item with the same key has already been added'");
        //other common ones are IndexOutOfRangeException and NullReferenceException, usually if uninitialized data is trying to get saved
    }

    public override void LoadWorldData(TagCompound tag)
    {
        base.LoadWorldData(tag);
    }
}
```

Then simply enter a world and quit the world.
For the other scenario, generate a new world, and you will get softlocked after it's finished.

### Expected Behavior

Handle such things more gracefully on tmls end

### Actual Behavior

Softlocks and hard crashes

### Reproduction frequency

100%

### Additional Information
A common reason for the worldgen thing is that modders haven't been properly using the initialization hooks in ModSystem. In 1.3, there used to be only one `Initialize` hook. Then in 1.4 some code changed and it forced modders to override two hooks to achieve the same thing: `OnWorldLoad` and `PreWorldGen`, the latter is usually forgotten during porting. It was then superceded by `ClearWorld` which runs in both contexts like 1.3. If mods are still using the old approach and forgot PreWorldGen, then that issue occurs depending on the type of data the modder has set up.

The code that normally spawns a message box only reacts to certain specific exception types, and none of the common ones mod code can throw.
![image](https://github.com/tModLoader/tModLoader/assets/15894498/6ea95a3b-f4a4-4a56-93f4-9d38384c2f95)

**Comment by JavidPack** [comment]
We should tackle this issue when also working on #3401

**Comment by Metratrj** [comment]
When nobody already did something on this, I would take care of this issue
