### ISSUE TITLE
Cannot open shared object file .../Libraries/Native/Linux/libSDL2.so

### ISSUE THREAD

**Issue by JacobC1921w** [bluemagic123/tModLoader#3997]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects

Gameplay as a Player

### Description

I decided to migrate my tModLoader server from my main PC to my RPI server so that my friends can play it while i'm away.

Upon launching the `./start-tModLoaderServer.sh` executable, i am met with the following message:

```
Use steam server (y/n): n
You are on platform: "Linux"
Logging to /home/jacob/TerrariaServer/tModLoader/tModLoader-Logs/Launch.log
Verifying .NET....
This may take a few moments.
Fixing .NET SDL PATH issues
Success!
Parsing .NET version requirements from runtimeconfig.json
Success! dotnet_version=6.0.14
Checking for old .NET versions to remove from folder
Cleanup Complete
Checking dotnet install...
Dotnet should be present in "/home/jacob/TerrariaServer/tModLoader/dotnet/6.0.14"
Attempting Launch...
Launched Using Local Dotnet. Launch command: "/home/jacob/TerrariaServer/tModLoader/dotnet/6.0.14/dotnet" tModLoader.dll "-server -config serverconfig.txt"
The method or operation is not implemented. tModLoader.RuntimeErrorSeeLogsForFullTrace
Unable to load shared library '/home/jacob/TerrariaServer/tModLoader/Libraries/Native/Linux/libSDL2.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /home/jacob/TerrariaServer/tModLoader/Libraries/Native/Linux/libSDL2.so: cannot open shared object file: No such file or directory tModLoader.RuntimeErrorSeeLogsForFullTrace
tModLoader v2023.10.3.0 Error
An unexpected error occurred during tML startup

System.NotImplementedException: The method or operation is not implemented.
   at MonoMod.Core.Platforms.Systems.LinuxSystem..ctor() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\Systems\LinuxSystem.cs:line 46
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 83
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 116
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock, IntPtr init, TParam obj) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Utils\Helpers.cs:line 187
   at MonoMod.Core.Platforms.PlatformTriple.get_Current() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 113
   at MonoMod.Core.DetourFactory.CreateDefaultFactory() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Core\IDetourFactory.cs:line 80
   at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location, IntPtr init, TParam obj) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.Utils\Helpers.cs:line 178
   at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\DetourContext.cs:line 104
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 410
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 378
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in Z:\Users\aaron\Source\Repos\MonoModReorg\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 320
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 73
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 16
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 92
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 284

A server.log file containing error information has been generated in
/home/jacob/TerrariaServer/tModLoader/tModLoader-Logs
(You will need to share this file if asking for help)
Unable to load shared library '/home/jacob/TerrariaServer/tModLoader/Libraries/Native/Linux/libSDL2.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: /home/jacob/TerrariaServer/tModLoader/Libraries/Native/Linux/libSDL2.so: cannot open shared object file: No such file or directory tModLoader.RuntimeErrorSeeLogsForFullTrace
```

Attached are the logs generated.

### Log File

[Launch.log](https://github.com/tModLoader/tModLoader/files/13790075/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/13790076/Natives.log)
[server.log](https://github.com/tModLoader/tModLoader/files/13790077/server.log)
[environment-server.log](https://github.com/tModLoader/tModLoader/files/13790078/environment-server.log)

### Expected Behavior

The server should be starting, as the file /home/jacob/TerrariaServer/tModLoader/Libraries/Native/Linux/libSDL2.so->/home/jacob/TerrariaServer/tModLoader/Libraries/Native/Linux/libSDL2-2.0.so.0 is present

### Actual Behavior

The server cannot find the file

### Reproduction frequency

Every time at launch

### Additional Information

# System information

 jacob  ~/TerrariaServer/tModLoader/tModLoader-Logs  uname -a
Linux jacob 6.2.0-1008-raspi #10-Ubuntu SMP PREEMPT Fri Jun 30 12:20:13 UTC 2023 aarch64 aarch64 aarch64 GNU/Linux
 jacob  ~/TerrariaServer/tModLoader/tModLoader-Logs  sudo lshw
    description: Computer
    product: Raspberry Pi 4 Model B Rev 1.5
    serial: 10000000b1637bb0
    width: 64 bits
    capabilities: smp cp15_barrier setend swp tagged_addr_disabled
  *-core
       description: Motherboard
       physical id: 0
     *-cpu:0
          description: CPU
          product: cpu
          physical id: 1
          bus info: cpu@0
          size: 1400MHz
          capacity: 1800MHz
          capabilities: fp asimd evtstrm crc32 cpuid cpufreq
        *-cache
             description: L1 Cache
             physical id: 0
             size: 32KiB
     *-cpu:1
          description: CPU
          product: cpu
          physical id: 2
          bus info: cpu@1
          size: 1400MHz
          capacity: 1800MHz
          capabilities: fp asimd evtstrm crc32 cpuid cpufreq
        *-cache
             description: L1 Cache
             physical id: 0
             size: 32KiB
     *-cpu:2
          description: CPU
          product: cpu
          physical id: 3
          bus info: cpu@2
          size: 1400MHz
          capacity: 1800MHz
          capabilities: fp asimd evtstrm crc32 cpuid cpufreq
        *-cache
             description: L1 Cache
             physical id: 0
             size: 32KiB
     *-cpu:3
          description: CPU
          product: cpu
          physical id: 4
          bus info: cpu@3
          size: 1400MHz
          capacity: 1800MHz
          capabilities: fp asimd evtstrm crc32 cpuid cpufreq
        *-cache
             description: L1 Cache
             physical id: 0
             size: 32KiB
     *-cpu:4 DISABLED
          description: CPU
          product: l2-cache0
          physical id: 5
          bus info: cpu@4
     *-memory
          description: System memory
          physical id: 6
          size: 7809MiB
     *-pci
          description: PCI bridge
          product: BCM2711 PCIe Bridge
          vendor: Broadcom Inc. and subsidiaries
          physical id: 0
          bus info: pci@0000:00:00.0
          version: 20
          width: 32 bits
          clock: 33MHz
          capabilities: pci pm pciexpress normal_decode bus_master cap_list
          configuration: driver=pcieport
          resources: irq:31 memory:600000000-6000fffff
        *-usb
             description: USB controller
             product: VL805/806 xHCI USB 3.0 Controller
             vendor: VIA Technologies, Inc.
             physical id: 0
             bus info: pci@0000:01:00.0
             version: 01
             width: 64 bits
             clock: 33MHz
             capabilities: pm msi pciexpress xhci bus_master cap_list
             configuration: driver=xhci_hcd latency=0
             resources: irq:39 memory:600000000-600000fff
           *-usbhost:0
                product: xHCI Host Controller
                vendor: Linux 6.2.0-1008-raspi xhci-hcd
                physical id: 0
                bus info: usb@1
                logical name: usb1
                version: 6.02
                capabilities: usb-2.00
                configuration: driver=hub slots=1 speed=480Mbit/s
              *-usb
                   description: USB hub
                   product: USB2.0 Hub
                   vendor: VIA Labs, Inc.
                   physical id: 1
                   bus info: usb@1:1
                   version: 4.21
                   capabilities: usb-2.10
                   configuration: driver=hub maxpower=100mA slots=4 speed=480Mbit/s
           *-usbhost:1
                product: xHCI Host Controller
                vendor: Linux 6.2.0-1008-raspi xhci-hcd
                physical id: 1
                bus info: usb@2
                logical name: usb2
                version: 6.02
                capabilities: usb-3.00
                configuration: driver=hub slots=4 speed=5000Mbit/s
  *-usbhost
       product: DWC OTG Controller
       vendor: Linux 6.2.0-1008-raspi dwc2_hsotg
       physical id: 1
       bus info: usb@3
       logical name: usb3
       version: 6.02
       capabilities: usb-2.00
       configuration: driver=hub slots=1 speed=480Mbit/s
  *-mmc0
       description: MMC Host
       physical id: 2
       logical name: mmc0
     *-device
          description: SD Card
          product: SN128
          vendor: SanDisk
          physical id: aaaa
          logical name: /dev/mmcblk0
          version: 8.0
          date: 12/2019
          serial: 694884056
          size: 119GiB (127GB)
          capabilities: sd partitioned partitioned:dos
          configuration: logicalsectorsize=512 sectorsize=512 signature=8b707b32
        *-volume:0 UNCLAIMED
             description: Windows FAT volume
             vendor: mkfs.fat
             physical id: 1
             version: FAT32
             serial: 8083-8fec
             size: 255MiB
             capacity: 256MiB
             capabilities: primary bootable fat initialized
             configuration: FATs=2 filesystem=fat label=system-boot
        *-volume:1
             description: EXT4 volume
             vendor: Linux
             physical id: 2
             logical name: /dev/mmcblk0p2
             logical name: /
             logical name: /var/snap/firefox/common/host-hunspell
             version: 1.0
             serial: 65d266e9-d7b3-4b5a-806c-956a9f30c00e
             size: 118GiB
             capacity: 118GiB
             capabilities: primary journaled extended_attributes large_files huge_files dir_nlink recover 64bit extents ext4 ext2 initialized
             configuration: created=2023-04-18 08:28:24 filesystem=ext4 label=writable lastmountpoint=/ modified=2023-04-18 08:29:32 mount.fstype=ext4 mount.options=ro,noexec,noatime,discard mounted=2023-04-18 08:29:34 state=mounted
  *-mmc1
       description: MMC Host
       physical id: 3
       logical name: mmc1
     *-device
          description: SDIO Device
          physical id: 1
          bus info: mmc@1:0001
          serial: 0
          capabilities: sdio
        *-interface:0
             description: Wireless interface
             product: 43430
             vendor: Broadcom
             physical id: 1
             bus info: mmc@1:0001:1
             logical name: mmc1:0001:1
             logical name: wlan0
             serial: d8:3a:dd:02:9c:98
             capabilities: ethernet physical wireless
             configuration: broadcast=yes driver=brcmfmac driverversion=7.45.241 firmware=01-703fd60 ip=192.168.0.10 multicast=yes wireless=IEEE 802.11
        *-interface:1
             product: 43430
             vendor: Broadcom
             physical id: 2
             bus info: mmc@1:0001:2
             logical name: mmc1:0001:2
        *-bt
             description: BlueTooth interface
             product: 43430
             vendor: Broadcom
             physical id: 3
             bus info: mmc@1:0001:3
             logical name: mmc1:0001:3
             capabilities: wireless bluetooth
             configuration: wireless=BlueTooth
  *-sound:0
       description: Headphones
       physical id: 4
       logical name: card0
       logical name: /dev/snd/controlC0
       logical name: /dev/snd/pcmC0D0p
  *-sound:1
       description: vc4hdmi0
       physical id: 5
       logical name: card1
       logical name: /dev/snd/controlC1
       logical name: /dev/snd/pcmC1D0p
  *-sound:2
       description: vc4hdmi1
       physical id: 6
       logical name: card2
       logical name: /dev/snd/controlC2
       logical name: /dev/snd/pcmC2D0p
  *-graphics
       product: vc4drmfb
       physical id: 7
       logical name: /dev/fb0
       capabilities: fb
       configuration: depth=16 resolution=1920,1080
  *-input:0
       product: vc4-hdmi-0
       physical id: 8
       logical name: input0
       logical name: /dev/input/event0
       capabilities: cec
  *-input:1
       product: vc4-hdmi-1
       physical id: 9
       logical name: input1
       logical name: /dev/input/event1
       capabilities: cec
  *-network
       description: Ethernet interface
       physical id: a
       logical name: eth0
       serial: d8:3a:dd:02:9c:96
       capacity: 1Gbit/s
       capabilities: ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd 1000bt 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=bcmgenet driverversion=6.2.0-1008-raspi link=no multicast=yes port=twisted pair
 jacob  ~/TerrariaServer/tModLoader/tModLoader-Logs  lscpu
Architecture:            aarch64
  CPU op-mode(s):        32-bit, 64-bit
  Byte Order:            Little Endian
CPU(s):                  4
  On-line CPU(s) list:   0-3
Vendor ID:               ARM
  Model name:            Cortex-A72
    Model:               3
    Thread(s) per core:  1
    Core(s) per cluster: 4
    Socket(s):           -
    Cluster(s):          1
    Stepping:            r0p3
    CPU(s) scaling MHz:  86%
    CPU max MHz:         1800.0000
    CPU min MHz:         600.0000
    BogoMIPS:            108.00
    Flags:               fp asimd evtstrm crc32 cpuid
Caches (sum of all):
  L1d:                   128 KiB (4 instances)
  L1i:                   192 KiB (4 instances)
  L2:                    1 MiB (1 instance)
Vulnerabilities:
  Itlb multihit:         Not affected
  L1tf:                  Not affected
  Mds:                   Not affected
  Meltdown:              Not affected
  Mmio stale data:       Not affected
  Retbleed:              Not affected
  Spec store bypass:     Vulnerable
  Spectre v1:            Mitigation; __user pointer sanitization
  Spectre v2:            Vulnerable
  Srbds:                 Not affected
  Tsx async abort:       Not affected
 jacob  ~/TerrariaServer/tModLoader/tModLoader-Logs  lsblk
NAME        MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0         7:0    0     4K  1 loop /snap/bare/5
loop1         7:1    0 230.8M  1 loop /snap/firefox/3415
loop2         7:2    0  68.5M  1 loop /snap/core22/867
loop3         7:3    0 465.4M  1 loop /snap/gnome-42-2204/133
loop4         7:4    0  35.5M  1 loop
loop6         7:6    0  43.2M  1 loop /snap/certbot/3464
loop7         7:7    0  59.7M  1 loop /snap/core20/2107
loop8         7:8    0  35.5M  1 loop /snap/snapd/20102
loop9         7:9    0  93.3M  1 loop /snap/core/16096
loop10        7:10   0 464.7M  1 loop
loop11        7:11   0 228.2M  1 loop /snap/firefox/3357
loop12        7:12   0  91.7M  1 loop /snap/gtk-common-themes/1535
loop13        7:13   0  11.7M  1 loop /snap/snap-store/960
loop14        7:14   0  11.7M  1 loop /snap/snap-store/963
loop15        7:15   0  35.5M  1 loop /snap/snapd/20298
loop16        7:16   0  69.1M  1 loop /snap/core22/1035
loop17        7:17   0   416K  1 loop /snap/snapd-desktop-integration/85
loop18        7:18   0  59.3M  1 loop /snap/core20/2019
loop19        7:19   0 475.1M  1 loop /snap/gnome-42-2204/143
loop20        7:20   0  93.3M  1 loop /snap/core/16204
loop21        7:21   0  43.2M  1 loop /snap/certbot/3567
mmcblk0     179:0    0 119.1G  0 disk
|-mmcblk0p1 179:1    0   256M  0 part /boot/firmware
`-mmcblk0p2 179:2    0 118.8G  0 part /var/snap/firefox/common/host-hunspell
                                      /
 jacob  ~/TerrariaServer/tModLoader/tModLoader-Logs  lspci
00:00.0 PCI bridge: Broadcom Inc. and subsidiaries BCM2711 PCIe Bridge (rev 20)
01:00.0 USB controller: VIA Technologies, Inc. VL805/806 xHCI USB 3.0 Controller (rev 01)

**Comment by realvalked** [comment]
i have the same issue.

**Comment by Destructor-Ben** [comment]
I have had a similar issue with GitHub actions on Ubuntu, but the error was claiming that FAudio couldn't load because the SDL lib couldn't be found (the lib was there). No idea why FAudio was loading when I was launching tML server, might have been a fault on my end.

**Comment by Mirsario** [comment]
This happens because we do not currently ship natives for ARM, as well as 32-bit x86. But I'm not entirely sure why SDL2 is being accessed by a server.

**Comment by bwb408114278** [comment]
I have to get a similar issue when I start server on Cent OS 7.9, log file said my server can't read SDL lib and I need to install GLIBC 2.27, but Cent OS support 2.17 only.

**Comment by SavageTheUnicorn** [comment]
Natives for ARM64 eta when? I'm kidding, but on a serious note ARM64 would be freaking spectacular. I was mega sad seeing this.

**Comment by kode54** [comment]
There's already ARM64 native Mono, and I already know that the natives used by Terraria and this project already build natively for ARM64. I've gotten unmodded Terraria running with ARM64 native code, at least on macOS. The real problem for this case is the compatibility of the hooking, which needs to be ported as well. And it likely needs to be ported for both macOS and for Linux. Well, and Windows ARM. So there's three ports that need to be developed and tested. And it's probably not like there's a budget for a paid developer to do this.

I guess Ethan Lee was right to abandon ship. There's probably no money in this whole field. Or is this a volunteer driven project, and therefore mostly people doing things they love within their own motivation, and therefore probably no budget for all new test hardware, just people working within their own means on their preferred devices?

**Comment by Mirsario** [comment]
ARM support for Mac clients and non-Steam Linux servers is very close to seeing the light of day, as MonoMod now has it implemented.
See this Discord thread:
https://discord.com/channels/103110554649894912/1405829919187144765/1405830030201978900
(https://discord.gg/tModLoader to join the server)

**Comment by Chicken-Bones** [comment]
See #2639
