### ISSUE TITLE
Mods aren't loaded for GOG+Linux users, causing player select menu crashes

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#4081]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

GOG

### This bug affects...

Mod capability as a Modder

### Description

There have been a few reports of this issue. Basically users launch the game and go to the player select menu to create a character. The game then crashes with the following error:
```
[02:37:27.696] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Terraria.Player.GetModPlayer[T](T baseInstance) in tModLoader\Terraria\Player.TML.cs:line 92
   at Terraria.Player.LoadPlayer_LastMinuteFixes(Player newPlayer) in tModLoader\Terraria\Player.cs:line 45614
   at Terraria.Player.Deserialize(PlayerFileData data, Player newPlayer, BinaryReader fileIO, Byte[] tplrData, Int32 release, Boolean& gotToReadName) in tModLoader\Terraria\Player.cs:line 45065
   at Terraria.Player.LoadPlayerFromStream(PlayerFileData playerFileData, Byte[] plrData, Byte[] tplrData) in tModLoader\Terraria\Player.cs:line 45010
   at Terraria.Player.LoadPlayer(String playerPath, Boolean cloudSave) in tModLoader\Terraria\Player.cs:line 44975
   at Terraria.Player.GetFileData(String file, Boolean cloudSave) in tModLoader\Terraria\Player.cs:line 45670
   at Terraria.GameContent.UI.States.UICharacterSelect.LoadMigratablePlayers() in tModLoader\Terraria\GameContent\UI\States\UICharacterSelect.TML.cs:line 76
   at Terraria.GameContent.UI.States.UICharacterSelect.OnActivate() in tModLoader\Terraria\GameContent\UI\States\UICharacterSelect.cs:line 135
   at Terraria.UI.UIElement.Activate() in tModLoader\Terraria\UI\UIElement.cs:line 452
   at Terraria.UI.UserInterface.SetState(UIState state) in tModLoader\Terraria\UI\UserInterface.cs:line 262
   at Terraria.Main.OpenCharacterSelectUI() in tModLoader\Terraria\Main.cs:line 44887
   at Terraria.Main.DrawMenu(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 41909
```
Other errors in the log include similar `GetModPlayer` errors from `UpdateDyes` and `LegacyPlayerRenderer`.

An examination of client.log shows that `Finding Mods...` and `Adding Content: ModLoader (tModLoader)` lines are absent. Both reports also show `Steam Game Server failed to Init. Steam Workshop downloading on GoG is unavailable. Make sure Steam is installed`, so Steam isn't installed on these machines.

The reports for this are both Linux + GOG users. Likely some logic is changing `Main.menuMode` to 0, skipping loading mods. We should be able to track down the issue with some debugging. 

Reports: 
https://discord.com/channels/103110554649894912/1211234306995920906
https://discord.com/channels/103110554649894912/1193392460777406524

The workaround is to go to Workshop -> Manage Mods -> Force Reload each time the game is launched.

**Comment by JavidPack** [comment]
Ok, probably caused by 

https://github.com/tModLoader/tModLoader/blob/94f6d91b5ec66d0ab4e6130a508256dc7a3d47e5/patches/tModLoader/Terraria/Social/Steam/SteamedWraps.cs#L84

Should probably be `Main.menuMode` or `Interface.loadModsID` instead of 0. Need to test or study the code to check when that code is executed to make sure it's a suitable solution.
