### ISSUE TITLE
External Drive install launch issues

### ISSUE THREAD

**Issue by JavidPack** [bluemagic123/tModLoader#4136]
We have had many reports in the past of issues where users were able to resolve the issue by moving the installed game to the internal hard drive from an external hard drive. Since this issue is so prevalent, it is a good idea to collect these issues here in an attempt to identify the root issue. My suspicion is that behavior inconsistencies of various file system formats are causing issues. This issue will be filled out with more examples as time goes on. 

### Report 1
https://discord.com/channels/103110554649894912/1222230797432655992

This issue seems to fail enumerating files in a directory when the file exists in that directory.  I'm not sure how that is possible.

```
System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at Terraria.ModLoader.Engine.TMLContentManager.TryFixFileCasings(String rootDirectory) in tModLoader\Terraria\ModLoader\Engine\TMLContentManager.cs:line 107
   at Terraria.ModLoader.Engine.TMLContentManager..ctor(IServiceProvider serviceProvider, String rootDirectory, TMLContentManager overrideContentManager) in tModLoader\Terraria\ModLoader\Engine\TMLContentManager.cs:line 28
```

![chrome_2024-03-26_12-11-21](https://github.com/tModLoader/tModLoader/assets/4522492/a21da62e-a88a-4773-b1e6-eb93fba85841)

[client - 2024-03-26T121011.214.log](https://github.com/tModLoader/tModLoader/files/14763169/client.-.2024-03-26T121011.214.log)

**Comment by JavidPack** [comment]
Another report: (https://discord.com/channels/103110554649894912/1291961627020886016)

User would experience crashes with `Asset could not be found: "Images\Tiles_650"`. The logs mention `Found vanilla asset with wrong case, renaming: (from D:\SteamLibrary\steamapps\common\Terraria\Content) Images\TIles_650.xnb -> Images/Tiles_650.xnb`. The file would never actually rename successfully apparently. The issue was resolved when they moved Terraria to the C drive (NTFS) instead of the D drive, which was an external drive with the exFAT file system.

Something is definitely wrong with `TryFixFileCasings` on some file systems. Either we fix this or revert the case sensitive issue altogether. (https://github.com/tModLoader/tModLoader/issues/3979#issuecomment-1883988896)

**Comment by Chicken-Bones** [comment]
https://resource.dopus.com/t/solved-rename-doesnt-work-on-external-drive-with-exfat-format/43801

I've heard this before. We can try doing the rename in 2 passes where we add and remove an `_` or something as well.

**Comment by JavidPack** [comment]
Note: Another report today. 

We could consider logging the file system of the terraria and tmodloader install drives, in case they are relevant for other issues: https://learn.microsoft.com/en-us/dotnet/api/system.io.driveinfo?view=net-10.0

...and also skip this method the specific file system is case insensitive
