### ISSUE TITLE
Game crashes with "Fatal Deadlock in FastParallelFor ..."

### ISSUE THREAD

**Issue by emisanpre** [bluemagic123/tModLoader#4144]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

Game does not stop crashing, pls help. I play at multiplayer with a friend.

### Log File

[client.log](https://github.com/tModLoader/tModLoader/files/14820282/client.log)
[environment-client.log](https://github.com/tModLoader/tModLoader/files/14820283/environment-client.log)
[Launch.log](https://github.com/tModLoader/tModLoader/files/14820284/Launch.log)
[Natives.log](https://github.com/tModLoader/tModLoader/files/14820285/Natives.log)
[terrariasteamclient.log](https://github.com/tModLoader/tModLoader/files/14820286/terrariasteamclient.log)

### Steps to reproduce

The crash appears randomly, sometimes at 5 minutes since i start playing and sometimes at 30 minutes.

First time happens when i break a cristal heart in the caves, second and third time happens breaking ore with a mod called ore excavator, this mod makes that you break all the ore zone faster. I don't know if it is a mod problem or what, but my friend does not have this crashes.

### Expected Behavior

Game should not crash

### Actual Behavior

Game crashes

### Reproduction frequency

A lot, 3 times in a row playing for 2 hours with a friend

### Additional Information

[00:24:44.586] [Main Thread/ERROR] [Terraria]: System.Exception: Fatal Deadlock in FastParallelFor. pending: 219. avail: 32749
   at ReLogic.Threading.FastParallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelForAction callback, Object context) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Threading\FastParallel.cs:line 102
   at Terraria.Graphics.Light.TileLightScanner.ExportTo(Rectangle area, LightMap outputMap, TileLightScannerOptions options) in tModLoader\Terraria\Graphics\Light\TileLightScanner.cs:line 36
   at Terraria.Graphics.Light.LightingEngine.ProcessScan(Rectangle area) in tModLoader\Terraria\Graphics\Light\LightingEngine.cs:line 118
   at Terraria.Graphics.Light.LightingEngine.ProcessArea(Rectangle area) in tModLoader\Terraria\Graphics\Light\LightingEngine.cs:line 68
   at Terraria.Lighting.LightTiles(Int32 firstX, Int32 lastX, Int32 firstY, Int32 lastY) in tModLoader\Terraria\Lighting.cs:line 88
   at DMD<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at SyncProxy<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52919
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52900
[00:24:44.626] [Main Thread/FATAL] [tML]: Main engine crash

System.Exception: Fatal Deadlock in FastParallelFor. pending: 219. avail: 32749
   at ReLogic.Threading.FastParallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelForAction callback, Object context) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Threading\FastParallel.cs:line 102
   at Terraria.Graphics.Light.TileLightScanner.ExportTo(Rectangle area, LightMap outputMap, TileLightScannerOptions options) in tModLoader\Terraria\Graphics\Light\TileLightScanner.cs:line 36
   at Terraria.Graphics.Light.LightingEngine.ProcessScan(Rectangle area) in tModLoader\Terraria\Graphics\Light\LightingEngine.cs:line 118
   at Terraria.Graphics.Light.LightingEngine.ProcessArea(Rectangle area) in tModLoader\Terraria\Graphics\Light\LightingEngine.cs:line 68
   at Terraria.Lighting.LightTiles(Int32 firstX, Int32 lastX, Int32 firstY, Int32 lastY) in tModLoader\Terraria\Lighting.cs:line 88
   at DMD<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at SyncProxy<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52919
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52900
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266

**Comment by Mirsario** [comment]
Please see if you can reproduce this at least once without using any mods. It may be a CPU threading issue of ours, or it may be a mod causing a really long freeze or an infinite loop in lighting-related functions.

**Comment by emisanpre** [comment]
I will try to reproduce it with out any mods. I will let you know.

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
