### ISSUE TITLE
我无法在centos9 中创建游戏服务器

### ISSUE THREAD

**Issue by AndreasByrsting** [bluemagic123/tModLoader#4266]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

未添加任何mod之前可以正常加入，但是一旦增加了任何一个mod 在启动之后，玩家加入房间时提示
`error:03000098:digital envelope routines::invalid digest (see server.log for full trace)
Read out of bounds. (see server.log for full trace)
`
玩家客户端始终显示 发现服务器

### Log File

在 ` server.log ` 中详细日志为
`
[00:12:39.307] [.NET TP Worker/DEBUG] [tML]: SSDP search line separator: CRLF
[00:12:54.240] [TCP Listen Thread/INFO] [Terraria]: ip:port is connecting...
[00:12:54.260] [Main Thread/WARN] [tML]: Silently Caught Exception: 
Interop+Crypto+OpenSslCryptographicException: error:03000098:digital envelope routines::invalid digest
   at Interop.Crypto.RsaVerifyHash(SafeEvpPKeyHandle pkey, RSASignaturePaddingMode paddingMode, IntPtr digestAlgorithm, ReadOnlySpan`1 hash, ReadOnlySpan`1 signature)
   at System.Security.Cryptography.RSAOpenSsl.VerifyHash(ReadOnlySpan`1 hash, ReadOnlySpan`1 signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSAPKCS1SignatureDeformatter.VerifySignature(Byte[] rgbHash, Byte[] rgbSignature)
   at Terraria.ModLoader.ModLoader.IsSignedBy(TmodFile mod, String xmlPublicKey) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 319
   at Terraria.ModLoader.Core.TmodFile.get_ValidModBrowserSignature() in tModLoader\Terraria\ModLoader\Core\TmodFile.cs:line 72
   at Terraria.ModLoader.ModNet.SyncMods(Int32 clientIndex) in tModLoader\Terraria\ModLoader\ModNet.cs:line 151
   at DMD<System.Void Terraria.MessageBuffer:GetData(System.Int32, System.Int32, System.Int32&)>(MessageBuffer this, Int32 start, Int32 length, Int32& messageType)
   at SyncProxy<System.Void Terraria.MessageBuffer:GetData(System.Int32, System.Int32, System.Int32&)>(MessageBuffer , Int32 , Int32 , Int32& )
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at Terraria.Netplay.UpdateServerInMainThread()
   at Terraria.Netplay.UpdateInMainThread()
   at Terraria.Main.DoUpdate(GameTime& gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods)
   at Terraria.Main.DedServ()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()
   at Terraria.MonoLaunch.Main(String[] args)

[00:12:54.261] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(Assembly assembly, String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, Boolean isFileLayout, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& sourceColumn)
   at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
   at DMD<System.Void System.Diagnostics.StackTrace:CaptureStackTrace(System.Int32, System.Boolean, System.Exception)>(StackTrace this, Int32 skipFrames, Boolean fNeedFileInfo, Exception e)
   at Hook<System.Void Terraria.ModLoader.Engine.LoggingHooks::Hook_StackTrace_CaptureStackTrace(Terraria.ModLoader.Engine.LoggingHooks+orig_StackTrace_CaptureStackTrace,System.Diagnostics.StackTrace,System.Int32,System.Boolean,System.Exception)>(StackTrace , Int32 , Boolean , Exception )
   at SyncProxy<System.Void System.Diagnostics.StackTrace:CaptureStackTrace(System.Int32, System.Boolean, System.Exception)>(StackTrace , Int32 , Boolean , Exception )
   at System.Exception.get_StackTrace()
   at System.Exception.ToString()
   at log4net.ObjectRenderer.DefaultRenderer.RenderObject(RendererMap rendererMap, Object obj, TextWriter writer)
   at log4net.ObjectRenderer.RendererMap.FindAndRender(Object obj, TextWriter writer)
   at log4net.ObjectRenderer.RendererMap.FindAndRender(Object obj)
   at log4net.Core.LoggingEvent.GetExceptionString()
   at log4net.Appender.AppenderSkeleton.RenderLoggingEvent(TextWriter writer, LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.RenderLoggingEvent(LoggingEvent loggingEvent)
   at log4net.Appender.DebugAppender.Append(LoggingEvent loggingEvent)
   at log4net.Appender.AppenderSkeleton.DoAppend(LoggingEvent loggingEvent)
   at log4net.Util.AppenderAttachedImpl.AppendLoopOnAppenders(LoggingEvent loggingEvent)
   at log4net.Repository.Hierarchy.Logger.CallAppenders(LoggingEvent loggingEvent)
   at log4net.Repository.Hierarchy.Logger.ForcedLog(Type callerStackBoundaryDeclaringType, Level level, Object message, Exception exception)
   at log4net.Repository.Hierarchy.Logger.Log(Type callerStackBoundaryDeclaringType, Level level, Object message, Exception exception)
   at log4net.Core.LogImpl.Error(Object message, Exception exception)
   at Terraria.ModLoader.ModNet.Error(String s, Exception e)
   at Terraria.ModLoader.ModNet.Error(Int32 whoAmI, String s, Exception e)
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
   at Terraria.Netplay.UpdateServerInMainThread()
   at Terraria.Netplay.UpdateInMainThread()
   at Terraria.Main.DoUpdate(GameTime& gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Terraria.Main.DedServ_PostModLoad(Boolean& reloadMods)
   at Terraria.Main.DedServ()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()
   at Terraria.MonoLaunch.Main(String[] args)

[00:12:54.260] [Main Thread/ERROR] [Network]: [0][ip:port (Anonymous)] Hello(1)
Interop+Crypto+OpenSslCryptographicException: error:03000098:digital envelope routines::invalid digest
   at Interop.Crypto.RsaVerifyHash(SafeEvpPKeyHandle pkey, RSASignaturePaddingMode paddingMode, IntPtr digestAlgorithm, ReadOnlySpan`1 hash, ReadOnlySpan`1 signature)
   at System.Security.Cryptography.RSAOpenSsl.VerifyHash(ReadOnlySpan`1 hash, ReadOnlySpan`1 signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash(Byte[] hash, Byte[] signature, HashAlgorithmName hashAlgorithm, RSASignaturePadding padding)
   at System.Security.Cryptography.RSAPKCS1SignatureDeformatter.VerifySignature(Byte[] rgbHash, Byte[] rgbSignature)
   at Terraria.ModLoader.ModLoader.IsSignedBy(TmodFile mod, String xmlPublicKey) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 319
   at Terraria.ModLoader.Core.TmodFile.get_ValidModBrowserSignature() in tModLoader\Terraria\ModLoader\Core\TmodFile.cs:line 72
   at Terraria.ModLoader.ModNet.SyncMods(Int32 clientIndex) in tModLoader\Terraria\ModLoader\ModNet.cs:line 151
   at DMD<System.Void Terraria.MessageBuffer:GetData(System.Int32, System.Int32, System.Int32&)>(MessageBuffer this, Int32 start, Int32 length, Int32& messageType)
   at SyncProxy<System.Void Terraria.MessageBuffer:GetData(System.Int32, System.Int32, System.Int32&)>(MessageBuffer , Int32 , Int32 , Int32& )
   at Terraria.NetMessage.CheckBytes(Int32 bufferIndex)
[00:14:54.250] [Main Thread/INFO] [Network]: [0][ip:port (Anonymous)] Terminating: Timeout
[00:14:54.252] [Server Loop Thread/INFO] [Network]: [0][ip:port (Anonymous)] Closing TcpSocket
`

### Steps to reproduce

1. Use steam server (y/n): n
2. Choose World: 1
3. Max players (press enter for 16): 
4. Server port (press enter for 7777): 
5. Automatically forward port? (y/n): 
6. Server password (press enter for none):

**Comment by JavidPack** [comment]
This looks like an issue that is fixed in https://github.com/tModLoader/tModLoader/commit/f0b1bf404739efcbdac7e5a4d9c686790f4f2467, which means it's in 2024.05 preview right now and will be in 2024.05 stable next month. You can test on preview if you'd like to confirm that the issue is fixed for next month if you'd like.

**Comment by AndreasByrsting** [comment]
> 这似乎是一个在[f0b1bf4](https://github.com/tModLoader/tModLoader/commit/f0b1bf404739efcbdac7e5a4d9c686790f4f2467)中修复的问题，这意味着它现在在2024.05 预览版中，下个月将在 2024.05 稳定版中出现。如果您想确认该问题在下个月是否已修复，请使用预览版上进行测试。

Alright, I will test it with the preview version later and give you feedback on the results. Thank you for your response

**Comment by AndreasByrsting** [comment]
> This looks like an issue that is fixed in [f0b1bf4](https://github.com/tModLoader/tModLoader/commit/f0b1bf404739efcbdac7e5a4d9c686790f4f2467), which means it's in 2024.05 preview right now and will be in 2024.05 stable next month. You can test on preview if you'd like to confirm that the issue is fixed for next month if you'd like.

Alright, I will test it with the preview version later and give you feedback on the results. Thank you for your response :D

**Comment by AndreasByrsting** [comment]
"It worked! I successfully joined the server and didn't encounter the mentioned errors. Thanks it was really helpful for me. I'm looking forward to the next stableupdate, when i will upload the existing Steam world to it. so i think this issue can be closed，thank u very much"
