### ISSUE TITLE
Game crash caused by Config

### ISSUE THREAD

**Issue by Silencersn** [bluemagic123/tModLoader#4281]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

When I open the special config, game crashed.

### Log File

[client.log](https://github.com/user-attachments/files/16053835/client.log)
```
System.Reflection.TargetParameterCountException: Parameter count mismatch.
   at System.Reflection.MethodBaseInvoker.ThrowTargetParameterCountException()
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at Terraria.ModLoader.Config.UI.PropertyFieldWrapper.GetValue(Object obj) in tModLoader\Terraria\ModLoader\Config\UI\PropertyFieldWrapper.cs:line 32
   at Terraria.ModLoader.Config.UI.ConfigElement.GetObject() in tModLoader\Terraria\ModLoader\Config\UI\ConfigElement.cs:line 133
   at Terraria.ModLoader.Config.UI.ConfigElement`1.get_Value() in tModLoader\Terraria\ModLoader\Config\UI\ConfigElement.cs:line 17
   at Terraria.ModLoader.Config.UI.ObjectElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\ObjectElement.cs:line 69
   at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 624
   at Terraria.ModLoader.Config.UI.ObjectElement.SetupList() in tModLoader\Terraria\ModLoader\Config\UI\ObjectElement.cs:line 272
   at Terraria.ModLoader.Config.UI.ObjectElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\ObjectElement.cs:line 198
   at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 624
   at Terraria.ModLoader.Config.UI.ListElement.SetupList() in tModLoader\Terraria\ModLoader\Config\UI\ListElement.cs:line 47
   at Terraria.ModLoader.Config.UI.CollectionElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 78
   at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 624
   at Terraria.ModLoader.Config.UI.UIModConfig.OnActivate() in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 495
   at Terraria.UI.UIElement.Activate() in tModLoader\Terraria\UI\UIElement.cs:line 452
   at Terraria.UI.UserInterface.SetState(UIState state) in tModLoader\Terraria\UI\UserInterface.cs:line 262
   at Terraria.ModLoader.UI.Interface.ModLoaderMenus(Main main, Int32 selectedMenu, String[] buttonNames, Single[] buttonScales, Int32[] buttonVerticalSpacing, Int32& offY, Int32& spacing, Int32& numButtons, Boolean& backButtonDown) in tModLoader\Terraria\ModLoader\UI\Interface.cs:line 389
   at Terraria.Main.DrawMenu(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 43757
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 53362
   at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52927
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 52914
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266

```
### Steps to reproduce
```
namespace Demo
{
    public class MyConfig : ModConfig
    {
        public override ConfigScope Mode => ConfigScope.ClientSide;

        public List<object> Objects { get; set; } = [new MyObject()];
    }

    public class MyObject
    {
        public string Name { get; set; }
    }
}
```
### Expected Behavior

Show as object or show something like "This object could not be shown".

### Actual Behavior

Game crashed.

### Reproduction frequency

All the time.

**Comment by JavidPack** [comment]
This will no longer crash and will now show "FIELDNAME can't be of the Type Object."
