### ISSUE TITLE
Every time I start it throws an error

### ISSUE THREAD

**Issue by latesfun2** [bluemagic123/tModLoader#4298]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

[16:38:08.858] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.4.9+2024.05.3.3|2024.05|stable|Stable|a6627c59393a3bfd2a461fcd787dc95a50ba0b9f|5250246912586725617 built 09.07.2024 9:36
[16:38:08.875] [Main Thread/INFO] [tML]: Log date: 13.07.2024
[16:38:08.876] [Main Thread/INFO] [tML]: Running on Windows (v6.2.9200.0) X64 NetCore 8.0.0
[16:38:08.885] [Main Thread/INFO] [tML]: CPU: 8 processors. RAM: 11,9 GB
[16:38:08.885] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 8.0.0
[16:38:08.885] [Main Thread/INFO] [tML]: Executable: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\tModLoader.dll
[16:38:08.885] [Main Thread/INFO] [tML]: Working Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader
[16:38:09.611] [Main Thread/INFO] [tML]: No config.json found at C:/Users/ASUS\Documents\My Games\Terraria\tModLoader\config.json
Assuming nothing to port
[16:38:09.612] [Main Thread/WARN] [tML]: Saves paths had incorrect slashes somehow: "C:/Users/ASUS\Documents\My Games\Terraria\tModLoader"=>"C:\Users\ASUS\Documents\My Games\Terraria\tModLoader", "C:/Users/ASUS\Documents\My Games\Terraria\tModLoader"=>"C:\Users\ASUS\Documents\My Games\Terraria\tModLoader"
[16:38:09.612] [Main Thread/INFO] [tML]: Saves Are Located At: C:\Users\ASUS\Documents\My Games\Terraria\tModLoader
[16:38:09.635] [Main Thread/INFO] [tML]: Display DPI: Diagonal DPI is 96. Vertical DPI is 96. Horizontal DPI is 96
[16:38:09.635] [Main Thread/INFO] [tML]: High DPI Display detected: setting FNA to highdpi mode
[16:38:09.641] [Main Thread/DEBUG] [FNA]: Querying linked library versions...
[16:38:09.642] [Main Thread/DEBUG] [FNA]: SDL v2.28.2
[16:38:09.643] [Main Thread/DEBUG] [FNA]: FNA3D v23.10.0
[16:38:09.646] [Main Thread/DEBUG] [FNA]: FAudio v22.9.1
[16:38:10.449] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[16:38:10.470] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "C:\Program Files (x86)\Steam\steamapps\common\tModLoader\dotnet\dotnet.exe" tModLoader.dll -terrariasteamclient 1680
[16:38:11.469] [Main Thread/DEBUG] [TerrariaSteamClient]: Recv: init_success
[16:38:11.470] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: acknowledged
[16:38:12.839] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 952.0 MB available
[16:38:12.839] [Main Thread/INFO] [tML]: Steam beta branch: None
[16:38:12.840] [Main Thread/INFO] [tML]: SteamBackend: Running standard Steam Desktop Client API
[16:38:12.841] [Main Thread/INFO] [tML]: Current 1281930 Workshop Folder Directory: C:\Program Files (x86)\Steam\steamapps\common\tModLoader\..\..\workshop
[16:38:12.971] [Main Thread/INFO] [FNA]: SDL Video Diver: windows
[16:38:12.971] [Main Thread/INFO] [FNA]: FNA3D Driver: D3D11
[16:38:12.972] [Main Thread/INFO] [FNA]: D3D11 Adapter: Intel(R) HD Graphics 3000
[16:38:12.976] [Main Thread/INFO] [FNA]: SetStringMarker not supported!
[16:38:12.981] [Main Thread/ERROR] [FNA]: Could not create swapchain! Error Code: �������� ����� �������. (0x80070057)
[16:38:13.015] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.InvalidOperationException: Could not create swapchain! Error Code: �������� ����� �������. (0x80070057)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateDevice(FNA3D_PresentationParameters& presentationParameters, Byte debugMode)
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateDevice(FNA3D_PresentationParameters& presentationParameters, Byte debugMode)
   at Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_CreateDevice(FNA3D_PresentationParameters& presentationParameters, Byte debugMode) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\FNA3D_SafeAccess.cs:line 21
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\GraphicsDevice.cs:line 405
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice() in D:\a\tModLoader\tModLoader\FNA\src\GraphicsDeviceManager.cs:line 546
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 776
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 411
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 213
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 79
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in tModLoader\Terraria\MonoLaunch.cs:line 65

[16:38:13.021] [Main Thread/WARN] [tML]: Silently Caught Exception: 
Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Could not create swapchain! Error Code: �������� ����� �������. (0x80070057)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\GraphicsDevice.cs:line 405
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice() in D:\a\tModLoader\tModLoader\FNA\src\GraphicsDeviceManager.cs:line 546
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 776
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 411
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
   at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 240
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 213
   at Terraria.MonoLaunch.Main_End(String[] args) in tModLoader\Terraria\MonoLaunch.cs:line 79
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in tModLoader\Terraria\MonoLaunch.cs:line 65

[16:38:13.027] [Main Thread/FATAL] [tML]: Main engine crash

Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Could not create swapchain! Error Code: �������� ����� �������. (0x80070057)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\GraphicsDevice.cs:line 420
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice() in D:\a\tModLoader\tModLoader\FNA\src\GraphicsDeviceManager.cs:line 546
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 776
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 411
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
[16:38:13.028] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

**Comment by JavidPack** [comment]
I believe your graphics card, `Intel(R) HD Graphics 3000`, does not support the minimum specifications required for tModLoader (DirectX 11). Unfortunately there isn't anything you can do to change this I believe, aside from upgrading your computer/gpu.

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
