### ISSUE TITLE
fail to play

### ISSUE THREAD

**Issue by xiexishan** [bluemagic123/tModLoader#4302]
### Version

Latest 1.4.4-preview

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Stuck while playing

### Log File

[23:06:35.982] [Main Thread/ERROR] [FNA]: Texture2D creation failed! Error Code: GPU (0x887A0006)
[23:06:35.987] [Main Thread/WARN] [tML]: 静默捕获异常: 
System.InvalidOperationException: Texture2D creation failed! Error Code: GPU (0x887A0006)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateTexture2D(IntPtr device, SurfaceFormat format, Int32 width, Int32 height, Int32 levelCount, Byte isRenderTarget)
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateTexture2D(IntPtr device, SurfaceFormat format, Int32 width, Int32 height, Int32 levelCount, Byte isRenderTarget)
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat format) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\Texture2D.cs:line 116
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 132
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 92
   at Luminance.Core.Graphics.PrimitivePixelationSystem.CreatePixelTarget(Int32 width, Int32 height) in Luminance\Core\Graphics\Primitives\PrimitivePixelationSystem.cs:line 25
   at Luminance.Core.Graphics.ManagedRenderTarget.Recreate(Int32 screenWidth, Int32 screenHeight) in Luminance\Core\Graphics\Automators\ManagedRenderTarget.cs:line 148
   at Luminance.Core.Graphics.RenderTargetManager.<>c__DisplayClass10_0.<PerformTargetResetCheck>b__0() in Luminance\Core\Graphics\Automators\RenderTargetManager.cs:line 107
   at Terraria.Main.ConsumeAllMainThreadActions() in tModLoader\Terraria\Main.cs:line 14161
   at DMD<System.Void Terraria.Main:Update(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at Hook<System.Void ThoriumMod.UI.ThoriumInterfaceResources::OnResolutionChanged(Terraria.On_Main+orig_Update,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at SyncProxy<System.Void Terraria.Main:Update(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()

[23:06:37.791] [Main Thread/WARN] [tML]: 静默捕获异常: 
System.BadImageFormatException: Read out of bounds.
   at System.Reflection.Throw.OutOfBounds()
   at System.Diagnostics.StackTraceSymbols.GetSourceLineInfo(Assembly assembly, String assemblyPath, IntPtr loadedPeAddress, Int32 loadedPeSize, Boolean isFileLayout, IntPtr inMemoryPdbAddress, Int32 inMemoryPdbSize, Int32 methodToken, Int32 ilOffset, String& sourceFile, Int32& sourceLine, Int32& sourceColumn)
   at System.Diagnostics.StackFrameHelper.InitializeSourceInfo(Int32 iSkip, Boolean fNeedFileInfo, Exception exception)
   at DMD<System.Void System.Diagnostics.StackTrace:CaptureStackTrace(System.Int32, System.Boolean, System.Exception)>(StackTrace this, Int32 skipFrames, Boolean fNeedFileInfo, Exception e)
   at Hook<System.Void Terraria.ModLoader.Engine.LoggingHooks::Hook_StackTrace_CaptureStackTrace(Terraria.ModLoader.Engine.LoggingHooks+orig_StackTrace_CaptureStackTrace,System.Diagnostics.StackTrace,System.Int32,System.Boolean,System.Exception)>(StackTrace , Int32 , Boolean , Exception )
   at SyncProxy<System.Void System.Diagnostics.StackTrace:CaptureStackTrace(System.Int32, System.Boolean, System.Exception)>(StackTrace , Int32 , Boolean , Exception )
   at System.Exception.get_StackTrace()
   at System.Exception.ToString()
   at Terraria.ModLoader.Engine.ErrorReporting.FatalExit(String message, Exception e)
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()

[23:06:37.794] [Main Thread/FATAL] [tML]: Main engine crash

提示：很有可能是哪个模组崩溃了。你可以试着逐个禁用模组看看问题是否仍会重复出现。

System.InvalidOperationException: Texture2D creation failed! Error Code: GPU (0x887A0006)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg) in D:\a\tModLoader\tModLoader\FNA\src\FNALoggerEXT.cs:line 98
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateTexture2D(IntPtr device, SurfaceFormat format, Int32 width, Int32 height, Int32 levelCount, Byte isRenderTarget)
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat format) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\Texture2D.cs:line 116
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipMap, SurfaceFormat preferredFormat, DepthFormat preferredDepthFormat, Int32 preferredMultiSampleCount, RenderTargetUsage usage) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 132
   at Microsoft.Xna.Framework.Graphics.RenderTarget2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\RenderTarget2D.cs:line 92
   at Luminance.Core.Graphics.PrimitivePixelationSystem.CreatePixelTarget(Int32 width, Int32 height) in Luminance\Core\Graphics\Primitives\PrimitivePixelationSystem.cs:line 25
   at Luminance.Core.Graphics.ManagedRenderTarget.Recreate(Int32 screenWidth, Int32 screenHeight) in Luminance\Core\Graphics\Automators\ManagedRenderTarget.cs:line 148
   at Luminance.Core.Graphics.RenderTargetManager.<>c__DisplayClass10_0.<PerformTargetResetCheck>b__0() in Luminance\Core\Graphics\Automators\RenderTargetManager.cs:line 107
   at Terraria.Main.ConsumeAllMainThreadActions() in tModLoader\Terraria\Main.cs:line 14161
   at DMD<System.Void Terraria.Main:Update(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at Hook<System.Void ThoriumMod.UI.ThoriumInterfaceResources::OnResolutionChanged(Terraria.On_Main+orig_Update,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at SyncProxy<System.Void Terraria.Main:Update(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
[23:06:37.808] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

**Comment by Chicken-Bones** [comment]
Seems like your GPU gave up. Maybe you have an old GPU and too many fancy mods.

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
