### ISSUE TITLE
TagCompound Collection Serialization Too Naive

### ISSUE THREAD

**Issue by steviegt6** [bluemagic123/tModLoader#4316]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

Attempting to serialize an array of `TagCompound`s errors with a cryptic error message.

See: https://github.com/Path-of-Terraria/PathOfTerraria/issues/288

### Log File

```
[21:58:37.894] [.NET TP Worker/ERROR] [tML]: Unhandled Exception
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__21_21(BinaryWriter w, IList v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 113
   at Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 41
   at Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 325
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__21_24(BinaryWriter w, TagCompound v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 142
   at Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 41
   at Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 325
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__21_24(BinaryWriter w, TagCompound v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 142
   at Terraria.ModLoader.IO.TagIO.PayloadHandler`1.WriteList(BinaryWriter w, IList list) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 55
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__21_21(BinaryWriter w, IList v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 120
   at Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 41
   at Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 325
   at Terraria.ModLoader.IO.TagIO.<>c.<.cctor>b__21_24(BinaryWriter w, TagCompound v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 142
   at Terraria.ModLoader.IO.TagIO.PayloadHandler`1.Write(BinaryWriter w, Object v) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 41
   at Terraria.ModLoader.IO.TagIO.WriteTag(String name, Object tag, BinaryWriter w) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 325
   at Terraria.ModLoader.IO.TagIO.Write(TagCompound root, BinaryWriter writer) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 381
   at Terraria.ModLoader.IO.TagIO.ToStream(TagCompound root, Stream stream, Boolean compress) in tModLoader\Terraria\ModLoader\IO\TagIO.cs:line 377
   at Terraria.Utilities.FileUtilities.WriteTagCompound(String path, Boolean isCloud, TagCompound tag) in tModLoader\Terraria\Utilities\FileUtilities.TML.cs:line 124
   at Terraria.ModLoader.IO.PlayerIO.Save(TagCompound tag, String path, Boolean isCloudSave) in tModLoader\Terraria\ModLoader\IO\PlayerIO.cs:line 37
   at Terraria.Player.SavePlayerFile_Write(PlayerFileData playerFile, Byte[] plrData, TagCompound tplrData) in tModLoader\Terraria\Player.cs:line 44779
   at Terraria.Player.InternalSavePlayerFile(PlayerFileData playerFile) in tModLoader\Terraria\Player.cs:line 44736
   at Terraria.Player.<>c__DisplayClass1967_0.<SavePlayer>b__0() in tModLoader\Terraria\Player.cs:line 44694
   at Terraria.Utilities.FileUtilities.ProtectedInvoke(Action action) in tModLoader\Terraria\Utilities\FileUtilities.cs:line 207
   at DMD<System.Void Terraria.Player:SavePlayer(Terraria.IO.PlayerFileData, System.Boolean)>(PlayerFileData playerFile, Boolean skipMapSave)
   at SyncProxy<System.Void Terraria.Player:SavePlayer(Terraria.IO.PlayerFileData, System.Boolean)>(PlayerFileData , Boolean )
   at Terraria.WorldGen.SaveAndQuitCallBack(Object threadContext)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Steps to reproduce

```cs
	public override void SaveData(TagCompound tag)
	{
		tag["inventory"] = new TagCompound[] { /* ... */ };
	}
```

### Expected Behavior

Either support `TagCompound[]` or produce a better error message.

### Actual Behavior

![351941734-6bac9a3e-7038-4fc1-a475-481c0b8df1dd](https://github.com/user-attachments/assets/3c7d1a26-5415-4dae-95bf-64232b19c32e)
![351941782-e4d21bde-2837-4519-9e79-1291e8ca1cd0](https://github.com/user-attachments/assets/d658847e-1a7b-4821-8ec4-9f3d895b5b95)

### Reproduction frequency

100%

### Additional Information

N/A

**Comment by steviegt6** [comment]
```cs
		new ClassPayloadHandler<IList>(
			r => GetHandler(r.ReadByte()).ReadList(r, r.ReadInt32()),
			(w, v) => {
				int id;
				try {
					id = GetPayloadId(v.GetType().GetGenericArguments()[0]);
				}
				catch (IOException) {
					throw new IOException("Invalid NBT list type: " + v.GetType());
				}
				w.Write((byte)id);
				w.Write(v.Count);
				PayloadHandlers![id].WriteList(w, v);
			},
```

The payload handler does not handle `IList` very well. It assumes a generic parameter on the actual type being serialized, meaning types list `List<T>` work but `TagCompound[]` and other array types don't. `Type::GetElementType` may be used in the context of an array, but more advanced checks may be required for complex cases like non-generic `IList` or `IList<T>` implementations.

**Comment by Chicken-Bones** [comment]
One of the reasons not to serialize array types is that we'd have to deserialize as a `List` and use `ToArray` regardless. You're certainly right that the error message should be better

**Comment by steviegt6** [comment]
Lists and arrays both fulfill the `IList<T>` interface.

**Comment by Chicken-Bones** [comment]
We had tests for arrays (and even multidimensional arrays) but they didn't actually cover serializing to/from a stream, only storing and retrieving from the `TagCompound`.

It was an easy one line fix, because as you pointed out, arrays fulfil the `IList<T>` interface
