### ISSUE TITLE
Playing modded terriara on a dedicated server lags

### ISSUE THREAD

**Issue by bjccdsrlcr** [bluemagic123/tModLoader#4334]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

1. about 5 player in this dedicated server, and the dotnet cpu 40%
2. only 1 player lags, can't pickup items  
3. use `ss -t`, found that lagging player has more packets in tcp send Queue
$ ss -t
State   Recv-Q  Send-Q       Local Address:Port          Peer Address:Port
ESTAB     0           14           192.168.14.84:7777         111.23.215.163:29216
ESTAB     0           0             192.168.14.84:7777         27.47.169.154:23185
ESTAB     0           64           192.168.14.84:ssh            121.36.59.153:47051
ESTAB     0           14           192.168.14.84:7777         139.227.130.49:15598
ESTAB     0           7             192.168.14.84:7777         112.47.168.100:26581
**ESTAB     0           1324       192.168.14.84:7777         124.14.99.73:22667**
as you san see, the 1324 packets to send may cause the lag, when we fight with a boss, the packets can up to 10000, other player only around 500~600; 

lagging player computer is not so bad, windows 10, and the dotnot process cpu  35% memory 43% gpu 29%

**Comment by JavidPack** [comment]
Networking issues are particularly hard to diagnose, but I have a few suggestions.

While playing, press `F8` twice to bring up the mod network diagnostics menu. While experiencing lag, try to look at the numbers presented as they change and identify any mod that might be sending or receiving a disproportionally large amount of data. A mod constantly sending data could be incorrectly programmed and would likely need to be disabled. 

![image](https://github.com/user-attachments/assets/5ba0fc45-a9f9-4cb5-a370-e7b1833c572b)

Another thing to try is narrowing down the issue. For example, does the issue happen with just the lagging player on the server? Does the issue happen only on this world? Does the issue resolve itself if the lagging player joins with a newly created player? Does the issue fix itself if you try with 0 mods? Does the issue still happen if the lagging player hosts?

And finally, read the client.log (https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#reading-clientlog) of the lagging player, if there are any exceptions there is likely an issue that will need to be fixed, most likely be disabling a mod.

**Comment by bjccdsrlcr** [comment]
OK, I will troubleshoot step-by-step according to your suggestion. If I find the reason, will back to reply in this issue.

**Comment by bjccdsrlcr** [comment]
[14:23:47.723] [TCP Client Thread/INFO] [Terraria]: Connecting to 116.205.138.13:7777
[14:23:48.004] [TCP Client Thread/INFO] [StatusText]: 连接到116.205.138.13:7777
[14:23:48.006] [TCP Client Thread/INFO] [StatusText]: 发现服务器
[14:23:51.940] [Main Thread/INFO] [StatusText]: 同步模组
[14:23:51.942] [Main Thread/INFO] [tML]: Finding Mods...
[14:23:51.953] [Main Thread/DEBUG] [tML]: Server mods:
		BossChecklist v2.2.1[64e53f29]
		CalamityHunt v1.1.3[734533d9]
		CalamityModMusic v2.0.4.3[df93aad5]
		CalamityMod v2.0.4.3[cdabceea]
		CatalystMod v1.1.2.3[6aa266bc]
		ColoredCalRelics v1.0.7[0726a542]
		Consolaria v2.1.0.13[932808b5]
		DPSExtreme v0.3.1.4[951a030f]
		SerousCommonLib v1.0.5.1[b8310598]
		MagicStorage v0.6.0.3[c0f57bfb]
		RecipeBrowser v0.10.7[2b0706af]
		WeaponDisplay v1.20.1[11199aca]
[14:23:51.954] [Main Thread/DEBUG] [tML]: Download queue: 
[14:23:51.954] [Main Thread/DEBUG] [tML]: Configs:
		Consolaria:ConsolariaConfig {}
		MagicStorage:MagicStorageServerConfig {}
		WeaponDisplay:ConfigurationServer {"ItemAttackCD":7,"ParryItems":[{"Mod":"WeaponDisplay","Name":"旧日支配者","DisplayName":"Great Old Ones"},{"Mod":"WeaponDisplay","Name":"真旧日支配者","DisplayName":"True Great Old Ones"},{"Name":"TheHorsemansBlade","DisplayName":"The Horseman's Blade"}]}
[14:24:26.530] [TCP Client Thread/INFO] [StatusText]: 正在加载地图数据：
[14:24:26.716] [TCP Client Thread/INFO] [StatusText]: 正在绘制地图：
[14:24:26.720] [TCP Client Thread/INFO] [StatusText]: 正在请求图格数据
[14:24:27.127] [TCP Client Thread/INFO] [StatusText]: 正在接收图格数据
[14:24:27.251] [TCP Client Thread/INFO] [StatusText]: 正在接收图格数据：完成！
[14:24:27.419] [Main Thread/INFO] [Terraria]: Entering world with player: 小卿, IsCloud=False, Width: 8400, Height: 2400, Evil: 0, GameMode: 1
[14:24:32.024] [Main Thread/INFO] [tML]: tModLoader RAM usage has increased: 4.2 GB
[14:24:46.874] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: HiDef, Width: 1062 -> 1920, Height: 720 -> 991, Fullscreen: False, Display: \\.\DISPLAY1
[14:24:51.101] [.NET TP Worker/DEBUG] [tML]: Assembly Resolve: System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a -> System.Net.Security.resources, Version=8.0.0.0, Culture=zh-CN, PublicKeyToken=b03f5f7f11d50a3a
[14:24:51.102] [.NET TP Worker/DEBUG] [tML]: Assembly Resolve: System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a -> System.Net.Security.resources, Version=8.0.0.0, Culture=zh-Hans, PublicKeyToken=b03f5f7f11d50a3a
[14:24:51.103] [.NET TP Worker/DEBUG] [tML]: Assembly Resolve: System.Net.Security, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a -> System.Net.Security.resources, Version=8.0.0.0, Culture=zh, PublicKeyToken=b03f5f7f11d50a3a
[14:24:51.111] [.NET TP Worker/WARN] [tML]: 静默捕获异常: 
System.IO.IOException: The read operation failed, see inner exception.
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext()
   at System.Net.Security.SslStream.EnsureFullTlsFrameAsync[TIOAdapter](CancellationToken cancellationToken, Int32 estimatedSize)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.MoveNext()
   at System.Net.Sockets.SocketAsyncEventArgs.<>c.<.cctor>b__173_0(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   at System.Threading.PortableThreadPool.IOCompletionPoller.Callback.Invoke(Event e)
   at System.Threading.ThreadPoolTypedWorkItemQueue`2.System.Threading.IThreadPoolWorkItem.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

[14:24:52.836] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: HiDef, Width: 1920 -> 1062, Height: 991 -> 720, Fullscreen: False, Display: \\.\DISPLAY1
[14:24:52.852] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: HiDef, Width: 1062, Height: 720, Fullscreen: False, Display: \\.\DISPLAY1
[14:27:22.747] [TCP Client Thread/INFO] [StatusText]: 正在接收图格数据
[14:27:22.755] [TCP Client Thread/INFO] [StatusText]: 正在接收图格数据：完成！
[14:29:12.451] [Main Thread/INFO] [BossChecklist]: 渐进式日志已启用
[14:29:25.238] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: HiDef, Width: 1062 -> 1920, Height: 720 -> 991, Fullscreen: False, Display: \\.\DISPLAY1
[14:30:52.768] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: HiDef, Width: 1920 -> 1062, Height: 991 -> 720, Fullscreen: False, Display: \\.\DISPLAY1
[14:30:52.799] [Main Thread/DEBUG] [Terraria]: Device Reset, Adapter: Generic PnP Monitor, DisplayMode: {{Width:1920 Height:1080 Format:Color}}, Profile: HiDef, Width: 1062, Height: 720, Fullscreen: False, Display: \\.\DISPLAY1

**Comment by bjccdsrlcr** [comment]
hi, I find some error log in `client.log`, will this matters?

**Comment by JavidPack** [comment]
I'm not sure what that error is right now, but it seems like if it was the cause it would prevent all networking and wouldn't just causes lag. Keep trying the other suggestions.

**Comment by bjccdsrlcr** [comment]
yes， I found the reason of lags is because of a anti-virus software called "360 Security Guard", exit the software, and the lags disappeared!  really incredible

Document it to prevent others from encountering the same problem....
