### ISSUE TITLE
ModOrganizer.EnsureRecentlyBuildModsAreLoading failed to throw Exception with message ModLoader.LoadErrorRecentlyBuiltLocalModWithLowerVersion and modname.

### ISSUE THREAD

**Issue by TunaFish2K** [bluemagic123/tModLoader#4338]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

i got the latest Calamity Mod installed from steam workshop and put an older version inside %user%\Documents\My Games\Terraria\tModLoader\Mods.
in the mod menu however only one version is shown. If you enable it, when loading it will throw an exception:
```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Terraria.ModLoader.Core.ModOrganizer.EnsureRecentlyBuildModsAreLoading(List`1 mods) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 463
   at Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods(IEnumerable`1 availableMods, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 374
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 124
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass46_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 109
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```
the exception thrown by:(/tModLoader/Terraria/ModLoader/Core/ModOrganizer.cs:463)
```csharp
var localMod = AllFoundMods.SingleOrDefault(x => x.Name == mod.Name && x.location == ModLocation.Local);
```
after i remove the older version no exception is raised,
so im pretty sure its not an issue about Calamity.
i guess we should catch the possible exception and throw another with message like "version conflict:${mod_name}"

### Log File

[client.log](https://github.com/user-attachments/files/16556971/client.log)

### Steps to reproduce

1. install Calamity from steam workshop.
2. get another older version of Calamity and put it in %user%\Documents\My Games\Terraria\tModLoader\Mods.
3. enable calamity and exit the mod menu.

### Expected Behavior

Calamity is successfully loaded.

### Actual Behavior

an exception will be thrown.
```
System.InvalidOperationException: Sequence contains more than one matching element
   at System.Linq.ThrowHelper.ThrowMoreThanOneMatchException()
   at System.Linq.Enumerable.TryGetSingle[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at Terraria.ModLoader.Core.ModOrganizer.EnsureRecentlyBuildModsAreLoading(List`1 mods) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 463
   at Terraria.ModLoader.Core.ModOrganizer.SelectAndSortMods(IEnumerable`1 availableMods, CancellationToken token) in tModLoader\Terraria\ModLoader\Core\ModOrganizer.cs:line 374
   at Terraria.ModLoader.ModLoader.Load(CancellationToken token) in tModLoader\Terraria\ModLoader\ModLoader.cs:line 124
   at Terraria.ModLoader.ModLoader.<>c__DisplayClass46_0.<BeginLoad>b__0() in tModLoader\Terraria\ModLoader\ModLoader.cs:line 109
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
```

### Reproduction frequency

always.

**Comment by JavidPack** [comment]
Thanks for the report, I've been working on a fix and will have it fixed rather soon.
