### ISSUE TITLE
System.IO.FileNotFoundException: Could not load file or assembly System.Runtime.Intrinsics

### ISSUE THREAD

**Issue by Mark-Pineda-C** [bluemagic123/tModLoader#4375]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

until a couple of hours ago everything worked fine, but suddenly I get this error when I want to start the game.

![{48796752-B2C4-4D0B-82FD-451C87F038F5}](https://github.com/user-attachments/assets/9868e70d-81a7-4b6a-b011-2dd468c50a5f)

### Log File

[23:18:49.637] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.4.9+2024.07.3.1|2024.07|stable|Stable|eb67fa4c28886b38b0c350a4b008e4fd3e73b36d|5250293797007678076 built 1/09/2024 03:57
[23:18:49.643] [Main Thread/INFO] [tML]: Log date: 10/09/2024
[23:18:49.644] [Main Thread/INFO] [tML]: Running on Windows (v10.0.22631.0) X64 NetCore 8.0.0
[23:18:49.646] [Main Thread/INFO] [tML]: CPU: 12 processors. RAM: 31.9 GB
[23:18:49.646] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 8.0.0
[23:18:49.646] [Main Thread/INFO] [tML]: Executable: D:\SteamLibrary\steamapps\common\tModLoader\tModLoader.dll
[23:18:49.646] [Main Thread/INFO] [tML]: Working Directory: D:\SteamLibrary\steamapps\common\tModLoader
[23:18:49.881] [Main Thread/DEBUG] [tML]: Assembly Resolve: System.Reflection.Metadata, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a -> System.Reflection.Metadata.resources, Version=8.0.0.0, Culture=es-MX, PublicKeyToken=b03f5f7f11d50a3a
[23:18:49.883] [Main Thread/DEBUG] [tML]: Assembly Resolve: System.Reflection.Metadata, Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a -> System.Reflection.Metadata.resources, Version=8.0.0.0, Culture=es, PublicKeyToken=b03f5f7f11d50a3a
[23:18:49.890] [Main Thread/WARN] [tML]: tModLoader.RuntimeErrorSilentlyCaughtException
System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Intrinsics, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. El sistema no puede encontrar el archivo especificado.
   at Terraria.ModLoader.Engine.LogArchiver.Archive()
   at Terraria.ModLoader.Engine.LogArchiver.ArchiveLogs()
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ)
   at Terraria.Program.StartupSequenceTml(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()

[23:18:49.894] [Main Thread/FATAL] [tML]: An unexpected error occurred during tML startup

System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime.Intrinsics, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. El sistema no puede encontrar el archivo especificado.
File name: 'System.Runtime.Intrinsics, Version=8.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'
   at Terraria.ModLoader.Engine.LogArchiver.Archive() in tModLoader\Terraria\ModLoader\Engine\LogArchiver.cs:line 120
   at Terraria.ModLoader.Engine.LogArchiver.ArchiveLogs() in tModLoader\Terraria\ModLoader\Engine\LogArchiver.cs:line 34
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in tModLoader\Terraria\ModLoader\Logging.cs:line 104
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in tModLoader\Terraria\Program.TML.cs:line 344

### Additional Information

windows 11 user

**Comment by JavidPack** [comment]
That `System.Runtime.Intrinsics.dll` file should be inside `D:\SteamLibrary\steamapps\common\tModLoader\dotnet\shared\Microsoft.NETCore.App\8.0.0\`. Since it is not, that means it got deleted somehow, usually the main culprit is antivirus programs quarantining the file.

These instructions go over what to do, deleting the dotnet folder and making sure your antivirus isn't quarantining the tModLoader files: https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#delete-dotnet-folder

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
