### ISSUE TITLE
can't find a suitable graphics device

### ISSUE THREAD

**Issue by TheBearodactyl** [bluemagic123/tModLoader#4405]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

the game won't launch

### Log File

[06:09:43.201] [Main Thread/INFO] [tML]: Starting tModLoader client 1.4.4.9+2024.08.3.2|2024.08|stable|Stable|e139bc1c3dcd5fabf6865fbc3de4fe88be9f9ca2|5250319477331921743 built 9/30/2024 9:18 PM
[06:09:43.206] [Main Thread/INFO] [tML]: Log date: 10/10/2024
[06:09:43.206] [Main Thread/INFO] [tML]: Running on Windows (v10.0.22631.0) X64 NetCore 8.0.0
[06:09:43.208] [Main Thread/INFO] [tML]: CPU: 24 processors. RAM: 29.7 GB
[06:09:43.208] [Main Thread/INFO] [tML]: FrameworkDescription: .NET 8.0.0
[06:09:43.208] [Main Thread/INFO] [tML]: Executable: D:\SteamLibrary\steamapps\common\tModLoader\tModLoader.dll
[06:09:43.209] [Main Thread/INFO] [tML]: Working Directory: D:\SteamLibrary\steamapps\common\tModLoader
[06:09:43.351] [Main Thread/INFO] [tML]: Ensuring OneDrive is running before starting to Migrate Files
[06:09:43.352] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "C:/Users/thebe\AppData\Local\Microsoft\OneDrive\OneDrive.exe" /background
[06:09:46.402] [Main Thread/INFO] [tML]: Attempt to Port from "C:\Users\thebe\OneDrive\Documents\My Games\Terraria\tModLoader" to "C:\Users\thebe\OneDrive\Documents\My Games\Terraria\tModLoader-1.4.3" aborted, "2024.8.3.2" is a newer version.
[06:09:46.402] [Main Thread/INFO] [tML]: Saves Are Located At: C:\Users\thebe\OneDrive\Documents\My Games\Terraria\tModLoader
[06:09:46.403] [Main Thread/INFO] [tML]: Developer mode enabled
[06:09:46.409] [Main Thread/INFO] [tML]: Display DPI: Diagonal DPI is 96. Vertical DPI is 96. Horizontal DPI is 96
[06:09:46.409] [Main Thread/INFO] [tML]: High DPI Display detected: setting FNA to highdpi mode
[06:09:46.411] [Main Thread/DEBUG] [FNA]: Querying linked library versions...
[06:09:46.411] [Main Thread/DEBUG] [FNA]: SDL v2.28.2
[06:09:46.411] [Main Thread/DEBUG] [FNA]: FNA3D v23.10.0
[06:09:46.413] [Main Thread/DEBUG] [FNA]: FAudio v22.9.1
[06:09:46.590] [Main Thread/INFO] [tML]: Distribution Platform: Steam. Detection method: CWD is /steamapps/
[06:09:46.595] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = False): "D:\SteamLibrary\steamapps\common\tModLoader\dotnet\dotnet.exe" tModLoader.dll -terrariasteamclient 1704
[06:09:46.818] [Main Thread/DEBUG] [TerrariaSteamClient]: Recv: init_success
[06:09:46.818] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: acknowledged
[06:09:47.170] [Main Thread/INFO] [FNA]: SDL.SDL_Init(SDL.SDL_INIT_VIDEO)...
[06:09:47.171] [Main Thread/INFO] [FNA]: Success
[06:09:47.171] [Main Thread/INFO] [FNA]: SDL.SDL_InitSubSystem(SDL.SDL_INIT_GAMECONTROLLER)...
[06:09:47.184] [Main Thread/INFO] [FNA]: Success
[06:09:47.350] [Main Thread/INFO] [tML]: Attempt to Port from "C:\Program Files (x86)\Steam\userdata\1159196328\105600\remote\tModLoader" to "C:\Program Files (x86)\Steam\userdata\1159196328\105600\remote\tModLoader-1.4.3" aborted, "2024.8.3.2" is a newer version.
[06:09:47.355] [Main Thread/INFO] [Terraria]: Steam Cloud Quota: 930.1 MB available
[06:09:47.355] [Main Thread/INFO] [tML]: Steam beta branch: None
[06:09:47.356] [Main Thread/INFO] [tML]: SteamBackend: Running standard Steam Desktop Client API
[06:09:47.356] [Main Thread/INFO] [tML]: Current 1281930 Workshop Folder Directory: D:\SteamLibrary\steamapps\common\tModLoader\..\..\workshop
[06:09:47.493] [Main Thread/INFO] [FNA]: SDL Video Diver: windows
[06:09:47.494] [Main Thread/INFO] [FNA]: FNA3D Driver: D3D11
[06:09:47.494] [Main Thread/INFO] [FNA]: D3D11 Adapter: NVIDIA GeForce RTX 4060 Laptop GPU
[06:09:47.533] [Main Thread/ERROR] [FNA]: Could not create swapchain! Error Code: The operation completed successfully. (0x00000000)
[06:09:47.542] [Main Thread/WARN] [tML]: Silently Caught Exception: 
System.InvalidOperationException: Could not create swapchain! Error Code: The operation completed successfully. (0x00000000)
   at Microsoft.Xna.Framework.FNALoggerEXT.FNA3DLogError(IntPtr msg)
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateDevice(FNA3D_PresentationParameters& presentationParameters, Byte debugMode)
   at Microsoft.Xna.Framework.Graphics.FNA3D_Impl.FNA3D_CreateDevice(FNA3D_PresentationParameters& presentationParameters, Byte debugMode)
   at Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_CreateDevice(FNA3D_PresentationParameters& presentationParameters, Byte debugMode)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()

[06:09:47.545] [Main Thread/WARN] [tML]: Silently Caught Exception: 
Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Could not create swapchain! Error Code: The operation completed successfully. (0x00000000)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters)
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
   at Terraria.Program.LaunchGame_(Boolean isServer)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.MonoLaunch.Main_End(String[] args)
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1()

[06:09:47.548] [Main Thread/FATAL] [tML]: Main engine crash

Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Could not create swapchain! Error Code: The operation completed successfully. (0x00000000)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\GraphicsDevice.cs:line 420
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice() in D:\a\tModLoader\tModLoader\FNA\src\GraphicsDeviceManager.cs:line 546
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 776
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 411
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
[06:09:47.548] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

### Steps to reproduce

Launch the game

### Expected Behavior

tModLoader should load up terraria with all my mods

### Actual Behavior

it's telling me it can't find a graphics device

### Reproduction frequency

100% of the time

### Additional Information

vanilla terraria seems to run just fine on its own

**Comment by JavidPack** [comment]
We aren't totally sure what causes this specific error, but many users with similar errors have had success following https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#nosuitablegraphicsdeviceexception-could-not-create-swapchain-error-code-the-parameter-is-incorrect-0x80070057

**Comment by TheBearodactyl** [comment]
> We aren't totally sure what causes this specific error, but many users with similar errors have had success following https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#nosuitablegraphicsdeviceexception-could-not-create-swapchain-error-code-the-parameter-is-incorrect-0x80070057

oh shit thanks

**Comment by Averagegayperson** [comment]
didn't work for me

**Comment by JavidPack** [comment]
Average, you need to make your own issue.
