### ISSUE TITLE
Error Code: The operation completed successfully. (0x00000000)

### ISSUE THREAD

**Issue by Averagegayperson** [bluemagic123/tModLoader#4417]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

When I try to open the game it has a main engine crash

[19:15:53.300] [Main Thread/FATAL] [tML]: Main engine crash

Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Could not create swapchain! Error Code: The operation completed successfully. (0x00000000)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice..ctor(GraphicsAdapter adapter, GraphicsProfile graphicsProfile, PresentationParameters presentationParameters) in D:\a\tModLoader\tModLoader\FNA\src\Graphics\GraphicsDevice.cs:line 420
   at Microsoft.Xna.Framework.GraphicsDeviceManager.Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice() in D:\a\tModLoader\tModLoader\FNA\src\GraphicsDeviceManager.cs:line 546
   at Microsoft.Xna.Framework.Game.DoInitialize() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 776
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 411
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
[19:15:53.301] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

### Log File

[client.log](https://github.com/user-attachments/files/17357781/client.log)
[environment-client.log](https://github.com/user-attachments/files/17357782/environment-client.log)
[Launch.log](https://github.com/user-attachments/files/17357783/Launch.log)
[Natives.log](https://github.com/user-attachments/files/17357784/Natives.log)
[terrariasteamclient.log](https://github.com/user-attachments/files/17357785/terrariasteamclient.log)

### Steps to reproduce

1. Click "Play"
2. Crash

### Expected Behavior

The game should be opening and not crashing

### Actual Behavior

The game has a main engine crash

### Reproduction frequency

100% of the time

**Comment by Averagegayperson** [comment]
No the Basic tModLoader Usage FAQ didn't work

**Comment by Averagegayperson** [comment]
I reinstalled the game, restarted my computer, and updated my drivers, it still wont work

**Comment by Chicken-Bones** [comment]
Did you try `/glevice:OpenGL` as per https://github.com/tModLoader/tModLoader/wiki/Basic-tModLoader-Usage-FAQ#low-fps?

Can you run `dxdiag` from the start menu, and send us a screenshot of the `Display` tab? (example below)
![image](https://github.com/user-attachments/assets/d1e1ec84-f92b-4965-b1fb-a84655fb7578)

**Comment by Averagegayperson** [comment]
@Chicken-Bones 
It worked. Thank you so much, I had looked at that solution before but didn't think it would work because my problem wasn't FPS related.

**Comment by Averagegayperson** [comment]
@Chicken-Bones 
It worked. Thank you so much, I had looked at that solution before but didn't think it would work because my problem wasn't FPS related.

**Comment by Chicken-Bones** [comment]
Glad to hear @Averagegayperson. Would you be able to send the `dxdiag` screenshot so we can investigate this issue a little further for other users?
