### ISSUE TITLE
Array of Class Object in Config makes game crash

### ISSUE THREAD

**Issue by Silencersn** [bluemagic123/tModLoader#4418]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

```
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Terraria.ModLoader.Config.UI.ObjectElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\ObjectElement.cs:line 41
   at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 627
   at Terraria.ModLoader.Config.UI.ArrayElement.SetupList() in tModLoader\Terraria\ModLoader\Config\UI\ArrayElement.cs:line 46
   at Terraria.ModLoader.Config.UI.CollectionElement.OnBind() in tModLoader\Terraria\ModLoader\Config\UI\CollectionElement.cs:line 78
   at Terraria.ModLoader.Config.UI.UIModConfig.WrapIt(UIElement parent, Int32& top, PropertyFieldWrapper memberInfo, Object item, Int32 order, Object list, Type arrayType, Int32 index) in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 627
   at Terraria.ModLoader.Config.UI.UIModConfig.OnActivate() in tModLoader\Terraria\ModLoader\Config\UI\UIModConfig.cs:line 495
   at Terraria.UI.UIElement.Activate() in tModLoader\Terraria\UI\UIElement.cs:line 469
   at Terraria.UI.UserInterface.SetState(UIState state) in tModLoader\Terraria\UI\UserInterface.cs:line 262
   at Terraria.ModLoader.UI.Interface.ModLoaderMenus(Main main, Int32 selectedMenu, String[] buttonNames, Single[] buttonScales, Int32[] buttonVerticalSpacing, Int32& offY, Int32& spacing, Int32& numButtons, Boolean& backButtonDown) in tModLoader\Terraria\ModLoader\UI\Interface.cs:line 389
   at Terraria.Main.DrawMenu(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 43852
   at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 53457
   at Terraria.Main.Draw_Inner(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 53022
   at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 53009
   at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
   at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
   at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 266
```

### Log File

[client.log](https://github.com/user-attachments/files/17360880/client.log)

### Steps to reproduce

```
public class DemoConfig : ModConfig
{
    public override ConfigScope Mode => ConfigScope.ClientSide;

    // OK
    public int[] Ints = [0];
    public List<MyObject> MyObjectList = [new MyObject()];

    // Not handled yet
    public MyEnum[] MyEnums = [MyEnum.Default];

    // Throw IndexOutOfRangeException
    public MyObject[] MyObjects1 = [new()];
    public MyObject[] MyObjects2 = [null];
    public MyObject[] MyObjects3 = new MyObject[1];
}

public enum MyEnum
{
    Default
}

public class MyObject
{

}
```

### Expected Behavior

Not throw exception

### Actual Behavior

Throw IndexOutOfRangeException

### Reproduction frequency

Always

**Comment by JavidPack** [comment]
K, the fix fixes arrays of objects. I didn't do fixes for null entries in collections, that doesn't seem useful for configs anyway and the code to fix it would be a bit of a mess.
