### ISSUE TITLE
System.NotImplementedException: The method or operation is not implemented.

### ISSUE THREAD

**Issue by han2044953296** [bluemagic123/tModLoader#4428]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

I tried running on ubantu on arm64 with the latest version of tModLoader and it appeared
System.NotImplementedException: The method or operation is not implemented.
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrentSystem() in Y:\src\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 90
   at MonoMod.Core.Platforms.PlatformTriple.CreateCurrent() in Y:\src\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 124
   at MonoMod.Utils.Helpers.InitializeValueWithLock[T,TParam](T& location, Object lock,  init, TParam obj) in Y:\src\MonoMod\src\MonoMod.Utils\Helpers.cs:line 222
   at MonoMod.Core.Platforms.PlatformTriple.get_Current() in Y:\src\MonoMod\src\MonoMod.Core\Platforms\PlatformTriple.cs:line 120
   at MonoMod.Core.DetourFactory.CreateDefaultFactory() in Y:\src\MonoMod\src\MonoMod.Core\IDetourFactory.cs:line 86
   at MonoMod.Utils.Helpers.InitializeValue[T,TParam](T& location,  init, TParam obj) in Y:\src\MonoMod\src\MonoMod.Utils\Helpers.cs:line 211
   at MonoMod.RuntimeDetour.DetourContext.GetDefaultFactory() in Y:\src\MonoMod\src\MonoMod.RuntimeDetour\DetourContext.cs:line 116
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config, Boolean applyByDefault) in Y:\src\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 420
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target, DetourConfig config) in Y:\src\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 388
   at MonoMod.RuntimeDetour.Hook..ctor(MethodBase source, Delegate target) in Y:\src\MonoMod\src\MonoMod.RuntimeDetour\Hook.cs:line 330
   at Terraria.ModLoader.Engine.LoggingHooks.PrettifyStackTraceSources() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 73
   at Terraria.ModLoader.Engine.LoggingHooks.Init() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 17
   at Terraria.ModLoader.Logging.LogStartup(Boolean dedServ) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\ModLoader\Logging.cs:line 103
   at Terraria.Program.StartupSequenceTml(Boolean isServer) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.TML.cs:line 344
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\Program.cs:line 211
   at Terraria.MonoLaunch.Main_End(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 79
   at Terraria.MonoLaunch.<>c__DisplayClass1_0.<Main>b__1() in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 65
   at Terraria.MonoLaunch.Main(String[] args) in D:\a\tModLoader\tModLoader\src\tModLoader\Terraria\MonoLaunch.cs:line 72

[09:49:17.687] [Main Thread/FATAL] [tML]: An unexpected error occurred during tML startup

### Log File

![11](https://github.com/user-attachments/assets/164e14a6-5abe-43fc-9efc-6fcb807af638)

### Steps to reproduce

Open the server side of tModLoader

### Actual Behavior

tModLoader won't start

### Reproduction frequency

always

### Additional Information

arm64 ubantu 18.04 
tModLoader

**Comment by han2044953296** [comment]
I don't really know how to fix this problem trouble everyone

**Comment by Rijam** [comment]
tModLoader does not support ARM at this moment.
https://github.com/tModLoader/tModLoader/tree/stable/patches/tModLoader/Terraria/release_extras/DedicatedServerUtils#installation-options
> **Currently ARM support does not exist for TML.**
