### ISSUE TITLE
SDL Error: Couldn't find matching GLX visual

### ISSUE THREAD

**Issue by alie4751** [bluemagic123/tModLoader#4455]
### Version

Latest 1.4.4-stable

### OS

Linux

### Platform

Steam

### This bug affects...

Gameplay as a Player

### Description

When launching tMoadLoader I get the attached error.
Terraria launches fine, but can't launch tMoadLoader
I was able to launch tMoLoader yesterday and played for a couple of hours

### Log File

[client.log](https://github.com/user-attachments/files/17917656/client.log)
[environment-client.log](https://github.com/user-attachments/files/17917659/environment-client.log)
[Launch.log](https://github.com/user-attachments/files/17917661/Launch.log)
[Natives.log](https://github.com/user-attachments/files/17917662/Natives.log)
[terrariasteamclient.log](https://github.com/user-attachments/files/17917663/terrariasteamclient.log)

### Additional Information

SDL Error: Couldn't find matching GLX visual

Microsoft.Xna.Framework.Graphics.NoSuitableGraphicsDeviceException: Couldn't find matching GLX visual
   at Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow() in D:\a\tModLoader\tModLoader\FNA\src\FNAPlatform\SDL2_FNAPlatform.cs:line 500
   at Microsoft.Xna.Framework.Game..ctor(Boolean headlessMode) in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 274
   at Terraria.Main..ctor() in tModLoader\Terraria\Main.cs:line 5583
   at Terraria.Program.RunGame() in tModLoader\Terraria\Program.cs:line 257
[13:24:51.107] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown
tModLoader v2024.9.3.0 Error
Main engine crash

SDL Error: Couldn't find matching GLX visual

**Comment by alie4751** [comment]
Fixed, Needed to update flatpak
