### ISSUE TITLE
The game crashes when I appear in a friend's world

### ISSUE THREAD

**Issue by dronix237** [bluemagic123/tModLoader#4466]
### Version

Latest 1.4.4-stable

### OS

Windows

### Platform

Steam

### This bug affects...

Mod capability as a Modder

### Description

The game crashes when I appear in a friend's world

### Log File

System.Exception: Fatal Deadlock in FastParallelFor. Tasks Queued: 6, Unfinished: 1, Proc Count: 8
	ThreadPool Completed: 91465 (+112), Pending: 0 (+0)
   at ReLogic.Threading.FastParallel.For(Int32 fromInclusive, Int32 toExclusive, ParallelForAction callback, Object context) in D:\a\tModLoader\tModLoader\src\tModLoader\ReLogic\Threading\FastParallel.cs:line 106
   at Terraria.Graphics.Light.TileLightScanner.ExportTo(Rectangle area, LightMap outputMap, TileLightScannerOptions options) in tModLoader\Terraria\Graphics\Light\TileLightScanner.cs:line 20
   at Terraria.Graphics.Light.LightingEngine.ProcessScan(Rectangle area) in tModLoader\Terraria\Graphics\Light\LightingEngine.cs:line 115
   at Terraria.Graphics.Light.LightingEngine.ProcessArea(Rectangle area) in tModLoader\Terraria\Graphics\Light\LightingEngine.cs:line 89
   at Terraria.Lighting.LightTiles(Int32 firstX, Int32 lastX, Int32 firstY, Int32 lastY) in tModLoader\Terraria\Lighting.cs:line 90
   at Terraria.Main.DoLightTiles() in tModLoader\Terraria\Main.cs:line 55248
   at DMD<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at TerrariaOverhaul.Core.Time.TimeSystem.OnDoDraw(orig_DoDraw orig, Main main, GameTime gameTime)
   at Hook<System.Void TerrariaOverhaul.Core.Time.TimeSystem::OnDoDraw(Terraria.On_Main+orig_DoDraw,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at SyncProxy<System.Void Terraria.Main:DoDraw(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Terraria.Main.Draw_Inner(GameTime gameTime)
   at DMD<System.Void Terraria.Main:Draw(Microsoft.Xna.Framework.GameTime)>(Main this, GameTime gameTime)
   at Hook<System.Void MrPlagueRaces.Common.Systems.UIRedirectionSystem::InterceptCharacterCreationMenu(Terraria.On_Main+orig_Draw,Terraria.Main,Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at SyncProxy<System.Void Terraria.Main:Draw(Microsoft.Xna.Framework.GameTime)>(Main , GameTime )
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.RunLoop()
   at Microsoft.Xna.Framework.Game.Run()
   at Terraria.Program.RunGame()
[16:31:59.626] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown

### Steps to reproduce

1. I go to the terrarium 2.multiplay 
3.a friend's server 4. ships then the flight

**Comment by JavidPack** [comment]
If you are still having this issue, can you post the actual log files, not just a snippet? It has important context in it.

**Comment by JavidPack** [comment]
This issue has either no recent activity or no reproducible steps, so it is being closed. We assume this issue has solved itself in some manner. Feel free to open a new issue if the issue persists and fill out the issue template completely.
